"""Exact source-premise instantiation and adaptive joint/resource numerical bounds."""
import json
from fractions import Fraction as Q
from pathlib import Path
from replaylib import sha
W=Path.cwd();I=W/'inputs/bootstrap'
def read(p):return json.loads((W/p).read_text())
def dump(p,x):(W/p).write_text(json.dumps(x,indent=2)+'\n')
order=read('SOURCE_ORDER.json');M=order['root_call_count'];assert M==3072
ga=read('inputs/bootstrap/GAUSS/SCALAR_GAUSSIAN_CERTIFICATE.json');le=read('inputs/bootstrap/GAUSS/ERROR_LEDGER.json');left=read('inputs/bootstrap/LEFT/LEFT_ROOT_CORRELATED_TRANSFER_CERTIFICATE.json');post=read('inputs/bootstrap/POST/SOURCE_POSTPROCESSING_CERTIFICATE.json');bank=read('inputs/bootstrap/LEFT/BANK_WEIGHTED_BOUNDS.json')
assert ga['game']=='IID_BUFFER' and ga['TV_bound_proved'] and ga['forward_chi2_bound_proved'] and ga['normalizer_bound']['source_A_lower']=='1/8'
assert left['left_forward_closure_proved'] and left['mu_domain_before_floor_proved'] and left['fault_unreachable_for_certified_entries']
assert bank['terminal_A2_energy_integer_upper']==849346588 and bank['right_768_terminal_budget']==768*849346588==652298179584
assert Q(bank['terminal_A2_energy_exact_upper'])<bank['terminal_A2_energy_integer_upper']
eps=Q(ga['TV_bound_value']);kap=Q(ga['chi2_bound_or_infinite']);tau=Q(le['entries']['G_mass_outside_positive_K_support_upper']);assert eps==Q(1,2**36) and kap==Q(1,2**60) and 0<tau<1
D=M*kap/(1-M*kap);tv=Q(1,2**25);assert D<Q(1,2**48) and D<=4*tv**2
exit=M*tau;assert exit<Q(1,2**50)
metrics=[dict(from_law='P_value',to_law=q,metric='chi2',direction='forward',exact_upper_expression='(1+2^-60)^3072-1',rational_upper=str(D),power2_upper='2^-48',scope='one root; all required entries; legal entry PAST; same value prefix parameters') for q in ['Q_stop','Q_S']]
metrics +=[dict(from_law='P_value',to_law=q,metric='TV',upper=str(tv),power2_upper='2^-25',alternative_sequential_upper=str(M*eps),proof='min of chain second moment and same-prefix adaptive coupling; no double-counted tail') for q in ['Q_stop','Q_S']]
metrics +=[dict(from_law='Q_S',to_law='Q_stop',metric='TV',value_expression='Q_stop(EXIT)=1-E_QS[product_i(1-t_h_i)]',upper=str(exit),power2_upper='2^-50'),dict(from_law='Q_stop',to_law='P_value',metric='chi2',value='infinity',absolute_continuity=False),dict(from_law='Q_S',to_law='P_value',metric='chi2',upper_expression='2^811008-1',absolute_continuity=True,utility='very loose; derived from K_h(y)>=2^-264 for y in S_h, not from reversing scalar forward chi2')]
dump('JOINT_COMPARISON.json',dict(schema='ORDERED_JOINT_COMPARISON_V1',status='PASS_EXACT_ADAPTIVE_NUMERICAL_INSTANCE',game='IID_BUFFER',M=M,epsilon=str(eps),kappa=str(kap),local_QS_identity='1+chi2(K_h||G_h|S_h)=(1-t_h)(1+chi2(K_h||G_h))',chain_second_moment='E_Qstop[L_i^2 | prefix h]=L_prev^2 * sum_y_in_S K_h(y)^2/G_h(y); zero on EXIT',metrics=metrics,reverse_QS_positive_atom_floor='1/2^264',reverse_QS_exponent=264*M,gaussian_ledger_sha256=sha(I/'GAUSS/ERROR_LEDGER.json'),source_Gaussian_certificate_sha256=sha(I/'GAUSS/SCALAR_GAUSSIAN_CERTIFICATE.json'),no_independent_marginals=True,no_global_lattice_Gaussian_claim=True))
dump('SUPPORT_EXIT.json',dict(schema='ORDERED_JOINT_SUPPORT_EXIT_V1',game='IID_BUFFER',S_definition='positive literal table mass AND e_C<64; unique y=s_C-k or s_C+1+k; Z>0',tau=str(tau),tau_origin='GAUSS/ERROR_LEDGER.json: entries.G_mass_outside_positive_K_support_upper',M=M,exit_upper_expression='1-(1-tau)^M <= M*tau',exit_rational_upper=str(exit),exit_power2_upper='2^-50',exit_strictly_positive=True,exit_interpretation='reference support exit BEFORE C conversion/update, not a proved UB or source abort',QS_live_product='prod_i G_h(y_i)/(1-t_h)',Qstop_live_product='prod_i G_h(y_i)',survival_tilt='Qstop(y|live)=QS(y)*prod_i(1-t_h)/E_QS[prod_i(1-t_h)]',QS_is_whole_survival_conditioning=False,tail_double_counted=False))
expected=8*M;cap=16*M;factor=Q(17,9)*Q(16,17)**16;assert factor<Q(3,4) and Q(3,4)**3<Q(1,2)
rbound=1+(33*cap)//4087
dump('RESOURCE_BOUND.json',dict(schema='ORDERED_JOINT_RESOURCE_V1',game='IID_BUFFER',M=M,A_lower='1/8',local_tail='Pr(N_i>m | PAST_i)<=(7/8)^m',expected_T=expected,returned_bytes_per_proposal=33,expected_returned_bytes=33*expected,expected_new_refills_upper=str(1+Q(33*expected,4087)),expected_discarded_upper=str(9*(1+Q(33*expected,4087))),expected_new_generated_bytes_upper=str(4096*(1+Q(33*expected,4087))),exact_schedule='iterate literal 8,8,1,8,8 getters from entry ptr; no reset between calls; q,R,D functions of ptr and T alone',schedule_conservation='ptr+33T+D=4096R+q, 0<=D<=9R, 8<=q<=4094',refill_upper='min(T,1+floor(33T/4087))',union_tail=dict(formula='Pr(T>M*m)<=Pr(exists i:N_i>m)<=M*(7/8)^m',m=768,T_cap=M*768,power2_tail_upper='2^-136'),mgf=dict(range='1<z<8/7',formula='E[z^T]<=[z/(8-7z)]^M',independence_not_assumed=True,z='17/16',chernoff_factor=str(factor),T_cap=cap,tail_expression='[(17/9)*(16/17)^16]^3072 <(3/4)^3072 <2^-1024',tail_power2='2^-1024'),ghost_budget=dict(T=cap,returned_bytes=33*cap,new_refills=rbound,discarded_bytes=9*rbound,new_generated_bytes=4096*rbound,including_entry_block=4096*(1+rbound)),ghost_is_source_abort=False,root_a_s_return_IID=True,real_termination_proved=False))
assert M*Q(7,8)**768<Q(1,2**136)
closure=dict(status='PASS_PINNED_FORWARD_CLOSURE_INSTANCE',required_domain='same emitted/canonical normalized root entry as ORDERED/LEFT/POST, legal buffers and entry IID PAST',positive_support_witness='one proposal raw33-byte atom with U at lower CDF interval endpoint,b parity chosen,w0=w1=0; any legal ptr; ignore dropped bytes; positive probability at least2^-264',right_mu_cap=156276714,left_mu_cap=937866518,terminal_energy=849346588,branch_terminal_budget=652298179584,raw_stable_metric_factors=[2,6],root_U_coefficient_cap=786308210,root_U_frequency_cap=20099472117,terminal_residual_caps=[552,367],rejection_stores_caller=False,closure_proof='construct finite actual return witness then source intercall frame/ORDERED/LEFT; paired and stored outcomes consumed in actual source order with same D; no future NumericCenter/fault/termination premise',dependencies={r:sha(I/r) for r in ['LEFT/LEFT_ROOT_CORRELATED_TRANSFER_CERTIFICATE.json','LEFT/BANK_WEIGHTED_BOUNDS.json','LEFT/ORDERED_COMPOSITION.md','LEFT/LEFT_INVARIANT.md','LEFT/RIGHT_RESIDUAL_ENERGY.md','ORDERED/INVARIANT.md','ORDERED/SCALAR_OUTCOMES.md','NORMALIZED/WIDTH_BOUNDS.json','POST/SAMPLING_RETURN_INTERFACE.md']})
dump('artifacts/closure_instance.json',closure)
print(json.dumps(dict(status='PASS_JOINT_AND_RESOURCE_BOUNDS',M=M,TV='2^-25',forward_chi2='2^-48',support_exit='2^-50',E_T=expected,ghost_T=cap,ghost_tail='2^-1024',reverse_Qstop='infinity',reverse_QS='finite but <=2^811008-1'),indent=2))
