import FloorConsumers
set_option pp.all true
#check @FloorCT.fields
#print FloorCT.fields
#check @FloorCT.mantissa_range
#print FloorCT.mantissa_range
#check @FloorCT.xi_range
#print FloorCT.xi_range
#check @FloorCT.irsh_eq
#print FloorCT.irsh_eq
#check @FloorCT.enc_bound
#print FloorCT.enc_bound
#check @FloorCT.decode_encode
#print FloorCT.decode_encode
#check @FloorCT.div_range
#print FloorCT.div_range
#check @FloorCT.old_range
#print FloorCT.old_range
#check @FloorCT.uand_full
#print FloorCT.uand_full
#check @FloorCT.candidate_bit_equivalence
#print FloorCT.candidate_bit_equivalence
#check @FloorCT.all_word64_equivalence
#print FloorCT.all_word64_equivalence
#check @FloorCT.all_word64_defined
#print FloorCT.all_word64_defined
#check @FloorCT.FLOOR_ZERO_CANDIDATE
#print FloorCT.FLOOR_ZERO_CANDIDATE
#check @FloorCT.C_INT_BRIDGE_CANDIDATE
#print FloorCT.C_INT_BRIDGE_CANDIDATE
#check @FloorCT.zero_endpoints
#print FloorCT.zero_endpoints
#print FloorCT.irsh
#print FloorCT.candidateBits
#print FloorCT.candidateLong
#print FloorCT.DefinedLP64
