/- Project Niirmata — C_TASK_1_BINBIND / warstwa FFT-NTT.
Przypięty tekst M0 (FT1536_M0_CONTRACT_RUN_001/source) dla falcon-fft.c
i falcon-enc.c; styl Source3 (pinned text -> parser -> typed execution).
Plik generowany przez scripts/gen_fftpin.py — NIE edytować ręcznie.
Piny: CONTRACTS.md i inputs/SHA256SUMS_M0; tekst <-> hash wiąże maszynowo
scripts/check_embed.py. Komentarze C NIE są źródłem założeń numerycznych. -/
set_option maxRecDepth 32768
namespace FT1536.FftBind.FftPin

/-- Pinned M0 text of `falcon-fft.c`, one String per source line. -/
def fftLines : List String := ["/*\n",
" * FFT code.\n",
" *\n",
" * ==========================(LICENSE BEGIN)============================\n",
" *\n",
" * Copyright (c) 2017  Falcon Project\n",
" *\n",
" * Permission is hereby granted, free of charge, to any person obtaining\n",
" * a copy of this software and associated documentation files (the\n",
" * \"Software\"), to deal in the Software without restriction, including\n",
" * without limitation the rights to use, copy, modify, merge, publish,\n",
" * distribute, sublicense, and/or sell copies of the Software, and to\n",
" * permit persons to whom the Software is furnished to do so, subject to\n",
" * the following conditions:\n",
" *\n",
" * The above copyright notice and this permission notice shall be\n",
" * included in all copies or substantial portions of the Software.\n",
" *\n",
" * THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n",
" * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n",
" * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n",
" * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\n",
" * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\n",
" * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\n",
" * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
" *\n",
" * ===========================(LICENSE END)=============================\n",
" *\n",
" * @author   Thomas Pornin <thomas.pornin@nccgroup.trust>\n",
" */\n",
"\n",
"#include \"internal.h\"\n",
"\n",
"/*\n",
" * Load the table of constants for FFT.\n",
" */\n",
"#define FPC(re, im)   re, im\n",
"#include FPR_IMPL\n",
"#undef FPC\n",
"\n",
"/*\n",
" * Rules for complex number macros:\n",
" * --------------------------------\n",
" *\n",
" * Operand order is: destination, source1, source2...\n",
" *\n",
" * Each operand is a real and an imaginary part.\n",
" *\n",
" * All overlaps are allowed.\n",
" */\n",
"\n",
"/*\n",
" * Addition of two complex numbers (d = a + b).\n",
" */\n",
"#define FPC_ADD(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n",
"\t\tfpr fpct_re, fpct_im; \\\n",
"\t\tfpct_re = fpr_add(a_re, b_re); \\\n",
"\t\tfpct_im = fpr_add(a_im, b_im); \\\n",
"\t\t(d_re) = fpct_re; \\\n",
"\t\t(d_im) = fpct_im; \\\n",
"\t} while (0)\n",
"\n",
"/*\n",
" * Subtraction of two complex numbers (d = a - b).\n",
" */\n",
"#define FPC_SUB(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n",
"\t\tfpr fpct_re, fpct_im; \\\n",
"\t\tfpct_re = fpr_sub(a_re, b_re); \\\n",
"\t\tfpct_im = fpr_sub(a_im, b_im); \\\n",
"\t\t(d_re) = fpct_re; \\\n",
"\t\t(d_im) = fpct_im; \\\n",
"\t} while (0)\n",
"\n",
"/*\n",
" * Multplication of two complex numbers (d = a * b).\n",
" */\n",
"#define FPC_MUL(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n",
"\t\tfpr fpct_a_re, fpct_a_im; \\\n",
"\t\tfpr fpct_b_re, fpct_b_im; \\\n",
"\t\tfpr fpct_d_re, fpct_d_im; \\\n",
"\t\tfpct_a_re = (a_re); \\\n",
"\t\tfpct_a_im = (a_im); \\\n",
"\t\tfpct_b_re = (b_re); \\\n",
"\t\tfpct_b_im = (b_im); \\\n",
"\t\tfpct_d_re = fpr_sub( \\\n",
"\t\t\tfpr_mul(fpct_a_re, fpct_b_re), \\\n",
"\t\t\tfpr_mul(fpct_a_im, fpct_b_im)); \\\n",
"\t\tfpct_d_im = fpr_add( \\\n",
"\t\t\tfpr_mul(fpct_a_re, fpct_b_im), \\\n",
"\t\t\tfpr_mul(fpct_a_im, fpct_b_re)); \\\n",
"\t\t(d_re) = fpct_d_re; \\\n",
"\t\t(d_im) = fpct_d_im; \\\n",
"\t} while (0)\n",
"\n",
"/*\n",
" * Squaring of a complex number (d = a * a).\n",
" */\n",
"#define FPC_SQR(d_re, d_im, a_re, a_im)   do { \\\n",
"\t\tfpr fpct_a_re, fpct_a_im; \\\n",
"\t\tfpr fpct_d_re, fpct_d_im; \\\n",
"\t\tfpct_a_re = (a_re); \\\n",
"\t\tfpct_a_im = (a_im); \\\n",
"\t\tfpct_d_re = fpr_sub(fpr_sqr(fpct_a_re), fpr_sqr(fpct_a_im)); \\\n",
"\t\tfpct_d_im = fpr_double(fpr_mul(fpct_a_re, fpct_a_im)); \\\n",
"\t\t(d_re) = fpct_d_re; \\\n",
"\t\t(d_im) = fpct_d_im; \\\n",
"\t} while (0)\n",
"\n",
"/*\n",
" * Inversion of a complex number (d = 1 / a).\n",
" */\n",
"#define FPC_INV(d_re, d_im, a_re, a_im)   do { \\\n",
"\t\tfpr fpct_a_re, fpct_a_im; \\\n",
"\t\tfpr fpct_d_re, fpct_d_im; \\\n",
"\t\tfpr fpct_m; \\\n",
"\t\tfpct_a_re = (a_re); \\\n",
"\t\tfpct_a_im = (a_im); \\\n",
"\t\tfpct_m = fpr_add(fpr_sqr(fpct_a_re), fpr_sqr(fpct_a_im)); \\\n",
"\t\tfpct_d_re = fpr_div(fpct_a_re, fpct_m); \\\n",
"\t\tfpct_d_im = fpr_div(fpr_neg(fpct_a_im), fpct_m); \\\n",
"\t\t(d_re) = fpct_d_re; \\\n",
"\t\t(d_im) = fpct_d_im; \\\n",
"\t} while (0)\n",
"\n",
"/*\n",
" * Division of complex numbers (d = a / b).\n",
" */\n",
"#define FPC_DIV(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n",
"\t\tfpr fpct_a_re, fpct_a_im; \\\n",
"\t\tfpr fpct_b_re, fpct_b_im; \\\n",
"\t\tfpr fpct_d_re, fpct_d_im; \\\n",
"\t\tfpr fpct_m; \\\n",
"\t\tfpct_a_re = (a_re); \\\n",
"\t\tfpct_a_im = (a_im); \\\n",
"\t\tfpct_b_re = (b_re); \\\n",
"\t\tfpct_b_im = (b_im); \\\n",
"\t\tfpct_m = fpr_add(fpr_sqr(fpct_b_re), fpr_sqr(fpct_b_im)); \\\n",
"\t\tfpct_b_re = fpr_div(fpct_b_re, fpct_m); \\\n",
"\t\tfpct_b_im = fpr_div(fpr_neg(fpct_b_im), fpct_m); \\\n",
"\t\tfpct_d_re = fpr_sub( \\\n",
"\t\t\tfpr_mul(fpct_a_re, fpct_b_re), \\\n",
"\t\t\tfpr_mul(fpct_a_im, fpct_b_im)); \\\n",
"\t\tfpct_d_im = fpr_add( \\\n",
"\t\t\tfpr_mul(fpct_a_re, fpct_b_im), \\\n",
"\t\t\tfpr_mul(fpct_a_im, fpct_b_re)); \\\n",
"\t\t(d_re) = fpct_d_re; \\\n",
"\t\t(d_im) = fpct_d_im; \\\n",
"\t} while (0)\n",
"\n",
"/*\n",
" * Let w = exp(i*pi/N); w is a primitive 2N-th root of 1. We define the\n",
" * values w_j = w^(2j+1) for all j from 0 to N-1: these are the roots\n",
" * of X^N+1 in the field of complex numbers. A crucial property is that\n",
" * w_{N-1-j} = conj(w_j) = 1/w_j for all j.\n",
" *\n",
" * FFT representation of a polynomial f (taken modulo X^N+1) is the\n",
" * set of values f(w_j). Since f is real, conj(f(w_j)) = f(conj(w_j)),\n",
" * thus f(w_{N-1-j}) = conj(f(w_j)). We thus store only half the values,\n",
" * for j = 0 to N/2-1; the other half can be recomputed easily when (if)\n",
" * needed. A consequence is that FFT representation has the same size\n",
" * as normal representation: N/2 complex numbers use N real numbers (each\n",
" * complex number is the combination of a real and an imaginary part).\n",
" *\n",
" * We use a specific ordering which makes computations easier. Let rev()\n",
" * be the bit-reversal function over log(N) bits. For j in 0..N/2-1, we\n",
" * store the real and imaginary parts of f(w_j) in slots:\n",
" *\n",
" *    Re(f(w_j)) -> slot rev(j)/2\n",
" *    Im(f(w_j)) -> slot rev(j)/2+N/2\n",
" *\n",
" * (Note that rev(j) is even for j < N/2.)\n",
" */\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_FFT(fpr *f, unsigned logn)\n",
"{\n",
"\t/*\n",
"\t * FFT algorithm in bit-reversal order uses the following\n",
"\t * iterative algorithm:\n",
"\t *\n",
"\t *   t = N\n",
"\t *   for m = 1; m < N; m *= 2:\n",
"\t *       ht = t/2\n",
"\t *       for i1 = 0; i1 < m; i1 ++:\n",
"\t *           j1 = i1 * t\n",
"\t *           s = GM[m + i1]\n",
"\t *           for j = j1; j < (j1 + ht); j ++:\n",
"\t *               x = f[j]\n",
"\t *               y = s * f[j + ht]\n",
"\t *               f[j] = x + y\n",
"\t *               f[j + ht] = x - y\n",
"\t *       t = ht\n",
"\t *\n",
"\t * GM[k] contains w^rev(k) for primitive root w = exp(i*pi/N).\n",
"\t *\n",
"\t * In the description above, f[] is supposed to contain complex\n",
"\t * numbers. In our in-memory representation, the real and\n",
"\t * imaginary parts of f[k] are in array slots k and k+N/2.\n",
"\t *\n",
"\t * We only keep the first half of the complex numbers. We can\n",
"\t * see that after the first iteration, the first and second halves\n",
"\t * of the array of complex numbers have separate lives, so we\n",
"\t * simply ignore the second part.\n",
"\t */\n",
"\n",
"\tunsigned u;\n",
"\tsize_t t, n, hn, m;\n",
"\n",
"\t/*\n",
"\t * First iteration: compute f[j] + i * f[j+N/2] for all j < N/2\n",
"\t * (because GM[1] = w^rev(1) = w^(N/2) = i).\n",
"\t * In our chosen representation, this is a no-op: everything is\n",
"\t * already where it should be.\n",
"\t */\n",
"\n",
"\t/*\n",
"\t * Subsequent iterations are truncated to use only the first\n",
"\t * half of values.\n",
"\t */\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tt = hn;\n",
"\tfor (u = 1, m = 2; u < logn; u ++, m <<= 1) {\n",
"\t\tsize_t ht, hm, i1, j1;\n",
"\n",
"\t\tht = t >> 1;\n",
"\t\thm = m >> 1;\n",
"\t\tfor (i1 = 0, j1 = 0; i1 < hm; i1 ++, j1 += t) {\n",
"\t\t\tunsigned j, j2;\n",
"\t\t\tfpr s_re, s_im;\n",
"\n",
"\t\t\ts_re = fpr_gm_tab[((m + i1) << 1) + 0];\n",
"\t\t\ts_im = fpr_gm_tab[((m + i1) << 1) + 1];\n",
"\t\t\tj2 = j1 + ht;\n",
"\t\t\tfor (j = j1; j < j2; j ++) {\n",
"\t\t\t\tfpr x_re, x_im, y_re, y_im;\n",
"\n",
"\t\t\t\tx_re = f[j];\n",
"\t\t\t\tx_im = f[j + hn];\n",
"\t\t\t\ty_re = f[j + ht];\n",
"\t\t\t\ty_im = f[j + ht + hn];\n",
"\t\t\t\tFPC_MUL(y_re, y_im, y_re, y_im, s_re, s_im);\n",
"\t\t\t\tFPC_ADD(f[j], f[j + hn],\n",
"\t\t\t\t\tx_re, x_im, y_re, y_im);\n",
"\t\t\t\tFPC_SUB(f[j + ht], f[j + ht + hn],\n",
"\t\t\t\t\tx_re, x_im, y_re, y_im);\n",
"\t\t\t}\n",
"\t\t}\n",
"\t\tt = ht;\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_iFFT(fpr *f, unsigned logn)\n",
"{\n",
"\t/*\n",
"\t * Inverse FFT algorithm in bit-reversal order uses the following\n",
"\t * iterative algorithm:\n",
"\t *\n",
"\t *   t = 1\n",
"\t *   for m = N; m > 1; m /= 2:\n",
"\t *       hm = m/2\n",
"\t *       dt = t*2\n",
"\t *       for i1 = 0; i1 < hm; i1 ++:\n",
"\t *           j1 = i1 * dt\n",
"\t *           s = iGM[hm + i1]\n",
"\t *           for j = j1; j < (j1 + t); j ++:\n",
"\t *               x = f[j]\n",
"\t *               y = f[j + t]\n",
"\t *               f[j] = x + y\n",
"\t *               f[j + t] = s * (x - y)\n",
"\t *       t = dt\n",
"\t *   for i1 = 0; i1 < N; i1 ++:\n",
"\t *       f[i1] = f[i1] / N\n",
"\t *\n",
"\t * iGM[k] contains (1/w)^rev(k) for primitive root w = exp(i*pi/N)\n",
"\t * (actually, iGM[k] = 1/GM[k] = conj(GM[k])).\n",
"\t *\n",
"\t * In the main loop (not counting the final division loop), in\n",
"\t * all iterations except the last, the first and second half of f[]\n",
"\t * (as an array of complex numbers) are separate. In our chosen\n",
"\t * representation, we do not keep the second half.\n",
"\t *\n",
"\t * The last iteration recombines the recomputed half with the\n",
"\t * implicit half, and should yield only real numbers since the\n",
"\t * target polynomial is real; moreover, s = i at that step.\n",
"\t * Thus, when considering x and y:\n",
"\t *    y = conj(x) since the final f[j] must be real\n",
"\t *    Therefore, f[j] is filled with 2*Re(x), and f[j + t] is\n",
"\t *    filled with 2*Im(x).\n",
"\t * But we already have Re(x) and Im(x) in array slots j and j+t\n",
"\t * in our chosen representation. That last iteration is thus a\n",
"\t * simple doubling of the values in all the array.\n",
"\t *\n",
"\t * We make the last iteration a no-op by tweaking the final\n",
"\t * division into a division by N/2, not N.\n",
"\t */\n",
"\tsize_t u, n, hn, t, m;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tt = 1;\n",
"\tm = n;\n",
"\thn = n >> 1;\n",
"\tfor (u = logn; u > 1; u --) {\n",
"\t\tsize_t hm, dt, i1, j1;\n",
"\n",
"\t\thm = m >> 1;\n",
"\t\tdt = t << 1;\n",
"\t\tfor (i1 = 0, j1 = 0; j1 < hn; i1 ++, j1 += dt) {\n",
"\t\t\tsize_t j, j2;\n",
"\t\t\tfpr s_re, s_im;\n",
"\n",
"\t\t\tj2 = j1 + t;\n",
"\t\t\ts_re = fpr_gm_tab[((hm + i1) << 1) + 0];\n",
"\t\t\ts_im = fpr_neg(fpr_gm_tab[((hm + i1) << 1) + 1]);\n",
"\t\t\tfor (j = j1; j < j2; j ++) {\n",
"\t\t\t\tfpr x_re, x_im, y_re, y_im;\n",
"\n",
"\t\t\t\tx_re = f[j];\n",
"\t\t\t\tx_im = f[j + hn];\n",
"\t\t\t\ty_re = f[j + t];\n",
"\t\t\t\ty_im = f[j + t + hn];\n",
"\t\t\t\tFPC_ADD(f[j], f[j + hn],\n",
"\t\t\t\t\tx_re, x_im, y_re, y_im);\n",
"\t\t\t\tFPC_SUB(x_re, x_im, x_re, x_im, y_re, y_im);\n",
"\t\t\t\tFPC_MUL(f[j + t], f[j + t + hn],\n",
"\t\t\t\t\tx_re, x_im, s_re, s_im);\n",
"\t\t\t}\n",
"\t\t}\n",
"\t\tt = dt;\n",
"\t\tm = hm;\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * Last iteration is a no-op, provided that we divide by N/2\n",
"\t * instead of N. We need to make a special case for logn = 0.\n",
"\t */\n",
"\tif (logn > 0) {\n",
"\t\tfpr ni;\n",
"\n",
"\t\tni = fpr_scaled(2, -(int)logn);\n",
"\t\tfor (u = 0; u < n; u ++) {\n",
"\t\t\tf[u] = fpr_mul(f[u], ni);\n",
"\t\t}\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_add(fpr *restrict a, const fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_add(a[u], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_addconst(fpr *a, fpr x, unsigned logn)\n",
"{\n",
"\t(void)logn;\n",
"\ta[0] = fpr_add(a[0], x);\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_addconst_fft(fpr *a, fpr x, unsigned logn)\n",
"{\n",
"\tsize_t hn, u;\n",
"\n",
"\thn = (size_t)1 << (logn - 1);\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\ta[u] = fpr_add(a[u], x);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_sub(fpr *restrict a, const fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_sub(a[u], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_neg(fpr *a, unsigned logn)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_neg(a[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_adj(fpr *a, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 1; u < hn; u ++) {\n",
"\t\tfpr t;\n",
"\n",
"\t\tt = fpr_neg(a[u]);\n",
"\t\ta[u] = fpr_neg(a[n - u]);\n",
"\t\ta[n - u] = t;\n",
"\t}\n",
"\ta[hn] = fpr_neg(a[hn]);\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_adj_fft(fpr *a, unsigned logn)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tfor (u = (n >> 1); u < n; u ++) {\n",
"\t\ta[u] = fpr_neg(a[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mul_fft(fpr *restrict a, const fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = b[u + hn];\n",
"\t\tFPC_MUL(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_sqr_fft(fpr *a, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tFPC_SQR(a[u], a[u + hn], a_re, a_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_muladj_fft(fpr *restrict a, const fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = fpr_neg(b[u + hn]);\n",
"\t\tFPC_MUL(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mulselfadj_fft(fpr *a, unsigned logn)\n",
"{\n",
"\t/*\n",
"\t * Since each coefficient is multiplied with its own conjugate,\n",
"\t * the result contains only real values.\n",
"\t */\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\ta[u] = fpr_add(fpr_sqr(a_re), fpr_sqr(a_im));\n",
"\t\ta[u + hn] = fpr_of(0);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mulconst(fpr *a, fpr x, unsigned logn)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_mul(a[u], x);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_inv_fft(fpr *a, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tFPC_INV(a[u], a[u + hn], a_re, a_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_div_fft(fpr *restrict a, const fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = b[u + hn];\n",
"\t\tFPC_DIV(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_divadj_fft(fpr *restrict a, const fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = fpr_neg(b[u + hn]);\n",
"\t\tFPC_DIV(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_invnorm2_fft(fpr *restrict d,\n",
"\tconst fpr *restrict a, const fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\t\tfpr b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = b[u + hn];\n",
"\t\td[u] = fpr_inv(fpr_add(\n",
"\t\t\tfpr_add(fpr_sqr(a_re), fpr_sqr(a_im)),\n",
"\t\t\tfpr_add(fpr_sqr(b_re), fpr_sqr(b_im))));\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_add_muladj_fft(fpr *restrict d,\n",
"\tconst fpr *restrict F, const fpr *restrict G,\n",
"\tconst fpr *restrict f, const fpr *restrict g, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr F_re, F_im, G_re, G_im;\n",
"\t\tfpr f_re, f_im, g_re, g_im;\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\tF_re = F[u];\n",
"\t\tF_im = F[u + hn];\n",
"\t\tG_re = G[u];\n",
"\t\tG_im = G[u + hn];\n",
"\t\tf_re = f[u];\n",
"\t\tf_im = f[u + hn];\n",
"\t\tg_re = g[u];\n",
"\t\tg_im = g[u + hn];\n",
"\n",
"\t\tFPC_MUL(a_re, a_im, F_re, F_im, f_re, fpr_neg(f_im));\n",
"\t\tFPC_MUL(b_re, b_im, G_re, G_im, g_re, fpr_neg(g_im));\n",
"\t\td[u] = fpr_add(a_re, b_re);\n",
"\t\td[u + hn] = fpr_add(a_im, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mul_autoadj_fft(fpr *restrict a,\n",
"\tconst fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\ta[u] = fpr_mul(a[u], b[u]);\n",
"\t\ta[u + hn] = fpr_mul(a[u + hn], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_div_autoadj_fft(fpr *restrict a,\n",
"\tconst fpr *restrict b, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\ta[u] = fpr_div(a[u], b[u]);\n",
"\t\ta[u + hn] = fpr_div(a[u + hn], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_split_fft(fpr *restrict f0, fpr *restrict f1,\n",
"\tconst fpr *restrict f, unsigned logn)\n",
"{\n",
"\t/*\n",
"\t * The FFT representation we use is in bit-reversed order\n",
"\t * (element i contains f(w^(rev(i))), where rev() is the\n",
"\t * bit-reversal function over the ring degree. This changes\n",
"\t * indexes with regards to the Falcon specification.\n",
"\t */\n",
"\tsize_t n, hn, qn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tqn = hn >> 1;\n",
"\n",
"\t/*\n",
"\t * We process complex values by pairs. For logn = 1, there is only\n",
"\t * one complex value (the other one is the implicit conjugate),\n",
"\t * so we add the two lines below because the loop will be\n",
"\t * skipped.\n",
"\t */\n",
"\tf0[0] = f[0];\n",
"\tf1[0] = f[hn];\n",
"\n",
"\tfor (u = 0; u < qn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\t\tfpr t_re, t_im;\n",
"\n",
"\t\ta_re = f[(u << 1) + 0];\n",
"\t\ta_im = f[(u << 1) + 0 + hn];\n",
"\t\tb_re = f[(u << 1) + 1];\n",
"\t\tb_im = f[(u << 1) + 1 + hn];\n",
"\n",
"\t\tFPC_ADD(t_re, t_im, a_re, a_im, b_re, b_im);\n",
"\t\tf0[u] = fpr_half(t_re);\n",
"\t\tf0[u + qn] = fpr_half(t_im);\n",
"\n",
"\t\tFPC_SUB(t_re, t_im, a_re, a_im, b_re, b_im);\n",
"\t\tFPC_MUL(t_re, t_im, t_re, t_im,\n",
"\t\t\tfpr_gm_tab[((u + hn) << 1) + 0],\n",
"\t\t\tfpr_neg(fpr_gm_tab[((u + hn) << 1) + 1]));\n",
"\t\tf1[u] = fpr_half(t_re);\n",
"\t\tf1[u + qn] = fpr_half(t_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_merge_fft(fpr *restrict f,\n",
"\tconst fpr *restrict f0, const fpr *restrict f1, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, qn, u;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tqn = hn >> 1;\n",
"\n",
"\t/*\n",
"\t * An extra copy to handle the special case logn = 1.\n",
"\t */\n",
"\tf[0] = f0[0];\n",
"\tf[hn] = f1[0];\n",
"\n",
"\tfor (u = 0; u < qn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\t\tfpr t_re, t_im;\n",
"\n",
"\t\ta_re = f0[u];\n",
"\t\ta_im = f0[u + qn];\n",
"\t\tFPC_MUL(b_re, b_im, f1[u], f1[u + qn],\n",
"\t\t\tfpr_gm_tab[((u + hn) << 1) + 0],\n",
"\t\t\tfpr_gm_tab[((u + hn) << 1) + 1]);\n",
"\t\tFPC_ADD(t_re, t_im, a_re, a_im, b_re, b_im);\n",
"\t\tf[(u << 1) + 0] = t_re;\n",
"\t\tf[(u << 1) + 0 + hn] = t_im;\n",
"\t\tFPC_SUB(t_re, t_im, a_re, a_im, b_re, b_im);\n",
"\t\tf[(u << 1) + 1] = t_re;\n",
"\t\tf[(u << 1) + 1 + hn] = t_im;\n",
"\t}\n",
"}\n",
"\n",
"/* ==================================================================== */\n",
"/*\n",
" * Here begins code for FFT3. Modulus is X^N-X^(N/2)+1.\n",
" *\n",
" * (X^N-X^(N/2)+1)*(X^(N/2)+1) = X^(1.5*N)+1. The roots of X^N-X^(N/2)+1\n",
" * are thus the roots of X^(1.5*N)+1 which are not roots of X^(N/2)+1.\n",
" */\n",
"\n",
"#define MKN(logn, full)   ((size_t)(1 + ((full) << 1)) << ((logn) - (full)))\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_FFT3(fpr *a, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u, t, tmin, m;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\n",
"\t/*\n",
"\t * First pass, for sub-polynomials of degree 2, each modulo\n",
"\t * X^2-X+1. If w = exp(i*pi/3), then the roots are w and w^5.\n",
"\t * We keep only a(w) = a0 + a1*w.\n",
"\t */\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a0, a1;\n",
"\n",
"\t\ta0 = a[u];\n",
"\t\ta1 = a[u + hn];\n",
"\t\ta[u] = fpr_add(a0, fpr_mul(a1, fpr_W1R));\n",
"\t\ta[u + hn] = fpr_mul(a1, fpr_W1I);\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * Intermediate steps for doubling the degree.\n",
"\t */\n",
"\tt = hn;\n",
"\ttmin = 1 + (full << 1);\n",
"\tfor (m = 2; t > tmin; m <<= 1) {\n",
"\t\tsize_t ht, hm, u1, v1;\n",
"\n",
"\t\tht = t >> 1;\n",
"\t\thm = m >> 1;\n",
"\t\tfor (u1 = 0, v1 = 0; u1 < hm; u1 ++, v1 += t) {\n",
"\t\t\tsize_t v, v2;\n",
"\t\t\tfpr sr, si;\n",
"\n",
"\t\t\tsr = fpr_gm3_square[((m + u1) << 1) + 0];\n",
"\t\t\tsi = fpr_gm3_square[((m + u1) << 1) + 1];\n",
"\t\t\tv2 = v1 + ht;\n",
"\t\t\tfor (v = v1; v < v2; v ++) {\n",
"\t\t\t\tfpr a0r, a0i, a1r, a1i;\n",
"\n",
"\t\t\t\ta0r = a[v];\n",
"\t\t\t\ta0i = a[v + hn];\n",
"\t\t\t\ta1r = a[v + ht];\n",
"\t\t\t\ta1i = a[v + ht + hn];\n",
"\t\t\t\tFPC_MUL(a1r, a1i, a1r, a1i, sr, si);\n",
"\t\t\t\tFPC_ADD(a[v], a[v + hn],\n",
"\t\t\t\t\ta0r, a0i, a1r, a1i);\n",
"\t\t\t\tFPC_SUB(a[v + ht], a[v + ht + hn],\n",
"\t\t\t\t\ta0r, a0i, a1r, a1i);\n",
"\t\t\t}\n",
"\t\t}\n",
"\t\tt = ht;\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * Last step: degree tripling (only if degree is multiple of 3).\n",
"\t */\n",
"\tif (full) {\n",
"\t\tsize_t v;\n",
"\n",
"\t\tfor (u = 0, v = (size_t)1 << logn; u < hn; u += 3, v += 2) {\n",
"\t\t\tfpr fAr, fAi, fBr, fBi, fCr, fCi;\n",
"\t\t\tfpr xr, xi;\n",
"\t\t\tfpr fB0r, fB0i, fB1r, fB1i, fB2r, fB2i;\n",
"\t\t\tfpr fC0r, fC0i, fC1r, fC1i, fC2r, fC2i;\n",
"\n",
"\t\t\tfAr = a[u];\n",
"\t\t\tfAi = a[u + hn];\n",
"\t\t\tfBr = a[u + 1];\n",
"\t\t\tfBi = a[u + 1 + hn];\n",
"\t\t\tfCr = a[u + 2];\n",
"\t\t\tfCi = a[u + 2 + hn];\n",
"\n",
"\t\t\txr = fpr_gm3_cubic[v + 0];\n",
"\t\t\txi = fpr_gm3_cubic[v + 1];\n",
"\t\t\tFPC_MUL(fB0r, fB0i, fBr, fBi, xr, xi);\n",
"\t\t\tFPC_MUL(fB1r, fB1i, fB0r, fB0i, fpr_W2R, fpr_W2I);\n",
"\t\t\tFPC_MUL(fB2r, fB2i, fB0r, fB0i, fpr_W4R, fpr_W4I);\n",
"\t\t\tFPC_SQR(xr, xi, xr, xi);\n",
"\t\t\tFPC_MUL(fC0r, fC0i, fCr, fCi, xr, xi);\n",
"\t\t\tFPC_MUL(fC1r, fC1i, fC0r, fC0i, fpr_W2R, fpr_W2I);\n",
"\t\t\tFPC_MUL(fC2r, fC2i, fC0r, fC0i, fpr_W4R, fpr_W4I);\n",
"\t\t\tFPC_ADD(fB0r, fB0i, fB0r, fB0i, fC0r, fC0i);\n",
"\t\t\tFPC_ADD(fB1r, fB1i, fB1r, fB1i, fC2r, fC2i);\n",
"\t\t\tFPC_ADD(fB2r, fB2i, fB2r, fB2i, fC1r, fC1i);\n",
"\t\t\tFPC_ADD(a[u + 0], a[u + 0 + hn], fAr, fAi, fB0r, fB0i);\n",
"\t\t\tFPC_ADD(a[u + 1], a[u + 1 + hn], fAr, fAi, fB1r, fB1i);\n",
"\t\t\tFPC_ADD(a[u + 2], a[u + 2 + hn], fAr, fAi, fB2r, fB2i);\n",
"\t\t}\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_iFFT3(fpr *a, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u, t, m;\n",
"\tfpr ni;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\n",
"\t/*\n",
"\t * First step: divide degree by 3.\n",
"\t */\n",
"\tif (full) {\n",
"\t\tsize_t v;\n",
"\n",
"\t\tfor (u = 0, v = (size_t)1 << logn; u < hn; u += 3, v += 2) {\n",
"\t\t\tfpr f0r, f0i, f1r, f1i, f2r, f2i, xr, xi;\n",
"\t\t\tfpr f11r, f11i, f12r, f12i, f21r, f21i, f22r, f22i;\n",
"\n",
"\t\t\tf0r = a[u];\n",
"\t\t\tf0i = a[u + hn];\n",
"\t\t\tf1r = a[u + 1];\n",
"\t\t\tf1i = a[u + 1 + hn];\n",
"\t\t\tf2r = a[u + 2];\n",
"\t\t\tf2i = a[u + 2 + hn];\n",
"\n",
"\t\t\txr = fpr_gm3_cubic[v + 0];\n",
"\t\t\txi = fpr_neg(fpr_gm3_cubic[v + 1]);\n",
"\t\t\tFPC_MUL(f11r, f11i, f1r, f1i, fpr_W4R, fpr_W4I);\n",
"\t\t\tFPC_MUL(f12r, f12i, f1r, f1i, fpr_W2R, fpr_W2I);\n",
"\t\t\tFPC_MUL(f21r, f21i, f2r, f2i, fpr_W4R, fpr_W4I);\n",
"\t\t\tFPC_MUL(f22r, f22i, f2r, f2i, fpr_W2R, fpr_W2I);\n",
"\n",
"\t\t\tFPC_ADD(f1r, f1i, f1r, f1i, f2r, f2i);\n",
"\t\t\tFPC_ADD(a[u], a[u + hn], f0r, f0i, f1r, f1i);\n",
"\n",
"\t\t\tFPC_ADD(f11r, f11i, f11r, f11i, f22r, f22i);\n",
"\t\t\tFPC_ADD(f11r, f11i, f11r, f11i, f0r, f0i);\n",
"\t\t\tFPC_MUL(a[u + 1], a[u + 1 + hn], xr, xi, f11r, f11i);\n",
"\n",
"\t\t\tFPC_SQR(xr, xi, xr, xi);\n",
"\t\t\tFPC_ADD(f12r, f12i, f12r, f12i, f21r, f21i);\n",
"\t\t\tFPC_ADD(f12r, f12i, f12r, f12i, f0r, f0i);\n",
"\t\t\tFPC_MUL(a[u + 2], a[u + 2 + hn], xr, xi, f12r, f12i);\n",
"\t\t}\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * Intermediate steps for halving the degree.\n",
"\t */\n",
"\tt = 2 + (full << 2);\n",
"\tfor (m = (size_t)1 << (logn - 1 - full); t < n; m >>= 1) {\n",
"\t\tsize_t ht, hm, u1, v1;\n",
"\n",
"\t\tht = t >> 1;\n",
"\t\thm = m >> 1;\n",
"\t\tfor (u1 = 0, v1 = 0; u1 < hm; u1 ++, v1 += t) {\n",
"\t\t\tsize_t v, v2;\n",
"\t\t\tfpr sr, si;\n",
"\n",
"\t\t\tsr = fpr_gm3_square[((m + u1) << 1) + 0];\n",
"\t\t\tsi = fpr_neg(fpr_gm3_square[((m + u1) << 1) + 1]);\n",
"\t\t\tv2 = v1 + ht;\n",
"\t\t\tfor (v = v1; v < v2; v ++) {\n",
"\t\t\t\tfpr a0r, a0i, a1r, a1i;\n",
"\n",
"\t\t\t\ta0r = a[v];\n",
"\t\t\t\ta0i = a[v + hn];\n",
"\t\t\t\ta1r = a[v + ht];\n",
"\t\t\t\ta1i = a[v + ht + hn];\n",
"\t\t\t\tFPC_ADD(a[v], a[v + hn],\n",
"\t\t\t\t\ta0r, a0i, a1r, a1i);\n",
"\t\t\t\tFPC_SUB(a0r, a0i, a0r, a0i, a1r, a1i);\n",
"\t\t\t\tFPC_MUL(a[v + ht], a[v + ht + hn],\n",
"\t\t\t\t\ta0r, a0i, sr, si);\n",
"\t\t\t}\n",
"\t\t}\n",
"\t\tt <<= 1;\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * Last step: modulo X^2-X+1.\n",
"\t *\n",
"\t * For w = exp(i*pi/3), roots of X^2-X+1 are w and w^5. Since\n",
"\t * w^3 = -1, we have w^5 = -w^2 = -w + 1.\n",
"\t *\n",
"\t * The FFT computed a(w) = a0 + a1*w. Since a0 and a1 are\n",
"\t * real, we can recompute a0 and a1:\n",
"\t *\n",
"\t *   a1 = Im(a(w)) / Im(w)\n",
"\t *   a0 = Re(a(w)) - Re(w) * a1\n",
"\t *\n",
"\t * Note that Re(w) = 1/2.\n",
"\t */\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr xr, xi, a0, a1;\n",
"\n",
"\t\txr = a[u];\n",
"\t\txi = a[u + hn];\n",
"\t\ta1 = fpr_mul(xi, fpr_IW1I);\n",
"\t\ta0 = fpr_sub(xr, fpr_half(a1));\n",
"\t\ta[u] = a0;\n",
"\t\ta[u + hn] = a1;\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * We have an accumulated N/2 multiplier to remove.\n",
"\t */\n",
"\tni = fpr_inverse_of(n >> 1);\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_mul(ni, a[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_add3(fpr *restrict a, const fpr *restrict b,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_add(a[u], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_addconst3(fpr *restrict a, fpr x, unsigned logn, unsigned full)\n",
"{\n",
"\t(void)logn;\n",
"\t(void)full;\n",
"\ta[0] = fpr_add(a[0], x);\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_addconst_fft3(fpr *restrict a, fpr x, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_add(a[u], x);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_sub3(fpr *restrict a, const fpr *restrict b,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_sub(a[u], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_neg3(fpr *restrict a, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_neg(a[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_adj_fft3(fpr *a, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = hn; u < n; u ++) {\n",
"\t\ta[u] = fpr_neg(a[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mul_fft3(fpr *restrict a, const fpr *restrict b,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = b[u + hn];\n",
"\t\tFPC_MUL(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_sqr_fft3(fpr *a, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tFPC_SQR(a[u], a[u + hn], a_re, a_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_muladj_fft3(fpr *restrict a, const fpr *restrict b,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = fpr_neg(b[u + hn]);\n",
"\t\tFPC_MUL(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mulselfadj_fft3(fpr *a, unsigned logn, unsigned full)\n",
"{\n",
"\t/*\n",
"\t * Since each coefficient is multiplied with its own conjugate,\n",
"\t * the result contains only real values.\n",
"\t */\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\ta[u] = fpr_add(fpr_sqr(a_re), fpr_sqr(a_im));\n",
"\t\ta[u + hn] = fpr_of(0);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mulconst3(fpr *a, fpr x, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\ta[u] = fpr_mul(a[u], x);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_inv_fft3(fpr *a, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tFPC_INV(a[u], a[u + hn], a_re, a_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_div_fft3(fpr *restrict a, const fpr *restrict b,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = b[u + hn];\n",
"\t\tFPC_DIV(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_divadj_fft3(fpr *restrict a, const fpr *restrict b,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = fpr_neg(b[u + hn]);\n",
"\t\tFPC_DIV(a[u], a[u + hn], a_re, a_im, b_re, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_invnorm2_fft3(fpr *restrict d,\n",
"\tconst fpr *restrict a, const fpr *restrict b,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr a_re, a_im;\n",
"\t\tfpr b_re, b_im;\n",
"\n",
"\t\ta_re = a[u];\n",
"\t\ta_im = a[u + hn];\n",
"\t\tb_re = b[u];\n",
"\t\tb_im = b[u + hn];\n",
"\t\td[u] = fpr_inv(fpr_add(\n",
"\t\t\tfpr_add(fpr_sqr(a_re), fpr_sqr(a_im)),\n",
"\t\t\tfpr_add(fpr_sqr(b_re), fpr_sqr(b_im))));\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_add_muladj_fft3(fpr *restrict d,\n",
"\tconst fpr *restrict F, const fpr *restrict G,\n",
"\tconst fpr *restrict f, const fpr *restrict g,\n",
"\tunsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\tfpr F_re, F_im, G_re, G_im;\n",
"\t\tfpr f_re, f_im, g_re, g_im;\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\n",
"\t\tF_re = F[u];\n",
"\t\tF_im = F[u + hn];\n",
"\t\tG_re = G[u];\n",
"\t\tG_im = G[u + hn];\n",
"\t\tf_re = f[u];\n",
"\t\tf_im = f[u + hn];\n",
"\t\tg_re = g[u];\n",
"\t\tg_im = g[u + hn];\n",
"\n",
"\t\tFPC_MUL(a_re, a_im, F_re, F_im, f_re, fpr_neg(f_im));\n",
"\t\tFPC_MUL(b_re, b_im, G_re, G_im, g_re, fpr_neg(g_im));\n",
"\t\td[u] = fpr_add(a_re, b_re);\n",
"\t\td[u + hn] = fpr_add(a_im, b_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_mul_autoadj_fft3(fpr *restrict a,\n",
"\tconst fpr *restrict b, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\ta[u] = fpr_mul(a[u], b[u]);\n",
"\t\ta[u + hn] = fpr_mul(a[u + hn], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_div_autoadj_fft3(fpr *restrict a,\n",
"\tconst fpr *restrict b, unsigned logn, unsigned full)\n",
"{\n",
"\tsize_t n, hn, u;\n",
"\n",
"\tn = MKN(logn, full);\n",
"\thn = n >> 1;\n",
"\tfor (u = 0; u < hn; u ++) {\n",
"\t\ta[u] = fpr_div(a[u], b[u]);\n",
"\t\ta[u + hn] = fpr_div(a[u + hn], b[u]);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_split_top_fft3(\n",
"\tfpr *restrict f0, fpr *restrict f1, fpr *restrict f2,\n",
"\tconst fpr *restrict f, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, qn, u, v;\n",
"\n",
"\tn = (size_t)3 << (logn - 1);\n",
"\thn = n >> 1;\n",
"\tqn = (size_t)1 << (logn - 2);\n",
"\tfor (u = 0, v = 0; u < hn; u += 3, v ++) {\n",
"\t\tfpr fAr, fAi, fBr, fBi, fCr, fCi, xr, xi;\n",
"\t\tfpr fB1r, fB1i, fB2r, fB2i, fC1r, fC1i, fC2r, fC2i;\n",
"\t\tfpr t0r, t0i, t1r, t1i, t2r, t2i;\n",
"\n",
"\t\tfAr = f[u];\n",
"\t\tfAi = f[u + hn];\n",
"\t\tfBr = f[u + 1];\n",
"\t\tfBi = f[u + 1 + hn];\n",
"\t\tfCr = f[u + 2];\n",
"\t\tfCi = f[u + 2 + hn];\n",
"\n",
"\t\txr = fpr_gm3_cubic[(v << 1) + ((size_t)1 << logn) + 0];\n",
"\t\txi = fpr_neg(fpr_gm3_cubic[(v << 1) + ((size_t)1 << logn) + 1]);\n",
"\t\tFPC_MUL(fB1r, fB1i, fBr, fBi, fpr_W4R, fpr_W4I);\n",
"\t\tFPC_MUL(fB2r, fB2i, fBr, fBi, fpr_W2R, fpr_W2I);\n",
"\t\tFPC_MUL(fC1r, fC1i, fCr, fCi, fpr_W4R, fpr_W4I);\n",
"\t\tFPC_MUL(fC2r, fC2i, fCr, fCi, fpr_W2R, fpr_W2I);\n",
"\n",
"\t\tFPC_ADD(fBr, fBi, fBr, fBi, fCr, fCi);\n",
"\t\tFPC_ADD(t0r, t0i, fAr, fAi, fBr, fBi);\n",
"\n",
"\t\tFPC_ADD(fB1r, fB1i, fB1r, fB1i, fC2r, fC2i);\n",
"\t\tFPC_ADD(fB1r, fB1i, fB1r, fB1i, fAr, fAi);\n",
"\t\tFPC_MUL(t1r, t1i, xr, xi, fB1r, fB1i);\n",
"\n",
"\t\tFPC_SQR(xr, xi, xr, xi);\n",
"\t\tFPC_ADD(fB2r, fB2i, fB2r, fB2i, fC1r, fC1i);\n",
"\t\tFPC_ADD(fB2r, fB2i, fB2r, fB2i, fAr, fAi);\n",
"\t\tFPC_MUL(t2r, t2i, xr, xi, fB2r, fB2i);\n",
"\n",
"\t\tf0[v] = fpr_mul(t0r, fpr_inverse_of(3));\n",
"\t\tf0[v + qn] = fpr_mul(t0i, fpr_inverse_of(3));\n",
"\t\tf1[v] = fpr_mul(t1r, fpr_inverse_of(3));\n",
"\t\tf1[v + qn] = fpr_mul(t1i, fpr_inverse_of(3));\n",
"\t\tf2[v] = fpr_mul(t2r, fpr_inverse_of(3));\n",
"\t\tf2[v + qn] = fpr_mul(t2i, fpr_inverse_of(3));\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_split_deep_fft3(fpr *restrict f0, fpr *restrict f1,\n",
"\tconst fpr *restrict f, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, qn, u, m;\n",
"\n",
"\t/*\n",
"\t * Special code for n = 2.\n",
"\t */\n",
"\tif (logn == 1) {\n",
"\t\tfpr re, im, xx;\n",
"\n",
"\t\tre = f[0];\n",
"\t\tim = f[1];\n",
"\t\txx = fpr_mul(fpr_IW1I, im);\n",
"\t\t*f1 = xx;\n",
"\t\t*f0 = fpr_sub(re, fpr_half(xx));\n",
"\t\treturn;\n",
"\t}\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tqn = hn >> 1;\n",
"\n",
"\tm = (size_t)1 << (logn - 1);\n",
"\tfor (u = 0; u < qn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\t\tfpr t_re, t_im;\n",
"\n",
"\t\ta_re = f[(u << 1) + 0];\n",
"\t\ta_im = f[(u << 1) + 0 + hn];\n",
"\t\tb_re = f[(u << 1) + 1];\n",
"\t\tb_im = f[(u << 1) + 1 + hn];\n",
"\n",
"\t\tFPC_ADD(t_re, t_im, a_re, a_im, b_re, b_im);\n",
"\t\tf0[u] = fpr_half(t_re);\n",
"\t\tf0[u + qn] = fpr_half(t_im);\n",
"\n",
"\t\tFPC_SUB(t_re, t_im, a_re, a_im, b_re, b_im);\n",
"\t\tFPC_MUL(t_re, t_im, t_re, t_im,\n",
"\t\t\tfpr_gm3_square[((u + m) << 1) + 0],\n",
"\t\t\tfpr_neg(fpr_gm3_square[((u + m) << 1) + 1]));\n",
"\t\tf1[u] = fpr_half(t_re);\n",
"\t\tf1[u + qn] = fpr_half(t_im);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_merge_top_fft3(fpr *restrict f,\n",
"\tconst fpr *restrict f0, const fpr *restrict f1, const fpr *restrict f2,\n",
"\tunsigned logn)\n",
"{\n",
"\tsize_t n, hn, qn, u, v;\n",
"\n",
"\tn = (size_t)3 << (logn - 1);\n",
"\thn = n >> 1;\n",
"\tqn = (size_t)1 << (logn - 2);\n",
"\tfor (u = 0, v = 0; u < hn; u += 3, v ++) {\n",
"\t\tfpr fAr, fAi, fBr, fBi, fCr, fCi;\n",
"\t\tfpr xr, xi;\n",
"\t\tfpr fB0r, fB0i, fB1r, fB1i, fB2r, fB2i;\n",
"\t\tfpr fC0r, fC0i, fC1r, fC1i, fC2r, fC2i;\n",
"\n",
"\t\tfAr = f0[v];\n",
"\t\tfAi = f0[v + qn];\n",
"\t\tfBr = f1[v];\n",
"\t\tfBi = f1[v + qn];\n",
"\t\tfCr = f2[v];\n",
"\t\tfCi = f2[v + qn];\n",
"\n",
"\t\txr = fpr_gm3_cubic[(v << 1) + ((size_t)1 << logn) + 0];\n",
"\t\txi = fpr_gm3_cubic[(v << 1) + ((size_t)1 << logn) + 1];\n",
"\t\tFPC_MUL(fB0r, fB0i, fBr, fBi, xr, xi);\n",
"\t\tFPC_MUL(fB1r, fB1i, fB0r, fB0i, fpr_W2R, fpr_W2I);\n",
"\t\tFPC_MUL(fB2r, fB2i, fB0r, fB0i, fpr_W4R, fpr_W4I);\n",
"\t\tFPC_SQR(xr, xi, xr, xi);\n",
"\t\tFPC_MUL(fC0r, fC0i, fCr, fCi, xr, xi);\n",
"\t\tFPC_MUL(fC1r, fC1i, fC0r, fC0i, fpr_W2R, fpr_W2I);\n",
"\t\tFPC_MUL(fC2r, fC2i, fC0r, fC0i, fpr_W4R, fpr_W4I);\n",
"\t\tFPC_ADD(fB0r, fB0i, fB0r, fB0i, fC0r, fC0i);\n",
"\t\tFPC_ADD(fB1r, fB1i, fB1r, fB1i, fC2r, fC2i);\n",
"\t\tFPC_ADD(fB2r, fB2i, fB2r, fB2i, fC1r, fC1i);\n",
"\t\tFPC_ADD(f[u + 0], f[u + 0 + hn], fAr, fAi, fB0r, fB0i);\n",
"\t\tFPC_ADD(f[u + 1], f[u + 1 + hn], fAr, fAi, fB1r, fB1i);\n",
"\t\tFPC_ADD(f[u + 2], f[u + 2 + hn], fAr, fAi, fB2r, fB2i);\n",
"\t}\n",
"}\n",
"\n",
"/* see internal.h */\n",
"void\n",
"falcon_poly_merge_deep_fft3(fpr *restrict f,\n",
"\tconst fpr *restrict f0, const fpr *restrict f1, unsigned logn)\n",
"{\n",
"\tsize_t n, hn, qn, u, m;\n",
"\n",
"\t/*\n",
"\t * Special code for n = 2.\n",
"\t */\n",
"\tif (logn == 1) {\n",
"\t\tfpr x, y;\n",
"\n",
"\t\tx = *f0;\n",
"\t\ty = *f1;\n",
"\t\tf[0] = fpr_add(x, fpr_mul(y, fpr_W1R));\n",
"\t\tf[1] = fpr_mul(y, fpr_W1I);\n",
"\t\treturn;\n",
"\t}\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\thn = n >> 1;\n",
"\tqn = hn >> 1;\n",
"\n",
"\tm = (size_t)1 << (logn - 1);\n",
"\tfor (u = 0; u < qn; u ++) {\n",
"\t\tfpr a_re, a_im, b_re, b_im;\n",
"\t\tfpr t_re, t_im;\n",
"\n",
"\t\ta_re = f0[u];\n",
"\t\ta_im = f0[u + qn];\n",
"\t\tb_re = f1[u];\n",
"\t\tb_im = f1[u + qn];\n",
"\t\tFPC_MUL(t_re, t_im, b_re, b_im,\n",
"\t\t\tfpr_gm3_square[((u + m) << 1) + 0],\n",
"\t\t\tfpr_gm3_square[((u + m) << 1) + 1]);\n",
"\t\tFPC_ADD(f[(u << 1) + 0], f[(u << 1) + 0 + hn],\n",
"\t\t\ta_re, a_im, t_re, t_im);\n",
"\t\tFPC_SUB(f[(u << 1) + 1], f[(u << 1) + 1 + hn],\n",
"\t\t\ta_re, a_im, t_re, t_im);\n",
"\t}\n",
"}\n"]

/-- Pinned M0 text of `falcon-enc.c`, one String per source line. -/
def encLines : List String := ["/*\n",
" * Encoding/decoding of keys and signatures.\n",
" *\n",
" * ==========================(LICENSE BEGIN)============================\n",
" *\n",
" * Copyright (c) 2017  Falcon Project\n",
" *\n",
" * Permission is hereby granted, free of charge, to any person obtaining\n",
" * a copy of this software and associated documentation files (the\n",
" * \"Software\"), to deal in the Software without restriction, including\n",
" * without limitation the rights to use, copy, modify, merge, publish,\n",
" * distribute, sublicense, and/or sell copies of the Software, and to\n",
" * permit persons to whom the Software is furnished to do so, subject to\n",
" * the following conditions:\n",
" *\n",
" * The above copyright notice and this permission notice shall be\n",
" * included in all copies or substantial portions of the Software.\n",
" *\n",
" * THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n",
" * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n",
" * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n",
" * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\n",
" * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\n",
" * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\n",
" * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
" *\n",
" * ===========================(LICENSE END)=============================\n",
" *\n",
" * @author   Thomas Pornin <thomas.pornin@nccgroup.trust>\n",
" */\n",
"\n",
"#include \"internal.h\"\n",
"\n",
"/*\n",
" * Encoding rules\n",
" * ==============\n",
" *\n",
" * In this description we number bits left-to-right, starting at 0. In\n",
" * an octet (a \"byte\"), there are eight bits, the most significant being\n",
" * leftmost (i.e. bit 0 here).\n",
" *\n",
" *\n",
" * Ring elements, q = 12289\n",
" * ------------------------\n",
" *\n",
" * A point coordinate is an integer between 0 and 12288 (inclusive), which\n",
" * is encoded as a 14-bit sequence, again numbered 0 to 13, 0 being most\n",
" * significant.\n",
" *\n",
" * An arbitrary point (e.g. public key H) is a sequence of values modulo\n",
" * q. These are encoded in due order as sequences of 14 bits. These are\n",
" * then concatenated, then split over bytes in left-to-right order. For\n",
" * instance, if the first two coordinates are 11911 (10111010000111 in\n",
" * binary) and 3446 (00110101110110 in binary), then the bit sequence\n",
" * will be:\n",
" *\n",
" *   10111010000111 00110101110110 ...\n",
" *\n",
" * which gets resplit into eight-bit chunks as:\n",
" *\n",
" *   10111010 00011100 11010111 0110...\n",
" *\n",
" * so the three first bytes of the encoding will have values 186, 28\n",
" * and 215, in that order.\n",
" *\n",
" * If the total bit length is not a multiple of 8, then extra padding\n",
" * bits are added to complete the final bytes. These padding bits MUST\n",
" * have value 0.\n",
" *\n",
" *\n",
" * Ring elements, q = 18433\n",
" * ------------------------\n",
" *\n",
" * For the ternary case, modulus q is 18433. Encoding is similar to\n",
" * the case q = 12289, except that each value uses 15 bits instead\n",
" * of 14.\n",
" *\n",
" * Also, array length is 1.5*2^logn in that case.\n",
" *\n",
" *\n",
" * Small vectors\n",
" * -------------\n",
" *\n",
" * \"Small vectors\" are private keys and signatures. They consist in\n",
" * _signed_ integers with values close to 0. They are encoded into bytes\n",
" * with a static code that approximates Huffman codes.\n",
" */\n",
"\n",
"/* see falcon-internal.h */\n",
"size_t\n",
"falcon_encode_12289(void *out, size_t max_out_len,\n",
"\tconst uint16_t *x, unsigned logn)\n",
"{\n",
"\tunsigned char *buf;\n",
"\tsize_t n, u;\n",
"\tuint32_t acc;\n",
"\tint acc_len;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tbuf = out;\n",
"\tu = 0;\n",
"\tacc = 0;\n",
"\tacc_len = 0;\n",
"\twhile (n > 0) {\n",
"\t\tacc = (acc << 14) | (*x ++);\n",
"\t\tn --;\n",
"\t\tacc_len += 14;\n",
"\t\twhile (acc_len >= 8) {\n",
"\t\t\tacc_len -= 8;\n",
"\t\t\tif (out != NULL) {\n",
"\t\t\t\tif (u >= max_out_len) {\n",
"\t\t\t\t\treturn 0;\n",
"\t\t\t\t}\n",
"\t\t\t\tbuf[u] = (unsigned char)(acc >> acc_len);\n",
"\t\t\t}\n",
"\t\t\tu ++;\n",
"\t\t\tacc &= (1U << acc_len) - 1U;\n",
"\t\t}\n",
"\t}\n",
"\tif (acc_len > 0) {\n",
"\t\tif (out != NULL) {\n",
"\t\t\tif (u >= max_out_len) {\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\tbuf[u] = (unsigned char)(acc << (8 - acc_len));\n",
"\t\t}\n",
"\t\tu ++;\n",
"\t}\n",
"\treturn u;\n",
"}\n",
"\n",
"/* see falcon-internal.h */\n",
"size_t\n",
"falcon_decode_12289(uint16_t *x, unsigned logn, const void *data, size_t len)\n",
"{\n",
"\tconst unsigned char *buf;\n",
"\tsize_t n, u;\n",
"\tuint32_t acc;\n",
"\tint acc_len;\n",
"\n",
"\tn = (size_t)1 << logn;\n",
"\tbuf = data;\n",
"\tu = 0;\n",
"\tacc = 0;\n",
"\tacc_len = 0;\n",
"\twhile (n > 0) {\n",
"\t\tif (u >= len) {\n",
"\t\t\treturn 0;\n",
"\t\t}\n",
"\t\tacc = (acc << 8) | buf[u ++];\n",
"\t\tacc_len += 8;\n",
"\t\tif (acc_len >= 14) {\n",
"\t\t\tuint32_t w;\n",
"\n",
"\t\t\tacc_len -= 14;\n",
"\t\t\tw = acc >> acc_len;\n",
"\t\t\tif (w >= 12289) {\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\t*x ++ = (uint16_t)w;\n",
"\t\t\tn --;\n",
"\t\t\tacc &= (1U << acc_len) - 1U;\n",
"\t\t}\n",
"\t}\n",
"\tif (acc != 0) {\n",
"\t\treturn 0;\n",
"\t}\n",
"\treturn len;\n",
"}\n",
"\n",
"/* see falcon-internal.h */\n",
"size_t\n",
"falcon_encode_18433(void *out, size_t max_out_len,\n",
"\tconst uint16_t *x, unsigned logn)\n",
"{\n",
"\tunsigned char *buf;\n",
"\tsize_t n, u;\n",
"\tuint32_t acc;\n",
"\tint acc_len;\n",
"\n",
"\tn = (size_t)3 << (logn - 1);\n",
"\tbuf = out;\n",
"\tu = 0;\n",
"\tacc = 0;\n",
"\tacc_len = 0;\n",
"\twhile (n > 0) {\n",
"\t\tacc = (acc << 15) | (*x ++);\n",
"\t\tn --;\n",
"\t\tacc_len += 15;\n",
"\t\twhile (acc_len >= 8) {\n",
"\t\t\tacc_len -= 8;\n",
"\t\t\tif (out != NULL) {\n",
"\t\t\t\tif (u >= max_out_len) {\n",
"\t\t\t\t\treturn 0;\n",
"\t\t\t\t}\n",
"\t\t\t\tbuf[u] = (unsigned char)(acc >> acc_len);\n",
"\t\t\t}\n",
"\t\t\tu ++;\n",
"\t\t\tacc &= (1U << acc_len) - 1U;\n",
"\t\t}\n",
"\t}\n",
"\tif (acc_len > 0) {\n",
"\t\tif (out != NULL) {\n",
"\t\t\tif (u >= max_out_len) {\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\tbuf[u] = (unsigned char)(acc << (8 - acc_len));\n",
"\t\t}\n",
"\t\tu ++;\n",
"\t}\n",
"\treturn u;\n",
"}\n",
"\n",
"/* see falcon-internal.h */\n",
"size_t\n",
"falcon_decode_18433(uint16_t *x, unsigned logn, const void *data, size_t len)\n",
"{\n",
"\tconst unsigned char *buf;\n",
"\tsize_t n, u;\n",
"\tuint32_t acc;\n",
"\tint acc_len;\n",
"\n",
"\tn = (size_t)3 << (logn - 1);\n",
"\tbuf = data;\n",
"\tu = 0;\n",
"\tacc = 0;\n",
"\tacc_len = 0;\n",
"\twhile (n > 0) {\n",
"\t\tif (u >= len) {\n",
"\t\t\treturn 0;\n",
"\t\t}\n",
"\t\tacc = (acc << 8) | buf[u ++];\n",
"\t\tacc_len += 8;\n",
"\t\tif (acc_len >= 15) {\n",
"\t\t\tuint32_t w;\n",
"\n",
"\t\t\tacc_len -= 15;\n",
"\t\t\tw = acc >> acc_len;\n",
"\t\t\tif (w >= 18433) {\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\t*x ++ = (uint16_t)w;\n",
"\t\t\tn --;\n",
"\t\t\tacc &= (1U << acc_len) - 1U;\n",
"\t\t}\n",
"\t}\n",
"\tif (acc != 0) {\n",
"\t\treturn 0;\n",
"\t}\n",
"\treturn len;\n",
"}\n",
"\n",
"/*\n",
" * Encoding of a small vector, no compression, 16 bits per value.\n",
" */\n",
"static size_t\n",
"compress_none(void *out, size_t max_out_len,\n",
"\tunsigned q, const int16_t *x, unsigned logn)\n",
"{\n",
"\tsize_t len, u;\n",
"\tunsigned char *buf;\n",
"\n",
"\tif (q == 12289) {\n",
"\t\tlen = (size_t)2 << logn;\n",
"\t} else {\n",
"\t\tlen = (size_t)3 << logn;\n",
"\t}\n",
"\tif (out == NULL) {\n",
"\t\treturn len;\n",
"\t}\n",
"\tif (max_out_len < len) {\n",
"\t\treturn 0;\n",
"\t}\n",
"\tbuf = out;\n",
"\tfor (u = 0; u < len; u += 2) {\n",
"\t\tunsigned w;\n",
"\n",
"\t\tw = *x ++;\n",
"\t\tbuf[u + 0] = (unsigned char)(w >> 8);\n",
"\t\tbuf[u + 1] = (unsigned char)w;\n",
"\t}\n",
"\treturn len;\n",
"}\n",
"\n",
"/*\n",
" * Encoding of a small vector, using (sort-of) Huffman codes.\n",
" */\n",
"static size_t\n",
"compress_static(void *out, size_t max_out_len,\n",
"\tunsigned q, const int16_t *x, unsigned logn)\n",
"{\n",
"\tunsigned char *buf;\n",
"\tsize_t n, u;\n",
"\tunsigned acc, mask;\n",
"\tint acc_len, j;\n",
"\n",
"\t/*\n",
"\t * Let x be a value to encode. We first encode its sign as 1 bit\n",
"\t * (1 = negative, 0 = positive), and replace x with |x|.\n",
"\t * The low j bits are encoded as-is in the stream (number j depends\n",
"\t * on the modulus q); then we follow with x/(2^j) bits of value 0,\n",
"\t * and a final bit of value 1.\n",
"\t *\n",
"\t * We use j = 7 for q = 12289, j = 8 for q = 18433.\n",
"\t */\n",
"\n",
"\tif (q == 12289) {\n",
"\t\tn = (size_t)1 << logn;\n",
"\t\tj = 7;\n",
"\t} else {\n",
"\t\tn = (size_t)3 << (logn - 1);\n",
"\t\tj = 8;\n",
"\t}\n",
"\tmask = (1U << j) - 1U;\n",
"\tbuf = out;\n",
"\tu = 0;\n",
"\tacc = 0;\n",
"\tacc_len = 0;\n",
"\twhile (n > 0) {\n",
"\t\tint w;\n",
"\t\tunsigned lo;\n",
"\t\tint ne;\n",
"\n",
"\t\tw = *x ++;\n",
"\t\tn --;\n",
"\n",
"\t\t/*\n",
"\t\t * First part: 1 bit for sign, and then the 7 low bits of\n",
"\t\t * the absolute value of the integer.\n",
"\t\t */\n",
"\t\tif (w < 0) {\n",
"\t\t\tw = -w;\n",
"\t\t\tlo = 1U << j;\n",
"\t\t} else {\n",
"\t\t\tlo = 0;\n",
"\t\t}\n",
"\t\tlo |= w & mask;\n",
"\t\tne = w >> j;\n",
"\t\tacc = (acc << (j + 1)) | lo;\n",
"\t\tacc_len += j + 1;\n",
"\t\twhile (acc_len >= 8) {\n",
"\t\t\tacc_len -= 8;\n",
"\t\t\tif (buf != NULL) {\n",
"\t\t\t\tif (u >= max_out_len) {\n",
"\t\t\t\t\treturn 0;\n",
"\t\t\t\t}\n",
"\t\t\t\tbuf[u] = (unsigned char)(acc >> acc_len);\n",
"\t\t\t}\n",
"\t\t\tu ++;\n",
"\t\t}\n",
"\n",
"\t\t/*\n",
"\t\t * Second part: 'ne' bits of value 0, and one bit of value 1.\n",
"\t\t */\n",
"\t\twhile (ne -- >= 0) {\n",
"\t\t\tacc <<= 1;\n",
"\t\t\tacc += ((unsigned)ne >> 15) & 1;\n",
"\t\t\tif (++ acc_len == 8) {\n",
"\t\t\t\tif (buf != NULL) {\n",
"\t\t\t\t\tif (u >= max_out_len) {\n",
"\t\t\t\t\t\treturn 0;\n",
"\t\t\t\t\t}\n",
"\t\t\t\t\tbuf[u] = (unsigned char)acc;\n",
"\t\t\t\t}\n",
"\t\t\t\tu ++;\n",
"\t\t\t\tacc_len = 0;\n",
"\t\t\t}\n",
"\t\t}\n",
"\t}\n",
"\tif (acc_len > 0) {\n",
"\t\tif (buf != NULL) {\n",
"\t\t\tif (u >= max_out_len) {\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\tbuf[u] = (unsigned char)(acc << (8 - acc_len));\n",
"\t\t}\n",
"\t\tu ++;\n",
"\t}\n",
"\treturn u;\n",
"}\n",
"\n",
"/* see falcon-internal.h */\n",
"size_t\n",
"falcon_encode_small(void *out, size_t max_out_len,\n",
"\tint comp, unsigned q, const int16_t *x, unsigned logn)\n",
"{\n",
"\tswitch (comp) {\n",
"\tcase FALCON_COMP_NONE:\n",
"\t\treturn compress_none(out, max_out_len, q, x, logn);\n",
"\tcase FALCON_COMP_STATIC:\n",
"\t\treturn compress_static(out, max_out_len, q, x, logn);\n",
"\tdefault:\n",
"\t\treturn 0;\n",
"\t}\n",
"}\n",
"\n",
"/*\n",
" * Decoding of a small vector, no compression.\n",
" */\n",
"static size_t\n",
"uncompress_none(int16_t *x, unsigned logn,\n",
"\tunsigned q, const void *data, size_t len)\n",
"{\n",
"\tsize_t n, u;\n",
"\tconst unsigned char *buf;\n",
"\tuint32_t hq, tq;\n",
"\n",
"\tif (q == 12289) {\n",
"\t\tn = (size_t)1 << logn;\n",
"\t} else {\n",
"\t\tn = (size_t)3 << (logn - 1);\n",
"\t}\n",
"\tif (len < (n << 1)) {\n",
"\t\treturn 0;\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * hq = floor(q/2)\n",
"\t * tq = ceil(3q/2)\n",
"\t * (Remember that q is odd).\n",
"\t */\n",
"\thq = q >> 1;\n",
"\ttq = hq + q + 1;\n",
"\n",
"\tbuf = data;\n",
"\tfor (u = 0; u < n; u ++) {\n",
"\t\tuint32_t w;\n",
"\t\tlong y;\n",
"\n",
"\t\t/*\n",
"\t\t * Decode the value as a 32-bit signed value (held in an\n",
"\t\t * unsigned integer).\n",
"\t\t */\n",
"\t\tw = ((uint32_t)buf[(u << 1) + 0] << 8)\n",
"\t\t\t| (uint32_t)buf[(u << 1) + 1];\n",
"\t\tw |= -(w & 0x8000);\n",
"\n",
"\t\t/*\n",
"\t\t * Add q. The result must be greater than q/2, and lower\n",
"\t\t * than 3q/2.\n",
"\t\t */\n",
"\t\tw += q;\n",
"\t\tif (!(((hq - w) & (w - tq)) >> 31)) {\n",
"\t\t\treturn 0;\n",
"\t\t}\n",
"\n",
"\t\t/*\n",
"\t\t * Assemble the signed value in a 'long'. Thanks to the\n",
"\t\t * verifications above, we know that the result will fit\n",
"\t\t * in an int16_t, so the cast is valid.\n",
"\t\t */\n",
"\t\ty = (long)w - (long)q;\n",
"\t\tx[u] = (int16_t)y;\n",
"\t}\n",
"\treturn n << 1;\n",
"}\n",
"\n",
"/*\n",
" * Decoding of a small vector, compressed with fixed (sort-of) Huffman codes.\n",
" */\n",
"static size_t\n",
"uncompress_static(int16_t *x, unsigned logn,\n",
"\tunsigned q, const void *data, size_t len)\n",
"{\n",
"\tconst unsigned char *buf;\n",
"\tsize_t n, u, v;\n",
"\tunsigned db, mask;\n",
"\tunsigned db_len, j;\n",
"\n",
"\tif (q == 12289) {\n",
"\t\tn = (size_t)1 << logn;\n",
"\t\tj = 7;\n",
"\t} else {\n",
"\t\tn = (size_t)3 << (logn - 1);\n",
"\t\tj = 8;\n",
"\t}\n",
"\tmask = (1U << j) - 1U;\n",
"\tbuf = data;\n",
"\tu = 0;\n",
"\tv = 0;\n",
"\tdb = 0;\n",
"\tdb_len = 0;\n",
"\tfor (;;) {\n",
"\t\tunsigned sign;\n",
"\t\tunsigned lo;\n",
"\t\tunsigned ne;\n",
"\n",
"\t\t/*\n",
"\t\t * Read next byte(s) for the sign bit and the low j bits\n",
"\t\t * of the absolute value of the next integer.\n",
"\t\t */\n",
"\t\twhile (db_len <= j) {\n",
"\t\t\tif (v >= len) {\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\tdb = (db << 8) + buf[v ++];\n",
"\t\t\tdb_len += 8;\n",
"\t\t}\n",
"\t\tsign = (db >> (db_len - 1)) & 1;\n",
"\t\tdb_len -= j + 1;\n",
"\t\tlo = (db >> db_len) & mask;\n",
"\n",
"\t\t/*\n",
"\t\t * Read subsequent bits until next '1' (inclusive).\n",
"\t\t */\n",
"\t\tfor (ne = 0;; ne ++) {\n",
"\t\t\tunsigned bit;\n",
"\n",
"\t\t\tif (db_len == 0) {\n",
"\t\t\t\tif (v >= len) {\n",
"\t\t\t\t\treturn 0;\n",
"\t\t\t\t}\n",
"\t\t\t\tdb = buf[v ++];\n",
"\t\t\t\tdb_len = 8;\n",
"\t\t\t}\n",
"\t\t\tdb_len --;\n",
"\t\t\tbit = (db >> db_len) & 1;\n",
"\t\t\tif (bit) {\n",
"\t\t\t\tbreak;\n",
"\t\t\t}\n",
"\t\t}\n",
"\n",
"\t\t/*\n",
"\t\t * Write value.\n",
"\t\t */\n",
"\t\tif (ne > 255) {\n",
"\t\t\treturn 0;\n",
"\t\t}\n",
"\t\tlo += (ne << j);\n",
"\t\tif (sign) {\n",
"\t\t\tx[u] = -(int16_t)lo;\n",
"\t\t} else {\n",
"\t\t\tx[u] = (int16_t)lo;\n",
"\t\t}\n",
"\t\tif (++ u >= n) {\n",
"\t\t\t/*\n",
"\t\t\t * Check that the remaining bits are all zero.\n",
"\t\t\t */\n",
"\t\t\tif ((db & ((1U << db_len) - 1U)) != 0) {\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\treturn v;\n",
"\t\t}\n",
"\t}\n",
"}\n",
"\n",
"/* see falcon-internal.h */\n",
"size_t\n",
"falcon_decode_small(int16_t *x, unsigned logn,\n",
"\tint comp, unsigned q, const void *data, size_t len)\n",
"{\n",
"\tswitch (comp) {\n",
"\tcase FALCON_COMP_NONE:\n",
"\t\treturn uncompress_none(x, logn, q, data, len);\n",
"\tcase FALCON_COMP_STATIC:\n",
"\t\treturn uncompress_static(x, logn, q, data, len);\n",
"\tdefault:\n",
"\t\treturn 0;\n",
"\t}\n",
"}\n",
"\n",
"/* see falcon-internal.h */\n",
"void\n",
"falcon_hash_to_point(shake_context *sc, unsigned q, uint16_t *x, unsigned logn)\n",
"{\n",
"\t/*\n",
"\t * TODO: make a constant-time version of this process, in case\n",
"\t * the signed data is confidential. We could generate twice as\n",
"\t * many values as necessary, then move proper values into place\n",
"\t * with logn passes that perform conditional swaps.\n",
"\t */\n",
"\n",
"\tsize_t n;\n",
"\tuint32_t lim;\n",
"\n",
"\tif (q == 12289) {\n",
"\t\tn = (size_t)1 << logn;\n",
"\t} else {\n",
"\t\tn = (size_t)3 << (logn - 1);\n",
"\t}\n",
"\tlim = (uint32_t)65536 - ((uint32_t)65536 % q);\n",
"\twhile (n > 0) {\n",
"\t\tunsigned char buf[2];\n",
"\t\tuint32_t w;\n",
"\n",
"\t\tshake_extract(sc, buf, sizeof buf);\n",
"\t\tw = (buf[0] << 8) | buf[1];\n",
"\t\tif (w < lim) {\n",
"\t\t\t*x ++ = (uint16_t)(w % q);\n",
"\t\t\tn --;\n",
"\t\t}\n",
"\t}\n",
"}\n",
"\n",
"/* see falcon-internal.h */\n",
"int\n",
"falcon_is_short(const int16_t *s1, const int16_t *s2,\n",
"\tunsigned logn, unsigned ter)\n",
"{\n",
"\tif (ter) {\n",
"\t\t/*\n",
"\t\t * In the ternary case, we must compute the norm in\n",
"\t\t * the FFT embedding. Fortunately, this can be done\n",
"\t\t * without computing the FFT.\n",
"\t\t */\n",
"\t\tsize_t n, hn, u;\n",
"\t\tint64_t s;\n",
"\n",
"\t\tn = (size_t)3 << (logn - 1);\n",
"\t\thn = n >> 1;\n",
"\t\ts = 0;\n",
"\t\tfor (u = 0; u < n; u ++) {\n",
"\t\t\tint32_t z;\n",
"\n",
"\t\t\tz = s1[u];\n",
"\t\t\ts += z * z;\n",
"\t\t\tz = s2[u];\n",
"\t\t\ts += z * z;\n",
"\t\t}\n",
"\t\tfor (u = 0; u < hn; u ++) {\n",
"\t\t\ts += (int32_t)s1[u] * (int32_t)s1[u + hn];\n",
"\t\t\ts += (int32_t)s2[u] * (int32_t)s2[u + hn];\n",
"\t\t}\n",
"\n",
"\t\t/*\n",
"\t\t * If the norm is v, then we computed (v^2)/N (in s).\n",
"\t\t */\n",
"\n",
"\t\t/*\n",
"\t\t * Candidate ternary verification bounds in the normalized-canonical\n",
"\t\t * quadratic form above. The active FT1536 value is\n",
"\t\t * floor(1.075^2 * 2*N * 768^2). SIG-001 and the final norm/security\n",
"\t\t * selection remain open.\n",
"\t\t */\n",
"\t\t{\n",
"\t\t\tint64_t bound;\n",
"\n",
"\t\t\tswitch (logn) {\n",
"\t\t\tcase 3:\n",
"\t\t\t\tbound = 987497;\n",
"\t\t\t\tbreak;\n",
"\t\t\tcase 4:\n",
"\t\t\t\tbound = 2052189;\n",
"\t\t\t\tbreak;\n",
"\t\t\tcase 5:\n",
"\t\t\t\tbound = 4258765;\n",
"\t\t\t\tbreak;\n",
"\t\t\tcase 6:\n",
"\t\t\t\tbound = 8826305;\n",
"\t\t\t\tbreak;\n",
"\t\t\tcase 7:\n",
"\t\t\t\tbound = 18270159;\n",
"\t\t\t\tbreak;\n",
"\t\t\tcase 8:\n",
"\t\t\t\tbound = 37775417;\n",
"\t\t\t\tbreak;\n",
"\t\t\tcase 9:\n",
"\t\t\t\tbound = 78021029;\n",
"\t\t\t\tbreak;\n",
"\t\t\tcase 10:\n",
"\t\t\t\tbound = FALCON_FT1536_NORM_BOUND2;\n",
"\t\t\t\tbreak;\n",
"\t\t\tdefault:\n",
"\t\t\t\treturn 0;\n",
"\t\t\t}\n",
"\t\t\treturn s < bound;\n",
"\t\t}\n",
"\t} else {\n",
"\t\t/*\n",
"\t\t * In the binary case, we use the l2-norm. Code below\n",
"\t\t * uses only 32-bit operations to compute the square\n",
"\t\t * of the norm with saturation to 2^32-1 if the value\n",
"\t\t * exceeds 2^31-1.\n",
"\t\t */\n",
"\t\tsize_t n, u;\n",
"\t\tuint32_t s, ng;\n",
"\n",
"\t\tn = (size_t)1 << logn;\n",
"\t\ts = 0;\n",
"\t\tng = 0;\n",
"\t\tfor (u = 0; u < n; u ++) {\n",
"\t\t\tint32_t z;\n",
"\n",
"\t\t\tz = s1[u];\n",
"\t\t\ts += (uint32_t)(z * z);\n",
"\t\t\tng |= s;\n",
"\t\t\tz = s2[u];\n",
"\t\t\ts += (uint32_t)(z * z);\n",
"\t\t\tng |= s;\n",
"\t\t}\n",
"\t\ts |= -(ng >> 31);\n",
"\n",
"\t\t/*\n",
"\t\t * Acceptance bound on the l2-norm is:\n",
"\t\t *   1.2*1.55*sqrt(q)*sqrt(2*N)\n",
"\t\t * Value 7085 is floor((1.2^2)*(1.55^2)*2*1024).\n",
"\t\t */\n",
"\t\treturn s < (((uint32_t)7085 * (uint32_t)12289) >> (10 - logn));\n",
"\t}\n",
"}\n"]

/-- SHA256 pin M0: falcon-fft.c. -/
def fftSha256 : String := "06b573b636ae368dcda3eb4d89c3936ab31272123440d0d5362317e55d9ac063"
/-- SHA256 pin M0: falcon-enc.c. -/
def encSha256 : String := "0f7085fa975d41ebbeb96d5db4cb68482c344ef2d602ca8853e20a4d4f04fb05"
/-- SHA256 pin M0: falcon-keygen.c. -/
def keygenSha256 : String := "0a09b6ed2363308f54584dfd1e2d33ee1b4601a68c77712c50da920b5074a5cf"
/-- SHA256 pin M0: fpr-emulated.h. -/
def fprHeaderSha256 : String := "242a7027d854e1317a3382f198271c69d40f4b34e80192ff896a42a65c83edfa"

theorem fft_line_count : fftLines.length = 1455 := by decide
theorem enc_line_count : encLines.length = 700 := by decide

/-- Slice helper (1-based source line numbers), konwencja jak FprPrimitives.hslice. -/
def fftSlice (line count : Nat) : List Char :=
  ((fftLines.drop (line-1)).take count).flatMap String.toList
def encSlice (line count : Nat) : List Char :=
  ((encLines.drop (line-1)).take count).flatMap String.toList
theorem fft_line_38 : fftLines[37]? = some "#include FPR_IMPL\n" := by decide
theorem fft_line_55 : fftLines[54]? = some "#define FPC_ADD(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n" := by decide
theorem fft_line_66 : fftLines[65]? = some "#define FPC_SUB(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n" := by decide
theorem fft_line_77 : fftLines[76]? = some "#define FPC_MUL(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n" := by decide
theorem fft_line_98 : fftLines[97]? = some "#define FPC_SQR(d_re, d_im, a_re, a_im)   do { \\\n" := by decide
theorem fft_line_112 : fftLines[111]? = some "#define FPC_INV(d_re, d_im, a_re, a_im)   do { \\\n" := by decide
theorem fft_line_128 : fftLines[127]? = some "#define FPC_DIV(d_re, d_im, a_re, a_im, b_re, b_im)   do { \\\n" := by decide
theorem fft_line_176 : fftLines[175]? = some "falcon_FFT(fpr *f, unsigned logn)\n" := by decide
theorem fft_line_256 : fftLines[255]? = some "falcon_iFFT(fpr *f, unsigned logn)\n" := by decide
theorem fft_line_755 : fftLines[754]? = some "#define MKN(logn, full)   ((size_t)(1 + ((full) << 1)) << ((logn) - (full)))\n" := by decide
theorem fft_line_759 : fftLines[758]? = some "falcon_FFT3(fpr *a, unsigned logn, unsigned full)\n" := by decide
theorem fft_line_854 : fftLines[853]? = some "falcon_iFFT3(fpr *a, unsigned logn, unsigned full)\n" := by decide
theorem fft_line_1041 : fftLines[1040]? = some "falcon_poly_mul_fft3(fpr *restrict a, const fpr *restrict b,\n" := by decide
theorem enc_line_173 : encLines[172]? = some "falcon_encode_18433(void *out, size_t max_out_len,\n" := by decide
theorem enc_line_216 : encLines[215]? = some "falcon_decode_18433(uint16_t *x, unsigned logn, const void *data, size_t len)\n" := by decide
theorem enc_line_384 : encLines[383]? = some "falcon_encode_small(void *out, size_t max_out_len,\n" := by decide
theorem enc_line_549 : encLines[548]? = some "falcon_decode_small(int16_t *x, unsigned logn,\n" := by decide
theorem enc_line_564 : encLines[563]? = some "falcon_hash_to_point(shake_context *sc, unsigned q, uint16_t *x, unsigned logn)\n" := by decide
theorem enc_line_597 : encLines[596]? = some "falcon_is_short(const int16_t *s1, const int16_t *s2,\n" := by decide

end FT1536.FftBind.FftPin

#print axioms FT1536.FftBind.FftPin.fft_line_count
#print axioms FT1536.FftBind.FftPin.enc_line_count
#print axioms FT1536.FftBind.FftPin.fft_line_38
#print axioms FT1536.FftBind.FftPin.fft_line_55
#print axioms FT1536.FftBind.FftPin.fft_line_66
#print axioms FT1536.FftBind.FftPin.fft_line_77
#print axioms FT1536.FftBind.FftPin.fft_line_98
#print axioms FT1536.FftBind.FftPin.fft_line_112
#print axioms FT1536.FftBind.FftPin.fft_line_128
#print axioms FT1536.FftBind.FftPin.fft_line_176
#print axioms FT1536.FftBind.FftPin.fft_line_256
#print axioms FT1536.FftBind.FftPin.fft_line_755
#print axioms FT1536.FftBind.FftPin.fft_line_759
#print axioms FT1536.FftBind.FftPin.fft_line_854
#print axioms FT1536.FftBind.FftPin.fft_line_1041
#print axioms FT1536.FftBind.FftPin.enc_line_173
#print axioms FT1536.FftBind.FftPin.enc_line_216
#print axioms FT1536.FftBind.FftPin.enc_line_384
#print axioms FT1536.FftBind.FftPin.enc_line_549
#print axioms FT1536.FftBind.FftPin.enc_line_564
#print axioms FT1536.FftBind.FftPin.enc_line_597
