import Floor
import ValueDomain
import SourceFloor
import Proposal
import CDF
import OrderedResidual
import Comparator
import GuardPrefix
import ZeroRho
import BitErrors
import PackOf
import ErrorArithmetic
import RootDiv
import RootFrame
import RootBounds
import RootModel
import NodeInverse
import NodeDataflow
import NodeConstants
import Half
import TargetWords
import TargetAlgebra
import TargetFrame
import TargetSequence
import ReachOutcomes
import ReachFrame
set_option pp.all true
#check @OrderedReach.fault_sticky
#print OrderedReach.fault_sticky
#check @OrderedReach.clear_prefix
#print OrderedReach.clear_prefix
#check @OrderedReach.safe_normal_return
#print OrderedReach.safe_normal_return
#check @OrderedReach.normal_residual_after_center
#print OrderedReach.normal_residual_after_center
#check @OrderedReach.fault_zero_is_not_close
#print OrderedReach.fault_zero_is_not_close
#check @OrderedReach.normal_zero_distinct_tag
#print OrderedReach.normal_zero_distinct_tag
#check @OrderedReach.rejection_no_return
#print OrderedReach.rejection_no_return
#check @OrderedReach.shifted_half_bound
#print OrderedReach.shifted_half_bound
#check @OrderedReach.next_center_needs_update
#print OrderedReach.next_center_needs_update
#check @OrderedReach.final_residual_after_unshift
#print OrderedReach.final_residual_after_unshift
#check @OrderedReach.right_margin
#print OrderedReach.right_margin
#check @OrderedReach.right_margin_constants
#print OrderedReach.right_margin_constants
#check @OrderedReach.cutoff_counts
#print OrderedReach.cutoff_counts
#check @OrderedReach.safe_shift
#print OrderedReach.safe_shift
#check @OrderedReach.scalar_integer_products
#print OrderedReach.scalar_integer_products
#check @OrderedReach.key_and_root_target_frame
#print OrderedReach.key_and_root_target_frame
#check @OrderedReach.scratch_formula
#print OrderedReach.scratch_formula
#check @OrderedReach.root_peak
#print OrderedReach.root_peak
#check @OrderedReach.structural_calls
#print OrderedReach.structural_calls
#check @OrderedReach.right_and_whole_counts
#print OrderedReach.right_and_whole_counts
#check @OrderedReach.terminal_inverse_identity
#print OrderedReach.terminal_inverse_identity
#check @OrderedReach.repeated_product_same_inputs
#print OrderedReach.repeated_product_same_inputs
#check @OrderedReach.rounded_cancellation_requires_error
#print OrderedReach.rounded_cancellation_requires_error
#print OrderedReach.Outcome
#print OrderedReach.nextFault
#print OrderedReach.faults
#print OrderedReach.normalResult
#print OrderedReach.callerStep
#print OrderedReach.scratch
#print OrderedReach.visits
