import Floor
import ValueDomain
import SourceFloor
import Proposal
import CDF
import OrderedResidual
import Comparator
import GuardPrefix
import ZeroRho
import BitErrors
import PackOf
import RootDiv
import RootFrame
import RootBounds
import RootModel
import NodeInverse
import NodeDataflow
import NodeConstants
import Half
import BinaryMargin
import NodeFrame
import BinaryFrame
import BinaryConstants
import HalfMain
import TowerShape
import TowerOrder
import TowerMargin
import TowerExecution
import RawLayout
import RawComposition
import RawMatching
set_option pp.all true
#check @RawAssembly.allocation_sizes
#print RawAssembly.allocation_sizes
#check @RawAssembly.count_from_children
#print RawAssembly.count_from_children
#check @RawAssembly.internal_leaf_counts
#print RawAssembly.internal_leaf_counts
#check @RawAssembly.scratch_from_children
#print RawAssembly.scratch_from_children
#check @RawAssembly.branch_bounds
#print RawAssembly.branch_bounds
#check @RawAssembly.level8_bounds
#print RawAssembly.level8_bounds
#check @RawAssembly.inner7_bounds
#print RawAssembly.inner7_bounds
#check @RawAssembly.separate_branches
#print RawAssembly.separate_branches
#check @RawAssembly.separate_children
#print RawAssembly.separate_children
#check @RawAssembly.separate_inner7
#print RawAssembly.separate_inner7
#check @RawAssembly.full_tree_partition
#print RawAssembly.full_tree_partition
#check @RawAssembly.depth_partition
#print RawAssembly.depth_partition
#check @RawAssembly.level8_partition
#print RawAssembly.level8_partition
#check @RawAssembly.packed_tree_offset
#print RawAssembly.packed_tree_offset
#check @RawAssembly.all_byte_offsets_fit
#print RawAssembly.all_byte_offsets_fit
#check @RawAssembly.checked_coeff_fits_int16
#print RawAssembly.checked_coeff_fits_int16
#check @RawAssembly.raw_tree_frame
#print RawAssembly.raw_tree_frame
#check @RawAssembly.depth_children_preserve_diagonals
#print RawAssembly.depth_children_preserve_diagonals
#check @RawAssembly.inner_first_child_preserves_input
#print RawAssembly.inner_first_child_preserves_input
#check @RawAssembly.root_D_read_before_reuse_ranges
#print RawAssembly.root_D_read_before_reuse_ranges
#check @RawAssembly.inner_step_match
#print RawAssembly.inner_step_match
#check @RawAssembly.inner8_from_actual_inner7
#print RawAssembly.inner8_from_actual_inner7
#check @RawAssembly.depth_from_local_domains
#print RawAssembly.depth_from_local_domains
#check @RawAssembly.top_from_local_domains
#print RawAssembly.top_from_local_domains
#check @RawAssembly.raw_prefix_totality_from_local_domains
#print RawAssembly.raw_prefix_totality_from_local_domains
#check @RawAssembly.emitted_corollary
#print RawAssembly.emitted_corollary
#check @RawAssembly.all_append
#print RawAssembly.all_append
#check @RawAssembly.inner8_length
#print RawAssembly.inner8_length
#check @RawAssembly.depth_length
#print RawAssembly.depth_length
#check @RawAssembly.top_length
#print RawAssembly.top_length
#check @RawAssembly.all_local_words_finite
#print RawAssembly.all_local_words_finite
#check @RawAssembly.snapshot_read_before_reuse
#print RawAssembly.snapshot_read_before_reuse
#check @RawAssembly.fixed_profile_and_late_guard
#print RawAssembly.fixed_profile_and_late_guard
#print RawAssembly.Ops
#print RawAssembly.LocalDomains
#print RawAssembly.depth
#print RawAssembly.top
#print RawAssembly.rawPrefix
#print RawAssembly.treeStore
#print RawAssembly.keepAfterGram
