# T03-B RUN_002 — niezależny odbiór częściowy

**Werdykt: PASS_SCOPED_REVIEW dla BLOCKED_UPSTREAM_EXPORTS.** Recenzent: GPT-6 Sol Fast (`openai/gpt-6-sol-fast`, wariant Fast), świeży kontekst, sesja `ses_f13139bc5ffeFI41laN8mgF1PA`; autor był GPT-6 Astra Fast (`openai/gpt-6-astra-fast`), sesja `ses_f13640949ffeJ0RtC7tFAz07UR`. Projekt Niirmata; zachowano atrybucję Falcon Project / Thomas Pornin i licencje. Odbiór nie dotyczy pełnego B-gap.

## R1. Integralność

Zewnętrzne SHA-256 raportu `b2e8c9af003edee089b49156541e631e3ab8bb01c93f9cad521edf7b66a59dfc` i OUTPUTS `12df61056ddada2f79c1b94b3b17e8f326db2b3a2cbe53d1694754d79d7958cc` zgadzają się. `audit_inputs.py` ponownie wyliczył exact sets/hashes/no symlinks: 1946 review inputs (76241324 B), 1939 autor outputs (75969266 B), 1437 author inputs, 1396 bootstrap (32721541 B), 17 source17 oraz 14 source spans. Żaden cache/bin/olean nie jest wymaganym outputem według OUTPUT_SCOPE. `audit_claim.py` sprawdził 15 nazw, pełne typy/terms, odczytane aksjomaty i źródła; 13 manifestowanych receipts/57 kroków/114 raw logów z SHA i kodami wyjścia. Biblioteki ponownie przechodzi gate w świeżym replayu.

## R2–R3. Lokalna algebra i ledger

`formal/Ledger.lean` i `Audit.lean` zawierają 15 twierdzeń w ogólnym `CommRing`/`AddMonoidHom` oraz arytmetyczne `ℚ`; brak twierdzenia dla osiągniętego wykonania C. W szczególności `ledger_first/second` są tożsamościami pod przesłanką `lambda*q=Cw`, a `inverse_sum` wymaga *dostarczonego* addytywnego homomorfizmu, nie tworzy fizycznego iFFT. `A4+B=-Z DeltaB`, z `B=(t−Z)DeltaB`; stara historyczna nazwa B nie autoryzuje przeniesienia jej starej majoranty. Common reciprocal anulowany w drugiej współrzędnej dotyczy wspólnego `nu`, nie dwóch niezależnych błędów. `D` drugiej pary to `y*w11+x*w01` dla starego `x`; `A_total` jest crosscheck sumy, nie jedenastym składnikiem. A1–D są root-space, E jest coefficient-space: do transportu konieczny fizyczny `I`, a lemat ledgeru z `e` stosować przy `e=0`, potem dodać E. Błąd komponentu musi dostać czynnik `sqrt(2)` przy modulus. Source spans wiążą bajty, nie execution theorem.

## R4. Terminal old-target

Zweryfikowany `falcon-sign.c:1633–1650` robi `r1=old_t1−Y1`, `rx=half(r1)`, `mu0=add(old_t0,rx)`, `sub0=mu0−Y0`, `z0=sub0−rx`; H6P xi0 definiuje się względem **actual updated** mu0. Algebraicznie `z0−(old_t0−Y0)=eadd1643+esub+elast`, jeżeli ten sam stored `rx` jest użyty w obu miejscach. Jego half rounding znika w tej równości, ale update-add nie znika; dla stale snapshot dochodzi różnica produktów. Publiczne dwa local fixtures mają ±1/33554432 update defect, zerowe half/pozostałe sub defects i final raw z0 związany z recomputed pure primitives, bez świadectwa emitted/history membership. To diagnoza brakującego transportu 3072 defektów, **nie kontrprzykład required domain**.

## R5. Arytmetyka

Własny `reviewer_arithmetic.sage` odczytuje pierwotne pinned JSON i używa `ZZ/QQ`, preparsera, `RealIntervalField(256)` oraz sprawdzonych z góry racjonalnych endpointów pierwiastków. Ponownie rozdziela historyczne dziesięć majorant, A_total, old ablation; wyprowadza D z oryginalnego U/eta/Ps/PL i wariant per-vector, A3 z pełnych rational rho i modulus caps, a sumę warunkową. Dokładne QQ równe deklarowanym; RIF: historyczna suma ≈6086.40076164597, ablacja ≈16.10835955645, warunkowe D ≈11.07859486908, A3 ≈0.42676412142, suma reszty ≈11.51331244515; budżet 6557/16000<1/2 to cel, nie bound. Równolegle wielomiany obu współrzędnych ledgeru oraz raw C words/rint są sprawdzane niezależnie. Żadna poprawa liczbowa nie jest nową instancją source theorem.

## R6. Blokady

Siedem statusów `OPEN_NOT_ASSUMED` potwierdzono z dowodami pochodzenia. P02 local freeze 68/68 nadal nie jest akceptacją V02. Kopia frozen P02 `ScalarCalls.lean` dispatchuje tylko `fpr_ursh/irsh/ulsh`; `PrimObligation fpr_add/mul/div/sqrt` nie ma realizacji przez ten dispatcher i brak real-error/caller-domain bounds. P06 reference/ring, P07 uniform basis, INTEGER_DEFECT_TRANSPORT, fizyczny inverse/iFFT, P02 real-rint pozostają otwarte. `source_gap=null` i `full_recovery=false` są zgodne z danymi.

## R7–R8. Kontrole i historia

Failed attempts: `initial_001` miał external 120s timeout w trakcie gate, bez końcowego receiptu; `normal_001` skończył exit1 w Sage JSON Integer serialization przed C; `finalize_001` wykrył ucięte drukowane terms `⋯` (104 znaki w starym logu), `audit_001` drukuje pełne terms; `finalize_002` odrzucił universe suffix `Quot.sound.{u}`, reporting-only `packaging/seal.py` zachowuje oryginalne nazwy. Żadna z tych tras nie jest poprawką do source algebra. Kontrole missing D/A3, double A_total, wrong suffix sign/stale operand, omitted terminal update, endpoint shrink i component/modulus mają wykrywalne różnice; `noop` jest tautologicznym baseline, nie silnym mutacyjnym testem. Publiczne rint ties/parity/±0/subnormals to skończone fixture, nie uniform bridge. Sanitizery to osobne joby, nie produkty dziesięciu semantic matches.

**Dalszy krok:** `NEXT_INTERFACE.md`. Bez source-instantiated boundu i prawdziwej domeny nie ma integer recovery ani nowego security claimu. Status autora BLOCKED_UPSTREAM_EXPORTS jest prawidłowy w tym zakresie; werdykt review, komplet wyników świeżego replayu i sanitizery są zapisane w REVIEW_RESULT.json i powiązanych receiptach.

**Fresh joby recenzenta:** `run/fresh_001` zachował nieudaną próbę izolacji (`/proc` RO → nested bwrap uid-map denied; jeszcze przed toolchain gate); poprawiona izolacja `--proc /proc --dev-bind /dev /dev` w nowym `run/fresh_002` dała FRESH_REPLAY_PASS, 7/7 exit0, 10/10 bajtowo równych produktów, w tym FORMAL_TYPES_TERMS porównany z `audit_001`, wszystkie source before/after równe. `run/ubsan_001` i `run/asan_001` osobno: 3/3 exit0 każdy, czyste raw logs, lokalna kontrola C PASS. Własny `Reviewer.lean` kompilował się świeżo z przypiętym Mathlib (`-j1 -M2048`), aksjomaty ograniczone do propext/Classical.choice/Quot.sound; `reviewer_arithmetic.sage` z preparserem exit0. Pierwsze robocze próby własnego Sage ujawniły błędy ścieżki preparsera, pomyłkę ramy `z0` vs `z0−t0`, zapis nazw wielomianu i serializację Sage Integer; po korekcie kontrola jest kompletna. Pierwsze trzy stderr zostały nadpisane i nie są przedstawiane jako zachowane raw logs; jawna historia jest w `REVIEWER_FAILED_ATTEMPTS.md`. Końcowy przebieg i raw logs/receipts replayu, sanitizerów i Lean są skopiowane do `evidence/`. Wszystkie joby zakończone, source author niezmieniony.
