#!/usr/bin/env python3
"""Emit lexical witnesses; Lean checks every token against the pinned C bytes."""
import json
from pathlib import Path
import re
import sys

import job

SPANS = {
    'Lift': [(5924,31),(5955,6),(5961,42),(6003,21),(6024,87),(6111,7)],
    'Reduce': [(6222,30),(6252,22),(6274,24),(6298,17),(6315,19),(6334,19)],
    'Top': [(5805,19),(5824,14),(5838,23),(5861,37),(5898,18),(6119,80),(6199,22),(6354,36)],
}


def main():
    source = job.OLD / 'inputs/source/falcon-keygen.c'
    profile = json.loads((source.parent / 'PROFILE.json').read_text())
    assert job.sha(source) == profile['core']['source_files'][source.name]
    lines = source.read_text().splitlines(keepends=True)
    lexer = re.compile(r'[A-Za-z0-9_]+|>>=|<<=|\+\+|>>|<<|&&|\|\||[+\-*^&|=!<>]=|[(){}\[\];,^&|\-+*~=!<>.?:/%]')
    for family, spans in SPANS.items():
        for i, (start, count) in enumerate(spans):
            text = ''.join(lines[start-1:start-1+count]) + '}'
            text = re.sub(r'/\*.*?\*/|//[^\n]*', ' ', text, flags=re.S)
            tokens = []
            end = 0
            for match in lexer.finditer(text):
                assert not text[end:match.start()].strip(), text[end:match.start()]
                t = match.group()
                tokens.append('uint64_t' if t == 'size_t' else t)
                end = match.end()
            assert not text[end:].strip()
            name = 'KeygenIntermediateTokens' + family + str(i)
            chunks = [tokens[j:j+12] for j in range(0,len(tokens),12)]
            groups = []
            current = []
            in_comment = False
            for j,line in enumerate(lines[start-1:start-1+count]):
                current.append(j)
                for marker in re.findall(r'/\*|\*/',line):
                    if marker == '/*':
                        assert not in_comment
                        in_comment = True
                    else:
                        assert in_comment
                        in_comment = False
                if not in_comment:
                    groups.append(current)
                    current = []
            assert not current and not in_comment
            lexical_defs = []
            for j,group in enumerate(groups):
                group_text = ''.join(lines[start-1+k] for k in group)
                clean = re.sub(r'/\*.*?\*/|//[^\n]*',' ',group_text,flags=re.S)
                words = ['uint64_t' if m.group()=='size_t' else m.group() for m in lexer.finditer(clean)]
                lexical_defs.extend([
                    'def group'+str(j)+' : List String := ['+','.join('text'+str(k) for k in group)+']',
                    'def words'+str(j)+' : List B20.C.Token := ['+','.join(json.dumps(t) for t in words)+'].map String.toList',
                    'theorem lex'+str(j)+' : KeygenLexicalChunks.Checked group'+str(j)+' words'+str(j)+' := by\n  constructor <;> decide +kernel'])
            group_list = '['+','.join('group'+str(j) for j in range(len(groups)))+']'
            word_list = '['+','.join('words'+str(j) for j in range(len(groups)))+']'
            lexical_terms = 'List.Forall₂.nil'
            for j in reversed(range(len(groups))):
                lexical_terms = 'List.Forall₂.cons lex'+str(j)+' ('+lexical_terms+')'
            token_defs = '\n'.join(lexical_defs)
            source_defs = '\n'.join('def text'+str(j)+' : String := '+json.dumps(line)
                for j,line in enumerate(lines[start-1:start-1+count]))
            source_tails = [f'def tail{count} : List String := []']
            for j in reversed(range(count)):
                source_tails.append(f'def tail{j} : List String := text{j}::tail{j+1}')
            line_checks = '\n'.join(f'theorem line{j} : Pinned.keygenLines[{start-1+j}]?=some text{j} := by decide +kernel'
                for j,line in enumerate(lines[start-1:start-1+count]))
            tail_proofs = [f'theorem bytes{count} : (Pinned.keygenLines.drop {start-1+count}).take tail{count}.length=tail{count} := rfl']
            for j in reversed(range(count)):
                tail_proofs.append(f'theorem bytes{j} : (Pinned.keygenLines.drop {start-1+j}).take tail{j}.length=tail{j} :=\n'
                    f'  KeygenSourceLines.consSlice Pinned.keygenLines {start-1+j} text{j} tail{j+1} line{j} bytes{j+1}')
            content = f'''import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.{name}
{source_defs}
{chr(10).join(source_tails)}
def lines : List String := tail0
{line_checks}
{chr(10).join(tail_proofs)}
theorem bytes : (Pinned.keygenLines.drop {start-1}).take {count}=lines := bytes0
{token_defs}
def groups : List (List String) := {group_list}
def words : List (List B20.C.Token) := {word_list}
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := {lexical_terms}
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop {start-1}).take {count}) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.{name}
'''
            path = job.ROOT / 'formal/Source3' / (name+'.lean')
            if path.exists():
                if '--refresh' in sys.argv:
                    assert 'Generated by tools/keygen_intermediate_tokens.py' in path.read_text(), path
                    path.write_text(content)
                else:
                    assert path.read_text() == content, path
            else:
                path.write_text(content)
            print(path.relative_to(job.ROOT))
            if '--probe-prefix' in sys.argv and family == 'Lift' and i == 0:
                probe = content[:content.index('def group0')]
                probe += 'end FT1536.Source3.' + name + '\n'
                probe = probe.replace(name, 'KeygenTokenPinProbe')
                (job.ROOT / 'formal/Source3/KeygenTokenPinProbe.lean').write_text(probe)


if __name__ == '__main__':
    main()
