#!/usr/bin/env python3
"""Generate the complete BATCH_028 declaration/type/term/axiom audit."""
from collections import defaultdict
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MODULES = [
    'KeygenZintCall', 'KeygenZintExtract', 'KeygenZintCore', 'KeygenZintTop',
    'KeygenZintPoly', 'KeygenZintScaled', 'KeygenPolySubScaled',
    'KeygenBinaryNtt', 'KeygenMakeFgSource', 'KeygenDeepestSource',
]
INHERITED = [
    'KeygenMaterial.Represents', 'KeygenIntegerLift.Bound',
    'KeygenDepth0Call.call_gate_validated', 'KeygenOutputGateValidation.Validation',
    'KeygenSearchContext.Context', 'KeygenSearchContext.ReadLogn',
    'KeygenSearchContext.ReadTernary', 'KeygenSearchContext.ReadTmp',
    'C99ArrayReference.Bind', 'C99ArrayReference.Pointer',
    'C99ProcedureReference.ReturnValue', 'C99MemoryReference.Load32',
    'C99MemoryReference.Load64', 'C99MemoryReference.Store32',
    'C99MemoryReference.Store64', 'FprPrefixCalls.calls',
    'C99ModularReference.ModCall', 'KeygenMakeFgTop.Call',
]


def declarations():
    names = []
    for module in MODULES:
        text = (ROOT / 'formal/Source3' / (module + '.lean')).read_text()
        found = re.findall(r'^\s*(?:def|theorem|structure|inductive)\s+(\w+(?:\.\w+)*)', text, re.M)
        assert found and len(found) == len(set(found)), module
        names.extend('FT1536.Source3.' + module + '.' + name for name in found)
    return names


def main():
    groups = defaultdict(list)
    for name in declarations():
        namespace, declaration = name.rsplit('.', 1)
        groups[namespace].append(declaration)
    template = (ROOT / 'formal/Source3/KeygenLevelsAudit.lean').read_text()
    suffix = template[template.index('  let names := groups.flatMap'):].replace('LEVELS_AUDIT', 'ZINT_AUDIT')
    header = ''.join('import Source3.' + module + '\n' for module in MODULES)
    header += 'import Source3.KeygenDepth0Call\nimport Lean.Util.CollectAxioms\n\n'
    header += 'set_option maxRecDepth 32768\nset_option maxHeartbeats 2000000\n'
    header += 'set_option pp.proofs true\nset_option pp.deepTerms true\nset_option pp.fullNames true\n'
    header += 'set_option pp.universes true\nset_option pp.maxSteps 200000\n\n'
    header += '/- Generated by tools/keygen_zint_audit_source.py. Internal audit, not independent review. -/\n'
    header += 'run_cmd Lean.Elab.Command.liftTermElabM do\n'
    header += '  let groups : Array (Lean.Name × List String) := #[\n' + ',\n'.join(
        '    (`' + namespace + ',\n      [' + ','.join('"' + name + '"' for name in names) + '])'
        for namespace, names in groups.items()) + ']\n'
    header += '  let inherited : Array Lean.Name := #[\n' + ',\n'.join(
        '    ``FT1536.Source3.' + name for name in INHERITED) + ']\n'
    (ROOT / 'formal/Source3/KeygenZintAudit.lean').write_text(header + suffix)
    print({'modules': len(MODULES), 'declarations': len(declarations()), 'inherited': len(INHERITED)})


if __name__ == '__main__':
    main()
