#!/usr/bin/env python3
"""Generate the full named-declaration audit for the BATCH_023 midpoint."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MODULES = [
    'KeygenSearchFft', 'KeygenSearchProbe', 'KeygenSearchMemory',
    'KeygenSearchLeaves', 'KeygenSearchContext', 'KeygenSearchExec',
    'KeygenSearchFrame', 'KeygenSearchParser', 'KeygenDepth0Source',
    'KeygenDepth0Call', 'KeygenDepth0Return',
]
INHERITED = [
    'KeygenOutputGateValidation.gate_validated', 'KeygenOutputGateValidation.Validation',
    'KeygenOutputGateBounds.gate_material', 'KeygenSamplerCalls.two_calls',
    'KeygenSolverEquation.Bounds', 'KeygenSolverEquation.Equation',
    'KeygenIntegerLift.Bound', 'KeygenMaterial.Represents',
    'C99ArrayReference.Bind', 'C99ProcedureReference.ReturnValue',
    'C99MemoryReference.Load32', 'C99MemoryReference.Load64',
    'C99MemoryReference.Store32', 'C99MemoryReference.Store64',
    'KeygenSmallSource.PlainCall', 'FprPrefixCalls.calls',
]


def main():
    groups = []
    count = 0
    for module in MODULES:
        text = (ROOT/'formal/Source3'/(module+'.lean')).read_text()
        names = re.findall(r'^\s*(?:def|theorem|structure|inductive)\s+(\w+)', text, re.M)
        assert names and len(names) == len(set(names)), module
        count += len(names)
        groups.append('    (`FT1536.Source3.'+module+',\n      ['+
            ','.join('"'+n+'"' for n in names)+'])')
    previous = (ROOT/'formal/Source3/KeygenSmallBoundsAudit.lean').read_text()
    suffix = previous[previous.index('  let names := groups.flatMap'):]
    suffix = suffix.replace('SMALL_BOUNDS_AUDIT', 'SEARCH_AUDIT')
    header = ''.join('import Source3.'+m+'\n' for m in MODULES)
    header += 'import Source3.KeygenSamplerCalls\n'
    header += 'import Lean.Util.CollectAxioms\n\n'
    header += 'set_option maxRecDepth 32768\nset_option maxHeartbeats 2000000\n'
    header += 'set_option pp.proofs true\nset_option pp.deepTerms true\nset_option pp.fullNames true\n'
    header += 'set_option pp.universes true\nset_option pp.maxSteps 200000\n\n'
    header += '/- Generated by tools/keygen_search_audit_source.py. Internal audit, not independent review. -/\n'
    header += 'run_cmd Lean.Elab.Command.liftTermElabM do\n'
    header += '  let groups : Array (Lean.Name × List String) := #[\n'+',\n'.join(groups)+']\n'
    header += '  let inherited : Array Lean.Name := #[\n'
    header += ',\n'.join('    ``FT1536.Source3.'+n for n in INHERITED)+']\n'
    target = ROOT/'formal/Source3/KeygenSearchAudit.lean'
    target.write_text(header+suffix)
    print({'modules': len(MODULES), 'new_declarations': count, 'inherited': len(INHERITED),
        'audit_source': str(target.relative_to(ROOT))})


if __name__ == '__main__':
    main()
