#!/usr/bin/env python3
"""Generate the complete named-declaration audit for the BATCH_022 midpoint."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MODULES = [
    'KeygenOutputGateSource','KeygenOutputGateBounds','ShakeSource','ShakeBlock',
    'ShakeBlockProgram','ShakeEncode','ShakeExtractSource','ShakeRcBinding',
    'ShakeExtractBinding','ShakeExtractFrame','KeygenRngSource','KeygenSamplerSource',
    'KeygenSamplerInner','KeygenSamplerBounds','KeygenSamplerFrame','KeygenSamplerCalls',
    'KeygenOutputGateValidation',
]

def main():
    groups=[]
    for module in MODULES:
        text=(ROOT/'formal/Source3'/(module+'.lean')).read_text()
        names=re.findall(r'^\s*(?:def|theorem|structure|inductive)\s+(\w+)',text,re.M)
        assert names and len(names)==len(set(names)),module
        groups.append('    (`FT1536.Source3.'+module+',\n      ['+','.join('"'+n+'"' for n in names)+'])')
    previous=(ROOT/'formal/Source3/KeygenSmallBoundsAudit.lean').read_text()
    suffix=previous[previous.index('  let names := groups.flatMap'):]
    suffix=suffix.replace('SMALL_BOUNDS_AUDIT','EXECUTION_AUDIT')
    header=''.join('import Source3.'+m+'\n' for m in MODULES)
    header+='import Lean.Util.CollectAxioms\n\n'
    header+='set_option maxRecDepth 32768\nset_option maxHeartbeats 2000000\n'
    header+='set_option pp.proofs true\nset_option pp.deepTerms true\nset_option pp.fullNames true\n'
    header+='set_option pp.universes true\nset_option pp.maxSteps 200000\n\n'
    header+='/- Generated by tools/keygen_execution_audit_source.py. Full internal audit; not review. -/\n'
    header+='run_cmd Lean.Elab.Command.liftTermElabM do\n'
    header+='  let groups : Array (Lean.Name × List String) := #[\n'+',\n'.join(groups)+']\n'
    header+='  let inherited : Array Lean.Name := #[\n'
    inherited=[
        'KeygenSmallCalls.bound_call','KeygenSmallBounds.source_material',
        'KeygenTernaryStore.accepted_store','KeygenTernaryStore.rejected_heap',
        'KeygenSolverValidation.generated_converted_checked','KeygenSolverEquation.Bounds',
        'KeygenSolverEquation.Equation','KeygenIntegerLift.Bound','KeygenMaterial.Represents',
        'C99MemoryReference.Load64','C99MemoryReference.Store64','C99MemoryReference.Memcpy',
        'C99ArrayReference.Bind','KeygenSmallOutput.Store16',
    ]
    header+=',\n'.join('    ``FT1536.Source3.'+n for n in inherited)+']\n'
    target=ROOT/'formal/Source3/KeygenExecutionAudit.lean'
    target.write_text(header+suffix)
    print({'modules':len(MODULES),'new_declarations':sum(len(re.findall(r'"([A-Za-z_0-9]+)"',g)) for g in groups),
           'inherited':len(inherited),'audit_source':str(target.relative_to(ROOT))})

if __name__=='__main__':
    main()
