#!/usr/bin/env python3
"""Embed the pinned public-helper and header bytes for kernel source checks."""
import json
from pathlib import Path
import job


def main():
    files = [('internal.h', 'internalLines'), ('falcon-vrfy.c', 'vrfyLines')]
    profile = json.loads((job.OLD / 'inputs/source/PROFILE.json').read_text())
    lines = ['/- Pinned M0 source bytes. Generated by tools/keygen_attempt_sources.py. -/',
             'namespace FT1536.Source3.KeygenAttemptPin', '']
    pins = {}
    for filename, name in files:
        source = job.OLD / 'inputs/source' / filename
        pins[filename] = job.sha(source)
        lines += [f'def {name} : List String := [']
        lines += ['  ' + json.dumps(line, ensure_ascii=False) + ','
                  for line in source.read_text().splitlines(keepends=True)]
        lines[-1] = lines[-1].removesuffix(',') + ']'
        lines += ['']
    lines += ['end FT1536.Source3.KeygenAttemptPin', '']
    target = job.ROOT / 'formal/Source3/KeygenAttemptPin.lean'
    assert not target.exists(), 'Do not replace an existing source snapshot'
    target.write_text('\n'.join(lines))
    print(json.dumps({'source_pins': pins, 'profile_sha256': job.sha(job.OLD / 'inputs/source/PROFILE.json'),
                     'generated_sha256': job.sha(target), 'profile_present': bool(profile)}, indent=2))


if __name__ == '__main__':
    main()
