#!/usr/bin/env python3
"""Generate BATCH_033 full public-helper types/terms/constructors/axioms."""
from collections import defaultdict
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MODULES = ['KeygenPublicLinear', 'KeygenPublicLeafWords', 'KeygenPublicMontgomery',
           'KeygenPublicAlgebra', 'KeygenPublicArguments', 'KeygenPublicSquare',
           'KeygenPublicDivisionWords', 'KeygenPublicDivisionAlgebra', 'KeygenPublicRoots']
INHERITED = ['KeygenPublicScalar.Kind', 'KeygenPublicScalar.params',
             'KeygenPublicScalar.code', 'KeygenPublicScalar.parsed_source',
             'KeygenPublicScalar.Body', 'KeygenPublicScalar.Leaf',
             'KeygenPublicScalar.Square', 'KeygenPublicScalar.Call',
             'KeygenPublicSource.Call', 'KeygenPublicSource.code_checked',
             'KeygenPublicWord.Eval', 'KeygenPublicWord.Bind', 'KeygenPublicExec.Exec',
             'C99ModularReference.GenEval', 'C99ModularReference.GenExec',
             'C99ModularReference.bindParams', 'C99ArrayReference.scalar',
             'C99ScalarReference.BindArgs', 'C99ProcedureReference.ReturnValue',
             'KeygenMaterial.Represents', 'KeygenMkgm3Indices.tableExponent',
             'KeygenMkgm3IndexCert.all_indices', 'MontgomeryArithmetic.reduction_contract']


def declarations():
    names = []
    for module in MODULES:
        text = (ROOT/'formal/Source3'/(module+'.lean')).read_text()
        found = re.findall(r'^\s*(?:def|abbrev|theorem|structure|inductive|instance)\s+(\w+(?:\.\w+)*)', text, re.M)
        assert found and len(found) == len(set(found)), module
        names.extend('FT1536.Source3.'+module+'.'+name for name in found)
    return names


def main():
    groups = defaultdict(list)
    for name in declarations():
        namespace, declaration = name.rsplit('.', 1)
        groups[namespace].append(declaration)
    template = (ROOT/'formal/Source3/KeygenLevelsAudit.lean').read_text()
    suffix = template[template.index('  let names := groups.flatMap'):].replace('LEVELS_AUDIT', 'PUBLIC_AUDIT')
    suffix = suffix.replace(
        '    IO.FS.writeFile "../PUBLIC_AUDIT_PARTIAL.json" (Lean.Json.arr rows |>.pretty)',
        '    IO.FS.withFile "../PUBLIC_AUDIT_ENTRIES.jsonl" .append fun stream =>\n'
        '      stream.putStrLn rows.back!.compress')
    header = ''.join('import Source3.'+module+'\n' for module in MODULES)
    header += 'import Source3.KeygenPublicSource\nimport Lean.Util.CollectAxioms\n\n'
    header += 'set_option maxRecDepth 32768\nset_option maxHeartbeats 2000000\n'
    header += 'set_option pp.proofs true\nset_option pp.deepTerms true\nset_option pp.fullNames true\n'
    header += 'set_option pp.universes true\nset_option pp.maxSteps 200000\n\n'
    header += '/- Generated by tools/keygen_public_audit_source.py. Internal audit, not independent review. -/\n'
    header += 'run_cmd Lean.Elab.Command.liftTermElabM do\n'
    header += '  let groups : Array (Lean.Name × List String) := #[\n'+',\n'.join(
        '    (`'+namespace+',\n      ['+','.join('"'+name+'"' for name in names)+'])'
        for namespace,names in groups.items())+']\n'
    header += '  let inherited : Array Lean.Name := #[\n'+',\n'.join(
        '    ``FT1536.Source3.'+name for name in INHERITED)+']\n'
    (ROOT/'formal/Source3/KeygenPublicAudit.lean').write_text(header+suffix)
    print({'modules':len(MODULES),'declarations':len(declarations()),'inherited':len(INHERITED)})


if __name__ == '__main__':
    main()
