#!/usr/bin/env python3
"""Generate the BATCH_029 full declaration/type/term/axiom audit."""
from collections import defaultdict
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MODULES = [
    'KeygenPolySubNtt', 'KeygenIntermediateMemory', 'KeygenBinaryFft',
    'KeygenIntermediateCalls', 'KeygenIntermediateExec', 'KeygenIntermediateParser',
    'KeygenSourceLines', 'KeygenIntermediateCoverage', 'KeygenLexicalChunks',
] + ['KeygenIntermediateTokens' + family + str(i)
     for family, count in [('Lift',6), ('Reduce',6), ('Top',8)] for i in range(count)] + [
    'KeygenIntermediateLiftData',
] + ['KeygenIntermediateLiftCheck' + str(i) for i in range(6)] + [
    'KeygenIntermediateLift', 'KeygenIntermediateReduceData',
] + ['KeygenIntermediateReduceCheck' + str(i) for i in range(6)] + [
    'KeygenIntermediateReduce', 'KeygenIntermediateSource', 'KeygenStaticTables',
    'KeygenPrimeTablesBinary', 'KeygenPrimeTablesTernaryLow', 'KeygenPrimeTablesTernaryHigh',
    'KeygenPrimeTableBinding', 'KeygenStaticReads',
]
INHERITED = [
    'KeygenMaterial.Represents', 'KeygenIntegerLift.Bound',
    'KeygenDeepestSource.Call', 'KeygenDeepestSource.material',
    'KeygenDepth0Call.call_gate_validated', 'KeygenOutputGateValidation.Validation',
    'KeygenSearchContext.Context', 'KeygenSearchContext.ReadLogn',
    'KeygenSearchContext.ReadTernary', 'KeygenSearchContext.ReadTmp',
    'KeygenPolySubScaled.Exec', 'KeygenZintCall.Exec',
    'KeygenMakeFgSource.Call', 'KeygenZintPoly.Call',
    'C99MemoryReference.Load32', 'C99MemoryReference.Load64',
    'KeygenSearchMemory.Cast', 'KeygenSearchMemory.Memmove',
]


def declarations():
    names = []
    for module in MODULES:
        text = (ROOT / 'formal/Source3' / (module + '.lean')).read_text()
        found = re.findall(r'^\s*(?:def|abbrev|theorem|structure|inductive)\s+(\w+(?:\.\w+)*)', text, re.M)
        assert found and len(found) == len(set(found)), module
        names.extend('FT1536.Source3.' + module + '.' + name for name in found)
    return names


def main():
    groups = defaultdict(list)
    for name in declarations():
        namespace, declaration = name.rsplit('.', 1)
        groups[namespace].append(declaration)
    template = (ROOT / 'formal/Source3/KeygenLevelsAudit.lean').read_text()
    suffix = template[template.index('  let names := groups.flatMap'):].replace('LEVELS_AUDIT', 'INTERMEDIATE_AUDIT')
    suffix = suffix.replace(
        '    IO.FS.writeFile "../INTERMEDIATE_AUDIT_PARTIAL.json" (Lean.Json.arr rows |>.pretty)',
        '    IO.FS.withFile "../INTERMEDIATE_AUDIT_ENTRIES.jsonl" .append fun stream =>\n'
        '      stream.putStrLn rows.back!.compress')
    header = ''.join('import Source3.' + module + '\n' for module in MODULES)
    header += 'import Source3.KeygenDeepestSource\nimport Source3.KeygenDepth0Call\nimport Lean.Util.CollectAxioms\n\n'
    header += 'set_option maxRecDepth 32768\nset_option maxHeartbeats 2000000\n'
    header += 'set_option pp.proofs true\nset_option pp.deepTerms true\nset_option pp.fullNames true\n'
    header += 'set_option pp.universes true\nset_option pp.maxSteps 200000\n\n'
    header += '/- Generated by tools/keygen_intermediate_audit_source.py. Internal audit, not independent review. -/\n'
    header += 'run_cmd Lean.Elab.Command.liftTermElabM do\n'
    header += '  let groups : Array (Lean.Name × List String) := #[\n' + ',\n'.join(
        '    (`' + namespace + ',\n      [' + ','.join('"' + name + '"' for name in names) + '])'
        for namespace, names in groups.items()) + ']\n'
    header += '  let inherited : Array Lean.Name := #[\n' + ',\n'.join(
        '    ``FT1536.Source3.' + name for name in INHERITED) + ']\n'
    (ROOT / 'formal/Source3/KeygenIntermediateAudit.lean').write_text(header + suffix)
    print({'modules': len(MODULES), 'declarations': len(declarations()), 'inherited': len(INHERITED)})


if __name__ == '__main__':
    main()
