#!/usr/bin/env python3
"""Generate BATCH_024's complete declaration/type/term/axiom audit."""
from collections import defaultdict
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
MODULES=[
    'KeygenLevelModularFrame','KeygenLevelNtt','KeygenLevelCalls','KeygenLevelExec',
    'KeygenLevelParser','KeygenMakeFgTop','KeygenWordExpr','KeygenWordExec',
    'KeygenWordParser','KeygenZintLeaves','KeygenResultantSource','KeygenResultantGate','KeygenNormFrame',
]
INHERITED=[
    'KeygenSamplerCalls.two_calls','KeygenDepth0Call.call_gate_validated',
    'KeygenOutputGateValidation.Validation','KeygenMaterial.Represents','KeygenIntegerLift.Bound',
    'C99ModularReference.ModCall','C99ModularReference.LeafCall',
    'C99ModularReference.r2Body','C99ModularReference.divBody',
    'C99CompareObjects.Exec','C99CompareObjects.exists_execution','C99CompareObjects.source_decomposition',
    'FprCompare.source_parses','FprPrefixCalls.calls','KeygenSearchMemory.Memmove',
    'C99ArrayReference.Bind','C99ProcedureReference.ReturnValue',
    'C99MemoryReference.Load32','C99MemoryReference.Store32','KeygenM0Preprocess.preprocess',
]
PATTERN=r'^\s*(?:def|theorem|structure|inductive)\s+(\w+(?:\.\w+)*)'

def declarations():
    result=[]
    for module in MODULES:
        names=re.findall(PATTERN,(ROOT/'formal/Source3'/(module+'.lean')).read_text(),re.M)
        assert names and len(names)==len(set(names)),module
        result.extend('FT1536.Source3.'+module+'.'+n for n in names)
    return result

def main():
    groups=defaultdict(list)
    names=declarations()
    for name in names:
        namespace,decl=name.rsplit('.',1)
        groups[namespace].append(decl)
    previous=(ROOT/'formal/Source3/KeygenSmallBoundsAudit.lean').read_text()
    suffix=previous[previous.index('  let names := groups.flatMap'):].replace('SMALL_BOUNDS_AUDIT','LEVELS_AUDIT')
    header=''.join('import Source3.'+m+'\n' for m in MODULES)
    header+='import Source3.KeygenDepth0Call\nimport Lean.Util.CollectAxioms\n\n'
    header+='set_option maxRecDepth 32768\nset_option maxHeartbeats 2000000\n'
    header+='set_option pp.proofs true\nset_option pp.deepTerms true\nset_option pp.fullNames true\n'
    header+='set_option pp.universes true\nset_option pp.maxSteps 200000\n\n'
    header+='/- Generated by tools/keygen_levels_audit_source.py. Internal audit, not independent review. -/\n'
    header+='run_cmd Lean.Elab.Command.liftTermElabM do\n'
    header+='  let groups : Array (Lean.Name × List String) := #[\n'+',\n'.join(
        '    (`'+ns+',\n      ['+','.join('"'+n+'"' for n in ds)+'])' for ns,ds in groups.items())+']\n'
    header+='  let inherited : Array Lean.Name := #[\n'+',\n'.join(
        '    ``FT1536.Source3.'+name for name in INHERITED)+']\n'
    (ROOT/'formal/Source3/KeygenLevelsAudit.lean').write_text(header+suffix)
    print({'modules':len(MODULES),'new_declarations':len(names),'inherited':len(INHERITED)})

if __name__=='__main__':
    main()
