#!/usr/bin/env python3
"""Emit bounded kernel checks for every pinned small_prime initializer row."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    groups = [('Binary', 'binary', 0, 33), ('TernaryLow', 'ternary', 0, 35),
              ('TernaryHigh', 'ternary', 35, 34)]
    for suffix, table, start, count in groups:
        name = 'KeygenPrimeTables' + suffix
        lines = ['import Source3.KeygenStaticTables', '',
                 'set_option maxRecDepth 32768', 'set_option maxHeartbeats 2000000', '',
                 '/- Generated by tools/keygen_prime_table_source.py; every equality is kernel checked. -/',
                 'namespace FT1536.Source3.' + name, 'open KeygenStaticTables', '']
        for i in range(start, start + count):
            lines.append(f'theorem chunk{i} : Checked .{table} {i} := by decide')
        lines.extend(['', f'theorem all_chunks (i : Fin {count}) : Checked .{table} (i.val+{start}) := by',
                      '  fin_cases i'])
        for i in range(start, start + count):
            lines.append(f'  · exact chunk{i}')
        lines.extend(['', 'end FT1536.Source3.' + name, ''])
        target = ROOT / 'formal/Source3' / (name + '.lean')
        content = '\n'.join(lines)
        if target.exists():
            assert target.read_text() == content, 'Do not overwrite changed generated source: ' + str(target)
        else:
            target.write_text(content)
        print(target.relative_to(ROOT))


if __name__ == '__main__':
    main()
