#!/usr/bin/env python3
"""Generate separate kernel checks at the intermediate statement boundaries."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    for family in ['Lift', 'Reduce']:
        for i in range(6):
            name = 'KeygenIntermediate' + family + 'Check' + str(i)
            data = 'KeygenIntermediate' + family + 'Data'
            content = f'''import Source3.{data}

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_piece_source.py. -/
namespace FT1536.Source3.{name}
theorem checked : {data}.audit {i}=some true := by decide +kernel
end FT1536.Source3.{name}
'''
            target = ROOT / 'formal/Source3' / (name + '.lean')
            if target.exists():
                assert 'Generated by tools/keygen_intermediate_piece_source.py' in target.read_text(), target
                target.write_text(content)
            else:
                target.write_text(content)
            print(target.relative_to(ROOT))


if __name__ == '__main__':
    main()
