"""Assemble the explicitly mixed source/analytical/kernel certificate."""
import difflib,json
from pathlib import Path
from replaylib import sha
W=Path.cwd()
def load(p):return json.loads((W/p).read_text())
def save(p,x):(W/p).write_text(json.dumps(x,indent=2)+'\n')
C=load('STOPPED_COMPOSITION.json');R=load('RESOURCE_BOUND.json');A=load('artifacts/formal_audit.json');F=load('artifacts/fixtures.json');M=load('artifacts/mutations.json')
assert A['modules']==120 and A['checked_theorems']==922 and A['new_theorems']==26 and A['all_final_logs_clean']
assert F['count']==22 and M['meaningful']==11 and M['noops']==2
assert load('artifacts/sage_qq.json')['status']=='PASS_INDEPENDENT_SAGE_QQ_STOPPED_AND_RESET_ARITHMETIC'
for mode in ['normal','sanitized']:
 native=[]
 for g in range(3):native+=load('artifacts/native_'+mode+'_'+str(g)+'.json')['matches']
 assert len(native)==22 and {r['case'] for r in native}=={r['name'] for r in F['cases']}
 for r in native:assert r['exact_trace_targets_bytes_frames'] and r['stdout_sha256']==sha(W/'logs'/('native_'+mode+'_'+r['case']+'.stdout'))
 assert len(load('artifacts/reset_'+mode+'.json')['cases'])==6
for script in ['audit','kernel_build','binding','build']:
 old=W/'inputs/bootstrap/H6P/scripts'/(script+'.py');new=W/'scripts'/(script+'.py')
 (W/'artifacts/diffs'/(script+'.patch')).write_text(''.join(difflib.unified_diff(old.read_text().splitlines(True),new.read_text().splitlines(True),fromfile=old.relative_to(W).as_posix(),tofile=new.relative_to(W).as_posix())))
S=dict(schema='IID_RETRY_SCHEDULER_V1',source='source/falcon-sign.c',region=[3327,3421],initial_counter=0,cap=16,guard=dict(line=3332,increment_before_test=True,first_rejecting_counter=17,before_init_and_root=True),init=3356,fault_reset=3357,root_call=3372,root_entry=1897,fault_check=3374,norm=3388,first_accept_break=3403,encode=3412,encode_failure_return=3418,header=3420,positive_return=3421,norm_on='stored narrow16 vectors',norm_predicate='Q<2093922385',reached_count='J=sum_{j=1}^{16} 1_Rj; 1<=J<=16 almost surely; no geometric law assumed',unreached_source_outputs=False,encoder_failure_retries=False,inner_nonreturn_observation='NONRETURN, not ZERO',all_future_entries_assumed=False)
save('SCHEDULER.json',S)
ledger=dict(schema='IID_RETRY_ERROR_LEDGER_V1',new_floating_approximations=False,upstream_complete_source_error_bound=1095,per_root_p_outward=C['per_root_p_outward'],whole_region_union=C['uniform_union_bound'],whole_region_hazard=C['uniform_hazard_bound'],whole_region_power2='2^-80',checked_coupling_cost='same WholeRegionBad, not an additional independent loss',resource_ghost_tail='2^-1020',resource_sufficient_event=R['ghost_budget_sufficient_event'],success_denominator_lower_bound=None,real_PRNG_loss=None,new_M0_eta_pre=None)
save('ERROR_LEDGER.json',ledger)
closed=[('READY_ENTRY','REGION_ENTRY.md','one post-H2P legal current state, not assumed future entries'),('SOURCE_REENTRY_FRAME','REENTRY_AND_FRAME.md','guard/context/target/root/post frame induction including bad rejected histories'),('GLOBAL_IID_FILTRATION','FILTRATION.md','fresh independent blocks at init/refill with source state projection and admissible PAST'),('STOPPED_SCHEDULER_AS_RETURN','SCHEDULER.md','actual cap16 and conditional a.s. root composition; ZERO/BYTES/NONRETURN'),('H6P_EVERY_REACHED_ENTRY','STOPPED_COMPOSITION.md','uniform H6P consumed after source premises and fresh-tail discharge'),('WHOLE_REGION_BAD','STOPPED_COMPOSITION.md','joint BOTH-vector event across all completed reached attempts; <=2^-80'),('CHECKED_PUBLIC_COUPLING','CHECKED_PRECAST_COUPLING.md','first pre-store range guard, equal-until-bad and tagged/public TV'),('RESET_RESOURCE_INTERFACE','RESOURCE_BOUND.md','initial blocks/getter drops/reinit abandonment, simultaneous finite ghost budgets'),('EXACT_BYTES','OBSERVATIONS_AND_BYTES.md','strict stored norm, one STATIC encode, exact <=3160 returned bytes')]
flags={k:False for k in ['real_PRNG_bridge','H2P_prefix_termination','whole_real_Sign','universal_Safe16','reference_integer_recovery','Sign_to_Verify','security','CT']}
ob=dict(schema='IID_RETRY_OBLIGATIONS_V1',closed=[dict(id=i,status='PROVED_MIXED_SOURCE_ANALYTICAL_KERNEL',proof=p,claim=t) for i,p,t in closed],open=[dict(id=k,status='OPEN_OUTSIDE_REGION_CLAIM') for k in flags],minimal_missing_type_for_this_region_claim=None)
save('OBLIGATIONS.json',ob)
proofs=['CLAIM.md','REGION_ENTRY.md','SCHEDULER.md','SCHEDULER.json','REENTRY_AND_FRAME.md','FILTRATION.md','STOPPED_COMPOSITION.md','STOPPED_COMPOSITION.json','CHECKED_PRECAST_COUPLING.md','RESOURCE_BOUND.md','RESOURCE_BOUND.json','OBSERVATIONS_AND_BYTES.md','PRNG_NEXT_INTERFACE.md','SOURCE_MODEL_BINDING.md','ERROR_LEDGER.md','ERROR_LEDGER.json','COUNTERMODELS.md','FAILED_ROUTES.md','NEXT_INTERFACE.md','REUSED_RESULTS.md','OBLIGATIONS.json']
cert=dict(schema='IID_RETRY_CERTIFICATE_V1',task_id='FT1536_IID_RETRY_COMPOSITION_RUN_001',status='IID_RETRY_COMPOSITION_PROVED_FOR_PINNED_IID_BUFFER_MODEL',author='Niirmata',base='1ba7ae07c17d135fc8eff4aac7b56f8c2b3bc88c',task_sha256=sha(W/'TASK.md'),bootstrap_sha256=sha(W/'inputs/bootstrap/MANIFEST.sha256'),source_manifest_sha256=sha(W/'inputs/bootstrap/CANDIDATE.sha256'),game='G_retry_IID',initial_cut='single ReadyRetryEntry after H2P/canonical hm, before counter3327',region=[3327,3421],domain='emitted/same-STATIC normalized legal buffers, N1536 q18433 logn10 ter1 MODE1 FPEMU STATIC4096 cap16; arbitrary legal entry PAST',PAST='revealed prior reads/outcomes plus allowed latent entry state, excludes current unread/future ideal tape and future norm success',entry_induction='source-derived for every reached history, including earlier Bad plus norm rejection',all_future_entries_assumed=False,independence_of_attempts_assumed=False,reached_count=S['reached_count'],event=C['event'],per_root_p_outward=C['per_root_p_outward'],weighted_bound=C['reached_weighted_bound'],uniform_union_bound=C['uniform_union_bound'],uniform_conditional_hazard_bound=C['uniform_hazard_bound'],whole_region_power2='2^-80',bad_and_positive_bound=C['Bad_and_positive_return_bound'],bad_conditioned_on_positive=C['Bad_conditioned_on_positive_return'],checked_guard='first out-of-range rint immediately before its corresponding store, in original s1[u],s2[u] order, PRECAST_EXIT proof-only',checked_tagged_TV_bound=C['checked_tagged_TV_bound'],public_result='ZERO / exact positive BYTES / NONRETURN; fixed M0 nonce40 framing outside cut; no Verify filter',termination='almost sure region return only in G_retry_IID; null-tape inner nonreturn retained',bytes=dict(header='0xaa',capacity=4096,maximum_returned_length=3160,one_encode_after_first_stored_norm_acceptance=True,padding_to_capacity=False),resources=R,proof_kind='MIXED_UNIVERSAL_SOURCE_ANALYTICAL_KERNEL_EXACT_RATIONAL',fully_kernelized=False,C_compiler_verified=False,formal_boundary=A['boundary'],formal=dict(modules=A['modules'],theorems=A['checked_theorems'],new_theorems=A['new_theorems'],inherited_modules=A['inherited_modules_unchanged'],clean_final_logs=True),controls=dict(native_cases_per_mode=22,reset_cases_per_mode=6,modes=['normal','ASan/UBSan'],meaningful_mutations=11,noops=2,synthetic_Emitted_membership=False),flags=flags,new_M0_eta_pre=None,source_changed=False,production_source_changed=False,new_source_patch_integrated=False,owner_accepted=False,handoff='current user TUI chat only; later owner instruction cancels relay',proof_files={p:sha(W/p) for p in proofs},evidence={p:sha(W/p) for p in ['artifacts/input_validation.json','artifacts/source_binding.json','artifacts/formal_audit.json','artifacts/probability_controls.json','artifacts/mutations.json','artifacts/sage_qq.json']})
save('IID_RETRY_CERTIFICATE.json',cert);print(cert['status'])
