"""Exact stopped-probability and per-reset resource arithmetic, no success-rate premise."""
import json
from fractions import Fraction as Q
from pathlib import Path
from replaylib import sha
W=Path.cwd();I=W/'inputs/bootstrap';h=json.loads((I/'H6P/JOINT_TAIL_BOUND.json').read_text());jr=json.loads((I/'JOINT/RESOURCE_BOUND.json').read_text())
p=Q(h['IID_upper']);assert 0<p<=Q(1,2**84);cap=16;union=cap*p;hazard=1-(1-p)**cap;assert 0<hazard<=union<=Q(1,2**80)
composition=dict(schema='IID_RETRY_STOPPED_COMPOSITION_V1',game='G_retry_IID',initial_cut='post-H2P ReadyRetryEntry, before counter initialization3327',event='WholeRegionBad: exists reached/completed j<=16, joint BadPrecast of BOTH pre-narrow vectors, including norm-rejected attempts',conditioning='one ReadyRetryEntry and legal entry PAST; no unread/future tape or future success conditioning',per_root_p_outward=str(p),per_root_power2='2^-84',reached_weighted_bound='p_outward * sum_j Pr(R_j | ReadyRetryEntry,entry PAST)',uniform_union_bound=str(union),uniform_hazard_bound=str(hazard),power2_bound='2^-80',hazard_proof='conditional bad hazard <=p on reached histories, zero event padding elsewhere; inductive survival >=(1-p)^16, no independence assumption',Bad_and_positive_return_bound=str(hazard),Bad_conditioned_on_positive_return='only min(1,bound/Pr(positive_return)) when denominator>0; no success lower bound proved',checked_tagged_TV_bound=str(hazard),checked_public_projection_TV_bound=str(hazard),all_future_entries_assumed=False,independent_attempts_assumed=False,new_M0_eta_pre=None,dependencies={'H6P/JOINT_TAIL_BOUND.json':sha(I/'H6P/JOINT_TAIL_BOUND.json')})
(W/'STOPPED_COMPOSITION.json').write_text(json.dumps(composition,indent=2)+'\n')
ET=jr['expected_T'];Tcap=jr['mgf']['T_cap'];assert ET==24576 and Tcap==49152
expected_T=16*ET;expected_reads=33*expected_T;extra_per=Q(33*ET-8,4087);blocks_per=1+extra_per
extra_cap=(33*Tcap-8)//4087;block_cap=extra_cap+1;assert extra_cap==396 and block_cap==397
resources=dict(schema='IID_RETRY_RESOURCE_V1',game='G_retry_IID',scope='same post-H2P region, at most16 reached init/root calls; source nonreturn remains nonreturn on null tapes',root_expectation=ET,root_proposal_tail='Pr(T_j>49152 | reached entry PAST)<2^-1024',root_start_pointer=0,reached_roots='J=sum_j 1_Rj, 1<=J<=16 a.s.',root_refill_bound='r_j<=floor((33T_j-8)/4087) ADDITIONAL refills after initial block',per_root_conservation='4096*(1+r_j)=33T_j+D_j+(4096-ptr_end_j)',global_conservation='4096*(J+sum r_j)=33*T_region+D_getter+A_reinit+U_final',expectation_bounds=dict(roots=16,source_SHAKE56_bytes=896,proposals=expected_T,returned_bytes=expected_reads,additional_refills=str(16*extra_per),initial_blocks=16,total_generated_blocks=str(16*blocks_per),generated_bytes=str(4096*16*blocks_per),getter_drops=str(9*16*extra_per),abandoned_at_reinit=4088*15,final_unused_tail=4088),expected_reached_sensitive=dict(proposals='24576*E[J]',additional_refills=str(extra_per)+'*E[J]',total_blocks=str(blocks_per)+'*E[J]',SHAKE56='56*E[J]',reinit_abandonment='4088*(E[J]-1)'),ghost_budget=dict(proposals=16*Tcap,returned_bytes=33*16*Tcap,additional_refills=16*extra_cap,initial_blocks=16,total_generated_blocks=16*block_cap,generated_bytes=4096*16*block_cap,getter_drops=9*16*extra_cap,reinit_abandonments=15,abandoned_at_reinit_max=4088*15,final_unused_tail_max=4088,source_SHAKE56_bytes=896),region_tail_expression='Pr(T_region>16*49152)<=sum_j Pr(R_j and T_j>49152)<16*2^-1024',region_tail_power2='2^-1020',initial_existing_attempt_block_at_ReadyRetryEntry=False,nonce40_outside_cut=True,parent_M0_SHAKE_bytes_with_nonce_upper=936,real_state_counter='each refill adds64 modulo2^64 to state.d[48..55], leaves first48 unchanged; init reads56 actual SHAKE bytes then refills',state56_is_iid_seed_claimed=False,ghost_budget_is_source_abort=False,dependencies={'JOINT/RESOURCE_BOUND.json':sha(I/'JOINT/RESOURCE_BOUND.json')})
resources['ghost_budget_sufficient_event']='every reached root j has T_j<=49152; this event implies ALL listed simultaneous budgets'
resources['ghost_budget_failure_bound']='any listed budget exceeded implies some reached T_j>49152; union bound <2^-1020'
resources['total_proposals_alone_implies_block_budget']=False
(W/'RESOURCE_BOUND.json').write_text(json.dumps(resources,indent=2)+'\n')
print(json.dumps(dict(status='PASS_EXACT_STOPPED_UNION_HAZARD_AND_RESET_BUDGETS',game='G_retry_IID',WholeRegionBad='<=2^-80',mean_proposals=expected_T,proposal_budget=16*Tcap,tail='2^-1020',blocks_budget=16*block_cap,abandonment_max=4088*15),indent=2))
