import Floor
import ValueDomain
import SourceFloor
import Proposal
import CDF
import OrderedResidual
import Comparator
import GuardPrefix
import ZeroRho
import BitErrors
import PackOf
import RootDiv
import RootFrame
import RootBounds
import RootModel
import TargetWords
import TargetAlgebra
import TargetFrame
import TargetSequence
set_option pp.all true
#check @InitialTarget.one_word
#print InitialTarget.one_word
#check @InitialTarget.q_word
#print InitialTarget.q_word
#check @InitialTarget.ni_word
#print InitialTarget.ni_word
#check @InitialTarget.ni_fields
#print InitialTarget.ni_fields
#check @InitialTarget.ni_value_scaled
#print InitialTarget.ni_value_scaled
#check @InitialTarget.reciprocal_error_numerator
#print InitialTarget.reciprocal_error_numerator
#check @InitialTarget.reciprocal_interval
#print InitialTarget.reciprocal_interval
#check @InitialTarget.canonical_int_ranges
#print InitialTarget.canonical_int_ranges
#check @InitialTarget.canonical_of_exact
#print InitialTarget.canonical_of_exact
#check @InitialTarget.hash_to_point_written_range
#print InitialTarget.hash_to_point_written_range
#check @InitialTarget.hash_to_point_uint16
#print InitialTarget.hash_to_point_uint16
#check @InitialTarget.rejection_limit
#print InitialTarget.rejection_limit
#check @InitialTarget.basis_determinant
#print InitialTarget.basis_determinant
#check @InitialTarget.target_numerator_identity
#print InitialTarget.target_numerator_identity
#check @InitialTarget.reduced_low_count
#print InitialTarget.reduced_low_count
#check @InitialTarget.reduced_high_count
#print InitialTarget.reduced_high_count
#check @InitialTarget.reduced_row_bound
#print InitialTarget.reduced_row_bound
#check @InitialTarget.gram_pair_identities
#print InitialTarget.gram_pair_identities
#check @InitialTarget.gram_pair_bounds
#print InitialTarget.gram_pair_bounds
#check @InitialTarget.two_error_layers
#print InitialTarget.two_error_layers
#check @InitialTarget.inverse_eval_energy_transport
#print InitialTarget.inverse_eval_energy_transport
#check @InitialTarget.target_frame
#print InitialTarget.target_frame
#check @InitialTarget.prefix_offsets
#print InitialTarget.prefix_offsets
#check @InitialTarget.buffers_and_future_pointers
#print InitialTarget.buffers_and_future_pointers
#check @InitialTarget.target_read_write_indices
#print InitialTarget.target_read_write_indices
#check @InitialTarget.packed_indices
#print InitialTarget.packed_indices
#check @InitialTarget.copy_disjoint
#print InitialTarget.copy_disjoint
#check @InitialTarget.whole_key_frame
#print InitialTarget.whole_key_frame
#check @InitialTarget.source_word_match
#print InitialTarget.source_word_match
#check @InitialTarget.defined_prefix_from_local_domains
#print InitialTarget.defined_prefix_from_local_domains
#print InitialTarget.ni
#print InitialTarget.convolutionCount
#print InitialTarget.reducedCount
#print InitialTarget.Ops
#print InitialTarget.execute
