import json
from fractions import Fraction as Q
from pathlib import Path
from replaylib import sha,verify_manifest
W=Path.cwd();I=W/'inputs/bootstrap'
def read(p):return json.loads((W/p).read_text())
def write(p,x):(W/p).write_text(json.dumps(x,indent=2)+'\n')
verify_manifest(I,'MANIFEST.sha256','eb890ea42dad55d397ebd6f71fad5457676d705e5443a5a672201a0ce6e553a8')
for h,n in (s.split('  ',1) for s in (I/'CANDIDATE.sha256').read_text().splitlines()):assert sha(W/'source'/n)==h
f=read('artifacts/fixtures.json');a=read('artifacts/formal_audit.json');floor=read('ACCEPTANCE_FLOOR.json');oracle=read('artifacts/rational_oracle.json');mut=read('artifacts/mutations.json')
assert floor['a_min']=='1/256' and Q(floor['exact_rational_acceptance_lower'])>Q(1,256)
assert a['all_final_logs_clean'] and a['new_theorems']==37 and a['modules']==32 and oracle['pmf_examples']==54
native={m:[x for g in range(4) for x in read('artifacts/native_'+m+'_'+str(g)+'.json')['matches']] for m in ['normal','sanitized']}
assert native['normal']==native['sanitized'] and len(native['normal'])==len(f['cases'])==32
assert all(x['exact_match'] for x in native['normal']) and mut['meaningful_mutations']==13
docs=['CLAIM.md','RANDOMNESS_MODEL.md','BYTE_SCHEDULE.md','CDF_MASS.md','BEREXP_INTEGER_KERNEL.md','ACCEPTANCE_FLOOR.md','REJECTION_LAW.md','PRNG_GAP_INTERFACE.md','SOURCE_MODEL_BINDING.md','MEMORY_FRAME.md','FAILED_ROUTES.md','NEXT_INTERFACE.md','REUSED_RESULTS.md']
closed=['iid_buffer_game_defined','source_byte_schedule_proved','proposal_exact_mass_proved','berexp_exact_probability_proved','source_uniform_acceptance_lower_bound_proved','iid_rejection_kernel_proved','iid_scalar_as_termination_proved','iid_tail_resource_bounds_proved','post_call_fresh_tail_proved','source_high_word_refinement_proved','small_domain_trunc_refinement_proved','required_entry_source_corollary_proved']
opened=['all_tapes_termination_proved','real_prng_to_iid_bridge_proved','full_real_source_sampler_law_proved','full_ordered_joint_law_proved','Gaussian_comparison_proved','joint_BadPrecast_bound_proved','Safe16_proved','reference_integer_recovery_proved','Sign_to_Verify_proved','whole_Sign_termination_proved','security_reduction_proved','full_Sign_CT_proved','fully_kernelized','C_compiler_verified','source_changed','production_source_changed','new_source_patch_integrated','owner_accepted']
flags={**{k:True for k in closed},**{k:False for k in opened}}
obligations=[dict(id=k,status='PROVED_FOR_IID_BUFFER' if k in closed else 'OPEN_OR_OUT_OF_SCOPE',flag=v) for k,v in flags.items() if k.endswith('proved')]
write('OBLIGATIONS.json',dict(schema='SCALAR_IID_OBLIGATIONS_V1',game='IID_BUFFER',obligations=obligations,real_PRNG_gap='PRNG_REAL_TO_IID_BUFFER: exact source state56/ChaCha/root-SHAKE finite-resource transcript comparison; no loss value assigned',Gaussian_gap='compare exact K_C with separately chosen reference law, measure direction/cutoff/normalizer explicit',ordered_gap='conditional scalar kernels to actual recursion/retry joint law and POST WholeCallBad, not independent marginals',probability_or_security_epsilon_assigned=False,POST_status_unchanged='PARTIAL_PROOF'))
cert=dict(schema='FT1536_SCALAR_KERNEL_CERTIFICATE_V1',status='H3_SCALAR_KERNEL_PROVED_FOR_PINNED_IID_BUFFER_MODEL',game='IID_BUFFER',author='Niirmata',base_commit='fe6f92af799dc11830998f8ddf9cf1dc591a448a',source_pin=sha(I/'CANDIDATE.sha256'),bootstrap_pin=sha(I/'MANIFEST.sha256'),task_pin=sha(W/'TASK.md'),domain='all NumericCenter raw mu and certified actual normalized stored/paired widths, legal typed context/faultNONE/ptr0..4095, adaptive arguments from PAST only',past_conditioning_scope='revealed getter bytes/outcomes, deterministic state, ptr/counts, entry PAST; excludes unread buffer/future tape; fresh-tail conditional law, not arbitrary fixed buffer value',**flags,flags=flags,source_uniform_acceptance_lower_bound='1/256',stronger_exact_acceptance_floor=floor['exact_rational_acceptance_lower'],law=dict(proposal_mass='n_j,k/2^128 from strict interval counts with shared U128',Beta='0 if e>=64 else min(Z,2^55)/2^(e+55)',weight='n_j,k/2^129 * Beta_C(x_C(k,b))',normalizer='A=sum weights, 1/256<=A<=1',finite_prefix='Pr_IID_BUFFER[N=n,Y=y|PAST]=(1-A)^(n-1)*w_y',returned_pmf='w_y/A',tail='Pr_IID_BUFFER[N>m|PAST]=(1-A)^m<=(255/256)^m',nonreturn_mass='Pr_IID_BUFFER[N=infinity|PAST]=0',mean='E_IID_BUFFER[N|PAST]=1/A<=256',post_call='exact ptr/refill/drop map of entry ptr and N, conditional-IID unread tail and future blocks'),resources=oracle['resources'],proof_kind=a['proof_kind'],measure_theory_boundary='Countable product probability space; cylinder-factorization coupling; countable stopping-time sum; geometric limit/tail-sum argument explicit analytically, not Lean-mechanized',checks=dict(kernel_modules=a['modules'],kernel_theorems=a['checked_theorems'],new_theorems=a['new_theorems'],**f['counts'],native_invocations_each_build=32,normal_ASan_UBSan=True,LSan=False,meaningful_mutations=13,noop=1,small_trunc_native_cases=oracle['small_trunc_native_cases'],independent_QQ=True),proof_documents={p:sha(W/p) for p in docs},evidence={p:sha(W/p) for p in ['CDF_MASS.json','ACCEPTANCE_FLOOR.json','BYTE_SCHEDULE.json','artifacts/source_binding.json','artifacts/formal_audit.json','artifacts/fixtures.json','artifacts/pmf_examples.json','artifacts/rational_oracle.json','artifacts/mutations.json','artifacts/sampler_examples.json','OBLIGATIONS.json']},historical_POST_status='PARTIAL_PROOF',real_PRNG_statement='OPEN; IID game does not prove real ChaCha/SHAKE law or termination')
write('SCALAR_KERNEL_CERTIFICATE.json',cert);print(json.dumps(dict(status=cert['status'],game='IID_BUFFER',a_min='1/256',E_N_max=256,real_prng_to_iid_bridge_proved=False,checks=cert['checks']),indent=2))
