import Floor
import ValueDomain
import SourceFloor
import Proposal
import CDF
import OrderedResidual
import Comparator
import GuardPrefix
import ZeroRho
import BitErrors
import PackOf
import ErrorArithmetic
import RootDiv
import RootFrame
import RootBounds
import RootModel
import NodeInverse
import NodeDataflow
import NodeConstants
import Half
import TargetWords
import TargetAlgebra
import TargetFrame
import TargetSequence
import ReachOutcomes
import ReachFrame
import BankEnergy
import Buffer
import Layouts
import Deps.Tables
import Deps.Words
import Twiddles
import Deps.Composition
import SourceModel
import Deps.Linear
import Expressions
import BlockExpressions
import BlockChecks
import LocalInverse
import Stages
import InverseGlobal
import ForwardProgress
import Pipeline
import Sums
import Evaluation
import CRTStages
import NodeArithmetic
import LeafData.C00
import LeafData.C01
import LeafData.C02
import LeafData.C03
import LeafData.C04
import LeafData.C05
import LeafData.C06
import LeafData.C07
import LeafData.C08
import LeafData.C09
import LeafData.C10
import LeafData.C11
import LeafData.C12
import LeafData.C13
import LeafData.C14
import LeafData.C15
import LeafData.C16
import LeafData.C17
import LeafData.C18
import LeafData.C19
import LeafData.C20
import LeafData.C21
import LeafData.C22
import LeafData.C23
import LeafData.C24
import LeafData.C25
import LeafData.C26
import LeafData.C27
import LeafData.C28
import LeafData.C29
import LeafData.C30
import LeafData.C31
import LeafChecks
import LeafFacts
import ForwardGlobal
import Monomials
import Product
import Rho
import Complete
import BridgeWords
import Norm64
import RawBridge
import ByteCursor
import CapacityMath
import DecodeStatic
import EncoderCount
import IidCDF
import IidBytes
import IidBerExp
import IidHighWord
import IidRejection
import GaussianMul
import GaussianIntervals
import GaussianMetrics
import MetricTransport
import LeftClosure
import JointOrder
import JointPrefix
import JointMetrics
import RintBits
import RintRefinement
import H6PMap
import H6PVariance
import H6PMoment
import H6PEvent
import Precast
import SourceBytes
import RetryState
import RetryProbability
import RetryCoupling
import RetryResources
set_option pp.all true
#check @RetryIID.counter_guard
#print RetryIID.counter_guard
#check @RetryIID.reached_index
#print RetryIID.reached_index
#check @RetryIID.guard17_before_init
#print RetryIID.guard17_before_init
#check @RetryIID.source_reset_pointer
#print RetryIID.source_reset_pointer
#check @RetryIID.target_overwrite
#print RetryIID.target_overwrite
#check @RetryIID.reentry_induction
#print RetryIID.reentry_induction
#check @RetryIID.safe_interfaces
#print RetryIID.safe_interfaces
#check @RetryIID.weighted_stopped_sum
#print RetryIID.weighted_stopped_sum
#check @RetryIID.bounded_reach_sum
#print RetryIID.bounded_reach_sum
#check @RetryIID.survival_product
#print RetryIID.survival_product
#check @RetryIID.conjunction_not_conditioning
#print RetryIID.conjunction_not_conditioning
#check @RetryIID.sum_cap_proposals
#print RetryIID.sum_cap_proposals
#check @RetryIID.checked_good
#print RetryIID.checked_good
#check @RetryIID.checked_bad
#print RetryIID.checked_bad
#check @RetryIID.equal_iff_good
#print RetryIID.equal_iff_good
#check @RetryIID.preservation_before_norm
#print RetryIID.preservation_before_norm
#check @RetryIID.stored_wide_norm_agrees
#print RetryIID.stored_wide_norm_agrees
#check @RetryIID.public_map_preserves_agreement
#print RetryIID.public_map_preserves_agreement
#check @RetryIID.chunk_generated
#print RetryIID.chunk_generated
#check @RetryIID.fresh_pointer_refill_bound
#print RetryIID.fresh_pointer_refill_bound
#check @RetryIID.abandoned_root_tail
#print RetryIID.abandoned_root_tail
#check @RetryIID.initial_block_not_optional
#print RetryIID.initial_block_not_optional
#check @RetryIID.chunk_sum
#print RetryIID.chunk_sum
#check @RetryIID.block_bound_numbers
#print RetryIID.block_bound_numbers
#check @RetryIID.root_request_budget
#print RetryIID.root_request_budget
#check @RetryIID.counter_projection
#print RetryIID.counter_projection
