import Floor
import ValueDomain
import SourceFloor
import Proposal
import CDF
import OrderedResidual
import Comparator
import GuardPrefix
import ZeroRho
import BitErrors
import PackOf
import ErrorArithmetic
import RootDiv
import RootFrame
import RootBounds
import RootModel
import NodeInverse
import NodeDataflow
import NodeConstants
import Half
import TargetWords
import TargetAlgebra
import TargetFrame
import TargetSequence
import ReachOutcomes
import ReachFrame
import BankEnergy
import IidCDF
import IidBytes
import IidBerExp
import IidHighWord
import IidRejection
import GaussianMul
import GaussianIntervals
import GaussianMetrics
import MetricTransport
import LeftClosure
import JointOrder
import JointPrefix
import JointMetrics
import RintBits
import RintRefinement
import H6PMap
import H6PVariance
import H6PMoment
import H6PEvent
set_option pp.all true
#check @H6P.terminal_innovation_identity
#print H6P.terminal_innovation_identity
#check @H6P.terminal_A2
#print H6P.terminal_A2
#check @H6P.binary_map
#print H6P.binary_map
#check @H6P.cubic_map
#print H6P.cubic_map
#check @H6P.root_basis_map
#print H6P.root_basis_map
#check @H6P.no_affine_offset
#print H6P.no_affine_offset
#check @H6P.output_counts
#print H6P.output_counts
#check @H6P.A2_coordinate0
#print H6P.A2_coordinate0
#check @H6P.A2_coordinate1
#print H6P.A2_coordinate1
#check @H6P.gram_determinant
#print H6P.gram_determinant
#check @H6P.energy_max_composition
#print H6P.energy_max_composition
#check @H6P.row_norm_consumer
#print H6P.row_norm_consumer
#check @H6P.cauchy_two
#print H6P.cauchy_two
#check @H6P.completing_square
#print H6P.completing_square
#check @H6P.local_conditioning_count
#print H6P.local_conditioning_count
#check @H6P.conditional_product_bound
#print H6P.conditional_product_bound
#check @H6P.signed_union_count
#print H6P.signed_union_count
#check @H6P.event_factor_monotone
#print H6P.event_factor_monotone
#check @H6P.exit_subprobability_event
#print H6P.exit_subprobability_event
#check @H6P.joint_bad_has_coefficient
#print H6P.joint_bad_has_coefficient
#check @H6P.second_vector_matters
#print H6P.second_vector_matters
#check @H6P.negative_safe_tie
#print H6P.negative_safe_tie
#check @H6P.positive_bad_tie
#print H6P.positive_bad_tie
#check @H6P.bad_rint_argument
#print H6P.bad_rint_argument
#check @H6P.error_to_symmetric_tail
#print H6P.error_to_symmetric_tail
#check @H6P.exit_not_bad
#print H6P.exit_not_bad
