"""Render in-PDF identity from verified pins; never refresh the manifest."""
import hashlib
import json
from pathlib import Path
import re

PAPER = Path(__file__).resolve().parents[1]
ROOT = PAPER.parents[2]


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verified_inputs():
    pins = {}
    for line in (PAPER / "SOURCES.sha256").read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        expected, relative = line.split("  ", 1)
        assert relative not in pins, f"Duplicate pin: {relative}"
        assert re.fullmatch(r"[a-f0-9]{64}", expected), relative
        assert not Path(relative).is_absolute() and ".." not in Path(relative).parts
        path = ROOT / relative
        assert path.is_file(), f"Missing cited input: {relative}"
        actual = sha256(path)
        assert actual == expected, f"Changed cited input: {relative}: {actual} != {expected}"
        pins[relative] = expected
    return pins


def snapshot_tex(pins):
    metadata = json.loads((PAPER / "sources/DOCUMENT_SNAPSHOT.json").read_text())
    lines = ["% Generated by tools/document_snapshot.py from checked inputs."]
    for key, macro in [
        ("editorial_base_commit", "EditorialBaseCommit"),
        ("computational_commit", "ComputationalCommit"),
        ("b1_status_commit", "BOneStatusCommit"),
    ]:
        value = metadata[key]
        assert re.fullmatch(r"[a-f0-9]{40}", value), key
        lines.append("\\newcommand{\\" + macro + "}{" + value + "}")
    for filename, macro in [
        ("SOURCES.sha256", "EvidenceManifestSHA"),
        ("SOURCES.md", "SourceMapSHA"),
    ]:
        lines.append("\\newcommand{\\" + macro + "}{" + sha256(PAPER / filename) + "}")
    lines.append(r"\newcommand{\EvidencePinCount}{" + str(len(pins)) + "}")
    lines.append(r"\newcommand{\SelectedSnapshotBindings}{%")
    for item in metadata["selected_inputs"]:
        label, path = item["label"], item["path"]
        assert re.fullmatch(r"[A-Za-z0-9 .-]+", label), label
        assert re.fullmatch(r"[A-Za-z0-9_./-]+", path), path
        assert path in pins, f"Displayed artifact is not pinned: {path}"
        lines.extend([
            r"\item[" + label + "] " + r"\path{" + path + r"}\par",
            r"{\footnotesize\texttt{" + pins[path] + r"}}",
        ])
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    pins = verified_inputs()
    text = snapshot_tex(pins)
    destination = PAPER / "build/snapshot.tex"
    destination.parent.mkdir(exist_ok=True)
    if not destination.exists() or destination.read_text() != text:
        destination.write_text(text)
    print(f"Snapshot: {len(pins)} checked inputs; in-PDF hashes generated without repinning")


if __name__ == "__main__":
    main()
