#!/usr/bin/env python3
"""R7 (S01): generate the layout instance table from ONE source of record.

Source of record: results/layout.json (produced by scripts/check_layout.py).
This script renders the markdown table used in PARAMETRIC_TASK_LAYOUT.md
between the LAYOUT_TABLE_BEGIN/END markers and can verify an existing file.

Usage:
    python3 gen_layout_table.py            # write results/layout_table.md
    python3 gen_layout_table.py --check FILE
                                           # verify FILE's marker block equals
                                           # the generated table (exit 1 else)

A hand-written row is not the source of record (review R7).
Output: results/layout_table.md (deterministic bytes).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "results")
BEGIN = "<!-- LAYOUT_TABLE_BEGIN generated by scripts/gen_layout_table.py -->"
END = "<!-- LAYOUT_TABLE_END -->"

ROWS = [
    ("N", "`3*2^(logn-1)`", "N"),
    ("basis", "`4N`", "basis_words"),
    ("raw tree", "`(logn+2)N`", "tree_words"),
    ("raw leaves", "`N`", "leaf_words"),
    ("internal L", "`(logn+1)N`", "internal_L_words"),
    ("expanded key `sk`", "`(logn+6)N`", "sk_words"),
    ("`sk` bytes (KiB)", "`8*sk/1024`", "sk_kib"),
    ("tree bytes (KiB)", "", "tree_kib"),
    ("tmp allocation", "`7N`", "tmp_words"),
    ("tmp bytes (KiB)", "", "tmp_kib"),
    ("ffLDL scratch from gxx", "`7*2^(logn-1)`", "ffldl_scratch_from_gxx"),
    ("scratch high-water (incl. 3N Gram)", "`3N + scratch`", "scratch_high_water"),
]


def load_rows():
    with open(os.path.join(OUT, "layout.json"), encoding="utf-8") as f:
        data = json.load(f)
    by_n = {}
    for r in data["rows"]:
        r = dict(r)
        r["sk_kib"] = r["sk_bytes"] // 1024
        r["tree_kib"] = (r["tree_words"] * 8) // 1024
        r["tmp_kib"] = r["tmp_bytes"] // 1024
        by_n[r["N"]] = r
    return by_n


def render():
    by_n = load_rows()
    cols = [by_n[n] for n in (768, 1536, 3072)]
    lines = []
    lines.append(BEGIN)
    lines.append("| quantity | formula | FT768 (logn 9) | FT1536 (logn 10) | "
                 "FT3072 (logn 11) |")
    lines.append("|---|---|---:|---:|---:|")
    for label, formula, field in ROWS:
        lines.append("| %s | %s | %s |" % (label, formula,
                                           " | ".join(str(c[field])
                                                      for c in cols)))
    lines.append(END)
    return "\n".join(lines) + "\n"


def main():
    table = render()
    if len(sys.argv) == 3 and sys.argv[1] == "--check":
        with open(sys.argv[2], encoding="utf-8") as f:
            text = f.read()
        b = text.find(BEGIN)
        e = text.find(END)
        if b < 0 or e < 0:
            print("FAIL markers not found in", sys.argv[2])
            return 1
        current = text[b:e + len(END)] + "\n"
        ok = current == table
        print(("PASS" if ok else "FAIL") + " layout table check:",
              sys.argv[2])
        if not ok:
            print("--- expected ---")
            print(table)
            print("--- found ---")
            print(current)
        return 0 if ok else 1
    with open(os.path.join(OUT, "layout_table.md"), "w",
              encoding="utf-8") as f:
        f.write(table)
    print("wrote results/layout_table.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
