"""Reproduce the byte-exact pinned SHAKE source literals used by Lean."""
import hashlib
import json
import os
from pathlib import Path

root = Path(os.environ['FT1536_SOURCE3_ORIGINAL_W'])/'inputs/source'
pins = {
    'shake.c': 'c3e7864bf4139264f8c287053214bf869e242757bf555235da81454e40ea316a',
    'shake.h': '2373a37e09907c8e57a6b1adc05e26499d9cf2752518267a80291de931c2d8df',
}
parts = ['/- Generated by sage/generate_shake_source.sage; pinned source data.\n'
         '   Falcon Project / Thomas Pornin copyright and licence are retained below. -/\n'
         'namespace FT1536.Source3.ShakeSource\n']
for filename, pin in pins.items():
    data = (root/filename).read_bytes()
    assert hashlib.sha256(data).hexdigest() == pin
    name = 'sourceLines' if filename.endswith('.c') else 'headerLines'
    parts.append('def '+name+' : List String := [\n')
    parts.append(',\n'.join(json.dumps(line,ensure_ascii=False) for line in data.decode().splitlines(keepends=True)))
    parts.append('\n]\n')
parts.append('end FT1536.Source3.ShakeSource\n')
target = Path('ShakeSource.lean')
target.write_text(''.join(parts))
Path('SHAKE_SOURCE.json').write_text(json.dumps({'inputs':pins,
    'generated_sha256':hashlib.sha256(target.read_bytes()).hexdigest(),
    'bytes':int(target.stat().st_size)},indent=2)+'\n')
