"""Generate bounded kernel candidates for all 1024 physical gm indices."""
import hashlib
import json
from pathlib import Path

def rev(bits, i):
    return sum(((ZZ(i) >> b) & 1) << (bits - 1 - b) for b in range(bits))

def exponent(u):
    return 3 * ZZ(u) + 1 + ZZ(u) % 2

def table_exponent(i):
    i = max(ZZ(1), ZZ(i))
    k = i.nbits() - 1
    return (1 if k == 9 else 3 * 2^(8-k)) * exponent(rev(k, i-2^k))

for i in range(1024):
    e = table_exponent(i)
    k = max(ZZ(1), ZZ(i)).nbits() - 1
    order = 4608 if i >= 512 else 6 * 2^k
    assert e > 0 and 4608 // gcd(4608, e) == order
    if i < 512:
        r = rev(10, 2*i)
        assert r < 512 and rev(10, 2*r) == i
        assert table_exponent(512+r) == exponent(i)
    if 256 <= i < 512:
        assert e == 3 * table_exponent(2*i)
    if 1 <= i < 256:
        assert e == 2 * table_exponent(2*i)

lines = [
    'import Source3.KeygenMkgm3Indices', '',
    'set_option maxRecDepth 32768', 'set_option maxHeartbeats 2000000', '',
    '/- Generated by generate_keygen_row_certificate.sage. Each bounded',
    '   candidate below is checked by the kernel, including all indices. -/',
    'namespace FT1536.Source3.KeygenMkgm3IndexCert',
    'open KeygenMkgm3Indices', ''
]
for c in range(64):
    lines.append('theorem chunk%02d : ∀ i : Fin 16, IndexFact (%d+i.val) := by decide' % (c, 16*c))
lines += ['', 'theorem chunks (c : Fin 64) (i : Fin 16) : IndexFact (16*c.val+i.val) := by',
          '  fin_cases c']
for c in range(64):
    lines.append('  · exact chunk%02d i' % c)
lines += [
    '', 'theorem all_indices (i : Nat) (hi : i<1024) : IndexFact i := by',
    '  have hc : i/16<64 := by omega',
    '  have h := chunks ⟨i/16,hc⟩ ⟨i%16,Nat.mod_lt _ (by decide)⟩',
    '  have he : 16*(i/16)+i%16=i := by omega',
    '  simpa only [he] using h', '',
    'end FT1536.Source3.KeygenMkgm3IndexCert', ''
]
out = Path('KeygenMkgm3IndexCert.lean')
out.write_text('\n'.join(lines))
Path('ROW_CERT_GENERATION.json').write_text(json.dumps({
    'status': 'PASS_FINITE_SAGE_GENERATION',
    'indices': int(1024), 'kernel_chunks': int(64), 'chunk_size': int(16),
    'source': str(out), 'source_sha256': hashlib.sha256(out.read_bytes()).hexdigest(),
    'scope': 'Exact ZZ index/order candidates. Kernel validation is a separate Lean job.'
}, indent=2) + '\n')
