"""Exact source row/REV10 child candidates; Lean separately checks every case."""
import hashlib
import json
from pathlib import Path

def reverse(bits, x):
    return sum(((ZZ(x) >> b) & 1) << (bits-1-b) for b in range(bits))

def exponent(i):
    i = max(ZZ(1), ZZ(i))
    k = i.nbits()-1
    u = reverse(k, i-2^k)
    return (1 if k == 9 else 3*2^(8-k))*(3*u+1+u%2)

for r in range(2, 512):
    power = 2 if r < 256 else 3
    assert power*exponent(2*r) == exponent(r)
    assert (power*exponent(2*r+1))%4608 == (exponent(r)+2304)%4608
assert 2*exponent(2) == 768
assert 2*exponent(3) == 5*768

lines = [
    'import Source3.KeygenMkgm3Indices', '',
    'set_option maxRecDepth 32768', 'set_option maxHeartbeats 2000000', '',
    '/- Generated by generate_keygen_ntt_children.sage; bounded kernel checks',
    '   of the existing source row/REV10 exponents, not a replacement order. -/',
    'namespace FT1536.Source3.KeygenNttTwiddleCert',
    'open KeygenMkgm3Indices (tableExponent)', '',
    'def OddFact (r : Nat) : Prop :=',
    '  (2≤r ∧ r<256 → (2*tableExponent (2*r+1))%4608=(tableExponent r+2304)%4608) ∧',
    '  (256≤r ∧ r<512 → (3*tableExponent (2*r+1))%4608=(tableExponent r+2304)%4608)',
    'instance (r : Nat) : Decidable (OddFact r) := by unfold OddFact; infer_instance', ''
]
for c in range(32):
    lines.append('theorem chunk%02d : ∀ r : Fin 16, OddFact (%d+r.val) := by decide' % (c, 16*c))
lines += ['', 'theorem chunks (c : Fin 32) (r : Fin 16) : OddFact (16*c.val+r.val) := by', '  fin_cases c']
for c in range(32):
    lines.append('  · exact chunk%02d r' % c)
lines += [
    '', 'theorem all_indices (r : Nat) (hr : r<512) : OddFact r := by',
    '  have hc : r/16<32 := by omega',
    '  have h := chunks ⟨r/16,hc⟩ ⟨r%16,Nat.mod_lt _ (by decide)⟩',
    '  have he : 16*(r/16)+r%16=r := by omega',
    '  simpa only [he] using h', '',
    'end FT1536.Source3.KeygenNttTwiddleCert', ''
]
out = Path('KeygenNttTwiddleCert.lean')
out.write_text('\n'.join(lines))
Path('NTT_CHILDREN_GENERATION.json').write_text(json.dumps({
    'status': 'PASS_FINITE_SAGE_GENERATION', 'non_top_parents': int(510),
    'chunks': int(32), 'chunk_size': int(16),
    'certificate': str(out), 'sha256': hashlib.sha256(out.read_bytes()).hexdigest(),
    'scope': 'Exact ZZ checks and generated proof candidates. Lean kernel validation is separate.'
}, indent=2)+'\n')
