set_option maxRecDepth 32768
namespace FT1536.Source3.FprPinned
def cLines : List String := [
"/*\n",
" * Integer-emulated fpr arithmetic for the FREE Falcon ternary FFT3 port.\n",
" * Arithmetic routines are adapted from the Falcon Round3 FALCON_FPEMU backend;\n",
" * FFT3 constants stay in fpr-emulated.h and are generated from this build's\n",
" * fpr-double.h so the ternary Phi_4608 path is preserved.\n",
" */\n",
"\n",
"#ifndef FALCON_ASM_CORTEXM4\n",
"#define FALCON_ASM_CORTEXM4 0\n",
"#endif\n",
"\n",
"#include \"internal.h\"\n",
"\n",
"/*\n",
" * Normalize a provided unsigned integer to the 2^63..2^64-1 range by\n",
" * left-shifting it if necessary. The exponent e is adjusted accordingly\n",
" * (i.e. if the value was left-shifted by n bits, then n is subtracted\n",
" * from e). If source m is 0, then it remains 0, but e is altered.\n",
" * Both m and e must be simple variables (no expressions allowed).\n",
" */\n",
"#define FPR_NORM64(m, e)   do { \\\n",
"\t\tuint32_t nt; \\\n",
" \\\n",
"\t\t(e) -= 63; \\\n",
" \\\n",
"\t\tnt = (uint32_t)((m) >> 32); \\\n",
"\t\tnt = (nt | -nt) >> 31; \\\n",
"\t\t(m) ^= ((m) ^ ((m) << 32)) & ((uint64_t)nt - 1); \\\n",
"\t\t(e) += (int)(nt << 5); \\\n",
" \\\n",
"\t\tnt = (uint32_t)((m) >> 48); \\\n",
"\t\tnt = (nt | -nt) >> 31; \\\n",
"\t\t(m) ^= ((m) ^ ((m) << 16)) & ((uint64_t)nt - 1); \\\n",
"\t\t(e) += (int)(nt << 4); \\\n",
" \\\n",
"\t\tnt = (uint32_t)((m) >> 56); \\\n",
"\t\tnt = (nt | -nt) >> 31; \\\n",
"\t\t(m) ^= ((m) ^ ((m) <<  8)) & ((uint64_t)nt - 1); \\\n",
"\t\t(e) += (int)(nt << 3); \\\n",
" \\\n",
"\t\tnt = (uint32_t)((m) >> 60); \\\n",
"\t\tnt = (nt | -nt) >> 31; \\\n",
"\t\t(m) ^= ((m) ^ ((m) <<  4)) & ((uint64_t)nt - 1); \\\n",
"\t\t(e) += (int)(nt << 2); \\\n",
" \\\n",
"\t\tnt = (uint32_t)((m) >> 62); \\\n",
"\t\tnt = (nt | -nt) >> 31; \\\n",
"\t\t(m) ^= ((m) ^ ((m) <<  2)) & ((uint64_t)nt - 1); \\\n",
"\t\t(e) += (int)(nt << 1); \\\n",
" \\\n",
"\t\tnt = (uint32_t)((m) >> 63); \\\n",
"\t\t(m) ^= ((m) ^ ((m) <<  1)) & ((uint64_t)nt - 1); \\\n",
"\t\t(e) += (int)(nt); \\\n",
"\t} while (0)\n",
"\n",
"#if FALCON_ASM_CORTEXM4 // yyyASM_CORTEXM4+1\n",
"\n",
"__attribute__((naked))\n",
"fpr\n",
"fpr_scaled(int64_t i , int sc )\n",
"{\n",
"\t__asm__ (\n",
"\t\"push\t{ r4, r5, r6, lr }\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Input i is in r0:r1, and sc in r2.\\n\\t\"\n",
"\t\"@ Extract the sign bit, and compute the absolute value.\\n\\t\"\n",
"\t\"@ -> sign bit in r3, with value 0 or -1\\n\\t\"\n",
"\t\"asrs\tr3, r1, #31\\n\\t\"\n",
"\t\"eors\tr0, r3\\n\\t\"\n",
"\t\"eors\tr1, r3\\n\\t\"\n",
"\t\"subs\tr0, r3\\n\\t\"\n",
"\t\"sbcs\tr1, r3\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Scale exponent to account for the encoding; if the source is\\n\\t\"\n",
"\t\"@ zero or if the scaled exponent is negative, it is set to 32.\\n\\t\"\n",
"\t\"addw\tr2, r2, #1022\\n\\t\"\n",
"\t\"orrs\tr4, r0, r1\\n\\t\"\n",
"\t\"bics\tr4, r4, r2, asr #31\\n\\t\"\n",
"\t\"rsbs\tr5, r4, #0\\n\\t\"\n",
"\t\"orrs\tr4, r5\\n\\t\"\n",
"\t\"ands\tr2, r2, r4, asr #31\\n\\t\"\n",
"\t\"adds\tr2, #32\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Normalize value to a full 64-bit width, by shifting it left.\\n\\t\"\n",
"\t\"@ The shift count is subtracted from the exponent (in r2).\\n\\t\"\n",
"\t\"@ If the mantissa is 0, the exponent is set to 0.\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ If top word is 0, replace with low word; otherwise, add 32 to\\n\\t\"\n",
"\t\"@ the exponent.\\n\\t\"\n",
"\t\"rsbs\tr4, r1, #0\\n\\t\"\n",
"\t\"orrs\tr4, r1\\n\\t\"\n",
"\t\"eors\tr5, r0, r1\\n\\t\"\n",
"\t\"bics\tr5, r5, r4, asr #31\\n\\t\"\n",
"\t\"eors\tr1, r5\\n\\t\"\n",
"\t\"ands\tr0, r0, r4, asr #31\\n\\t\"\n",
"\t\"lsrs\tr4, r4, #31\\n\\t\"\n",
"\t\"adds\tr2, r2, r4, lsl #5\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Count leading zeros of r1 to finish the shift.\\n\\t\"\n",
"\t\"clz\tr4, r1\\n\\t\"\n",
"\t\"subs\tr2, r4\\n\\t\"\n",
"\t\"rsbs\tr5, r4, #32\\n\\t\"\n",
"\t\"lsls\tr1, r4\\n\\t\"\n",
"\t\"lsrs\tr5, r0, r5\\n\\t\"\n",
"\t\"lsls\tr0, r4\\n\\t\"\n",
"\t\"orrs\tr1, r5\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Clear the top bit; we know it's a 1 (unless the whole mantissa\\n\\t\"\n",
"\t\"@ was zero, but then it's still OK to clear it)\\n\\t\"\n",
"\t\"bfc\tr1, #31, #1\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Now shift right the value by 11 bits; this puts the value in\\n\\t\"\n",
"\t\"@ the 2^52..2^53-1 range. We also keep a copy of the pre-shift\\n\\t\"\n",
"\t\"@ low bits in r5.\\n\\t\"\n",
"\t\"movs\tr5, r0\\n\\t\"\n",
"\t\"lsrs\tr0, #11\\n\\t\"\n",
"\t\"orrs\tr0, r0, r1, lsl #21\\n\\t\"\n",
"\t\"lsrs\tr1, #11\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Also plug the exponent at the right place. This must be done\\n\\t\"\n",
"\t\"@ now so that, in case the rounding creates a carry, that carry\\n\\t\"\n",
"\t\"@ adds to the exponent, which would be exactly what we want at\\n\\t\"\n",
"\t\"@ that point.\\n\\t\"\n",
"\t\"orrs\tr1, r1, r2, lsl #20\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Rounding: we must add 1 to the mantissa in the following cases:\\n\\t\"\n",
"\t\"@  - bits 11 to 9 of r5 are '011', '110' or '111'\\n\\t\"\n",
"\t\"@  - bits 11 to 9 of r5 are '010' and one of the\\n\\t\"\n",
"\t\"@    bits 0 to 8 is non-zero\\n\\t\"\n",
"\t\"ubfx\tr6, r5, #0, #9\\n\\t\"\n",
"\t\"addw\tr6, r6, #511\\n\\t\"\n",
"\t\"orrs\tr5, r6\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"ubfx\tr5, r5, #9, #3\\n\\t\"\n",
"\t\"movs\tr6, #0xC8\\n\\t\"\n",
"\t\"lsrs\tr6, r5\\n\\t\"\n",
"\t\"ands\tr6, #1\\n\\t\"\n",
"\t\"adds\tr0, r6\\n\\t\"\n",
"\t\"adcs\tr1, #0\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Put back the sign.\\n\\t\"\n",
"\t\"orrs\tr1, r1, r3, lsl #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"pop\t{ r4, r5, r6, pc}\\n\\t\"\n",
"\t);\n",
"}\n",
"\n",
"#else // yyyASM_CORTEXM4+0\n",
"\n",
"fpr\n",
"fpr_scaled(int64_t i, int sc)\n",
"{\n",
"\t/*\n",
"\t * To convert from int to float, we have to do the following:\n",
"\t *  1. Get the absolute value of the input, and its sign\n",
"\t *  2. Shift right or left the value as appropriate\n",
"\t *  3. Pack the result\n",
"\t *\n",
"\t * We can assume that the source integer is not -2^63.\n",
"\t */\n",
"\tint s, e;\n",
"\tuint32_t t;\n",
"\tuint64_t m;\n",
"\n",
"\t/*\n",
"\t * Extract sign bit.\n",
"\t * We have: -i = 1 + ~i\n",
"\t */\n",
"\ts = (int)((uint64_t)i >> 63);\n",
"\ti ^= -(int64_t)s;\n",
"\ti += s;\n",
"\n",
"\t/*\n",
"\t * For now we suppose that i != 0.\n",
"\t * Otherwise, we set m to i and left-shift it as much as needed\n",
"\t * to get a 1 in the top bit. We can do that in a logarithmic\n",
"\t * number of conditional shifts.\n",
"\t */\n",
"\tm = (uint64_t)i;\n",
"\te = 9 + sc;\n",
"\tFPR_NORM64(m, e);\n",
"\n",
"\t/*\n",
"\t * Now m is in the 2^63..2^64-1 range. We must divide it by 512;\n",
"\t * if one of the dropped bits is a 1, this should go into the\n",
"\t * \"sticky bit\".\n",
"\t */\n",
"\tm |= ((uint32_t)m & 0x1FF) + 0x1FF;\n",
"\tm >>= 9;\n",
"\n",
"\t/*\n",
"\t * Corrective action: if i = 0 then all of the above was\n",
"\t * incorrect, and we clamp e and m down to zero.\n",
"\t */\n",
"\tt = (uint32_t)((uint64_t)(i | -i) >> 63);\n",
"\tm &= -(uint64_t)t;\n",
"\te &= -(int)t;\n",
"\n",
"\t/*\n",
"\t * Assemble back everything. The FPR() function will handle cases\n",
"\t * where e is too low.\n",
"\t */\n",
"\treturn FPR(s, e, m);\n",
"}\n",
"\n",
"#endif // yyyASM_CORTEXM4-\n",
"\n",
"#if FALCON_ASM_CORTEXM4 // yyyASM_CORTEXM4+1\n",
"\n",
"// yyyPQCLEAN+0\n",
"#if 0\n",
"/* Debug code -- To get a printout of registers from a specific point\n",
"   in ARM Cortex M4 assembly code, uncomment this code and add a\n",
"   \"bl DEBUG\" call where wished for. */\n",
"\n",
"void\n",
"print_regs(uint32_t *rr, uint32_t flags)\n",
"{\n",
"\tint i;\n",
"\textern int printf(const char *fmt, ...);\n",
"\n",
"\tprintf(\"\\nRegs:\\n\");\n",
"\tfor (i = 0; i < 7; i ++) {\n",
"\t\tint j;\n",
"\n",
"\t\tj = i + 7;\n",
"\t\tprintf(\"  %2d = %08X    %2d = %08X\\n\", i, rr[i], j, rr[j]);\n",
"\t}\n",
"\tprintf(\"  flags = %08X  \", flags);\n",
"\tif ((flags >> 31) & 1) {\n",
"\t\tprintf(\"N\");\n",
"\t}\n",
"\tif ((flags >> 30) & 1) {\n",
"\t\tprintf(\"Z\");\n",
"\t}\n",
"\tif ((flags >> 29) & 1) {\n",
"\t\tprintf(\"C\");\n",
"\t}\n",
"\tif ((flags >> 28) & 1) {\n",
"\t\tprintf(\"V\");\n",
"\t}\n",
"\tif ((flags >> 27) & 1) {\n",
"\t\tprintf(\"Q\");\n",
"\t}\n",
"\tprintf(\"\\n\");\n",
"}\n",
"\n",
"__attribute__((naked))\n",
"void\n",
"DEBUG(void)\n",
"{\n",
"\t__asm__ (\n",
"\t\"push\t{ r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, lr }\\n\\t\"\n",
"\t\"mov\tr0, sp\\n\\t\"\n",
"\t\"mrs\tr1, apsr\\n\\t\"\n",
"\t\"bl\tprint_regs\\n\\t\"\n",
"\t\"pop\t{ r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, pc }\\n\\t\"\n",
"\t);\n",
"}\n",
"#endif\n",
"// yyyPQCLEAN-\n",
"\n",
"__attribute__((naked))\n",
"fpr\n",
"fpr_add(fpr x , fpr y )\n",
"{\n",
"\t__asm__ (\n",
"\t\"push\t{ r4, r5, r6, r7, r8, r10, r11, lr }\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Make sure that the first operand (x) has the larger absolute\\n\\t\"\n",
"\t\"@ value. This guarantees that the exponent of y is less than\\n\\t\"\n",
"\t\"@ or equal to the exponent of x, and, if they are equal, then\\n\\t\"\n",
"\t\"@ the mantissa of y will not be greater than the mantissa of x.\\n\\t\"\n",
"\t\"@ However, if absolute values are equal and the sign of x is 1,\\n\\t\"\n",
"\t\"@ then we want to also swap the values.\\n\\t\"\n",
"\t\"ubfx\tr4, r1, #0, #31  @ top word without sign bit\\n\\t\"\n",
"\t\"ubfx\tr5, r3, #0, #31  @ top word without sign bit\\n\\t\"\n",
"\t\"subs\tr7, r0, r2       @ difference in r7:r4\\n\\t\"\n",
"\t\"sbcs\tr4, r5\\n\\t\"\n",
"\t\"orrs\tr7, r4\\n\\t\"\n",
"\t\"rsbs\tr5, r7, #0\\n\\t\"\n",
"\t\"orrs\tr7, r5      @ bit 31 of r7 is 0 iff difference is zero\\n\\t\"\n",
"\t\"bics\tr6, r1, r7\\n\\t\"\n",
"\t\"orrs\tr6, r4      @ bit 31 of r6 is 1 iff the swap must be done\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Conditional swap\\n\\t\"\n",
"\t\"eors\tr4, r0, r2\\n\\t\"\n",
"\t\"eors\tr5, r1, r3\\n\\t\"\n",
"\t\"ands\tr4, r4, r6, asr #31\\n\\t\"\n",
"\t\"ands\tr5, r5, r6, asr #31\\n\\t\"\n",
"\t\"eors\tr0, r4\\n\\t\"\n",
"\t\"eors\tr1, r5\\n\\t\"\n",
"\t\"eors\tr2, r4\\n\\t\"\n",
"\t\"eors\tr3, r5\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Extract mantissa of x into r0:r1, exponent in r4, sign in r5\\n\\t\"\n",
"\t\"ubfx\tr4, r1, #20, #11   @ Exponent in r4 (without sign)\\n\\t\"\n",
"\t\"addw\tr5, r4, #2047 @ Get a carry to test r4 for zero\\n\\t\"\n",
"\t\"lsrs\tr5, #11       @ r5 is the mantissa implicit high bit\\n\\t\"\n",
"\t\"bfc\tr1, #20, #11  @ Clear exponent bits (not the sign)\\n\\t\"\n",
"\t\"orrs\tr1, r1, r5, lsl #20  @ Set mantissa high bit\\n\\t\"\n",
"\t\"asrs\tr5, r1, #31   @ Get sign bit (sign-extended)\\n\\t\"\n",
"\t\"bfc\tr1, #31, #1   @ Clear the sign bit\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Extract mantissa of y into r2:r3, exponent in r6, sign in r7\\n\\t\"\n",
"\t\"ubfx\tr6, r3, #20, #11   @ Exponent in r6 (without sign)\\n\\t\"\n",
"\t\"addw\tr7, r6, #2047 @ Get a carry to test r6 for zero\\n\\t\"\n",
"\t\"lsrs\tr7, #11       @ r7 is the mantissa implicit high bit\\n\\t\"\n",
"\t\"bfc\tr3, #20, #11  @ Clear exponent bits (not the sign)\\n\\t\"\n",
"\t\"orrs\tr3, r3, r7, lsl #20  @ Set mantissa high bit\\n\\t\"\n",
"\t\"asrs\tr7, r3, #31   @ Get sign bit (sign-extended)\\n\\t\"\n",
"\t\"bfc\tr3, #31, #1   @ Clear the sign bit\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Scale mantissas up by three bits.\\n\\t\"\n",
"\t\"lsls\tr1, #3\\n\\t\"\n",
"\t\"orrs\tr1, r1, r0, lsr #29\\n\\t\"\n",
"\t\"lsls\tr0, #3\\n\\t\"\n",
"\t\"lsls\tr3, #3\\n\\t\"\n",
"\t\"orrs\tr3, r3, r2, lsr #29\\n\\t\"\n",
"\t\"lsls\tr2, #3\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ x: exponent=r4, sign=r5, mantissa=r0:r1 (scaled up 3 bits)\\n\\t\"\n",
"\t\"@ y: exponent=r6, sign=r7, mantissa=r2:r3 (scaled up 3 bits)\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ At that point, the exponent of x (in r4) is larger than that\\n\\t\"\n",
"\t\"@ of y (in r6). The difference is the amount of shifting that\\n\\t\"\n",
"\t\"@ should be done on y. If that amount is larger than 59 then\\n\\t\"\n",
"\t\"@ we clamp y to 0. We won't need y's exponent beyond that point,\\n\\t\"\n",
"\t\"@ so we store that shift count in r6.\\n\\t\"\n",
"\t\"subs\tr6, r4, r6\\n\\t\"\n",
"\t\"subs\tr8, r6, #60\\n\\t\"\n",
"\t\"ands\tr2, r2, r8, asr #31\\n\\t\"\n",
"\t\"ands\tr3, r3, r8, asr #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Shift right r2:r3 by r6 bits. The shift count is in the 0..59\\n\\t\"\n",
"\t\"@ range. r11 will be non-zero if and only if some non-zero bits\\n\\t\"\n",
"\t\"@ were dropped.\\n\\t\"\n",
"\t\"subs\tr8, r6, #32\\n\\t\"\n",
"\t\"bics\tr11, r2, r8, asr #31\\n\\t\"\n",
"\t\"ands\tr2, r2, r8, asr #31\\n\\t\"\n",
"\t\"bics\tr10, r3, r8, asr #31\\n\\t\"\n",
"\t\"orrs\tr2, r2, r10\\n\\t\"\n",
"\t\"ands\tr3, r3, r8, asr #31\\n\\t\"\n",
"\t\"ands\tr6, r6, #31\\n\\t\"\n",
"\t\"rsbs\tr8, r6, #32\\n\\t\"\n",
"\t\"lsls\tr10, r2, r8\\n\\t\"\n",
"\t\"orrs\tr11, r11, r10\\n\\t\"\n",
"\t\"lsrs\tr2, r2, r6\\n\\t\"\n",
"\t\"lsls\tr10, r3, r8\\n\\t\"\n",
"\t\"orrs\tr2, r2, r10\\n\\t\"\n",
"\t\"lsrs\tr3, r3, r6\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ If r11 is non-zero then some non-zero bit was dropped and the\\n\\t\"\n",
"\t\"@ low bit of r2 must be forced to 1 ('sticky bit').\\n\\t\"\n",
"\t\"rsbs\tr6, r11, #0\\n\\t\"\n",
"\t\"orrs\tr6, r6, r11\\n\\t\"\n",
"\t\"orrs\tr2, r2, r6, lsr #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ x: exponent=r4, sign=r5, mantissa=r0:r1 (scaled up 3 bits)\\n\\t\"\n",
"\t\"@ y: sign=r7, value=r2:r3 (scaled to same exponent as x)\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ If x and y don't have the same sign, then we should negate r2:r3\\n\\t\"\n",
"\t\"@ (i.e. subtract the mantissa instead of adding it). Signs of x\\n\\t\"\n",
"\t\"@ and y are in r5 and r7, as full-width words. We won't need r7\\n\\t\"\n",
"\t\"@ afterwards.\\n\\t\"\n",
"\t\"eors\tr7, r5    @ r7 = -1 if y must be negated, 0 otherwise\\n\\t\"\n",
"\t\"eors\tr2, r7\\n\\t\"\n",
"\t\"eors\tr3, r7\\n\\t\"\n",
"\t\"subs\tr2, r7\\n\\t\"\n",
"\t\"sbcs\tr3, r7\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ r2:r3 has been shifted, we can add to r0:r1.\\n\\t\"\n",
"\t\"adds\tr0, r2\\n\\t\"\n",
"\t\"adcs\tr1, r3\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ result: exponent=r4, sign=r5, mantissa=r0:r1 (scaled up 3 bits)\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Normalize the result with some left-shifting to full 64-bit\\n\\t\"\n",
"\t\"@ width. Shift count goes to r2, and exponent (r4) is adjusted.\\n\\t\"\n",
"\t\"clz\tr2, r0\\n\\t\"\n",
"\t\"clz\tr3, r1\\n\\t\"\n",
"\t\"sbfx\tr6, r3, #5, #1\\n\\t\"\n",
"\t\"ands\tr2, r6\\n\\t\"\n",
"\t\"adds\tr2, r2, r3\\n\\t\"\n",
"\t\"subs\tr4, r4, r2\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Shift r0:r1 to the left by r2 bits.\\n\\t\"\n",
"\t\"subs\tr7, r2, #32\\n\\t\"\n",
"\t\"lsls\tr7, r0, r7\\n\\t\"\n",
"\t\"lsls\tr1, r1, r2\\n\\t\"\n",
"\t\"rsbs\tr6, r2, #32\\n\\t\"\n",
"\t\"orrs\tr1, r1, r7\\n\\t\"\n",
"\t\"lsrs\tr6, r0, r6\\n\\t\"\n",
"\t\"orrs\tr1, r1, r6\\n\\t\"\n",
"\t\"lsls\tr0, r0, r2\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ The exponent of x was in r4. The left-shift operation has\\n\\t\"\n",
"\t\"@ subtracted some value from it, 8 in case the result has the\\n\\t\"\n",
"\t\"@ same exponent as x. However, the high bit of the mantissa will\\n\\t\"\n",
"\t\"@ add 1 to the exponent, so we only add back 7 (the exponent is\\n\\t\"\n",
"\t\"@ added in because rounding might have produced a carry, which\\n\\t\"\n",
"\t\"@ should then spill into the exponent).\\n\\t\"\n",
"\t\"adds\tr4, #7\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ If the mantissa new mantissa is non-zero, then its bit 63 is\\n\\t\"\n",
"\t\"@ non-zero (thanks to the normalizing shift). Otherwise, that bit\\n\\t\"\n",
"\t\"@ is zero, and we should then set the exponent to zero as well.\\n\\t\"\n",
"\t\"ands\tr4, r4, r1, asr #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Shrink back the value to a 52-bit mantissa. This requires\\n\\t\"\n",
"\t\"@ right-shifting by 11 bits; we keep a copy of the pre-shift\\n\\t\"\n",
"\t\"@ low word in r3.\\n\\t\"\n",
"\t\"movs\tr3, r0\\n\\t\"\n",
"\t\"lsrs\tr0, #11\\n\\t\"\n",
"\t\"orrs\tr0, r0, r1, lsl #21\\n\\t\"\n",
"\t\"lsrs\tr1, #11\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Apply rounding.\\n\\t\"\n",
"\t\"ubfx\tr6, r3, #0, #9\\n\\t\"\n",
"\t\"addw\tr6, r6, #511\\n\\t\"\n",
"\t\"orrs\tr3, r6\\n\\t\"\n",
"\t\"ubfx\tr3, r3, #9, #3\\n\\t\"\n",
"\t\"movs\tr6, #0xC8\\n\\t\"\n",
"\t\"lsrs\tr6, r3\\n\\t\"\n",
"\t\"ands\tr6, #1\\n\\t\"\n",
"\t\"adds\tr0, r6\\n\\t\"\n",
"\t\"adcs\tr1, #0\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@Plug in the exponent with an addition.\\n\\t\"\n",
"\t\"adds\tr1, r1, r4, lsl #20\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ If the new exponent is negative or zero, then it underflowed\\n\\t\"\n",
"\t\"@ and we must clear the whole mantissa and exponent.\\n\\t\"\n",
"\t\"rsbs\tr4, r4, #0\\n\\t\"\n",
"\t\"ands\tr0, r0, r4, asr #31\\n\\t\"\n",
"\t\"ands\tr1, r1, r4, asr #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Put back the sign. This is the sign of x: thanks to the\\n\\t\"\n",
"\t\"@ conditional swap at the start, this is always correct.\\n\\t\"\n",
"\t\"bfi\tr1, r5, #31, #1\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"pop\t{ r4, r5, r6, r7, r8, r10, r11, pc }\\n\\t\"\n",
"\t);\n",
"}\n",
"\n",
"#else // yyyASM_CORTEXM4+0\n",
"\n",
"fpr\n",
"fpr_add(fpr x, fpr y)\n",
"{\n",
"\tuint64_t m, xu, yu, za;\n",
"\tuint32_t cs;\n",
"\tint ex, ey, sx, sy, cc;\n",
"\n",
"\t/*\n",
"\t * Make sure that the first operand (x) has the larger absolute\n",
"\t * value. This guarantees that the exponent of y is less than\n",
"\t * or equal to the exponent of x, and, if they are equal, then\n",
"\t * the mantissa of y will not be greater than the mantissa of x.\n",
"\t *\n",
"\t * After this swap, the result will have the sign x, except in\n",
"\t * the following edge case: abs(x) = abs(y), and x and y have\n",
"\t * opposite sign bits; in that case, the result shall be +0\n",
"\t * even if the sign bit of x is 1. To handle this case properly,\n",
"\t * we do the swap is abs(x) = abs(y) AND the sign of x is 1.\n",
"\t */\n",
"\tm = ((uint64_t)1 << 63) - 1;\n",
"\tza = (x & m) - (y & m);\n",
"\tcs = (uint32_t)(za >> 63)\n",
"\t\t| ((1U - (uint32_t)(-za >> 63)) & (uint32_t)(x >> 63));\n",
"\tm = (x ^ y) & -(uint64_t)cs;\n",
"\tx ^= m;\n",
"\ty ^= m;\n",
"\n",
"\t/*\n",
"\t * Extract sign bits, exponents and mantissas. The mantissas are\n",
"\t * scaled up to 2^55..2^56-1, and the exponent is unbiased. If\n",
"\t * an operand is zero, its mantissa is set to 0 at this step, and\n",
"\t * its exponent will be -1078.\n",
"\t */\n",
"\tex = (int)(x >> 52);\n",
"\tsx = ex >> 11;\n",
"\tex &= 0x7FF;\n",
"\tm = (uint64_t)(uint32_t)((ex + 0x7FF) >> 11) << 52;\n",
"\txu = ((x & (((uint64_t)1 << 52) - 1)) | m) << 3;\n",
"\tex -= 1078;\n",
"\tey = (int)(y >> 52);\n",
"\tsy = ey >> 11;\n",
"\tey &= 0x7FF;\n",
"\tm = (uint64_t)(uint32_t)((ey + 0x7FF) >> 11) << 52;\n",
"\tyu = ((y & (((uint64_t)1 << 52) - 1)) | m) << 3;\n",
"\tey -= 1078;\n",
"\n",
"\t/*\n",
"\t * x has the larger exponent; hence, we only need to right-shift y.\n",
"\t * If the shift count is larger than 59 bits then we clamp the\n",
"\t * value to zero.\n",
"\t */\n",
"\tcc = ex - ey;\n",
"\tyu &= -(uint64_t)((uint32_t)(cc - 60) >> 31);\n",
"\tcc &= 63;\n",
"\n",
"\t/*\n",
"\t * The lowest bit of yu is \"sticky\".\n",
"\t */\n",
"\tm = fpr_ulsh(1, cc) - 1;\n",
"\tyu |= (yu & m) + m;\n",
"\tyu = fpr_ursh(yu, cc);\n",
"\n",
"\t/*\n",
"\t * If the operands have the same sign, then we add the mantissas;\n",
"\t * otherwise, we subtract the mantissas.\n",
"\t */\n",
"\txu += yu - ((yu << 1) & -(uint64_t)(sx ^ sy));\n",
"\n",
"\t/*\n",
"\t * The result may be smaller, or slightly larger. We normalize\n",
"\t * it to the 2^63..2^64-1 range (if xu is zero, then it stays\n",
"\t * at zero).\n",
"\t */\n",
"\tFPR_NORM64(xu, ex);\n",
"\n",
"\t/*\n",
"\t * Scale down the value to 2^54..s^55-1, handling the last bit\n",
"\t * as sticky.\n",
"\t */\n",
"\txu |= ((uint32_t)xu & 0x1FF) + 0x1FF;\n",
"\txu >>= 9;\n",
"\tex += 9;\n",
"\n",
"\t/*\n",
"\t * In general, the result has the sign of x. However, if the\n",
"\t * result is exactly zero, then the following situations may\n",
"\t * be encountered:\n",
"\t *   x > 0, y = -x   -> result should be +0\n",
"\t *   x < 0, y = -x   -> result should be +0\n",
"\t *   x = +0, y = +0  -> result should be +0\n",
"\t *   x = -0, y = +0  -> result should be +0\n",
"\t *   x = +0, y = -0  -> result should be +0\n",
"\t *   x = -0, y = -0  -> result should be -0\n",
"\t *\n",
"\t * But at the conditional swap step at the start of the\n",
"\t * function, we ensured that if abs(x) = abs(y) and the\n",
"\t * sign of x was 1, then x and y were swapped. Thus, the\n",
"\t * two following cases cannot actually happen:\n",
"\t *   x < 0, y = -x\n",
"\t *   x = -0, y = +0\n",
"\t * In all other cases, the sign bit of x is conserved, which\n",
"\t * is what the FPR() function does. The FPR() function also\n",
"\t * properly clamps values to zero when the exponent is too\n",
"\t * low, but does not alter the sign in that case.\n",
"\t */\n",
"\treturn FPR(sx, ex, xu);\n",
"}\n",
"\n",
"#endif // yyyASM_CORTEXM4-\n",
"\n",
"#if FALCON_ASM_CORTEXM4 // yyyASM_CORTEXM4+1\n",
"\n",
"__attribute__((naked))\n",
"fpr\n",
"fpr_mul(fpr x , fpr y )\n",
"{\n",
"\t__asm__ (\n",
"\t\"push\t{ r4, r5, r6, r7, r8, r10, r11, lr }\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Extract mantissas: x.m = r4:r5, y.m = r6:r7\\n\\t\"\n",
"\t\"@ r4 and r6 contain only 25 bits each.\\n\\t\"\n",
"\t\"bics\tr4, r0, #0xFE000000\\n\\t\"\n",
"\t\"lsls\tr5, r1, #7\\n\\t\"\n",
"\t\"orrs\tr5, r5, r0, lsr #25\\n\\t\"\n",
"\t\"orrs\tr5, r5, #0x08000000\\n\\t\"\n",
"\t\"bics\tr5, r5, #0xF0000000\\n\\t\"\n",
"\t\"bics\tr6, r2, #0xFE000000\\n\\t\"\n",
"\t\"lsls\tr7, r3, #7\\n\\t\"\n",
"\t\"orrs\tr7, r7, r2, lsr #25\\n\\t\"\n",
"\t\"orrs\tr7, r7, #0x08000000\\n\\t\"\n",
"\t\"bics\tr7, r7, #0xF0000000\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Perform product. Values are in the 2^52..2^53-1 range, so\\n\\t\"\n",
"\t\"@ the product is at most 106-bit long. Of the low 50 bits,\\n\\t\"\n",
"\t\"@ we only want to know if they are all zeros or not. Here,\\n\\t\"\n",
"\t\"@ we get the top 56 bits in r10:r11, and r8 will be non-zero\\n\\t\"\n",
"\t\"@ if and only if at least one of the low 50 bits is non-zero.\\n\\t\"\n",
"\t\"umull\tr8, r10, r4, r6      @ x0*y0\\n\\t\"\n",
"\t\"lsls\tr10, #7\\n\\t\"\n",
"\t\"orrs\tr10, r10, r8, lsr #25\\n\\t\"\n",
"\t\"eors\tr11, r11\\n\\t\"\n",
"\t\"umlal\tr10, r11, r4, r7     @ x0*y1\\n\\t\"\n",
"\t\"umlal\tr10, r11, r5, r6     @ x1*y0\\n\\t\"\n",
"\t\"orrs\tr8, r8, r10, lsl #7\\n\\t\"\n",
"\t\"lsrs\tr10, #25\\n\\t\"\n",
"\t\"orrs\tr10, r10, r11, lsl #7\\n\\t\"\n",
"\t\"eors\tr11, r11\\n\\t\"\n",
"\t\"umlal\tr10, r11, r5, r7     @ x1*y1\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Now r0, r2, r4, r5, r6 and r7 are free.\\n\\t\"\n",
"\t\"@ If any of the low 50 bits was non-zero, then we force the\\n\\t\"\n",
"\t\"@ low bit of r10 to 1.\\n\\t\"\n",
"\t\"rsbs\tr4, r8, #0\\n\\t\"\n",
"\t\"orrs\tr8, r8, r4\\n\\t\"\n",
"\t\"orrs\tr10, r10, r8, lsr #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ r8 is free.\\n\\t\"\n",
"\t\"@ r10:r11 contains the product in the 2^54..2^56-1 range. We\\n\\t\"\n",
"\t\"@ normalize it to 2^54..2^55-1 (into r6:r7) with a conditional\\n\\t\"\n",
"\t\"@ shift (low bit is sticky). r5 contains -1 if the shift was done,\\n\\t\"\n",
"\t\"@ 0 otherwise.\\n\\t\"\n",
"\t\"ands\tr6, r10, #1\\n\\t\"\n",
"\t\"lsrs\tr5, r11, #23\\n\\t\"\n",
"\t\"rsbs\tr5, r5, #0\\n\\t\"\n",
"\t\"orrs\tr6, r6, r10, lsr #1\\n\\t\"\n",
"\t\"orrs\tr6, r6, r11, lsl #31\\n\\t\"\n",
"\t\"lsrs\tr7, r11, #1\\n\\t\"\n",
"\t\"eors\tr10, r10, r6\\n\\t\"\n",
"\t\"eors\tr11, r11, r7\\n\\t\"\n",
"\t\"bics\tr10, r10, r5\\n\\t\"\n",
"\t\"bics\tr11, r11, r5\\n\\t\"\n",
"\t\"eors\tr6, r6, r10\\n\\t\"\n",
"\t\"eors\tr7, r7, r11\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Compute aggregate exponent: ex + ey - 1023 + w\\n\\t\"\n",
"\t\"@ (where w = 1 if the conditional shift was done, 0 otherwise)\\n\\t\"\n",
"\t\"@ But we subtract 1 because the injection of the mantissa high\\n\\t\"\n",
"\t\"@ bit will increment the exponent by 1.\\n\\t\"\n",
"\t\"lsls\tr0, r1, #1\\n\\t\"\n",
"\t\"lsls\tr2, r3, #1\\n\\t\"\n",
"\t\"lsrs\tr0, #21\\n\\t\"\n",
"\t\"addw\tr4, r0, #0x7FF   @ save ex + 2047 in r4\\n\\t\"\n",
"\t\"lsrs\tr2, #21\\n\\t\"\n",
"\t\"addw\tr8, r2, #0x7FF   @ save ey + 2047 in r8\\n\\t\"\n",
"\t\"adds\tr2, r0\\n\\t\"\n",
"\t\"subw\tr2, r2, #1024\\n\\t\"\n",
"\t\"subs\tr2, r5\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ r5 is free.\\n\\t\"\n",
"\t\"@ Also, if either of the source exponents is 0, or the result\\n\\t\"\n",
"\t\"@ exponent is 0 or negative, then the result is zero and the\\n\\t\"\n",
"\t\"@ mantissa and the exponent shall be clamped to zero. Since\\n\\t\"\n",
"\t\"@ r2 contains the result exponent minus 1, we test on r2\\n\\t\"\n",
"\t\"@ being strictly negative.\\n\\t\"\n",
"\t\"ands\tr4, r8    @ if bit 11 = 0 then one of the exponents was 0\\n\\t\"\n",
"\t\"mvns\tr5, r2\\n\\t\"\n",
"\t\"ands\tr5, r5, r4, lsl #20\\n\\t\"\n",
"\t\"ands\tr2, r2, r5, asr #31\\n\\t\"\n",
"\t\"ands\tr6, r6, r5, asr #31\\n\\t\"\n",
"\t\"ands\tr7, r7, r5, asr #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Sign is the XOR of the sign of the operands. This is true in\\n\\t\"\n",
"\t\"@ all cases, including very small results (exponent underflow)\\n\\t\"\n",
"\t\"@ and zeros.\\n\\t\"\n",
"\t\"eors\tr1, r3\\n\\t\"\n",
"\t\"bfc\tr1, #0, #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Plug in the exponent.\\n\\t\"\n",
"\t\"bfi\tr1, r2, #20, #11\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ r2 and r3 are free.\\n\\t\"\n",
"\t\"@ Shift back to the normal 53-bit mantissa, with rounding.\\n\\t\"\n",
"\t\"@ Mantissa goes into r0:r1. For r1, we must use an addition\\n\\t\"\n",
"\t\"@ because the rounding may have triggered a carry, that should\\n\\t\"\n",
"\t\"@ be added to the exponent.\\n\\t\"\n",
"\t\"movs\tr4, r6\\n\\t\"\n",
"\t\"lsrs\tr0, r6, #2\\n\\t\"\n",
"\t\"orrs\tr0, r0, r7, lsl #30\\n\\t\"\n",
"\t\"adds\tr1, r1, r7, lsr #2\\n\\t\"\n",
"\t\"ands\tr4, #0x7\\n\\t\"\n",
"\t\"movs\tr3, #0xC8\\n\\t\"\n",
"\t\"lsrs\tr3, r4\\n\\t\"\n",
"\t\"ands\tr3, #1\\n\\t\"\n",
"\t\"adds\tr0, r3\\n\\t\"\n",
"\t\"adcs\tr1, #0\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"pop\t{ r4, r5, r6, r7, r8, r10, r11, pc }\\n\\t\"\n",
"\t);\n",
"}\n",
"\n",
"#else // yyyASM_CORTEXM4+0\n",
"\n",
"fpr\n",
"fpr_mul(fpr x, fpr y)\n",
"{\n",
"\tuint64_t xu, yu, w, zu, zv;\n",
"\tuint32_t x0, x1, y0, y1, z0, z1, z2;\n",
"\tint ex, ey, d, e, s;\n",
"\n",
"\t/*\n",
"\t * Extract absolute values as scaled unsigned integers. We\n",
"\t * don't extract exponents yet.\n",
"\t */\n",
"\txu = (x & (((uint64_t)1 << 52) - 1)) | ((uint64_t)1 << 52);\n",
"\tyu = (y & (((uint64_t)1 << 52) - 1)) | ((uint64_t)1 << 52);\n",
"\n",
"\t/*\n",
"\t * We have two 53-bit integers to multiply; we need to split\n",
"\t * each into a lower half and a upper half. Moreover, we\n",
"\t * prefer to have lower halves to be of 25 bits each, for\n",
"\t * reasons explained later on.\n",
"\t */\n",
"\tx0 = (uint32_t)xu & 0x01FFFFFF;\n",
"\tx1 = (uint32_t)(xu >> 25);\n",
"\ty0 = (uint32_t)yu & 0x01FFFFFF;\n",
"\ty1 = (uint32_t)(yu >> 25);\n",
"\tw = (uint64_t)x0 * (uint64_t)y0;\n",
"\tz0 = (uint32_t)w & 0x01FFFFFF;\n",
"\tz1 = (uint32_t)(w >> 25);\n",
"\tw = (uint64_t)x0 * (uint64_t)y1;\n",
"\tz1 += (uint32_t)w & 0x01FFFFFF;\n",
"\tz2 = (uint32_t)(w >> 25);\n",
"\tw = (uint64_t)x1 * (uint64_t)y0;\n",
"\tz1 += (uint32_t)w & 0x01FFFFFF;\n",
"\tz2 += (uint32_t)(w >> 25);\n",
"\tzu = (uint64_t)x1 * (uint64_t)y1;\n",
"\tz2 += (z1 >> 25);\n",
"\tz1 &= 0x01FFFFFF;\n",
"\tzu += z2;\n",
"\n",
"\t/*\n",
"\t * Since xu and yu are both in the 2^52..2^53-1 range, the\n",
"\t * product is in the 2^104..2^106-1 range. We first reassemble\n",
"\t * it and round it into the 2^54..2^56-1 range; the bottom bit\n",
"\t * is made \"sticky\". Since the low limbs z0 and z1 are 25 bits\n",
"\t * each, we just take the upper part (zu), and consider z0 and\n",
"\t * z1 only for purposes of stickiness.\n",
"\t * (This is the reason why we chose 25-bit limbs above.)\n",
"\t */\n",
"\tzu |= ((z0 | z1) + 0x01FFFFFF) >> 25;\n",
"\n",
"\t/*\n",
"\t * We normalize zu to the 2^54..s^55-1 range: it could be one\n",
"\t * bit too large at this point. This is done with a conditional\n",
"\t * right-shift that takes into account the sticky bit.\n",
"\t */\n",
"\tzv = (zu >> 1) | (zu & 1);\n",
"\tw = zu >> 55;\n",
"\tzu ^= (zu ^ zv) & -w;\n",
"\n",
"\t/*\n",
"\t * Get the aggregate scaling factor:\n",
"\t *\n",
"\t *   - Each exponent is biased by 1023.\n",
"\t *\n",
"\t *   - Integral mantissas are scaled by 2^52, hence an\n",
"\t *     extra 52 bias for each exponent.\n",
"\t *\n",
"\t *   - However, we right-shifted z by 50 bits, and then\n",
"\t *     by 0 or 1 extra bit (depending on the value of w).\n",
"\t *\n",
"\t * In total, we must add the exponents, then subtract\n",
"\t * 2 * (1023 + 52), then add 50 + w.\n",
"\t */\n",
"\tex = (int)((x >> 52) & 0x7FF);\n",
"\tey = (int)((y >> 52) & 0x7FF);\n",
"\te = ex + ey - 2100 + (int)w;\n",
"\n",
"\t/*\n",
"\t * Sign bit is the XOR of the operand sign bits.\n",
"\t */\n",
"\ts = (int)((x ^ y) >> 63);\n",
"\n",
"\t/*\n",
"\t * Corrective actions for zeros: if either of the operands is\n",
"\t * zero, then the computations above were wrong. Test for zero\n",
"\t * is whether ex or ey is zero. We just have to set the mantissa\n",
"\t * (zu) to zero, the FPR() function will normalize e.\n",
"\t */\n",
"\td = ((ex + 0x7FF) & (ey + 0x7FF)) >> 11;\n",
"\tzu &= -(uint64_t)d;\n",
"\n",
"\t/*\n",
"\t * FPR() packs the result and applies proper rounding.\n",
"\t */\n",
"\treturn FPR(s, e, zu);\n",
"}\n",
"\n",
"#endif // yyyASM_CORTEXM4-\n",
"\n",
"#if FALCON_ASM_CORTEXM4 // yyyASM_CORTEXM4+1\n",
"\n",
"__attribute__((naked))\n",
"fpr\n",
"fpr_div(fpr x , fpr y )\n",
"{\n",
"\t__asm__ (\n",
"\t\"push\t{ r4, r5, r6, r7, r8, r10, r11, lr }\\n\\t\"\n",
"\n",
"\t\"@ Extract mantissas of x and y, in r0:r4 and r2:r5, respectively.\\n\\t\"\n",
"\t\"@ We don't touch r1 and r3 as they contain the exponents and\\n\\t\"\n",
"\t\"@ signs, which we'll need later on.\\n\\t\"\n",
"\t\"ubfx\tr4, r1, #0, #20\\n\\t\"\n",
"\t\"ubfx\tr5, r3, #0, #20\\n\\t\"\n",
"\t\"orrs\tr4, r4, #0x00100000\\n\\t\"\n",
"\t\"orrs\tr5, r5, #0x00100000\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Perform bit-by-bit division. We want a 56-bit result in r8:r10\\n\\t\"\n",
"\t\"@ (low bit is 0). Bits come from the carry flag and are\\n\\t\"\n",
"\t\"@ injected with rrx, i.e. in position 31; we thus get bits in\\n\\t\"\n",
"\t\"@ the reverse order. Bits accumulate in r8; after the first 24\\n\\t\"\n",
"\t\"@ bits, we move the quotient bits to r10.\\n\\t\"\n",
"\t\"eors\tr8, r8\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\n",
"#define DIVSTEP \\\n",
"\t\"subs\tr6, r0, r2\\n\\t\" \\\n",
"\t\"sbcs\tr7, r4, r5\\n\\t\" \\\n",
"\t\"rrx\tr8, r8\\n\\t\" \\\n",
"\t\"ands\tr6, r2, r8, asr #31\\n\\t\" \\\n",
"\t\"ands\tr7, r5, r8, asr #31\\n\\t\" \\\n",
"\t\"subs\tr0, r6\\n\\t\" \\\n",
"\t\"sbcs\tr4, r7\\n\\t\" \\\n",
"\t\"adds\tr0, r0, r0\\n\\t\" \\\n",
"\t\"adcs\tr4, r4, r4\\n\\t\"\n",
"\n",
"#define DIVSTEP4   DIVSTEP DIVSTEP DIVSTEP DIVSTEP\n",
"#define DIVSTEP8   DIVSTEP4 DIVSTEP4\n",
"\n",
"\tDIVSTEP8\n",
"\tDIVSTEP8\n",
"\tDIVSTEP8\n",
"\n",
"\t\"\\n\\t\"\n",
"\t\"@ We have the first 24 bits of the quotient, move them to r10.\\n\\t\"\n",
"\t\"rbit\tr10, r8\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\n",
"\tDIVSTEP8\n",
"\tDIVSTEP8\n",
"\tDIVSTEP8\n",
"\tDIVSTEP4 DIVSTEP DIVSTEP DIVSTEP\n",
"\n",
"#undef DIVSTEP\n",
"#undef DIVSTEP4\n",
"#undef DIVSTEP8\n",
"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Lowest bit will be set if remainder is non-zero at this point\\n\\t\"\n",
"\t\"@ (this is the 'sticky' bit).\\n\\t\"\n",
"\t\"subs\tr0, #1\\n\\t\"\n",
"\t\"sbcs\tr4, #0\\n\\t\"\n",
"\t\"rrx\tr8, r8\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ We now have the next (low) 32 bits of the quotient.\\n\\t\"\n",
"\t\"rbit\tr8, r8\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Since both operands had their top bit set, we know that the\\n\\t\"\n",
"\t\"@ result at this point is in 2^54..2^56-1. We scale it down\\n\\t\"\n",
"\t\"@ to 2^54..2^55-1 with a conditional shift. We also write the\\n\\t\"\n",
"\t\"@ result in r4:r5. If the shift is done, r6 will contain -1.\\n\\t\"\n",
"\t\"ands\tr4, r8, #1\\n\\t\"\n",
"\t\"lsrs\tr6, r10, #23\\n\\t\"\n",
"\t\"rsbs\tr6, r6, #0\\n\\t\"\n",
"\t\"orrs\tr4, r4, r8, lsr #1\\n\\t\"\n",
"\t\"orrs\tr4, r4, r10, lsl #31\\n\\t\"\n",
"\t\"lsrs\tr5, r10, #1\\n\\t\"\n",
"\t\"eors\tr8, r8, r4\\n\\t\"\n",
"\t\"eors\tr10, r10, r5\\n\\t\"\n",
"\t\"bics\tr8, r8, r6\\n\\t\"\n",
"\t\"bics\tr10, r10, r6\\n\\t\"\n",
"\t\"eors\tr4, r4, r8\\n\\t\"\n",
"\t\"eors\tr5, r5, r10\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Compute aggregate exponent: ex - ey + 1022 + w\\n\\t\"\n",
"\t\"@ (where w = 1 if the conditional shift was done, 0 otherwise)\\n\\t\"\n",
"\t\"@ But we subtract 1 because the injection of the mantissa high\\n\\t\"\n",
"\t\"@ bit will increment the exponent by 1.\\n\\t\"\n",
"\t\"lsls\tr0, r1, #1\\n\\t\"\n",
"\t\"lsls\tr2, r3, #1\\n\\t\"\n",
"\t\"lsrs\tr0, r0, #21\\n\\t\"\n",
"\t\"addw\tr7, r0, #0x7FF  @ save ex + 2047 in r7\\n\\t\"\n",
"\t\"subs\tr0, r0, r2, lsr #21\\n\\t\"\n",
"\t\"addw\tr0, r0, #1021\\n\\t\"\n",
"\t\"subs\tr0, r6\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ If the x operand was zero, then the computation was wrong and\\n\\t\"\n",
"\t\"@ the result is zero. Also, if the result exponent is zero or\\n\\t\"\n",
"\t\"@ negative, then the mantissa shall be clamped to zero. Since r0\\n\\t\"\n",
"\t\"@ contains the result exponent minus 1, we test on r0 being\\n\\t\"\n",
"\t\"@ strictly negative.\\n\\t\"\n",
"\t\"mvns\tr2, r0\\n\\t\"\n",
"\t\"ands\tr2, r2, r7, lsl #20\\n\\t\"\n",
"\t\"ands\tr0, r0, r2, asr #31\\n\\t\"\n",
"\t\"ands\tr4, r4, r2, asr #31\\n\\t\"\n",
"\t\"ands\tr5, r5, r2, asr #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Sign is the XOR of the sign of the operands. This is true in\\n\\t\"\n",
"\t\"@ all cases, including very small results (exponent underflow)\\n\\t\"\n",
"\t\"@ and zeros.\\n\\t\"\n",
"\t\"eors\tr1, r3\\n\\t\"\n",
"\t\"bfc\tr1, #0, #31\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Plug in the exponent.\\n\\t\"\n",
"\t\"bfi\tr1, r0, #20, #11\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Shift back to the normal 53-bit mantissa, with rounding.\\n\\t\"\n",
"\t\"@ Mantissa goes into r0:r1. For r1, we must use an addition\\n\\t\"\n",
"\t\"@ because the rounding may have triggered a carry, that should\\n\\t\"\n",
"\t\"@ be added to the exponent.\\n\\t\"\n",
"\t\"movs\tr6, r4\\n\\t\"\n",
"\t\"lsrs\tr0, r4, #2\\n\\t\"\n",
"\t\"orrs\tr0, r0, r5, lsl #30\\n\\t\"\n",
"\t\"adds\tr1, r1, r5, lsr #2\\n\\t\"\n",
"\t\"ands\tr6, #0x7\\n\\t\"\n",
"\t\"movs\tr3, #0xC8\\n\\t\"\n",
"\t\"lsrs\tr3, r6\\n\\t\"\n",
"\t\"ands\tr3, #1\\n\\t\"\n",
"\t\"adds\tr0, r3\\n\\t\"\n",
"\t\"adcs\tr1, #0\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"pop\t{ r4, r5, r6, r7, r8, r10, r11, pc }\\n\\t\"\n",
"\t);\n",
"}\n",
"\n",
"#else // yyyASM_CORTEXM4+0\n",
"\n",
"fpr\n",
"fpr_div(fpr x, fpr y)\n",
"{\n",
"\tuint64_t xu, yu, q, q2, w;\n",
"\tint i, ex, ey, e, d, s;\n",
"\n",
"\t/*\n",
"\t * Extract mantissas of x and y (unsigned).\n",
"\t */\n",
"\txu = (x & (((uint64_t)1 << 52) - 1)) | ((uint64_t)1 << 52);\n",
"\tyu = (y & (((uint64_t)1 << 52) - 1)) | ((uint64_t)1 << 52);\n",
"\n",
"\t/*\n",
"\t * Perform bit-by-bit division of xu by yu. We run it for 55 bits.\n",
"\t */\n",
"\tq = 0;\n",
"\tfor (i = 0; i < 55; i ++) {\n",
"\t\t/*\n",
"\t\t * If yu is less than or equal xu, then subtract it and\n",
"\t\t * push a 1 in the quotient; otherwise, leave xu unchanged\n",
"\t\t * and push a 0.\n",
"\t\t */\n",
"\t\tuint64_t b;\n",
"\n",
"\t\tb = ((xu - yu) >> 63) - 1;\n",
"\t\txu -= b & yu;\n",
"\t\tq |= b & 1;\n",
"\t\txu <<= 1;\n",
"\t\tq <<= 1;\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * We got 55 bits in the quotient, followed by an extra zero. We\n",
"\t * want that 56th bit to be \"sticky\": it should be a 1 if and\n",
"\t * only if the remainder (xu) is non-zero.\n",
"\t */\n",
"\tq |= (xu | -xu) >> 63;\n",
"\n",
"\t/*\n",
"\t * Quotient is at most 2^56-1. Its top bit may be zero, but in\n",
"\t * that case the next-to-top bit will be a one, since the\n",
"\t * initial xu and yu were both in the 2^52..2^53-1 range.\n",
"\t * We perform a conditional shift to normalize q to the\n",
"\t * 2^54..2^55-1 range (with the bottom bit being sticky).\n",
"\t */\n",
"\tq2 = (q >> 1) | (q & 1);\n",
"\tw = q >> 55;\n",
"\tq ^= (q ^ q2) & -w;\n",
"\n",
"\t/*\n",
"\t * Extract exponents to compute the scaling factor:\n",
"\t *\n",
"\t *   - Each exponent is biased and we scaled them up by\n",
"\t *     52 bits; but these biases will cancel out.\n",
"\t *\n",
"\t *   - The division loop produced a 55-bit shifted result,\n",
"\t *     so we must scale it down by 55 bits.\n",
"\t *\n",
"\t *   - If w = 1, we right-shifted the integer by 1 bit,\n",
"\t *     hence we must add 1 to the scaling.\n",
"\t */\n",
"\tex = (int)((x >> 52) & 0x7FF);\n",
"\tey = (int)((y >> 52) & 0x7FF);\n",
"\te = ex - ey - 55 + (int)w;\n",
"\n",
"\t/*\n",
"\t * Sign is the XOR of the signs of the operands.\n",
"\t */\n",
"\ts = (int)((x ^ y) >> 63);\n",
"\n",
"\t/*\n",
"\t * Corrective actions for zeros: if x = 0, then the computation\n",
"\t * is wrong, and we must clamp e and q to 0. We do not care\n",
"\t * about the case y = 0 (as per assumptions in this module,\n",
"\t * the caller does not perform divisions by zero).\n",
"\t */\n",
"\td = (ex + 0x7FF) >> 11;\n",
"\ts &= d;\n",
"\te &= -d;\n",
"\tq &= -(uint64_t)d;\n",
"\n",
"\t/*\n",
"\t * FPR() packs the result and applies proper rounding.\n",
"\t */\n",
"\treturn FPR(s, e, q);\n",
"}\n",
"\n",
"#endif // yyyASM_CORTEXM4-\n",
"\n",
"#if FALCON_ASM_CORTEXM4 // yyyASM_CORTEXM4+1\n",
"\n",
"__attribute__((naked))\n",
"fpr\n",
"fpr_sqrt(fpr x )\n",
"{\n",
"\t__asm__ (\n",
"\t\"push\t{ r4, r5, r6, r7, r8, r10, r11, lr }\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Extract mantissa (r0:r1) and exponent (r2). We assume that the\\n\\t\"\n",
"\t\"@ sign is positive. If the source is zero, then the mantissa is\\n\\t\"\n",
"\t\"@ set to 0.\\n\\t\"\n",
"\t\"lsrs\tr2, r1, #20\\n\\t\"\n",
"\t\"bfc\tr1, #20, #12\\n\\t\"\n",
"\t\"addw\tr3, r2, #0x7FF\\n\\t\"\n",
"\t\"subw\tr2, r2, #1023\\n\\t\"\n",
"\t\"lsrs\tr3, r3, #11\\n\\t\"\n",
"\t\"orrs\tr1, r1, r3, lsl #20\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ If the exponent is odd, then multiply mantissa by 2 and subtract\\n\\t\"\n",
"\t\"@ 1 from the exponent.\\n\\t\"\n",
"\t\"ands\tr3, r2, #1\\n\\t\"\n",
"\t\"subs\tr2, r2, r3\\n\\t\"\n",
"\t\"rsbs\tr3, r3, #0\\n\\t\"\n",
"\t\"ands\tr4, r1, r3\\n\\t\"\n",
"\t\"ands\tr3, r0\\n\\t\"\n",
"\t\"adds\tr0, r3\\n\\t\"\n",
"\t\"adcs\tr1, r4\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Left-shift the mantissa by 9 bits to put it in the\\n\\t\"\n",
"\t\"@ 2^61..2^63-1 range (unless it is exactly 0).\\n\\t\"\n",
"\t\"lsls\tr1, r1, #9\\n\\t\"\n",
"\t\"orrs\tr1, r1, r0, lsr #23\\n\\t\"\n",
"\t\"lsls\tr0, r0, #9\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Compute the square root bit-by-bit.\\n\\t\"\n",
"\t\"@ There are 54 iterations; first 30 can work on top word only.\\n\\t\"\n",
"\t\"@   q = r3 (bit-reversed)\\n\\t\"\n",
"\t\"@   s = r5\\n\\t\"\n",
"\t\"eors\tr3, r3\\n\\t\"\n",
"\t\"eors\tr5, r5\\n\\t\"\n",
"\n",
"#define SQRT_STEP_HI(bit) \\\n",
"\t\"orrs\tr6, r5, #(1 << (\" #bit \"))\\n\\t\" \\\n",
"\t\"subs\tr7, r1, r6\\n\\t\" \\\n",
"\t\"rrx\tr3, r3\\n\\t\" \\\n",
"\t\"ands\tr6, r6, r3, asr #31\\n\\t\" \\\n",
"\t\"subs\tr1, r1, r6\\n\\t\" \\\n",
"\t\"lsrs\tr6, r3, #31\\n\\t\" \\\n",
"\t\"orrs\tr5, r5, r6, lsl #((\" #bit \") + 1)\\n\\t\" \\\n",
"\t\"adds\tr0, r0\\n\\t\" \\\n",
"\t\"adcs\tr1, r1\\n\\t\"\n",
"\n",
"#define SQRT_STEP_HIx5(b)  \\\n",
"\t\tSQRT_STEP_HI((b)+4) \\\n",
"\t\tSQRT_STEP_HI((b)+3) \\\n",
"\t\tSQRT_STEP_HI((b)+2) \\\n",
"\t\tSQRT_STEP_HI((b)+1) \\\n",
"\t\tSQRT_STEP_HI(b)\n",
"\n",
"\tSQRT_STEP_HIx5(25)\n",
"\tSQRT_STEP_HIx5(20)\n",
"\tSQRT_STEP_HIx5(15)\n",
"\tSQRT_STEP_HIx5(10)\n",
"\tSQRT_STEP_HIx5(5)\n",
"\tSQRT_STEP_HIx5(0)\n",
"\n",
"#undef SQRT_STEP_HI\n",
"#undef SQRT_STEP_HIx5\n",
"\n",
"\t\"@ Top 30 bits of the result must be reversed: they were\\n\\t\"\n",
"\t\"@ accumulated with rrx (hence from the top bit).\\n\\t\"\n",
"\t\"rbit\tr3, r3\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ For the next 24 iterations, we must use two-word operations.\\n\\t\"\n",
"\t\"@   bits of q now accumulate in r4\\n\\t\"\n",
"\t\"@   s is in r6:r5\\n\\t\"\n",
"\t\"eors\tr4, r4\\n\\t\"\n",
"\t\"eors\tr6, r6\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ First iteration is special because the potential bit goes into\\n\\t\"\n",
"\t\"@ r5, not r6.\\n\\t\"\n",
"\t\"orrs\tr7, r6, #(1 << 31)\\n\\t\"\n",
"\t\"subs\tr8, r0, r7\\n\\t\"\n",
"\t\"sbcs\tr10, r1, r5\\n\\t\"\n",
"\t\"rrx\tr4, r4\\n\\t\"\n",
"\t\"ands\tr7, r7, r4, asr #31\\n\\t\"\n",
"\t\"ands\tr8, r5, r4, asr #31\\n\\t\"\n",
"\t\"subs\tr0, r0, r7\\n\\t\"\n",
"\t\"sbcs\tr1, r1, r8\\n\\t\"\n",
"\t\"lsrs\tr7, r4, #31\\n\\t\"\n",
"\t\"orrs\tr5, r5, r4, lsr #31\\n\\t\"\n",
"\t\"adds\tr0, r0\\n\\t\"\n",
"\t\"adcs\tr1, r1\\n\\t\"\n",
"\n",
"#define SQRT_STEP_LO(bit) \\\n",
"\t\"orrs\tr7, r6, #(1 << (\" #bit \"))\\n\\t\" \\\n",
"\t\"subs\tr8, r0, r7\\n\\t\" \\\n",
"\t\"sbcs\tr10, r1, r5\\n\\t\" \\\n",
"\t\"rrx\tr4, r4\\n\\t\" \\\n",
"\t\"ands\tr7, r7, r4, asr #31\\n\\t\" \\\n",
"\t\"ands\tr8, r5, r4, asr #31\\n\\t\" \\\n",
"\t\"subs\tr0, r0, r7\\n\\t\" \\\n",
"\t\"sbcs\tr1, r1, r8\\n\\t\" \\\n",
"\t\"lsrs\tr7, r4, #31\\n\\t\" \\\n",
"\t\"orrs\tr6, r6, r7, lsl #((\" #bit \") + 1)\\n\\t\" \\\n",
"\t\"adds\tr0, r0\\n\\t\" \\\n",
"\t\"adcs\tr1, r1\\n\\t\"\n",
"\n",
"#define SQRT_STEP_LOx4(b) \\\n",
"\t\tSQRT_STEP_LO((b)+3) \\\n",
"\t\tSQRT_STEP_LO((b)+2) \\\n",
"\t\tSQRT_STEP_LO((b)+1) \\\n",
"\t\tSQRT_STEP_LO(b)\n",
"\n",
"\tSQRT_STEP_LO(30)\n",
"\tSQRT_STEP_LO(29)\n",
"\tSQRT_STEP_LO(28)\n",
"\tSQRT_STEP_LOx4(24)\n",
"\tSQRT_STEP_LOx4(20)\n",
"\tSQRT_STEP_LOx4(16)\n",
"\tSQRT_STEP_LOx4(12)\n",
"\tSQRT_STEP_LOx4(8)\n",
"\n",
"#undef SQRT_STEP_LO\n",
"#undef SQRT_STEP_LOx4\n",
"\n",
"\t\"@ Put low 24 bits in the right order.\\n\\t\"\n",
"\t\"rbit\tr4, r4\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ We have a 54-bit result; compute the 55-th bit as the 'sticky'\\n\\t\"\n",
"\t\"@ bit: it is non-zero if and only if r0:r1 is non-zero. We put the\\n\\t\"\n",
"\t\"@ three low bits (including the sticky bit) in r5.\\n\\t\"\n",
"\t\"orrs\tr0, r1\\n\\t\"\n",
"\t\"rsbs\tr1, r0, #0\\n\\t\"\n",
"\t\"orrs\tr0, r1\\n\\t\"\n",
"\t\"lsls\tr5, r4, #1\\n\\t\"\n",
"\t\"orrs\tr5, r5, r0, lsr #31\\n\\t\"\n",
"\t\"ands\tr5, #0x7\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Compute the rounding: r6 is set to 0 or 1, and will be added\\n\\t\"\n",
"\t\"@ to the mantissa.\\n\\t\"\n",
"\t\"movs\tr6, #0xC8\\n\\t\"\n",
"\t\"lsrs\tr6, r5\\n\\t\"\n",
"\t\"ands\tr6, #1\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Put the mantissa (53 bits, in the 2^52..2^53-1 range) in r0:r1\\n\\t\"\n",
"\t\"@ (rounding not applied yet).\\n\\t\"\n",
"\t\"lsrs\tr0, r4, #1\\n\\t\"\n",
"\t\"orrs\tr0, r0, r3, lsl #23\\n\\t\"\n",
"\t\"lsrs\tr1, r3, #9\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Compute new exponent. This is half the old one (then reencoded\\n\\t\"\n",
"\t\"@ by adding 1023). Exception: if the mantissa is zero, then the\\n\\t\"\n",
"\t\"@ encoded exponent is set to 0. At that point, if the mantissa\\n\\t\"\n",
"\t\"@ is non-zero, then its high bit (bit 52, i.e. bit 20 of r1) is\\n\\t\"\n",
"\t\"@ non-zero. Note that the exponent cannot go out of range.\\n\\t\"\n",
"\t\"lsrs\tr2, r2, #1\\n\\t\"\n",
"\t\"addw\tr2, r2, #1023\\n\\t\"\n",
"\t\"lsrs\tr5, r1, #20\\n\\t\"\n",
"\t\"rsbs\tr5, r5, #0\\n\\t\"\n",
"\t\"ands\tr2, r5\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Place exponent. This overwrites the high bit of the mantissa.\\n\\t\"\n",
"\t\"bfi\tr1, r2, #20, #11\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"@ Apply rounding. This may create a carry that will spill into\\n\\t\"\n",
"\t\"@ the exponent, which is exactly what should be done in that case\\n\\t\"\n",
"\t\"@ (i.e. increment the exponent).\\n\\t\"\n",
"\t\"adds\tr0, r0, r6\\n\\t\"\n",
"\t\"adcs\tr1, r1, #0\\n\\t\"\n",
"\t\"\\n\\t\"\n",
"\t\"pop\t{ r4, r5, r6, r7, r8, r10, r11, pc }\\n\\t\"\n",
"\t);\n",
"}\n",
"\n",
"#else // yyyASM_CORTEXM4+0\n",
"\n",
"fpr\n",
"fpr_sqrt(fpr x)\n",
"{\n",
"\tuint64_t xu, q, s, r;\n",
"\tint ex, e;\n",
"\n",
"\t/*\n",
"\t * Extract the mantissa and the exponent. We don't care about\n",
"\t * the sign: by assumption, the operand is nonnegative.\n",
"\t * We want the \"true\" exponent corresponding to a mantissa\n",
"\t * in the 1..2 range.\n",
"\t */\n",
"\txu = (x & (((uint64_t)1 << 52) - 1)) | ((uint64_t)1 << 52);\n",
"\tex = (int)((x >> 52) & 0x7FF);\n",
"\te = ex - 1023;\n",
"\n",
"\t/*\n",
"\t * If the exponent is odd, double the mantissa and decrement\n",
"\t * the exponent. The exponent is then halved to account for\n",
"\t * the square root.\n",
"\t */\n",
"\txu += xu & -(uint64_t)(e & 1);\n",
"\te >>= 1;\n",
"\n",
"\t/*\n",
"\t * Double the mantissa.\n",
"\t */\n",
"\txu <<= 1;\n",
"\n",
"\t/*\n",
"\t * We now have a mantissa in the 2^53..2^55-1 range. It\n",
"\t * represents a value between 1 (inclusive) and 4 (exclusive)\n",
"\t * in fixed point notation (with 53 fractional bits). We\n",
"\t * compute the square root bit by bit.\n",
"\t */\n",
"\tq = 0;\n",
"\ts = 0;\n",
"\tr = (uint64_t)1 << 53;\n",
"\tfor (int i = 0; i < 54; i ++) {\n",
"\t\tuint64_t t, b;\n",
"\n",
"\t\tt = s + r;\n",
"\t\tb = ((xu - t) >> 63) - 1;\n",
"\t\ts += (r << 1) & b;\n",
"\t\txu -= t & b;\n",
"\t\tq += r & b;\n",
"\t\txu <<= 1;\n",
"\t\tr >>= 1;\n",
"\t}\n",
"\n",
"\t/*\n",
"\t * Now, q is a rounded-low 54-bit value, with a leading 1,\n",
"\t * 52 fractional digits, and an additional guard bit. We add\n",
"\t * an extra sticky bit to account for what remains of the operand.\n",
"\t */\n",
"\tq <<= 1;\n",
"\tq |= (xu | -xu) >> 63;\n",
"\n",
"\t/*\n",
"\t * Result q is in the 2^54..2^55-1 range; we bias the exponent\n",
"\t * by 54 bits (the value e at that point contains the \"true\"\n",
"\t * exponent, but q is now considered an integer, i.e. scaled\n",
"\t * up.\n",
"\t */\n",
"\te -= 54;\n",
"\n",
"\t/*\n",
"\t * Corrective action for an operand of value zero.\n",
"\t */\n",
"\tq &= -(uint64_t)((ex + 0x7FF) >> 11);\n",
"\n",
"\t/*\n",
"\t * Apply rounding and back result.\n",
"\t */\n",
"\treturn FPR(0, e, q);\n",
"}\n",
"\n",
"#endif // yyyASM_CORTEXM4-\n"
]
end FT1536.Source3.FprPinned
