import Source3.KeygenLevelModularFrame
import Source3.KeygenLevelNtt
import Source3.KeygenLevelCalls
import Source3.KeygenLevelExec
import Source3.KeygenLevelParser
import Source3.KeygenMakeFgTop
import Source3.KeygenWordExpr
import Source3.KeygenWordExec
import Source3.KeygenWordParser
import Source3.KeygenZintLeaves
import Source3.KeygenResultantSource
import Source3.KeygenResultantGate
import Source3.KeygenNormFrame
import Source3.KeygenDepth0Call
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated by tools/keygen_levels_audit_source.py. Internal audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenLevelModularFrame,
      ["only","body_frame","sequence_checked"]),
    (`FT1536.Source3.KeygenLevelNtt,
      ["region","declarators","mixed","mixedCode","ranges","parsed","part","sizeCode","inverse","writable","audit","signature_source","size_source","mixed_source","partition_source","closing_source","wrapper_source","audit0","audit1","audit2","audit3","audit4","audit_all","parsed_part","part_checked","inverse_checked","forward_checked","Kind","body","params","Call","checked","call_frame"]),
    (`FT1536.Source3.KeygenLevelCalls,
      ["Field","fieldPointer","PrimeRead","Expr","Eval","Arg","Bind","bind_heap","arguments","bind_outside","Kind","params","body","writable","generator_checked","checked","Call","call_frame"]),
    (`FT1536.Source3.KeygenLevelCalls.Field,
      ["offset"]),
    (`FT1536.Source3.KeygenLevelExec,
      ["Stmt","skip","chain","Exec","only","body_frame"]),
    (`FT1536.Source3.KeygenLevelParser,
      ["tokenize","field","prime","expr","argument","arguments","callee","callParams","expandArgs","simple","modularDeclarations","declarations","statement","body","region"]),
    (`FT1536.Source3.KeygenMakeFgTop,
      ["types","writable","parsed","code","signature_source","closing_source","source_audit","source_parsed","code_checked","params","Call","call_frame","actualArgs","actual_args_checked","material"]),
    (`FT1536.Source3.KeygenWordExpr,
      ["Expr","Eval","typeToken","mkn","applyOp","parseArgs","unary","more","parse","expression"]),
    (`FT1536.Source3.KeygenWordExec,
      ["Stmt","skip","chain","Exec","only","body_frame"]),
    (`FT1536.Source3.KeygenWordParser,
      ["increment","clause","clauses","simple","declarations","postLoop","statement","body","region"]),
    (`FT1536.Source3.KeygenZintLeaves,
      ["Kind","range","name","params","result","types","writable","parsed","code","header","sourceAudit","add_source","sub_source","mul_source","add_mul_source","shift_source","reduce_source","compare_source","sources","header_source","parsed_audit","parsed_source","code_checked","Call","frame"]),
    (`FT1536.Source3.KeygenResultantSource,
      ["region","types","setup","parsedPacking","packing","ranges","parsedPart","part","writable","audit","switchCode","parsedTail","tailCode","signature_source","opening_comment","array_source","setup_source","memset_source","switch_partition","closing_source","setup_checked","packing_audit","tail_audit","audit0","audit1","audit2","audit3","audit4","audit5","audit6","audit7","audit8","audit_all","from_audit","packing_source","packing_checked","part_source","part_checked","tail_source","tail_checked","chain_checked","switch_checked","allocated","object","zeroed","ZeroLegal","entry","params","Call","bytes"]),
    (`FT1536.Source3.KeygenResultantGate,
      ["selected","visible","selected_source","arguments","Exec","bytes","material","sampled_material"]),
    (`FT1536.Source3.KeygenNormFrame,
      ["selected","visible","selected_source","types","writable","parsed","code","source_audit","source_parsed","code_checked","gate_source","Compare","Gate","Exec","Protected","bytes","material"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.KeygenSamplerCalls.two_calls,
    ``FT1536.Source3.KeygenDepth0Call.call_gate_validated,
    ``FT1536.Source3.KeygenOutputGateValidation.Validation,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.C99ModularReference.ModCall,
    ``FT1536.Source3.C99ModularReference.LeafCall,
    ``FT1536.Source3.C99ModularReference.r2Body,
    ``FT1536.Source3.C99ModularReference.divBody,
    ``FT1536.Source3.C99CompareObjects.Exec,
    ``FT1536.Source3.C99CompareObjects.exists_execution,
    ``FT1536.Source3.C99CompareObjects.source_decomposition,
    ``FT1536.Source3.FprCompare.source_parses,
    ``FT1536.Source3.FprPrefixCalls.calls,
    ``FT1536.Source3.KeygenSearchMemory.Memmove,
    ``FT1536.Source3.C99ArrayReference.Bind,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue,
    ``FT1536.Source3.C99MemoryReference.Load32,
    ``FT1536.Source3.C99MemoryReference.Store32,
    ``FT1536.Source3.KeygenM0Preprocess.preprocess]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../LEVELS_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.writeFile "../LEVELS_AUDIT_PARTIAL.json" (Lean.Json.arr rows |>.pretty)
  IO.FS.writeFile "../LEVELS_AUDIT.json" (Lean.Json.arr rows |>.pretty)
