import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensReduce3
def text0 : String := "\t\t/*\n"
def text1 : String := "\t\t * We need to scale down k by at least scale_k bits. The\n"
def text2 : String := "\t\t * final scale will be: scale_FG + scale_k - maxbl_fg;\n"
def text3 : String := "\t\t * we also need this value to be nonnegative.\n"
def text4 : String := "\t\t */\n"
def text5 : String := "\t\tif (scale_k + scale_FG < maxbl_fg) {\n"
def text6 : String := "\t\t\tscale_k = maxbl_fg - scale_FG;\n"
def text7 : String := "\t\t\tif (scale_k > 62) {\n"
def text8 : String := "\t\t\t\tbreak;\n"
def text9 : String := "\t\t\t}\n"
def text10 : String := "\t\t}\n"
def text11 : String := "\n"
def text12 : String := "\t\tscale_FG += scale_k;\n"
def text13 : String := "\n"
def text14 : String := "\t\t/*\n"
def text15 : String := "\t\t * Get the coefficients of k as int32_t.\n"
def text16 : String := "\t\t */\n"
def tail17 : List String := []
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[6297]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[6298]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[6299]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[6300]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[6301]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[6302]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[6303]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[6304]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[6305]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[6306]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[6307]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[6308]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[6309]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[6310]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[6311]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[6312]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[6313]?=some text16 := by decide +kernel
theorem bytes17 : (Pinned.keygenLines.drop 6314).take tail17.length=tail17 := rfl
theorem bytes16 : (Pinned.keygenLines.drop 6313).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6313 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 6312).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6312 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 6311).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6311 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 6310).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6310 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 6309).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6309 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 6308).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6308 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 6307).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6307 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 6306).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6306 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 6305).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6305 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 6304).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6304 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 6303).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6303 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 6302).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6302 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 6301).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6301 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 6300).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6300 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 6299).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6299 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 6298).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6298 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 6297).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6297 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 6297).take 17=lines := bytes0
def group0 : List String := [text0,text1,text2,text3,text4]
def words0 : List B20.C.Token := [].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text5]
def words1 : List B20.C.Token := ["if","(","scale_k","+","scale_FG","<","maxbl_fg",")","{"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text6]
def words2 : List B20.C.Token := ["scale_k","=","maxbl_fg","-","scale_FG",";"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text7]
def words3 : List B20.C.Token := ["if","(","scale_k",">","62",")","{"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text8]
def words4 : List B20.C.Token := ["break",";"].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text9]
def words5 : List B20.C.Token := ["}"].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text10]
def words6 : List B20.C.Token := ["}"].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text11]
def words7 : List B20.C.Token := [].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text12]
def words8 : List B20.C.Token := ["scale_FG","+=","scale_k",";"].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text13]
def words9 : List B20.C.Token := [].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text14,text15,text16]
def words10 : List B20.C.Token := [].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.nil)))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 6297).take 17) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensReduce3
