import Source3.KeygenSearchFft
import Source3.KeygenSearchProbe
import Source3.KeygenSearchMemory
import Source3.KeygenSearchLeaves
import Source3.KeygenSearchContext
import Source3.KeygenSearchExec
import Source3.KeygenSearchFrame
import Source3.KeygenSearchParser
import Source3.KeygenDepth0Source
import Source3.KeygenDepth0Call
import Source3.KeygenDepth0Return
import Source3.KeygenSamplerCalls
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated by tools/keygen_search_audit_source.py. Internal audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenSearchFft,
      ["Id","all","name","find","region","text","header","signatures","source","program","writable","permissions","interfaces","audit","header_inverse","header_mul","header_invnorm","audit_inverse","audit_mul","audit_invnorm","audit_add","audit_sub","audit_neg","audit_adj","audit_selfAdj","audit_mulAuto","audit_divAuto","audit_fft","audit_mulAdj","audit_splitTop","audit_splitDeep","audit_ldl2","audit_ldl3","audit_inner","audit_depth1","audit_ldlTop","audit_inherited","audit_all","audited_body","aligned","closed","body_frame"]),
    (`FT1536.Source3.KeygenSearchProbe,
      ["alignLines","alignScaffold","alignment_source","remainder_lexer_rejects"]),
    (`FT1536.Source3.KeygenSearchMemory,
      ["view","Cast","cast_offset","cast_end","cast_outside","localNames","scalarEntry","condition","update","rounding","helper_source","signature_source","Align","align_outside","Memmove","memmove_frame"]),
    (`FT1536.Source3.KeygenSearchLeaves,
      ["smallBody","smallParsed","smallParams","small_header","small_source","small_writes","SmallCall","small_frame","rintBody","rintCode","rint_source","Rint"]),
    (`FT1536.Source3.KeygenSearchContext,
      ["Context","field","pointerWord","PointerLegal","ObjectLegal","Bound","ReadLogn","ReadTernary","ReadTmp","outputView","M0","logn_m0","ternary_m0","tmp_value","fields_source"]),
    (`FT1536.Source3.KeygenSearchExec,
      ["PointerExpr","EvalPointer","Expr","ScalarCall","Eval","Stmt","skip","chain","Exec"]),
    (`FT1536.Source3.KeygenSearchFrame,
      ["pointerOnly","only","pointer_outside","body_frame"]),
    (`FT1536.Source3.KeygenSearchParser,
      ["width","typeWidth","pointer","expr","sizes","simple","declarations","statement","body"]),
    (`FT1536.Source3.KeygenDepth0Source,
      ["types","region","lines","parsed","part","code","writable","audit","signature_source","macro_header","macro_body","macro_undef","closing_source","source_partition","audit0","audit1","audit2","audit3","audit4","audit_all","parsed_part","part_checked","sequence_checked","code_checked"]),
    (`FT1536.Source3.KeygenDepth0Call,
      ["params","arguments","call_source","Call","Protected","arguments_readonly","frame","slots","material","output_caller","MemberGate","call_gate_validated"]),
    (`FT1536.Source3.KeygenDepth0Return,
      ["Allowed","one","procedureOnly","procedure_flow","only","source_flow","audit","audit0","audit1","audit2","audit3","audit4","audit_all","part_checked","sequence_checked","code_checked","return_one"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.KeygenOutputGateValidation.gate_validated,
    ``FT1536.Source3.KeygenOutputGateValidation.Validation,
    ``FT1536.Source3.KeygenOutputGateBounds.gate_material,
    ``FT1536.Source3.KeygenSamplerCalls.two_calls,
    ``FT1536.Source3.KeygenSolverEquation.Bounds,
    ``FT1536.Source3.KeygenSolverEquation.Equation,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.C99ArrayReference.Bind,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue,
    ``FT1536.Source3.C99MemoryReference.Load32,
    ``FT1536.Source3.C99MemoryReference.Load64,
    ``FT1536.Source3.C99MemoryReference.Store32,
    ``FT1536.Source3.C99MemoryReference.Store64,
    ``FT1536.Source3.KeygenSmallSource.PlainCall,
    ``FT1536.Source3.FprPrefixCalls.calls]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../SEARCH_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.writeFile "../SEARCH_AUDIT_PARTIAL.json" (Lean.Json.arr rows |>.pretty)
  IO.FS.writeFile "../SEARCH_AUDIT.json" (Lean.Json.arr rows |>.pretty)
