import Source3.KeygenPublicLinear
import Source3.KeygenPublicLeafWords
import Source3.KeygenPublicMontgomery
import Source3.KeygenPublicAlgebra
import Source3.KeygenPublicArguments
import Source3.KeygenPublicSquare
import Source3.KeygenPublicDivisionWords
import Source3.KeygenPublicDivisionAlgebra
import Source3.KeygenPublicRoots
import Source3.KeygenPublicSource
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated by tools/keygen_public_audit_source.py. Internal audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenPublicLinear,
      ["atom","body","observation","ScalarFlow","atom_projection","body_projection","scope_return","return_value"]),
    (`FT1536.Source3.KeygenPublicLeafWords,
      ["var","correction","code","locals","Supported","source_binding","checked","montgomery","half","add_model","sub_model","mul_model","conv_model","half_model","body_complete","bound_add_sub","bound_mul","bound_two","source_add","source_sub","source_mul","source_conv","source_half"]),
    (`FT1536.Source3.KeygenPublicMontgomery,
      ["radix","modulus","inverse","inverse_source","product","low_product","correction_product","quotient_word","word_to_arithmetic","word_contract"]),
    (`FT1536.Source3.KeygenPublicAlgebra,
      ["R","modulusPrime","value","radix","Canonical","name_injective","leaf_body","call_leaf","radix_inverse","radix_word","radix_squared_word","source_add","source_sub","source_mul","source_twiddle","source_scaled_product","source_conv","halfNumerator","half_exact","half_contract","source_half"]),
    (`FT1536.Source3.KeygenPublicArguments,
      ["Conversion","lengths","bind_equal","body_conversion","call_leaf_conversion","U32","u32_self","u32_literal","source_add","source_sub","source_mul","source_mul_exact"]),
    (`FT1536.Source3.KeygenPublicSquare,
      ["read","code","source_code","Slot","variable_value","converted_word","ret_expression","square_body","source_square_exact","source_square_arguments","source_square"]),
    (`FT1536.Source3.KeygenPublicDivisionWords,
      ["Operand","Instruction","firstNames","lastNames","names","operand","word","target","expression","result","update","run","statement","chain","operandAllowed","allowed","Ready","steps","finalStep","tail","code","initial","division","source_code","allowed_steps","allowed_final","operand_value","expression_value","step_ready","chain_execution","base_tail","declared_locals","ready_entry","ternary_body","source_exact"]),
    (`FT1536.Source3.KeygenPublicDivisionAlgebra,
      ["multiply","Scaled","multiply_value","scaled_product","scaled_square","conversion","w0","w1","w2","w3","w4","w5","w6","w7","w8","w9","w10","w11","w12","w13","w14","w15","w16","w17","w18","scaled0","scaled1","scaled2","scaled3","scaled4","scaled5","scaled6","scaled7","scaled8","scaled9","scaled10","scaled11","scaled12","scaled13","scaled14","scaled15","scaled16","scaled17","scaled18","source_word_formula","division_power","nonzero_value","source_power","source_division","normalize_call","source_division_arguments"]),
    (`FT1536.Source3.KeygenPublicRoots,
      ["generator","root","firstRoot","pointExponent","point","unity","source_generator","generator_pow","order_power","order_half","order_third","generator_order","root_order","first_root_order","first_root_relation","first_root_fifth","last_exponent","last_bounds","last_injective","point_exponent_bounds","point_exponent_injective","points_distinct","point_exponent_mod_six","point_half_power","points_are_roots","coefficient_injective"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.KeygenPublicScalar.Kind,
    ``FT1536.Source3.KeygenPublicScalar.params,
    ``FT1536.Source3.KeygenPublicScalar.code,
    ``FT1536.Source3.KeygenPublicScalar.parsed_source,
    ``FT1536.Source3.KeygenPublicScalar.Body,
    ``FT1536.Source3.KeygenPublicScalar.Leaf,
    ``FT1536.Source3.KeygenPublicScalar.Square,
    ``FT1536.Source3.KeygenPublicScalar.Call,
    ``FT1536.Source3.KeygenPublicSource.Call,
    ``FT1536.Source3.KeygenPublicSource.code_checked,
    ``FT1536.Source3.KeygenPublicWord.Eval,
    ``FT1536.Source3.KeygenPublicWord.Bind,
    ``FT1536.Source3.KeygenPublicExec.Exec,
    ``FT1536.Source3.C99ModularReference.GenEval,
    ``FT1536.Source3.C99ModularReference.GenExec,
    ``FT1536.Source3.C99ModularReference.bindParams,
    ``FT1536.Source3.C99ArrayReference.scalar,
    ``FT1536.Source3.C99ScalarReference.BindArgs,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.KeygenMkgm3Indices.tableExponent,
    ``FT1536.Source3.KeygenMkgm3IndexCert.all_indices,
    ``FT1536.Source3.MontgomeryArithmetic.reduction_contract]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../PUBLIC_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.withFile "../PUBLIC_AUDIT_ENTRIES.jsonl" .append fun stream =>
      stream.putStrLn rows.back!.compress
  IO.FS.writeFile "../PUBLIC_AUDIT.json" (Lean.Json.arr rows |>.pretty)
