import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensTop4
def text0 : String := "\tfor (u = 0; u < llen; u ++) {\n"
def text1 : String := "\t\tuint32_t p, p0i, R2, Rx;\n"
def text2 : String := "\t\tsize_t v;\n"
def text3 : String := "\t\tuint32_t *xs, *ys, *xd, *yd;\n"
def text4 : String := "\n"
def text5 : String := "\t\tp = primes[u].p;\n"
def text6 : String := "\t\tp0i = modp_ninv31(p);\n"
def text7 : String := "\t\tR2 = modp_R2(p, p0i);\n"
def text8 : String := "\t\tRx = modp_Rx(dlen, p, p0i, R2);\n"
def text9 : String := "\t\tfor (v = 0, xs = Fd, ys = Gd, xd = Ft + u, yd = Gt + u;\n"
def text10 : String := "\t\t\tv < hn;\n"
def text11 : String := "\t\t\tv ++, xs += dlen, ys += dlen, xd += llen, yd += llen)\n"
def text12 : String := "\t\t{\n"
def text13 : String := "\t\t\t*xd = zint_mod_small_signed(xs, dlen, p, p0i, R2, Rx);\n"
def text14 : String := "\t\t\t*yd = zint_mod_small_signed(ys, dlen, p, p0i, R2, Rx);\n"
def text15 : String := "\t\t}\n"
def text16 : String := "\t}\n"
def text17 : String := "\n"
def tail18 : List String := []
def tail17 : List String := text17::tail18
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[5897]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[5898]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[5899]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[5900]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[5901]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[5902]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[5903]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[5904]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[5905]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[5906]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[5907]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[5908]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[5909]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[5910]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[5911]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[5912]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[5913]?=some text16 := by decide +kernel
theorem line17 : Pinned.keygenLines[5914]?=some text17 := by decide +kernel
theorem bytes18 : (Pinned.keygenLines.drop 5915).take tail18.length=tail18 := rfl
theorem bytes17 : (Pinned.keygenLines.drop 5914).take tail17.length=tail17 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5914 text17 tail18 line17 bytes18
theorem bytes16 : (Pinned.keygenLines.drop 5913).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5913 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 5912).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5912 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 5911).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5911 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 5910).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5910 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 5909).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5909 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 5908).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5908 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 5907).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5907 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 5906).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5906 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 5905).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5905 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 5904).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5904 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 5903).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5903 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 5902).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5902 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 5901).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5901 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 5900).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5900 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 5899).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5899 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 5898).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5898 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 5897).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5897 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 5897).take 18=lines := bytes0
def group0 : List String := [text0]
def words0 : List B20.C.Token := ["for","(","u","=","0",";","u","<","llen",";","u","++",")","{"].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text1]
def words1 : List B20.C.Token := ["uint32_t","p",",","p0i",",","R2",",","Rx",";"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text2]
def words2 : List B20.C.Token := ["uint64_t","v",";"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text3]
def words3 : List B20.C.Token := ["uint32_t","*","xs",",","*","ys",",","*","xd",",","*","yd",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text4]
def words4 : List B20.C.Token := [].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text5]
def words5 : List B20.C.Token := ["p","=","primes","[","u","]",".","p",";"].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text6]
def words6 : List B20.C.Token := ["p0i","=","modp_ninv31","(","p",")",";"].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text7]
def words7 : List B20.C.Token := ["R2","=","modp_R2","(","p",",","p0i",")",";"].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text8]
def words8 : List B20.C.Token := ["Rx","=","modp_Rx","(","dlen",",","p",",","p0i",",","R2",")",";"].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text9]
def words9 : List B20.C.Token := ["for","(","v","=","0",",","xs","=","Fd",",","ys","=","Gd",",","xd","=","Ft","+","u",",","yd","=","Gt","+","u",";"].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text10]
def words10 : List B20.C.Token := ["v","<","hn",";"].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def group11 : List String := [text11]
def words11 : List B20.C.Token := ["v","++",",","xs","+=","dlen",",","ys","+=","dlen",",","xd","+=","llen",",","yd","+=","llen",")"].map String.toList
theorem lex11 : KeygenLexicalChunks.Checked group11 words11 := by
  constructor <;> decide +kernel
def group12 : List String := [text12]
def words12 : List B20.C.Token := ["{"].map String.toList
theorem lex12 : KeygenLexicalChunks.Checked group12 words12 := by
  constructor <;> decide +kernel
def group13 : List String := [text13]
def words13 : List B20.C.Token := ["*","xd","=","zint_mod_small_signed","(","xs",",","dlen",",","p",",","p0i",",","R2",",","Rx",")",";"].map String.toList
theorem lex13 : KeygenLexicalChunks.Checked group13 words13 := by
  constructor <;> decide +kernel
def group14 : List String := [text14]
def words14 : List B20.C.Token := ["*","yd","=","zint_mod_small_signed","(","ys",",","dlen",",","p",",","p0i",",","R2",",","Rx",")",";"].map String.toList
theorem lex14 : KeygenLexicalChunks.Checked group14 words14 := by
  constructor <;> decide +kernel
def group15 : List String := [text15]
def words15 : List B20.C.Token := ["}"].map String.toList
theorem lex15 : KeygenLexicalChunks.Checked group15 words15 := by
  constructor <;> decide +kernel
def group16 : List String := [text16]
def words16 : List B20.C.Token := ["}"].map String.toList
theorem lex16 : KeygenLexicalChunks.Checked group16 words16 := by
  constructor <;> decide +kernel
def group17 : List String := [text17]
def words17 : List B20.C.Token := [].map String.toList
theorem lex17 : KeygenLexicalChunks.Checked group17 words17 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10,group11,group12,group13,group14,group15,group16,group17]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10,words11,words12,words13,words14,words15,words16,words17]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.cons lex11 (List.Forall₂.cons lex12 (List.Forall₂.cons lex13 (List.Forall₂.cons lex14 (List.Forall₂.cons lex15 (List.Forall₂.cons lex16 (List.Forall₂.cons lex17 (List.Forall₂.nil))))))))))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 5897).take 18) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensTop4
