import Source3.KeygenStaticTables

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000

/- Generated by tools/keygen_prime_table_source.py; every equality is kernel checked. -/
namespace FT1536.Source3.KeygenPrimeTablesTernaryLow
open KeygenStaticTables

theorem chunk0 : Checked .ternary 0 := by decide
theorem chunk1 : Checked .ternary 1 := by decide
theorem chunk2 : Checked .ternary 2 := by decide
theorem chunk3 : Checked .ternary 3 := by decide
theorem chunk4 : Checked .ternary 4 := by decide
theorem chunk5 : Checked .ternary 5 := by decide
theorem chunk6 : Checked .ternary 6 := by decide
theorem chunk7 : Checked .ternary 7 := by decide
theorem chunk8 : Checked .ternary 8 := by decide
theorem chunk9 : Checked .ternary 9 := by decide
theorem chunk10 : Checked .ternary 10 := by decide
theorem chunk11 : Checked .ternary 11 := by decide
theorem chunk12 : Checked .ternary 12 := by decide
theorem chunk13 : Checked .ternary 13 := by decide
theorem chunk14 : Checked .ternary 14 := by decide
theorem chunk15 : Checked .ternary 15 := by decide
theorem chunk16 : Checked .ternary 16 := by decide
theorem chunk17 : Checked .ternary 17 := by decide
theorem chunk18 : Checked .ternary 18 := by decide
theorem chunk19 : Checked .ternary 19 := by decide
theorem chunk20 : Checked .ternary 20 := by decide
theorem chunk21 : Checked .ternary 21 := by decide
theorem chunk22 : Checked .ternary 22 := by decide
theorem chunk23 : Checked .ternary 23 := by decide
theorem chunk24 : Checked .ternary 24 := by decide
theorem chunk25 : Checked .ternary 25 := by decide
theorem chunk26 : Checked .ternary 26 := by decide
theorem chunk27 : Checked .ternary 27 := by decide
theorem chunk28 : Checked .ternary 28 := by decide
theorem chunk29 : Checked .ternary 29 := by decide
theorem chunk30 : Checked .ternary 30 := by decide
theorem chunk31 : Checked .ternary 31 := by decide
theorem chunk32 : Checked .ternary 32 := by decide
theorem chunk33 : Checked .ternary 33 := by decide
theorem chunk34 : Checked .ternary 34 := by decide

theorem all_chunks (i : Fin 35) : Checked .ternary (i.val+0) := by
  fin_cases i
  · exact chunk0
  · exact chunk1
  · exact chunk2
  · exact chunk3
  · exact chunk4
  · exact chunk5
  · exact chunk6
  · exact chunk7
  · exact chunk8
  · exact chunk9
  · exact chunk10
  · exact chunk11
  · exact chunk12
  · exact chunk13
  · exact chunk14
  · exact chunk15
  · exact chunk16
  · exact chunk17
  · exact chunk18
  · exact chunk19
  · exact chunk20
  · exact chunk21
  · exact chunk22
  · exact chunk23
  · exact chunk24
  · exact chunk25
  · exact chunk26
  · exact chunk27
  · exact chunk28
  · exact chunk29
  · exact chunk30
  · exact chunk31
  · exact chunk32
  · exact chunk33
  · exact chunk34

end FT1536.Source3.KeygenPrimeTablesTernaryLow
