import Source3.KeygenMkgm3Indices

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000

/- Generated by generate_keygen_ntt_children.sage; bounded kernel checks
   of the existing source row/REV10 exponents, not a replacement order. -/
namespace FT1536.Source3.KeygenNttTwiddleCert
open KeygenMkgm3Indices (tableExponent)

def OddFact (r : Nat) : Prop :=
  (2≤r ∧ r<256 → (2*tableExponent (2*r+1))%4608=(tableExponent r+2304)%4608) ∧
  (256≤r ∧ r<512 → (3*tableExponent (2*r+1))%4608=(tableExponent r+2304)%4608)
instance (r : Nat) : Decidable (OddFact r) := by unfold OddFact; infer_instance

theorem chunk00 : ∀ r : Fin 16, OddFact (0+r.val) := by decide
theorem chunk01 : ∀ r : Fin 16, OddFact (16+r.val) := by decide
theorem chunk02 : ∀ r : Fin 16, OddFact (32+r.val) := by decide
theorem chunk03 : ∀ r : Fin 16, OddFact (48+r.val) := by decide
theorem chunk04 : ∀ r : Fin 16, OddFact (64+r.val) := by decide
theorem chunk05 : ∀ r : Fin 16, OddFact (80+r.val) := by decide
theorem chunk06 : ∀ r : Fin 16, OddFact (96+r.val) := by decide
theorem chunk07 : ∀ r : Fin 16, OddFact (112+r.val) := by decide
theorem chunk08 : ∀ r : Fin 16, OddFact (128+r.val) := by decide
theorem chunk09 : ∀ r : Fin 16, OddFact (144+r.val) := by decide
theorem chunk10 : ∀ r : Fin 16, OddFact (160+r.val) := by decide
theorem chunk11 : ∀ r : Fin 16, OddFact (176+r.val) := by decide
theorem chunk12 : ∀ r : Fin 16, OddFact (192+r.val) := by decide
theorem chunk13 : ∀ r : Fin 16, OddFact (208+r.val) := by decide
theorem chunk14 : ∀ r : Fin 16, OddFact (224+r.val) := by decide
theorem chunk15 : ∀ r : Fin 16, OddFact (240+r.val) := by decide
theorem chunk16 : ∀ r : Fin 16, OddFact (256+r.val) := by decide
theorem chunk17 : ∀ r : Fin 16, OddFact (272+r.val) := by decide
theorem chunk18 : ∀ r : Fin 16, OddFact (288+r.val) := by decide
theorem chunk19 : ∀ r : Fin 16, OddFact (304+r.val) := by decide
theorem chunk20 : ∀ r : Fin 16, OddFact (320+r.val) := by decide
theorem chunk21 : ∀ r : Fin 16, OddFact (336+r.val) := by decide
theorem chunk22 : ∀ r : Fin 16, OddFact (352+r.val) := by decide
theorem chunk23 : ∀ r : Fin 16, OddFact (368+r.val) := by decide
theorem chunk24 : ∀ r : Fin 16, OddFact (384+r.val) := by decide
theorem chunk25 : ∀ r : Fin 16, OddFact (400+r.val) := by decide
theorem chunk26 : ∀ r : Fin 16, OddFact (416+r.val) := by decide
theorem chunk27 : ∀ r : Fin 16, OddFact (432+r.val) := by decide
theorem chunk28 : ∀ r : Fin 16, OddFact (448+r.val) := by decide
theorem chunk29 : ∀ r : Fin 16, OddFact (464+r.val) := by decide
theorem chunk30 : ∀ r : Fin 16, OddFact (480+r.val) := by decide
theorem chunk31 : ∀ r : Fin 16, OddFact (496+r.val) := by decide

theorem chunks (c : Fin 32) (r : Fin 16) : OddFact (16*c.val+r.val) := by
  fin_cases c
  · exact chunk00 r
  · exact chunk01 r
  · exact chunk02 r
  · exact chunk03 r
  · exact chunk04 r
  · exact chunk05 r
  · exact chunk06 r
  · exact chunk07 r
  · exact chunk08 r
  · exact chunk09 r
  · exact chunk10 r
  · exact chunk11 r
  · exact chunk12 r
  · exact chunk13 r
  · exact chunk14 r
  · exact chunk15 r
  · exact chunk16 r
  · exact chunk17 r
  · exact chunk18 r
  · exact chunk19 r
  · exact chunk20 r
  · exact chunk21 r
  · exact chunk22 r
  · exact chunk23 r
  · exact chunk24 r
  · exact chunk25 r
  · exact chunk26 r
  · exact chunk27 r
  · exact chunk28 r
  · exact chunk29 r
  · exact chunk30 r
  · exact chunk31 r

theorem all_indices (r : Nat) (hr : r<512) : OddFact r := by
  have hc : r/16<32 := by omega
  have h := chunks ⟨r/16,hc⟩ ⟨r%16,Nat.mod_lt _ (by decide)⟩
  have he : 16*(r/16)+r%16=r := by omega
  simpa only [he] using h

end FT1536.Source3.KeygenNttTwiddleCert
