import Source3.KeygenPublicRadixProgram
import Source3.KeygenPublicSizeOps
import Source3.KeygenPublicValueFrames
import Source3.KeygenPublicRadixRow
import Source3.KeygenPublicRadixRows
import Source3.KeygenPublicRadixStages
import Source3.KeygenPublicRadixEntry
import Source3.KeygenPublicRadixInvocation
import Source3.KeygenPublicRootTree
import Source3.KeygenPublicRadixPolynomial
import Source3.KeygenPublicTripleProgram
import Source3.KeygenPublicTripleExpr
import Source3.KeygenPublicValueLists
import Source3.KeygenPublicTripleValues
import Source3.KeygenPublicTripleFold
import Source3.KeygenPublicEvaluation
import Source3.KeygenPublicEvaluationCalls
import Source3.KeygenPublicEvaluationMaterial
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated complete internal042 audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenPublicRadixProgram,
      ["rowNames","rowInner","rowBody","rowGuard","nextRow","nextBase","rowStep","rowLoop","initRows","rows","stageNames","htSet","tSet","stageInner","stageBody","stageGuard","stageStep","stageLoop","stages","start","triple","source_row","source_stage","source_remaining","row_supported","stage_supported"]),
    (`FT1536.Source3.KeygenPublicSizeOps,
      ["Declared","Has","variable_slot","sum","half","double","assign","init","increment","lt","gt_three","scalar_sum"]),
    (`FT1536.Source3.KeygenPublicValueFrames,
      ["onlyA","other_block","table_after","load_value"]),
    (`FT1536.Source3.KeygenPublicRadixRow,
      ["root","declareLimit","declareTwiddle","loadTwiddle","setLimit","initV","Fixed","fixedNames","fixed_after","source_row"]),
    (`FT1536.Source3.KeygenPublicRadixRows,
      ["image","Fixed","Inv","fixedNames","fixed_after","step","loop_result","source_rows"]),
    (`FT1536.Source3.KeygenPublicRadixStages,
      ["size","count","image","dimensions","size_bound","count_bound","terminal","Fixed","Inv","fixed_after","source_stage","step","loop_result","source_stages"]),
    (`FT1536.Source3.KeygenPublicRadixEntry,
      ["Header","headerNames","header_after","radixImage","ThroughRadix","tail_stages","Types","ready_stages"]),
    (`FT1536.Source3.KeygenPublicRadixInvocation,
      ["Outcome","source_radix"]),
    (`FT1536.Source3.KeygenPublicRootTree,
      ["twiddle","nodeRoot","half_order_negative","power_mod","even_square","odd_square","even_cube","odd_cube","top_low","top_high","parent_square","child_indices","children","leaf_power"]),
    (`FT1536.Source3.KeygenPublicRadixPolynomial,
      ["split","Invariant","rows_values","low_row","high_row","polynomial_of_coefficients","first_low","first_high","first_invariant","next_invariant","stages_invariant","original_block"]),
    (`FT1536.Source3.KeygenPublicTripleProgram,
      ["index","names1","names2","square","declarations","assignments","stores","inner","body","guard","step","loop","initU","initV","seed","pass","source_triple","source_inner","body_supported"]),
    (`FT1536.Source3.KeygenPublicTripleExpr,
      ["square_scaled","index_value"]),
    (`FT1536.Source3.KeygenPublicValueLists,
      ["Typed","Known","keep","assignment"]),
    (`FT1536.Source3.KeygenPublicTripleValues,
      ["names","assignmentCode","storeCode","Fixed","fixedNames","fixed_after","ResultCells","Stores","source_body"]),
    (`FT1536.Source3.KeygenPublicTripleFold,
      ["root","value","image","image_input","image_output","image_unchanged","Fixed","Inv","fixed_after","body_image","increment_result","iteration_result","loop_result","source_loop"]),
    (`FT1536.Source3.KeygenPublicEvaluation,
      ["Evaluations","init_v_value","source_triple","original_values","source_complete"]),
    (`FT1536.Source3.KeygenPublicEvaluationCalls,
      ["ternary_call","ternary_body","source_dispatch","source_call","both"]),
    (`FT1536.Source3.KeygenPublicEvaluationMaterial,
      ["Front","source_front","source_same_material"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.C99MemoryReference.Memory,
    ``FT1536.Source3.C99MemoryReference.ArrayPointer,
    ``FT1536.Source3.C99MemoryReference.ArrayPointer.offset,
    ``FT1536.Source3.C99MemoryReference.Allocated,
    ``FT1536.Source3.C99MemoryReference.PointerAdd,
    ``FT1536.Source3.C99IntegerReference.Ty,
    ``FT1536.Source3.C99IntegerReference.Value,
    ``FT1536.Source3.C99IntegerReference.Value.integer,
    ``FT1536.Source3.C99IntegerReference.Value.type,
    ``FT1536.Source3.C99IntegerReference.convert,
    ``FT1536.Source3.C99IntegerReference.compare,
    ``FT1536.Source3.C99IntegerReference.promote,
    ``FT1536.Source3.C99IntegerReference.usual,
    ``FT1536.Source3.C99IntegerReference.ArithmeticExec,
    ``FT1536.Source3.C99ScalarReference.Env,
    ``FT1536.Source3.C99ScalarReference.set,
    ``FT1536.Source3.C99ScalarReference.boolean,
    ``FT1536.Source3.C99ScalarReference.Stmt,
    ``FT1536.Source3.C99ScalarReference.Exec,
    ``FT1536.Source3.C99ScalarReference.Eval,
    ``FT1536.Source3.C99Frontend.scalar,
    ``FT1536.Source3.C99Frontend.expression,
    ``FT1536.Source3.C99Frontend.binary,
    ``FT1536.Source3.C99DeclarationCells.declareCells,
    ``FT1536.Source3.C99DeclarationCells.complete,
    ``FT1536.Source3.C99ArrayReference.Name,
    ``FT1536.Source3.C99ArrayReference.Arg,
    ``FT1536.Source3.C99ArrayReference.Param,
    ``FT1536.Source3.C99ArrayReference.State,
    ``FT1536.Source3.C99ArrayReference.bindValue,
    ``FT1536.Source3.C99ArrayReference.bindPointer,
    ``FT1536.Source3.C99ArrayReference.restoreScope,
    ``FT1536.Source3.C99ProcedureReference.Result,
    ``FT1536.Source3.C99ProcedureReference.Flow,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue,
    ``FT1536.Source3.C99ProcedureParser.zero,
    ``FT1536.Source3.C99CountedWords.comparison_result,
    ``FT1536.Source3.C99NarrowReads.Load16,
    ``FT1536.Source3.C99NarrowReads.le16,
    ``FT1536.Source3.C99NarrowReads.unsignedPromotion,
    ``FT1536.Source3.C99NarrowReads.unsigned_promotion_exact,
    ``FT1536.Source3.C99NarrowReads.load16_deterministic,
    ``FT1536.Source3.C99NarrowReads.load16_transport,
    ``FT1536.Source3.KeygenSmallOutput.element,
    ``FT1536.Source3.KeygenSmallOutput.byte16,
    ``FT1536.Source3.KeygenSmallOutput.Stored,
    ``FT1536.Source3.KeygenSmallOutput.Store16,
    ``FT1536.Source3.KeygenResidueVectors.join_bytes,
    ``FT1536.Source3.KeygenWordExpr.Expr,
    ``FT1536.Source3.KeygenWordExpr.expression,
    ``FT1536.Source3.KeygenPublicScalar.Kind,
    ``FT1536.Source3.KeygenPublicScalar.Call,
    ``FT1536.Source3.KeygenPublicScalar.Square,
    ``FT1536.Source3.KeygenPublicScalar.name,
    ``FT1536.Source3.KeygenPublicScalar.params,
    ``FT1536.Source3.KeygenPublicScalar.lines,
    ``FT1536.Source3.KeygenPublicScalar.expand,
    ``FT1536.Source3.KeygenPublicAlgebra.R,
    ``FT1536.Source3.KeygenPublicAlgebra.Canonical,
    ``FT1536.Source3.KeygenPublicAlgebra.value,
    ``FT1536.Source3.KeygenPublicAlgebra.source_add,
    ``FT1536.Source3.KeygenPublicAlgebra.source_sub,
    ``FT1536.Source3.KeygenPublicAlgebra.call_leaf,
    ``FT1536.Source3.KeygenPublicMontgomery.modulus,
    ``FT1536.Source3.KeygenPublicMontgomery.inverse,
    ``FT1536.Source3.KeygenPublicMontgomery.word_contract,
    ``FT1536.Source3.KeygenPublicArguments.U32,
    ``FT1536.Source3.KeygenPublicArguments.Conversion,
    ``FT1536.Source3.KeygenPublicArguments.u32_self,
    ``FT1536.Source3.KeygenPublicArguments.call_leaf_conversion,
    ``FT1536.Source3.KeygenPublicArguments.source_mul_exact,
    ``FT1536.Source3.KeygenPublicLeafWords.source_add,
    ``FT1536.Source3.KeygenPublicLeafWords.source_sub,
    ``FT1536.Source3.KeygenPublicSquare.source_square_arguments,
    ``FT1536.Source3.KeygenPublicWord.Eval,
    ``FT1536.Source3.KeygenPublicWord.Address,
    ``FT1536.Source3.KeygenPublicWord.scalar,
    ``FT1536.Source3.KeygenPublicWord.Bind,
    ``FT1536.Source3.KeygenPublicWord.narrow,
    ``FT1536.Source3.KeygenPublicWord.bind_heap,
    ``FT1536.Source3.KeygenPublicExec.Stmt,
    ``FT1536.Source3.KeygenPublicExec.Exec,
    ``FT1536.Source3.KeygenPublicExec.Function,
    ``FT1536.Source3.KeygenPublicExec.Program,
    ``FT1536.Source3.KeygenPublicExec.chain,
    ``FT1536.Source3.KeygenPublicExec.allocated,
    ``FT1536.Source3.KeygenPublicExec.localPointer,
    ``FT1536.Source3.KeygenPublicExec.localEntry,
    ``FT1536.Source3.KeygenPublicExec.localExit,
    ``FT1536.Source3.KeygenPublicParser.Types,
    ``FT1536.Source3.KeygenPublicParser.body,
    ``FT1536.Source3.KeygenPublicParser.statement,
    ``FT1536.Source3.KeygenPublicSource.Kind,
    ``FT1536.Source3.KeygenPublicSource.name,
    ``FT1536.Source3.KeygenPublicSource.code,
    ``FT1536.Source3.KeygenPublicSource.params,
    ``FT1536.Source3.KeygenPublicSource.function,
    ``FT1536.Source3.KeygenPublicSource.program,
    ``FT1536.Source3.KeygenPublicSource.types,
    ``FT1536.Source3.KeygenPublicSource.signatures,
    ``FT1536.Source3.KeygenPublicSource.code_checked,
    ``FT1536.Source3.KeygenPublicTableAtoms.Slot,
    ``FT1536.Source3.KeygenPublicTableAtoms.var,
    ``FT1536.Source3.KeygenPublicTableAtoms.literal,
    ``FT1536.Source3.KeygenPublicTableAtoms.variable_value,
    ``FT1536.Source3.KeygenPublicTableAtoms.literal_value,
    ``FT1536.Source3.KeygenPublicTableAtoms.literal_argument,
    ``FT1536.Source3.KeygenPublicTableIndex.address,
    ``FT1536.Source3.KeygenPublicTableStore.Pointers,
    ``FT1536.Source3.KeygenPublicTableStore.Separate,
    ``FT1536.Source3.KeygenPublicTableCells.Cell,
    ``FT1536.Source3.KeygenPublicTableControl.writes,
    ``FT1536.Source3.KeygenPublicTableControl.supported,
    ``FT1536.Source3.KeygenPublicTableControl.frame,
    ``FT1536.Source3.KeygenPublicTableControl.declare_frame,
    ``FT1536.Source3.KeygenPublicTableRows.noReturn,
    ``FT1536.Source3.KeygenPublicTableRows.normal,
    ``FT1536.Source3.KeygenPublicUpperLoops.PairCells,
    ``FT1536.Source3.KeygenPublicUpperFrames.UpperFrame,
    ``FT1536.Source3.KeygenPublicUpperFrames.OutsideFull,
    ``FT1536.Source3.KeygenPublicUpperImages.source_complete_tables,
    ``FT1536.Source3.KeygenPublicRoots.root,
    ``FT1536.Source3.KeygenMkgm3Indices.tableExponent,
    ``FT1536.Source3.KeygenRngSource.Fresh,
    ``FT1536.Source3.KeygenRngSource.disposed,
    ``FT1536.Source3.ShakeExtractFrame.SameBlock,
    ``FT1536.Source3.KeygenZintTop.tokens,
    ``FT1536.Source3.KeygenPublicForwardWrapper.source_forward_canonical,
    ``FT1536.Source3.KeygenPublicForwardWrapper.domain_of_image,
    ``FT1536.Source3.KeygenPublicForwardMemory.Block,
    ``FT1536.Source3.KeygenPublicForwardMemory.load_block,
    ``FT1536.Source3.KeygenPublicForwardMemory.initialized_live,
    ``FT1536.Source3.KeygenPublicForwardMemory.allocated_other,
    ``FT1536.Source3.KeygenPublicRangeMemory.read_after_store,
    ``FT1536.Source3.KeygenPublicRangeMemory.image,
    ``FT1536.Source3.KeygenPublicRangeMemory.domain_same_block,
    ``FT1536.Source3.KeygenPublicRangeMemory.initialized_same_block,
    ``FT1536.Source3.KeygenPublicRangeExpr.word_nat,
    ``FT1536.Source3.KeygenPublicRangeExpr.word_argument,
    ``FT1536.Source3.KeygenPublicRangeExpr.narrowed_range,
    ``FT1536.Source3.KeygenPublicAlgebra.source_conv,
    ``FT1536.Source3.KeygenPublicTableCells.stored_load,
    ``FT1536.Source3.KeygenPublicTableCells.narrowing,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.KeygenSmallOutput.narrowed_exact,
    ``FT1536.Source3.KeygenNttLoopSupport.USlot,
    ``FT1536.Source3.KeygenNttLoopSupport.plus_u64,
    ``FT1536.Source3.KeygenPublicFrame.body,
    ``FT1536.Source3.KeygenPublicRoots.firstRoot,
    ``FT1536.Source3.KeygenPublicRoots.first_root_relation,
    ``FT1536.Source3.KeygenPublicRoots.point_half_power,
    ``FT1536.Relation.reduceVec,
    ``FT1536.Run2.CoefficientQuotient.polynomial,
    ``FT1536.Run2.CoefficientQuotient.coefficient_low,
    ``FT1536.Run2.CoefficientQuotient.coefficient_high,
    ``FT1536.Run2.CoefficientQuotient.coefficient_outside,
    ``FT1536.Source3.KeygenPublicInputProgram.signed,
    ``FT1536.Source3.KeygenPublicInputProgram.index,
    ``FT1536.Source3.KeygenPublicInputProgram.converted,
    ``FT1536.Source3.KeygenPublicInputProgram.firstStore,
    ``FT1536.Source3.KeygenPublicInputProgram.secondStore,
    ``FT1536.Source3.KeygenPublicInputProgram.body,
    ``FT1536.Source3.KeygenPublicInputProgram.condition,
    ``FT1536.Source3.KeygenPublicInputProgram.increment,
    ``FT1536.Source3.KeygenPublicInputProgram.loop,
    ``FT1536.Source3.KeygenPublicInputProgram.initial,
    ``FT1536.Source3.KeygenPublicInputProgram.conversion,
    ``FT1536.Source3.KeygenPublicInputProgram.hArgs,
    ``FT1536.Source3.KeygenPublicInputProgram.tArgs,
    ``FT1536.Source3.KeygenPublicInputProgram.hForward,
    ``FT1536.Source3.KeygenPublicInputProgram.tForward,
    ``FT1536.Source3.KeygenPublicInputProgram.fragment,
    ``FT1536.Source3.KeygenPublicInputProgram.setup,
    ``FT1536.Source3.KeygenPublicInputProgram.suffix,
    ``FT1536.Source3.KeygenPublicInputProgram.append,
    ``FT1536.Source3.KeygenPublicInputProgram.ready,
    ``FT1536.Source3.KeygenPublicInputProgram.completeReady,
    ``FT1536.Source3.KeygenPublicInputProgram.declareDimensions,
    ``FT1536.Source3.KeygenPublicInputProgram.complete,
    ``FT1536.Source3.KeygenPublicInputProgram.source_complete,
    ``FT1536.Source3.KeygenPublicInputProgram.signed_source,
    ``FT1536.Source3.KeygenPublicInputProgram.body_supported,
    ``FT1536.Source3.KeygenPublicInputProgram.loop_supported,
    ``FT1536.Source3.KeygenPublicInputProgram.conversion_supported,
    ``FT1536.Source3.KeygenPublicInputProgram.loop_writes,
    ``FT1536.Source3.KeygenPublicInputProgram.body_writes,
    ``FT1536.Source3.KeygenPublicInputProgram.conversion_writes,
    ``FT1536.Source3.KeygenPublicInputCells.Cell,
    ``FT1536.Source3.KeygenPublicInputCells.Cells,
    ``FT1536.Source3.KeygenPublicInputCells.Signed,
    ``FT1536.Source3.KeygenPublicInputCells.TailEmpty,
    ``FT1536.Source3.KeygenPublicInputCells.written,
    ``FT1536.Source3.KeygenPublicInputCells.preserves,
    ``FT1536.Source3.KeygenPublicInputCells.other_block,
    ``FT1536.Source3.KeygenPublicInputCells.signed_other,
    ``FT1536.Source3.KeygenPublicInputCells.tail_store,
    ``FT1536.Source3.KeygenPublicInputCells.empty_allocated,
    ``FT1536.Source3.KeygenPublicInputCells.image,
    ``FT1536.Source3.KeygenPublicInputCells.domain,
    ``FT1536.Source3.KeygenPublicInputAtoms.seq_inv,
    ``FT1536.Source3.KeygenPublicInputAtoms.word64,
    ``FT1536.Source3.KeygenPublicInputAtoms.index_address,
    ``FT1536.Source3.KeygenPublicInputAtoms.converted_value,
    ``FT1536.Source3.KeygenPublicInputAtoms.store,
    ``FT1536.Source3.KeygenPublicInputAtoms.guard,
    ``FT1536.Source3.KeygenPublicInputAtoms.increment_result,
    ``FT1536.Source3.KeygenPublicInputAtoms.increment_counter,
    ``FT1536.Source3.KeygenPublicInputLoop.Pointers,
    ``FT1536.Source3.KeygenPublicInputLoop.Layout,
    ``FT1536.Source3.KeygenPublicInputLoop.Fixed,
    ``FT1536.Source3.KeygenPublicInputLoop.Data,
    ``FT1536.Source3.KeygenPublicInputLoop.Invariant,
    ``FT1536.Source3.KeygenPublicInputLoop.fixed_after,
    ``FT1536.Source3.KeygenPublicInputLoop.body_data,
    ``FT1536.Source3.KeygenPublicInputLoop.step,
    ``FT1536.Source3.KeygenPublicInputLoop.source_loop,
    ``FT1536.Source3.KeygenPublicInputMaterial.coefficient,
    ``FT1536.Source3.KeygenPublicInputMaterial.reduced,
    ``FT1536.Source3.KeygenPublicInputMaterial.Legal,
    ``FT1536.Source3.KeygenPublicInputMaterial.signed_material,
    ``FT1536.Source3.KeygenPublicInputMaterial.initial_result,
    ``FT1536.Source3.KeygenPublicInputMaterial.source_conversion,
    ``FT1536.Source3.KeygenPublicInputMaterial.source_vectors,
    ``FT1536.Source3.KeygenPublicInputSetup.ternaryShift,
    ``FT1536.Source3.KeygenPublicInputSetup.leftCount,
    ``FT1536.Source3.KeygenPublicInputSetup.rightCount,
    ``FT1536.Source3.KeygenPublicInputSetup.dimension,
    ``FT1536.Source3.KeygenPublicInputSetup.declareQ,
    ``FT1536.Source3.KeygenPublicInputSetup.nSet,
    ``FT1536.Source3.KeygenPublicInputSetup.qSet,
    ``FT1536.Source3.KeygenPublicInputSetup.complete,
    ``FT1536.Source3.KeygenPublicInputSetup.source_complete,
    ``FT1536.Source3.KeygenPublicInputSetup.supported,
    ``FT1536.Source3.KeygenPublicInputSetup.writes,
    ``FT1536.Source3.KeygenPublicInputSetup.ternary_value,
    ``FT1536.Source3.KeygenPublicInputSetup.dimension_value,
    ``FT1536.Source3.KeygenPublicInputSetup.source_setup,
    ``FT1536.Source3.KeygenPublicInputCalls.inputPrefix,
    ``FT1536.Source3.KeygenPublicInputCalls.forwards,
    ``FT1536.Source3.KeygenPublicInputCalls.convertedForward,
    ``FT1536.Source3.KeygenPublicInputCalls.remaining,
    ``FT1536.Source3.KeygenPublicInputCalls.Globals,
    ``FT1536.Source3.KeygenPublicInputCalls.complete_seam,
    ``FT1536.Source3.KeygenPublicInputCalls.prefix_supported,
    ``FT1536.Source3.KeygenPublicInputCalls.normal_seq_inv,
    ``FT1536.Source3.KeygenPublicInputCalls.append_inv,
    ``FT1536.Source3.KeygenPublicInputCalls.globals_preserved,
    ``FT1536.Source3.KeygenPublicInputCalls.global_range,
    ``FT1536.Source3.KeygenPublicInputCalls.prefix_result,
    ``FT1536.Source3.KeygenPublicInputCalls.call_binding,
    ``FT1536.Source3.KeygenPublicInputCalls.source_call_canonical,
    ``FT1536.Source3.KeygenPublicInputCalls.forward_other,
    ``FT1536.Source3.KeygenPublicInputCalls.source_both_forward,
    ``FT1536.Source3.KeygenPublicInputBridge.append_intro,
    ``FT1536.Source3.KeygenPublicInputBridge.tables_preserved,
    ``FT1536.Source3.KeygenPublicInputBridge.source_converted_forward,
    ``FT1536.Source3.KeygenPublicInputBridge.source_same_vectors_forward,
    ``FT1536.Source3.KeygenPublicInputLifetime.LiveTables,
    ``FT1536.Source3.KeygenPublicInputLifetime.Front,
    ``FT1536.Source3.KeygenPublicInputLifetime.legal_live,
    ``FT1536.Source3.KeygenPublicInputLifetime.signed_block,
    ``FT1536.Source3.KeygenPublicInputLifetime.source_front,
    ``FT1536.Source3.KeygenPublicInputLifetime.source_same_material_front,
    ``FT1536.Source3.KeygenPublicValueExpr.meaning,
    ``FT1536.Source3.KeygenPublicValueExpr.Evaluates,
    ``FT1536.Source3.KeygenPublicValueExpr.Local,
    ``FT1536.Source3.KeygenPublicValueExpr.add,
    ``FT1536.Source3.KeygenPublicValueExpr.sub,
    ``FT1536.Source3.KeygenPublicValueExpr.word_meaning,
    ``FT1536.Source3.KeygenPublicValueExpr.local_value,
    ``FT1536.Source3.KeygenPublicValueExpr.add_value,
    ``FT1536.Source3.KeygenPublicValueExpr.sub_value,
    ``FT1536.Source3.KeygenPublicValueExpr.twiddle_value,
    ``FT1536.Source3.KeygenPublicValueExpr.local_after,
    ``FT1536.Source3.KeygenPublicValueExpr.assign_value,
    ``FT1536.Source3.KeygenPublicFirstValues.lowIndex,
    ``FT1536.Source3.KeygenPublicFirstValues.highIndex,
    ``FT1536.Source3.KeygenPublicFirstValues.names,
    ``FT1536.Source3.KeygenPublicFirstValues.declaration,
    ``FT1536.Source3.KeygenPublicFirstValues.readLow,
    ``FT1536.Source3.KeygenPublicFirstValues.readHigh,
    ``FT1536.Source3.KeygenPublicFirstValues.multiply,
    ``FT1536.Source3.KeygenPublicFirstValues.storeLow,
    ``FT1536.Source3.KeygenPublicFirstValues.storeHigh,
    ``FT1536.Source3.KeygenPublicFirstValues.inner,
    ``FT1536.Source3.KeygenPublicFirstValues.body,
    ``FT1536.Source3.KeygenPublicFirstValues.firstLoop,
    ``FT1536.Source3.KeygenPublicFirstValues.pass,
    ``FT1536.Source3.KeygenPublicFirstValues.seed,
    ``FT1536.Source3.KeygenPublicFirstValues.remaining,
    ``FT1536.Source3.KeygenPublicFirstValues.source_first_pass,
    ``FT1536.Source3.KeygenPublicFirstValues.body_supported,
    ``FT1536.Source3.KeygenPublicFirstValues.Fixed,
    ``FT1536.Source3.KeygenPublicFirstValues.PairUpdate,
    ``FT1536.Source3.KeygenPublicFirstValues.fixed_after,
    ``FT1536.Source3.KeygenPublicFirstValues.low_value,
    ``FT1536.Source3.KeygenPublicFirstValues.high_value,
    ``FT1536.Source3.KeygenPublicFirstValues.load_value,
    ``FT1536.Source3.KeygenPublicFirstValues.store_value,
    ``FT1536.Source3.KeygenPublicFirstValues.source_body,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.low,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.high,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.low_coefficient,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.high_coefficient,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.low_degree,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.eval_original,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.first_low_evaluation,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.first_high_evaluation,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.original_reduced_coefficient,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.source_original_coefficients,
    ``FT1536.Source3.KeygenPublicFirstTables.Table,
    ``FT1536.Source3.KeygenPublicFirstTables.generate_values,
    ``FT1536.Source3.KeygenPublicFirstTables.dynamic_values,
    ``FT1536.Source3.KeygenPublicFirstTables.first_cell,
    ``FT1536.Source3.KeygenPublicFirstTables.cells_block,
    ``FT1536.Source3.KeygenPublicFirstEntry.Types,
    ``FT1536.Source3.KeygenPublicFirstEntry.initU,
    ``FT1536.Source3.KeygenPublicFirstEntry.n_value,
    ``FT1536.Source3.KeygenPublicFirstEntry.hn_value,
    ``FT1536.Source3.KeygenPublicFirstEntry.table_load,
    ``FT1536.Source3.KeygenPublicFirstEntry.FirstRun,
    ``FT1536.Source3.KeygenPublicFirstEntry.tail_first,
    ``FT1536.Source3.KeygenPublicFirstEntry.ready_first,
    ``FT1536.Source3.KeygenPublicFirstInvocation.Outcome,
    ``FT1536.Source3.KeygenPublicFirstInvocation.initialized,
    ``FT1536.Source3.KeygenPublicFirstInvocation.source_first,
    ``FT1536.Source3.KeygenPublicFirstInvocation.folded,
    ``FT1536.Source3.KeygenPublicFirstCalls.normal,
    ``FT1536.Source3.KeygenPublicFirstCalls.transport,
    ``FT1536.Source3.KeygenPublicFirstCalls.binding,
    ``FT1536.Source3.KeygenPublicFirstCalls.ternary_call,
    ``FT1536.Source3.KeygenPublicFirstCalls.ternary_body,
    ``FT1536.Source3.KeygenPublicFirstCalls.source_dispatch,
    ``FT1536.Source3.KeygenPublicFirstCalls.call,
    ``FT1536.Source3.KeygenPublicFirstCalls.source_call,
    ``FT1536.Source3.KeygenPublicFirstCalls.both,
    ``FT1536.Source3.KeygenPublicFirstMaterial.Front,
    ``FT1536.Source3.KeygenPublicFirstMaterial.source_front,
    ``FT1536.Source3.KeygenPublicFirstMaterial.source_same_material,
    ``FT1536.Source3.KeygenPublicRadixValues.lowIndex,
    ``FT1536.Source3.KeygenPublicRadixValues.highIndex,
    ``FT1536.Source3.KeygenPublicRadixValues.names,
    ``FT1536.Source3.KeygenPublicRadixValues.declaration,
    ``FT1536.Source3.KeygenPublicRadixValues.readLow,
    ``FT1536.Source3.KeygenPublicRadixValues.readHigh,
    ``FT1536.Source3.KeygenPublicRadixValues.multiply,
    ``FT1536.Source3.KeygenPublicRadixValues.storeLow,
    ``FT1536.Source3.KeygenPublicRadixValues.storeHigh,
    ``FT1536.Source3.KeygenPublicRadixValues.inner,
    ``FT1536.Source3.KeygenPublicRadixValues.body,
    ``FT1536.Source3.KeygenPublicRadixValues.contains,
    ``FT1536.Source3.KeygenPublicRadixValues.source_inner,
    ``FT1536.Source3.KeygenPublicRadixValues.source_occurrence,
    ``FT1536.Source3.KeygenPublicRadixValues.body_supported,
    ``FT1536.Source3.KeygenPublicRadixValues.Fixed,
    ``FT1536.Source3.KeygenPublicRadixValues.PairUpdate,
    ``FT1536.Source3.KeygenPublicRadixValues.fixed_after,
    ``FT1536.Source3.KeygenPublicRadixValues.low_value,
    ``FT1536.Source3.KeygenPublicRadixValues.high_value,
    ``FT1536.Source3.KeygenPublicRadixValues.source_body,
    ``FT1536.Source3.KeygenPublicRadixFold.guard,
    ``FT1536.Source3.KeygenPublicRadixFold.increment,
    ``FT1536.Source3.KeygenPublicRadixFold.loop,
    ``FT1536.Source3.KeygenPublicRadixFold.pass,
    ``FT1536.Source3.KeygenPublicRadixFold.source_pass,
    ``FT1536.Source3.KeygenPublicRadixFold.source_occurrence,
    ``FT1536.Source3.KeygenPublicRadixFold.low,
    ``FT1536.Source3.KeygenPublicRadixFold.high,
    ``FT1536.Source3.KeygenPublicRadixFold.image,
    ``FT1536.Source3.KeygenPublicRadixFold.image_zero,
    ``FT1536.Source3.KeygenPublicRadixFold.image_input_low,
    ``FT1536.Source3.KeygenPublicRadixFold.image_input_high,
    ``FT1536.Source3.KeygenPublicRadixFold.image_low,
    ``FT1536.Source3.KeygenPublicRadixFold.image_high,
    ``FT1536.Source3.KeygenPublicRadixFold.image_unchanged,
    ``FT1536.Source3.KeygenPublicRadixFold.Data,
    ``FT1536.Source3.KeygenPublicRadixFold.Inv,
    ``FT1536.Source3.KeygenPublicRadixFold.guard_value,
    ``FT1536.Source3.KeygenPublicRadixFold.increment_result,
    ``FT1536.Source3.KeygenPublicRadixFold.body_data,
    ``FT1536.Source3.KeygenPublicRadixFold.step,
    ``FT1536.Source3.KeygenPublicRadixFold.loop_result,
    ``FT1536.Source3.KeygenPublicRadixFold.source_loop,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.polynomial,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.lowPolynomial,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.highPolynomial,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.modulus,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.coefficient,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.degree_bound,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.split_halves,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.low_decomposition,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.negate_low,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.low_remainder,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.high_remainder,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.eval_low,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.eval_high,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.RemainderImage,
    ``FT1536.Source3.KeygenPublicSplitPolynomial.source_remainders,
    ``FT1536.Source3.KeygenPublicTripleOrder.unity_cube,
    ``FT1536.Source3.KeygenPublicTripleOrder.unity_power,
    ``FT1536.Source3.KeygenPublicTripleOrder.triple_order,
    ``FT1536.Source3.KeygenPublicTripleOrder.quadratic,
    ``FT1536.Source3.KeygenPublicTripleOrder.output,
    ``FT1536.Source3.KeygenPublicTripleOrder.output_eval,
    ``FT1536.Source3.KeygenPublicTripleOrder.physical_evaluation,
    ``FT1536.Source3.KeygenPublicTripleOrder.all_physical_evaluations,
    ``FT1536.Source3.KeygenPublicFirstFold.root,
    ``FT1536.Source3.KeygenPublicFirstFold.lowP,
    ``FT1536.Source3.KeygenPublicFirstFold.highP,
    ``FT1536.Source3.KeygenPublicFirstFold.image,
    ``FT1536.Source3.KeygenPublicFirstFold.reduced_low,
    ``FT1536.Source3.KeygenPublicFirstFold.reduced_high,
    ``FT1536.Source3.KeygenPublicFirstFold.lowP_coeff,
    ``FT1536.Source3.KeygenPublicFirstFold.highP_coeff,
    ``FT1536.Source3.KeygenPublicFirstFold.image_low,
    ``FT1536.Source3.KeygenPublicFirstFold.image_low_un,
    ``FT1536.Source3.KeygenPublicFirstFold.image_high,
    ``FT1536.Source3.KeygenPublicFirstFold.image_high_un,
    ``FT1536.Source3.KeygenPublicFirstFold.image_zero,
    ``FT1536.Source3.KeygenPublicFirstFold.image_advance,
    ``FT1536.Source3.KeygenPublicFirstFold.image_advance_high,
    ``FT1536.Source3.KeygenPublicFirstFold.image_input_low,
    ``FT1536.Source3.KeygenPublicFirstFold.image_input_high,
    ``FT1536.Source3.KeygenPublicFirstFold.image_unchanged,
    ``FT1536.Source3.KeygenPublicFirstFold.guard_cmp,
    ``FT1536.Source3.KeygenPublicFirstFold.increment_result,
    ``FT1536.Source3.KeygenPublicFirstFold.increment_counter,
    ``FT1536.Source3.KeygenPublicFirstFold.preserve_pair,
    ``FT1536.Source3.KeygenPublicFirstFold.Data,
    ``FT1536.Source3.KeygenPublicFirstFold.Inv,
    ``FT1536.Source3.KeygenPublicFirstFold.body_data,
    ``FT1536.Source3.KeygenPublicFirstFold.step,
    ``FT1536.Source3.KeygenPublicFirstFold.loop_result,
    ``FT1536.Source3.KeygenPublicFirstFold.folded,
    ``FT1536.Source3.KeygenPublicFirstFold.source_first_fold]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../PUBLIC_EVALUATION_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.withFile "../PUBLIC_EVALUATION_AUDIT_ENTRIES.jsonl" .append fun stream =>
      stream.putStrLn rows.back!.compress
  IO.FS.writeFile "../PUBLIC_EVALUATION_AUDIT.json" (Lean.Json.arr rows |>.pretty)
