import Source3.KeygenOutputGateSource
import Source3.KeygenOutputGateBounds
import Source3.ShakeSource
import Source3.ShakeBlock
import Source3.ShakeBlockProgram
import Source3.ShakeEncode
import Source3.ShakeExtractSource
import Source3.ShakeRcBinding
import Source3.ShakeExtractBinding
import Source3.ShakeExtractFrame
import Source3.KeygenRngSource
import Source3.KeygenSamplerSource
import Source3.KeygenSamplerInner
import Source3.KeygenSamplerBounds
import Source3.KeygenSamplerFrame
import Source3.KeygenSamplerCalls
import Source3.KeygenOutputGateValidation
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated by tools/keygen_execution_audit_source.py. Full internal audit; not review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenOutputGateSource,
      ["Context","view","Argument","lower","zero","arguments","Condition","condition","memberPointer","callTokens","gateTokens","parsed","source_bound","Call","Evaluate","Exec","call_frame","negate_call_false","passed_calls"]),
    (`FT1536.Source3.KeygenOutputGateBounds,
      ["destinationName","sourceIndex","Caller","view_logn","index_value","binding_entry","call_writes","caller_preserved","gate_writes","gate_material","gate_preserves"]),
    (`FT1536.Source3.ShakeSource,
      ["sourceLines","headerLines"]),
    (`FT1536.Source3.ShakeBlock,
      ["readName","ReadCall","Eval","unary","expressionAt","expression","Stmt","chain","clause","simple","declarations","statement","body","instruction","iterationLines","parseLines","parse_append","instructions","prologue","initial","condition","increment","assemble","scaffold","scaffold_source","closing_source","signature_source","Exec","pointers_frame","writesOnly","Outside","Frame","frame_trans","memory_frame"]),
    (`FT1536.Source3.ShakeBlockProgram,
      ["lines00","part00","bound00","lines01","part01","bound01","lines02","part02","bound02","lines03","part03","bound03","lines04","part04","bound04","lines05","part05","bound05","lines06","part06","bound06","lines07","part07","bound07","lines08","part08","bound08","lines09","part09","bound09","lines10","part10","bound10","lines11","part11","bound11","lines12","part12","bound12","lines13","part13","bound13","lines14","part14","bound14","lines15","part15","bound15","lines16","part16","bound16","lines17","part17","bound17","lines18","part18","bound18","lines19","part19","bound19","lines20","part20","bound20","lines21","part21","bound21","lines22","part22","bound22","lines23","part23","bound23","lines24","part24","bound24","lines25","part25","bound25","lines26","part26","bound26","lines27","part27","bound27","lines28","part28","bound28","lines29","part29","bound29","lines30","part30","bound30","lines31","part31","bound31","lines32","part32","bound32","lines33","part33","bound33","lines34","part34","bound34","lines35","part35","bound35","lines36","part36","bound36","lines37","part37","bound37","lines38","part38","bound38","lines39","part39","bound39","lines40","part40","bound40","lines41","part41","bound41","lines42","part42","bound42","lines43","part43","bound43","lines44","part44","bound44","lines45","part45","bound45","lines46","part46","bound46","lines47","part47","bound47","lines48","part48","bound48","partition","steps","instructions_bound","code","source_bound","writes_only_A","source_frame"]),
    (`FT1536.Source3.ShakeEncode,
      ["Store8","Instruction","byteExpression","code","parseLine","parsed","source_bound","scaffold_source","Exec","params","localDeclaration","localAssignment","Call","BlockFrame","frame","call_frame","entry","Invoke","invoke_frame","invoke_pointers"]),
    (`FT1536.Source3.ShakeExtractSource,
      ["Layout","Field","field","struct_source","rcTokens","rcInitializer","rc","StaticRC","blockEntry","Process","process_frame","process_pointers","Stmt","chain","var","zero","enc","refill","iteration","code","fieldToken","simple","declarations","statement","body","parsed","Exec"]),
    (`FT1536.Source3.ShakeRcBinding,
      ["rcPair","bind_source","line00","tokens00","values00","list00","pair00","line01","tokens01","values01","list01","pair01","line02","tokens02","values02","list02","pair02","line03","tokens03","values03","list03","pair03","line04","tokens04","values04","list04","pair04","line05","tokens05","values05","list05","pair05","line06","tokens06","values06","list06","pair06","line07","tokens07","values07","list07","pair07","line08","tokens08","values08","list08","pair08","line09","tokens09","values09","list09","pair09","line10","tokens10","values10","list10","pair10","line11","tokens11","values11","list11","pair11","rc_pairs"]),
    (`FT1536.Source3.ShakeExtractBinding,
      ["source_bound","rc_partition","rc_scaffold"]),
    (`FT1536.Source3.ShakeExtractFrame,
      ["PointersOutside","SameBlock","same_trans","address_outside","bind_outside","source_frame","entry","Call","call_frame"]),
    (`FT1536.Source3.KeygenRngSource,
      ["signature_source","little_endian_source","Fresh","allocated","disposed","object","bytes","Call","slots","source_frame"]),
    (`FT1536.Source3.KeygenSamplerSource,
      ["selected","visible","selected_source","signature_source","prologue","parsedPrologue","prologue_source","initial","increment","declareX","refillCondition","assignBits","control_source","clauses_source","Refill","Inner","closedScope","Outer","Exec"]),
    (`FT1536.Source3.KeygenSamplerInner,
      ["Control","control_trans","XDeclared","refill_slots","refill_control","refill_heap","tail_control","tail_x","inner_control","inner_store"]),
    (`FT1536.Source3.KeygenSamplerBounds,
      ["Writes","earlier_bytes","write_values","material","declaredX","declaration_result","outer_writes","prologue_counter","source_writes","source_material"]),
    (`FT1536.Source3.KeygenSamplerFrame,
      ["tail_frame","inner_frame","outer_frame","source_frame","represents"]),
    (`FT1536.Source3.KeygenSamplerCalls,
      ["params","arguments","calls_source","Call","binding_entry","slots","material","frame","two_calls"]),
    (`FT1536.Source3.KeygenOutputGateValidation,
      ["Validation","checked","material","gate_validated"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.KeygenSmallCalls.bound_call,
    ``FT1536.Source3.KeygenSmallBounds.source_material,
    ``FT1536.Source3.KeygenTernaryStore.accepted_store,
    ``FT1536.Source3.KeygenTernaryStore.rejected_heap,
    ``FT1536.Source3.KeygenSolverValidation.generated_converted_checked,
    ``FT1536.Source3.KeygenSolverEquation.Bounds,
    ``FT1536.Source3.KeygenSolverEquation.Equation,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.C99MemoryReference.Load64,
    ``FT1536.Source3.C99MemoryReference.Store64,
    ``FT1536.Source3.C99MemoryReference.Memcpy,
    ``FT1536.Source3.C99ArrayReference.Bind,
    ``FT1536.Source3.KeygenSmallOutput.Store16]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../EXECUTION_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.writeFile "../EXECUTION_AUDIT_PARTIAL.json" (Lean.Json.arr rows |>.pretty)
  IO.FS.writeFile "../EXECUTION_AUDIT.json" (Lean.Json.arr rows |>.pretty)
