import Source3.KeygenCallerInit
import Source3.KeygenCallerEntry
import Source3.KeygenCallerTransport
import Source3.KeygenCallerPrefix
import Source3.KeygenCallerSuccess
import Source3.KeygenCallerInitExecution
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated by tools/keygen_caller_audit_source.py. Internal audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenCallerInit,
      ["scalarDeclared","logged","ternary","sized","sizeExpr","lex","scalar_declarations_source","dimensions_source","Dimensions","dimensions_exact","rtNames","rtDeclared","rt","ready","setupCode","setupParsed","setup_source","setup_declarations","Setup","pointer_n","setup_exact","Exec","exact_state","ready_heap","ready_tables","ready_size","ready_slot","ready_rt"]),
    (`FT1536.Source3.KeygenCallerEntry,
      ["Initial","allocated_live","input_not_rt","input_slot","norm_protected","public_protected","entry","root_entry","context_norm","context_public"]),
    (`FT1536.Source3.KeygenCallerTransport,
      ["protected_slots","profile_bytes","legal_stable","prime_same","rev_same","sampler_locals","sampling_table","sampling_root","resultant_root","norm_root","public_slots","load32_live","context_live","public_root"]),
    (`FT1536.Source3.KeygenCallerPrefix,
      ["Ternary","ternary_slots","ternary_size","ternary_material","ternary_root","close","close_source","local_scope_source","close_array","close_root","close_public","Exec","ternary_entry_root","root_legal","material"]),
    (`FT1536.Source3.KeygenCallerSuccess,
      ["call_boolean","nonzero_one","root_gate_source","RootGate","Exec","Solved","success","exact_integer_ntru"]),
    (`FT1536.Source3.KeygenCallerInitExecution,
      ["declare","cleared","declarationCode","cleared_exact","skip_execution","declare_execution","declarations_execution","scalars_execution","setup_execution"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.KeygenAttemptMaterial.Entry,
    ``FT1536.Source3.KeygenAttemptMaterial.Exec,
    ``FT1536.Source3.KeygenAttemptMaterial.Material,
    ``FT1536.Source3.KeygenAttemptMaterial.material,
    ``FT1536.Source3.KeygenRootCaller.Legal,
    ``FT1536.Source3.KeygenRootCaller.success,
    ``FT1536.Source3.KeygenRootSource.Entry,
    ``FT1536.Source3.KeygenRootSource.Exec,
    ``FT1536.Source3.KeygenRootSource.Call,
    ``FT1536.Source3.KeygenRootValidationSource.Exec,
    ``FT1536.Source3.KeygenOutputGateValidation.Validation,
    ``FT1536.Source3.KeygenSamplerContext.Resolve,
    ``FT1536.Source3.KeygenSamplerContext.Call,
    ``FT1536.Source3.KeygenSamplerContext.profile,
    ``FT1536.Source3.KeygenSamplerCalls.Call,
    ``FT1536.Source3.KeygenResultantGate.Exec,
    ``FT1536.Source3.KeygenAttemptNorm.Exec,
    ``FT1536.Source3.KeygenPublicSource.Call,
    ``FT1536.Source3.KeygenSearchContext.Context,
    ``FT1536.Source3.KeygenSearchContext.M0,
    ``FT1536.Source3.KeygenSearchContext.ReadTmp,
    ``FT1536.Source3.KeygenStaticTables.PrimeObject,
    ``FT1536.Source3.KeygenMkgm3RevMemory.SourceTable,
    ``FT1536.Source3.KeygenMkgm3Layout.Legal,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.KeygenSolverEquation.Bounds,
    ``FT1536.Source3.KeygenSolverEquation.Equation,
    ``FT1536.Source3.C99ArrayReference.Bind,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue,
    ``FT1536.Source3.C99MemoryReference.PointerAdd,
    ``FT1536.Source3.KeygenMemoryStability.Stable]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../CALLER_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.withFile "../CALLER_AUDIT_ENTRIES.jsonl" .append fun stream =>
      stream.putStrLn rows.back!.compress
  IO.FS.writeFile "../CALLER_AUDIT.json" (Lean.Json.arr rows |>.pretty)
