import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensLift0
def text0 : String := "\t\tuint32_t p, p0i, R2;\n"
def text1 : String := "\t\tuint32_t *gm, *igm, *fx, *gx, *Fp, *Gp;\n"
def text2 : String := "\t\tsize_t v;\n"
def text3 : String := "\n"
def text4 : String := "\t\t/*\n"
def text5 : String := "\t\t * All computations are done modulo p.\n"
def text6 : String := "\t\t */\n"
def text7 : String := "\t\tp = primes[u].p;\n"
def text8 : String := "\t\tp0i = modp_ninv31(p);\n"
def text9 : String := "\t\tR2 = modp_R2(p, p0i);\n"
def text10 : String := "\n"
def text11 : String := "\t\t/*\n"
def text12 : String := "\t\t * If we processed slen words, then f and g have been\n"
def text13 : String := "\t\t * de-NTTized, and are in RNS; we can rebuild them.\n"
def text14 : String := "\t\t */\n"
def text15 : String := "\t\tif (u == slen) {\n"
def text16 : String := "\t\t\tzint_rebuild_CRT(ft, slen, slen, n, primes, 1, t1);\n"
def text17 : String := "\t\t\tzint_rebuild_CRT(gt, slen, slen, n, primes, 1, t1);\n"
def text18 : String := "\t\t}\n"
def text19 : String := "\n"
def text20 : String := "\t\tgm = t1;\n"
def text21 : String := "\t\tif (full) {\n"
def text22 : String := "\t\t\tigm = gm + ((size_t)1 << logn);\n"
def text23 : String := "\t\t\tfx = igm + ((size_t)1 << logn);\n"
def text24 : String := "\t\t} else {\n"
def text25 : String := "\t\t\tgm = t1;\n"
def text26 : String := "\t\t\tigm = gm + n;\n"
def text27 : String := "\t\t\tfx = igm + n;\n"
def text28 : String := "\t\t}\n"
def text29 : String := "\t\tgx = fx + n;\n"
def text30 : String := "\n"
def tail31 : List String := []
def tail30 : List String := text30::tail31
def tail29 : List String := text29::tail30
def tail28 : List String := text28::tail29
def tail27 : List String := text27::tail28
def tail26 : List String := text26::tail27
def tail25 : List String := text25::tail26
def tail24 : List String := text24::tail25
def tail23 : List String := text23::tail24
def tail22 : List String := text22::tail23
def tail21 : List String := text21::tail22
def tail20 : List String := text20::tail21
def tail19 : List String := text19::tail20
def tail18 : List String := text18::tail19
def tail17 : List String := text17::tail18
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[5923]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[5924]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[5925]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[5926]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[5927]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[5928]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[5929]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[5930]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[5931]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[5932]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[5933]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[5934]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[5935]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[5936]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[5937]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[5938]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[5939]?=some text16 := by decide +kernel
theorem line17 : Pinned.keygenLines[5940]?=some text17 := by decide +kernel
theorem line18 : Pinned.keygenLines[5941]?=some text18 := by decide +kernel
theorem line19 : Pinned.keygenLines[5942]?=some text19 := by decide +kernel
theorem line20 : Pinned.keygenLines[5943]?=some text20 := by decide +kernel
theorem line21 : Pinned.keygenLines[5944]?=some text21 := by decide +kernel
theorem line22 : Pinned.keygenLines[5945]?=some text22 := by decide +kernel
theorem line23 : Pinned.keygenLines[5946]?=some text23 := by decide +kernel
theorem line24 : Pinned.keygenLines[5947]?=some text24 := by decide +kernel
theorem line25 : Pinned.keygenLines[5948]?=some text25 := by decide +kernel
theorem line26 : Pinned.keygenLines[5949]?=some text26 := by decide +kernel
theorem line27 : Pinned.keygenLines[5950]?=some text27 := by decide +kernel
theorem line28 : Pinned.keygenLines[5951]?=some text28 := by decide +kernel
theorem line29 : Pinned.keygenLines[5952]?=some text29 := by decide +kernel
theorem line30 : Pinned.keygenLines[5953]?=some text30 := by decide +kernel
theorem bytes31 : (Pinned.keygenLines.drop 5954).take tail31.length=tail31 := rfl
theorem bytes30 : (Pinned.keygenLines.drop 5953).take tail30.length=tail30 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5953 text30 tail31 line30 bytes31
theorem bytes29 : (Pinned.keygenLines.drop 5952).take tail29.length=tail29 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5952 text29 tail30 line29 bytes30
theorem bytes28 : (Pinned.keygenLines.drop 5951).take tail28.length=tail28 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5951 text28 tail29 line28 bytes29
theorem bytes27 : (Pinned.keygenLines.drop 5950).take tail27.length=tail27 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5950 text27 tail28 line27 bytes28
theorem bytes26 : (Pinned.keygenLines.drop 5949).take tail26.length=tail26 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5949 text26 tail27 line26 bytes27
theorem bytes25 : (Pinned.keygenLines.drop 5948).take tail25.length=tail25 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5948 text25 tail26 line25 bytes26
theorem bytes24 : (Pinned.keygenLines.drop 5947).take tail24.length=tail24 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5947 text24 tail25 line24 bytes25
theorem bytes23 : (Pinned.keygenLines.drop 5946).take tail23.length=tail23 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5946 text23 tail24 line23 bytes24
theorem bytes22 : (Pinned.keygenLines.drop 5945).take tail22.length=tail22 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5945 text22 tail23 line22 bytes23
theorem bytes21 : (Pinned.keygenLines.drop 5944).take tail21.length=tail21 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5944 text21 tail22 line21 bytes22
theorem bytes20 : (Pinned.keygenLines.drop 5943).take tail20.length=tail20 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5943 text20 tail21 line20 bytes21
theorem bytes19 : (Pinned.keygenLines.drop 5942).take tail19.length=tail19 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5942 text19 tail20 line19 bytes20
theorem bytes18 : (Pinned.keygenLines.drop 5941).take tail18.length=tail18 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5941 text18 tail19 line18 bytes19
theorem bytes17 : (Pinned.keygenLines.drop 5940).take tail17.length=tail17 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5940 text17 tail18 line17 bytes18
theorem bytes16 : (Pinned.keygenLines.drop 5939).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5939 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 5938).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5938 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 5937).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5937 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 5936).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5936 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 5935).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5935 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 5934).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5934 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 5933).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5933 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 5932).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5932 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 5931).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5931 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 5930).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5930 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 5929).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5929 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 5928).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5928 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 5927).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5927 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 5926).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5926 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 5925).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5925 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 5924).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5924 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 5923).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5923 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 5923).take 31=lines := bytes0
def group0 : List String := [text0]
def words0 : List B20.C.Token := ["uint32_t","p",",","p0i",",","R2",";"].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text1]
def words1 : List B20.C.Token := ["uint32_t","*","gm",",","*","igm",",","*","fx",",","*","gx",",","*","Fp",",","*","Gp",";"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text2]
def words2 : List B20.C.Token := ["uint64_t","v",";"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text3]
def words3 : List B20.C.Token := [].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text4,text5,text6]
def words4 : List B20.C.Token := [].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text7]
def words5 : List B20.C.Token := ["p","=","primes","[","u","]",".","p",";"].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text8]
def words6 : List B20.C.Token := ["p0i","=","modp_ninv31","(","p",")",";"].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text9]
def words7 : List B20.C.Token := ["R2","=","modp_R2","(","p",",","p0i",")",";"].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text10]
def words8 : List B20.C.Token := [].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text11,text12,text13,text14]
def words9 : List B20.C.Token := [].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text15]
def words10 : List B20.C.Token := ["if","(","u","==","slen",")","{"].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def group11 : List String := [text16]
def words11 : List B20.C.Token := ["zint_rebuild_CRT","(","ft",",","slen",",","slen",",","n",",","primes",",","1",",","t1",")",";"].map String.toList
theorem lex11 : KeygenLexicalChunks.Checked group11 words11 := by
  constructor <;> decide +kernel
def group12 : List String := [text17]
def words12 : List B20.C.Token := ["zint_rebuild_CRT","(","gt",",","slen",",","slen",",","n",",","primes",",","1",",","t1",")",";"].map String.toList
theorem lex12 : KeygenLexicalChunks.Checked group12 words12 := by
  constructor <;> decide +kernel
def group13 : List String := [text18]
def words13 : List B20.C.Token := ["}"].map String.toList
theorem lex13 : KeygenLexicalChunks.Checked group13 words13 := by
  constructor <;> decide +kernel
def group14 : List String := [text19]
def words14 : List B20.C.Token := [].map String.toList
theorem lex14 : KeygenLexicalChunks.Checked group14 words14 := by
  constructor <;> decide +kernel
def group15 : List String := [text20]
def words15 : List B20.C.Token := ["gm","=","t1",";"].map String.toList
theorem lex15 : KeygenLexicalChunks.Checked group15 words15 := by
  constructor <;> decide +kernel
def group16 : List String := [text21]
def words16 : List B20.C.Token := ["if","(","full",")","{"].map String.toList
theorem lex16 : KeygenLexicalChunks.Checked group16 words16 := by
  constructor <;> decide +kernel
def group17 : List String := [text22]
def words17 : List B20.C.Token := ["igm","=","gm","+","(","(","uint64_t",")","1","<<","logn",")",";"].map String.toList
theorem lex17 : KeygenLexicalChunks.Checked group17 words17 := by
  constructor <;> decide +kernel
def group18 : List String := [text23]
def words18 : List B20.C.Token := ["fx","=","igm","+","(","(","uint64_t",")","1","<<","logn",")",";"].map String.toList
theorem lex18 : KeygenLexicalChunks.Checked group18 words18 := by
  constructor <;> decide +kernel
def group19 : List String := [text24]
def words19 : List B20.C.Token := ["}","else","{"].map String.toList
theorem lex19 : KeygenLexicalChunks.Checked group19 words19 := by
  constructor <;> decide +kernel
def group20 : List String := [text25]
def words20 : List B20.C.Token := ["gm","=","t1",";"].map String.toList
theorem lex20 : KeygenLexicalChunks.Checked group20 words20 := by
  constructor <;> decide +kernel
def group21 : List String := [text26]
def words21 : List B20.C.Token := ["igm","=","gm","+","n",";"].map String.toList
theorem lex21 : KeygenLexicalChunks.Checked group21 words21 := by
  constructor <;> decide +kernel
def group22 : List String := [text27]
def words22 : List B20.C.Token := ["fx","=","igm","+","n",";"].map String.toList
theorem lex22 : KeygenLexicalChunks.Checked group22 words22 := by
  constructor <;> decide +kernel
def group23 : List String := [text28]
def words23 : List B20.C.Token := ["}"].map String.toList
theorem lex23 : KeygenLexicalChunks.Checked group23 words23 := by
  constructor <;> decide +kernel
def group24 : List String := [text29]
def words24 : List B20.C.Token := ["gx","=","fx","+","n",";"].map String.toList
theorem lex24 : KeygenLexicalChunks.Checked group24 words24 := by
  constructor <;> decide +kernel
def group25 : List String := [text30]
def words25 : List B20.C.Token := [].map String.toList
theorem lex25 : KeygenLexicalChunks.Checked group25 words25 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10,group11,group12,group13,group14,group15,group16,group17,group18,group19,group20,group21,group22,group23,group24,group25]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10,words11,words12,words13,words14,words15,words16,words17,words18,words19,words20,words21,words22,words23,words24,words25]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.cons lex11 (List.Forall₂.cons lex12 (List.Forall₂.cons lex13 (List.Forall₂.cons lex14 (List.Forall₂.cons lex15 (List.Forall₂.cons lex16 (List.Forall₂.cons lex17 (List.Forall₂.cons lex18 (List.Forall₂.cons lex19 (List.Forall₂.cons lex20 (List.Forall₂.cons lex21 (List.Forall₂.cons lex22 (List.Forall₂.cons lex23 (List.Forall₂.cons lex24 (List.Forall₂.cons lex25 (List.Forall₂.nil))))))))))))))))))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 5923).take 31) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensLift0
