import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensTop1
def text0 : String := "\t/*\n"
def text1 : String := "\t * In the ternary case _and_ top-level, n is a multiple of 3,\n"
def text2 : String := "\t * and hn = n/3. Otherwise, n is a power of 2, and hn = n/2.\n"
def text3 : String := "\t */\n"
def text4 : String := "\tif (fk->ternary && depth == 0) {\n"
def text5 : String := "\t\tfull = 1;\n"
def text6 : String := "\t\tn = (size_t)3 << (logn - 1);\n"
def text7 : String := "\t\thn = (size_t)1 << (logn - 1);\n"
def text8 : String := "\t} else {\n"
def text9 : String := "\t\tfull = 0;\n"
def text10 : String := "\t\tn = (size_t)1 << logn;\n"
def text11 : String := "\t\thn = n >> 1;\n"
def text12 : String := "\t}\n"
def text13 : String := "\n"
def tail14 : List String := []
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[5823]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[5824]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[5825]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[5826]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[5827]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[5828]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[5829]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[5830]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[5831]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[5832]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[5833]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[5834]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[5835]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[5836]?=some text13 := by decide +kernel
theorem bytes14 : (Pinned.keygenLines.drop 5837).take tail14.length=tail14 := rfl
theorem bytes13 : (Pinned.keygenLines.drop 5836).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5836 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 5835).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5835 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 5834).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5834 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 5833).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5833 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 5832).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5832 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 5831).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5831 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 5830).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5830 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 5829).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5829 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 5828).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5828 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 5827).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5827 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 5826).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5826 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 5825).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5825 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 5824).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5824 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 5823).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5823 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 5823).take 14=lines := bytes0
def group0 : List String := [text0,text1,text2,text3]
def words0 : List B20.C.Token := [].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text4]
def words1 : List B20.C.Token := ["if","(","fk","-",">","ternary","&&","depth","==","0",")","{"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text5]
def words2 : List B20.C.Token := ["full","=","1",";"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text6]
def words3 : List B20.C.Token := ["n","=","(","uint64_t",")","3","<<","(","logn","-","1",")",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text7]
def words4 : List B20.C.Token := ["hn","=","(","uint64_t",")","1","<<","(","logn","-","1",")",";"].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text8]
def words5 : List B20.C.Token := ["}","else","{"].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text9]
def words6 : List B20.C.Token := ["full","=","0",";"].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text10]
def words7 : List B20.C.Token := ["n","=","(","uint64_t",")","1","<<","logn",";"].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text11]
def words8 : List B20.C.Token := ["hn","=","n",">>","1",";"].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text12]
def words9 : List B20.C.Token := ["}"].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text13]
def words10 : List B20.C.Token := [].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.nil)))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 5823).take 14) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensTop1
