import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensTop3
def text0 : String := "\n"
def text1 : String := "\t/*\n"
def text2 : String := "\t * Fd and Gd are the F and G from the deeper level.\n"
def text3 : String := "\t */\n"
def text4 : String := "\tFd = fk->tmp;\n"
def text5 : String := "\tGd = Fd + dlen * hn;\n"
def text6 : String := "\n"
def text7 : String := "\t/*\n"
def text8 : String := "\t * Compute the input f and g for this level. Note that we get f\n"
def text9 : String := "\t * and g in RNS + NTT representation.\n"
def text10 : String := "\t */\n"
def text11 : String := "\tft = Gd + dlen * hn;\n"
def text12 : String := "\tmake_fg(ft, f, g, logn_top, fk->ternary, depth, 1);\n"
def text13 : String := "\n"
def text14 : String := "\t/*\n"
def text15 : String := "\t * Move the newly computed f and g to make room for our candidate\n"
def text16 : String := "\t * F and G (unreduced).\n"
def text17 : String := "\t */\n"
def text18 : String := "\tFt = fk->tmp;\n"
def text19 : String := "\tGt = Ft + n * llen;\n"
def text20 : String := "\tt1 = Gt + n * llen;\n"
def text21 : String := "\tmemmove(t1, ft, 2 * n * slen * sizeof *ft);\n"
def text22 : String := "\tft = t1;\n"
def text23 : String := "\tgt = ft + slen * n;\n"
def text24 : String := "\tt1 = gt + slen * n;\n"
def text25 : String := "\n"
def text26 : String := "\t/*\n"
def text27 : String := "\t * Move Fd and Gd _after_ f and g.\n"
def text28 : String := "\t */\n"
def text29 : String := "\tmemmove(t1, Fd, 2 * hn * dlen * sizeof *Fd);\n"
def text30 : String := "\tFd = t1;\n"
def text31 : String := "\tGd = Fd + hn * dlen;\n"
def text32 : String := "\n"
def text33 : String := "\t/*\n"
def text34 : String := "\t * We reduce Fd and Gd modulo all the small primes we will need,\n"
def text35 : String := "\t * and store the values in Ft and Gt (only n/2 values in each).\n"
def text36 : String := "\t */\n"
def tail37 : List String := []
def tail36 : List String := text36::tail37
def tail35 : List String := text35::tail36
def tail34 : List String := text34::tail35
def tail33 : List String := text33::tail34
def tail32 : List String := text32::tail33
def tail31 : List String := text31::tail32
def tail30 : List String := text30::tail31
def tail29 : List String := text29::tail30
def tail28 : List String := text28::tail29
def tail27 : List String := text27::tail28
def tail26 : List String := text26::tail27
def tail25 : List String := text25::tail26
def tail24 : List String := text24::tail25
def tail23 : List String := text23::tail24
def tail22 : List String := text22::tail23
def tail21 : List String := text21::tail22
def tail20 : List String := text20::tail21
def tail19 : List String := text19::tail20
def tail18 : List String := text18::tail19
def tail17 : List String := text17::tail18
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[5860]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[5861]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[5862]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[5863]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[5864]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[5865]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[5866]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[5867]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[5868]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[5869]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[5870]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[5871]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[5872]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[5873]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[5874]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[5875]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[5876]?=some text16 := by decide +kernel
theorem line17 : Pinned.keygenLines[5877]?=some text17 := by decide +kernel
theorem line18 : Pinned.keygenLines[5878]?=some text18 := by decide +kernel
theorem line19 : Pinned.keygenLines[5879]?=some text19 := by decide +kernel
theorem line20 : Pinned.keygenLines[5880]?=some text20 := by decide +kernel
theorem line21 : Pinned.keygenLines[5881]?=some text21 := by decide +kernel
theorem line22 : Pinned.keygenLines[5882]?=some text22 := by decide +kernel
theorem line23 : Pinned.keygenLines[5883]?=some text23 := by decide +kernel
theorem line24 : Pinned.keygenLines[5884]?=some text24 := by decide +kernel
theorem line25 : Pinned.keygenLines[5885]?=some text25 := by decide +kernel
theorem line26 : Pinned.keygenLines[5886]?=some text26 := by decide +kernel
theorem line27 : Pinned.keygenLines[5887]?=some text27 := by decide +kernel
theorem line28 : Pinned.keygenLines[5888]?=some text28 := by decide +kernel
theorem line29 : Pinned.keygenLines[5889]?=some text29 := by decide +kernel
theorem line30 : Pinned.keygenLines[5890]?=some text30 := by decide +kernel
theorem line31 : Pinned.keygenLines[5891]?=some text31 := by decide +kernel
theorem line32 : Pinned.keygenLines[5892]?=some text32 := by decide +kernel
theorem line33 : Pinned.keygenLines[5893]?=some text33 := by decide +kernel
theorem line34 : Pinned.keygenLines[5894]?=some text34 := by decide +kernel
theorem line35 : Pinned.keygenLines[5895]?=some text35 := by decide +kernel
theorem line36 : Pinned.keygenLines[5896]?=some text36 := by decide +kernel
theorem bytes37 : (Pinned.keygenLines.drop 5897).take tail37.length=tail37 := rfl
theorem bytes36 : (Pinned.keygenLines.drop 5896).take tail36.length=tail36 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5896 text36 tail37 line36 bytes37
theorem bytes35 : (Pinned.keygenLines.drop 5895).take tail35.length=tail35 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5895 text35 tail36 line35 bytes36
theorem bytes34 : (Pinned.keygenLines.drop 5894).take tail34.length=tail34 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5894 text34 tail35 line34 bytes35
theorem bytes33 : (Pinned.keygenLines.drop 5893).take tail33.length=tail33 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5893 text33 tail34 line33 bytes34
theorem bytes32 : (Pinned.keygenLines.drop 5892).take tail32.length=tail32 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5892 text32 tail33 line32 bytes33
theorem bytes31 : (Pinned.keygenLines.drop 5891).take tail31.length=tail31 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5891 text31 tail32 line31 bytes32
theorem bytes30 : (Pinned.keygenLines.drop 5890).take tail30.length=tail30 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5890 text30 tail31 line30 bytes31
theorem bytes29 : (Pinned.keygenLines.drop 5889).take tail29.length=tail29 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5889 text29 tail30 line29 bytes30
theorem bytes28 : (Pinned.keygenLines.drop 5888).take tail28.length=tail28 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5888 text28 tail29 line28 bytes29
theorem bytes27 : (Pinned.keygenLines.drop 5887).take tail27.length=tail27 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5887 text27 tail28 line27 bytes28
theorem bytes26 : (Pinned.keygenLines.drop 5886).take tail26.length=tail26 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5886 text26 tail27 line26 bytes27
theorem bytes25 : (Pinned.keygenLines.drop 5885).take tail25.length=tail25 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5885 text25 tail26 line25 bytes26
theorem bytes24 : (Pinned.keygenLines.drop 5884).take tail24.length=tail24 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5884 text24 tail25 line24 bytes25
theorem bytes23 : (Pinned.keygenLines.drop 5883).take tail23.length=tail23 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5883 text23 tail24 line23 bytes24
theorem bytes22 : (Pinned.keygenLines.drop 5882).take tail22.length=tail22 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5882 text22 tail23 line22 bytes23
theorem bytes21 : (Pinned.keygenLines.drop 5881).take tail21.length=tail21 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5881 text21 tail22 line21 bytes22
theorem bytes20 : (Pinned.keygenLines.drop 5880).take tail20.length=tail20 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5880 text20 tail21 line20 bytes21
theorem bytes19 : (Pinned.keygenLines.drop 5879).take tail19.length=tail19 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5879 text19 tail20 line19 bytes20
theorem bytes18 : (Pinned.keygenLines.drop 5878).take tail18.length=tail18 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5878 text18 tail19 line18 bytes19
theorem bytes17 : (Pinned.keygenLines.drop 5877).take tail17.length=tail17 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5877 text17 tail18 line17 bytes18
theorem bytes16 : (Pinned.keygenLines.drop 5876).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5876 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 5875).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5875 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 5874).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5874 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 5873).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5873 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 5872).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5872 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 5871).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5871 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 5870).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5870 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 5869).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5869 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 5868).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5868 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 5867).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5867 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 5866).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5866 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 5865).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5865 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 5864).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5864 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 5863).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5863 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 5862).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5862 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 5861).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5861 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 5860).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5860 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 5860).take 37=lines := bytes0
def group0 : List String := [text0]
def words0 : List B20.C.Token := [].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text1,text2,text3]
def words1 : List B20.C.Token := [].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text4]
def words2 : List B20.C.Token := ["Fd","=","fk","-",">","tmp",";"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text5]
def words3 : List B20.C.Token := ["Gd","=","Fd","+","dlen","*","hn",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text6]
def words4 : List B20.C.Token := [].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text7,text8,text9,text10]
def words5 : List B20.C.Token := [].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text11]
def words6 : List B20.C.Token := ["ft","=","Gd","+","dlen","*","hn",";"].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text12]
def words7 : List B20.C.Token := ["make_fg","(","ft",",","f",",","g",",","logn_top",",","fk","-",">","ternary",",","depth",",","1",")",";"].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text13]
def words8 : List B20.C.Token := [].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text14,text15,text16,text17]
def words9 : List B20.C.Token := [].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text18]
def words10 : List B20.C.Token := ["Ft","=","fk","-",">","tmp",";"].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def group11 : List String := [text19]
def words11 : List B20.C.Token := ["Gt","=","Ft","+","n","*","llen",";"].map String.toList
theorem lex11 : KeygenLexicalChunks.Checked group11 words11 := by
  constructor <;> decide +kernel
def group12 : List String := [text20]
def words12 : List B20.C.Token := ["t1","=","Gt","+","n","*","llen",";"].map String.toList
theorem lex12 : KeygenLexicalChunks.Checked group12 words12 := by
  constructor <;> decide +kernel
def group13 : List String := [text21]
def words13 : List B20.C.Token := ["memmove","(","t1",",","ft",",","2","*","n","*","slen","*","sizeof","*","ft",")",";"].map String.toList
theorem lex13 : KeygenLexicalChunks.Checked group13 words13 := by
  constructor <;> decide +kernel
def group14 : List String := [text22]
def words14 : List B20.C.Token := ["ft","=","t1",";"].map String.toList
theorem lex14 : KeygenLexicalChunks.Checked group14 words14 := by
  constructor <;> decide +kernel
def group15 : List String := [text23]
def words15 : List B20.C.Token := ["gt","=","ft","+","slen","*","n",";"].map String.toList
theorem lex15 : KeygenLexicalChunks.Checked group15 words15 := by
  constructor <;> decide +kernel
def group16 : List String := [text24]
def words16 : List B20.C.Token := ["t1","=","gt","+","slen","*","n",";"].map String.toList
theorem lex16 : KeygenLexicalChunks.Checked group16 words16 := by
  constructor <;> decide +kernel
def group17 : List String := [text25]
def words17 : List B20.C.Token := [].map String.toList
theorem lex17 : KeygenLexicalChunks.Checked group17 words17 := by
  constructor <;> decide +kernel
def group18 : List String := [text26,text27,text28]
def words18 : List B20.C.Token := [].map String.toList
theorem lex18 : KeygenLexicalChunks.Checked group18 words18 := by
  constructor <;> decide +kernel
def group19 : List String := [text29]
def words19 : List B20.C.Token := ["memmove","(","t1",",","Fd",",","2","*","hn","*","dlen","*","sizeof","*","Fd",")",";"].map String.toList
theorem lex19 : KeygenLexicalChunks.Checked group19 words19 := by
  constructor <;> decide +kernel
def group20 : List String := [text30]
def words20 : List B20.C.Token := ["Fd","=","t1",";"].map String.toList
theorem lex20 : KeygenLexicalChunks.Checked group20 words20 := by
  constructor <;> decide +kernel
def group21 : List String := [text31]
def words21 : List B20.C.Token := ["Gd","=","Fd","+","hn","*","dlen",";"].map String.toList
theorem lex21 : KeygenLexicalChunks.Checked group21 words21 := by
  constructor <;> decide +kernel
def group22 : List String := [text32]
def words22 : List B20.C.Token := [].map String.toList
theorem lex22 : KeygenLexicalChunks.Checked group22 words22 := by
  constructor <;> decide +kernel
def group23 : List String := [text33,text34,text35,text36]
def words23 : List B20.C.Token := [].map String.toList
theorem lex23 : KeygenLexicalChunks.Checked group23 words23 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10,group11,group12,group13,group14,group15,group16,group17,group18,group19,group20,group21,group22,group23]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10,words11,words12,words13,words14,words15,words16,words17,words18,words19,words20,words21,words22,words23]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.cons lex11 (List.Forall₂.cons lex12 (List.Forall₂.cons lex13 (List.Forall₂.cons lex14 (List.Forall₂.cons lex15 (List.Forall₂.cons lex16 (List.Forall₂.cons lex17 (List.Forall₂.cons lex18 (List.Forall₂.cons lex19 (List.Forall₂.cons lex20 (List.Forall₂.cons lex21 (List.Forall₂.cons lex22 (List.Forall₂.cons lex23 (List.Forall₂.nil))))))))))))))))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 5860).take 37) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensTop3
