import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensTop5
def text0 : String := "\n"
def text1 : String := "\t/*\n"
def text2 : String := "\t * Rebuild F and G with the CRT.\n"
def text3 : String := "\t */\n"
def text4 : String := "\tzint_rebuild_CRT(Ft, llen, llen, n, primes, 1, t1);\n"
def text5 : String := "\tzint_rebuild_CRT(Gt, llen, llen, n, primes, 1, t1);\n"
def text6 : String := "\n"
def text7 : String := "\t/*\n"
def text8 : String := "\t * At that point, Ft, Gt, ft and gt are consecutive in RAM (in that\n"
def text9 : String := "\t * order).\n"
def text10 : String := "\t */\n"
def text11 : String := "\n"
def text12 : String := "\t/*\n"
def text13 : String := "\t * Apply Babai reduction to bring back F and G to size slen.\n"
def text14 : String := "\t *\n"
def text15 : String := "\t * We use the FFT to compute successive approximations of the\n"
def text16 : String := "\t * reduction coefficient. We first isolate the top bits of\n"
def text17 : String := "\t * the coefficients of f and g, and convert them to floating\n"
def text18 : String := "\t * point; with the FFT, we compute adj(f), adj(g), and\n"
def text19 : String := "\t * 1/(f*adj(f)+g*adj(g)).\n"
def text20 : String := "\t *\n"
def text21 : String := "\t * Then, we repeatedly apply the following:\n"
def text22 : String := "\t *\n"
def text23 : String := "\t *   - Get the top bits of the coefficients of F and G into\n"
def text24 : String := "\t *     floating point, and use the FFT to compute:\n"
def text25 : String := "\t *        (F*adj(f)+G*adj(g))/(f*adj(f)+g*adj(g))\n"
def text26 : String := "\t *\n"
def text27 : String := "\t *   - Convert back that value into normal representation, and\n"
def text28 : String := "\t *     round it to the nearest integers, yielding a polynomial k.\n"
def text29 : String := "\t *     Proper scaling is applied to f, g, F and G so that the\n"
def text30 : String := "\t *     coefficients fit on 32 bits (signed).\n"
def text31 : String := "\t *\n"
def text32 : String := "\t *   - Subtract k*f from F and k*g from G.\n"
def text33 : String := "\t *\n"
def text34 : String := "\t * The process is repeated as long as it works, i.e. it decreases\n"
def text35 : String := "\t * the maximum bit length of coefficients of F and G. This will\n"
def text36 : String := "\t * normally bring down F and G down from llen to slen words at\n"
def text37 : String := "\t * most.\n"
def text38 : String := "\t */\n"
def text39 : String := "\n"
def text40 : String := "\t/*\n"
def text41 : String := "\t * Memory layout:\n"
def text42 : String := "\t *  - We need to compute and keep adj(f), adj(g), and\n"
def text43 : String := "\t *    1/(f*adj(f)+g*adj(g)) (sizes N, N and N/2 fp numbers,\n"
def text44 : String := "\t *    respectively).\n"
def text45 : String := "\t *  - At each iteration we need two extra fp buffer (N fp values),\n"
def text46 : String := "\t *    and produce a k (N 32-bit words). k will be shared with one\n"
def text47 : String := "\t *    of the fp buffers.\n"
def text48 : String := "\t *  - To compute k*f and k*g efficiently (with the NTT), we need\n"
def text49 : String := "\t *    some extra room; we reuse the space of the temporary buffers.\n"
def text50 : String := "\t *\n"
def text51 : String := "\t * Arrays of 'fpr' are obtained from the temporary array itself.\n"
def text52 : String := "\t * We ensure that the base is at a properly aligned offset (the\n"
def text53 : String := "\t * source array fk->tmp was obtained with malloc(), and is thus\n"
def text54 : String := "\t * already aligned).\n"
def text55 : String := "\t */\n"
def text56 : String := "\n"
def text57 : String := "\trt3 = align_fpr(fk->tmp, t1);\n"
def text58 : String := "\trt4 = rt3 + n;\n"
def text59 : String := "\trt5 = rt4 + n;\n"
def text60 : String := "\trt1 = rt5 + (n >> 1);\n"
def text61 : String := "\tk = (int32_t *)align_u32(fk->tmp, rt1);\n"
def text62 : String := "\trt2 = align_fpr(fk->tmp, k + n);\n"
def text63 : String := "\tif (rt2 < (rt1 + n)) {\n"
def text64 : String := "\t\trt2 = rt1 + n;\n"
def text65 : String := "\t}\n"
def text66 : String := "\tt1 = (uint32_t *)k + n;\n"
def text67 : String := "\n"
def text68 : String := "\t/*\n"
def text69 : String := "\t * Get the maximum bit lengths of f and g. f and g are scaled\n"
def text70 : String := "\t * down by maxbl_fg bits, so that values will be below 1.\n"
def text71 : String := "\t */\n"
def text72 : String := "\tmaxbl_f = poly_max_bitlength(ft, slen, slen, logn, full);\n"
def text73 : String := "\tmaxbl_g = poly_max_bitlength(gt, slen, slen, logn, full);\n"
def text74 : String := "\tmaxbl_fg = maxbl_f < maxbl_g ? maxbl_g : maxbl_f;\n"
def text75 : String := "\n"
def text76 : String := "\t/*\n"
def text77 : String := "\t * Compute 1/(f*adj(f)+g*adj(g)) in rt5. We also keep adj(f)\n"
def text78 : String := "\t * and adj(g) in rt3 and rt4, respectively.\n"
def text79 : String := "\t */\n"
def tail80 : List String := []
def tail79 : List String := text79::tail80
def tail78 : List String := text78::tail79
def tail77 : List String := text77::tail78
def tail76 : List String := text76::tail77
def tail75 : List String := text75::tail76
def tail74 : List String := text74::tail75
def tail73 : List String := text73::tail74
def tail72 : List String := text72::tail73
def tail71 : List String := text71::tail72
def tail70 : List String := text70::tail71
def tail69 : List String := text69::tail70
def tail68 : List String := text68::tail69
def tail67 : List String := text67::tail68
def tail66 : List String := text66::tail67
def tail65 : List String := text65::tail66
def tail64 : List String := text64::tail65
def tail63 : List String := text63::tail64
def tail62 : List String := text62::tail63
def tail61 : List String := text61::tail62
def tail60 : List String := text60::tail61
def tail59 : List String := text59::tail60
def tail58 : List String := text58::tail59
def tail57 : List String := text57::tail58
def tail56 : List String := text56::tail57
def tail55 : List String := text55::tail56
def tail54 : List String := text54::tail55
def tail53 : List String := text53::tail54
def tail52 : List String := text52::tail53
def tail51 : List String := text51::tail52
def tail50 : List String := text50::tail51
def tail49 : List String := text49::tail50
def tail48 : List String := text48::tail49
def tail47 : List String := text47::tail48
def tail46 : List String := text46::tail47
def tail45 : List String := text45::tail46
def tail44 : List String := text44::tail45
def tail43 : List String := text43::tail44
def tail42 : List String := text42::tail43
def tail41 : List String := text41::tail42
def tail40 : List String := text40::tail41
def tail39 : List String := text39::tail40
def tail38 : List String := text38::tail39
def tail37 : List String := text37::tail38
def tail36 : List String := text36::tail37
def tail35 : List String := text35::tail36
def tail34 : List String := text34::tail35
def tail33 : List String := text33::tail34
def tail32 : List String := text32::tail33
def tail31 : List String := text31::tail32
def tail30 : List String := text30::tail31
def tail29 : List String := text29::tail30
def tail28 : List String := text28::tail29
def tail27 : List String := text27::tail28
def tail26 : List String := text26::tail27
def tail25 : List String := text25::tail26
def tail24 : List String := text24::tail25
def tail23 : List String := text23::tail24
def tail22 : List String := text22::tail23
def tail21 : List String := text21::tail22
def tail20 : List String := text20::tail21
def tail19 : List String := text19::tail20
def tail18 : List String := text18::tail19
def tail17 : List String := text17::tail18
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[6118]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[6119]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[6120]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[6121]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[6122]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[6123]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[6124]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[6125]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[6126]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[6127]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[6128]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[6129]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[6130]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[6131]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[6132]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[6133]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[6134]?=some text16 := by decide +kernel
theorem line17 : Pinned.keygenLines[6135]?=some text17 := by decide +kernel
theorem line18 : Pinned.keygenLines[6136]?=some text18 := by decide +kernel
theorem line19 : Pinned.keygenLines[6137]?=some text19 := by decide +kernel
theorem line20 : Pinned.keygenLines[6138]?=some text20 := by decide +kernel
theorem line21 : Pinned.keygenLines[6139]?=some text21 := by decide +kernel
theorem line22 : Pinned.keygenLines[6140]?=some text22 := by decide +kernel
theorem line23 : Pinned.keygenLines[6141]?=some text23 := by decide +kernel
theorem line24 : Pinned.keygenLines[6142]?=some text24 := by decide +kernel
theorem line25 : Pinned.keygenLines[6143]?=some text25 := by decide +kernel
theorem line26 : Pinned.keygenLines[6144]?=some text26 := by decide +kernel
theorem line27 : Pinned.keygenLines[6145]?=some text27 := by decide +kernel
theorem line28 : Pinned.keygenLines[6146]?=some text28 := by decide +kernel
theorem line29 : Pinned.keygenLines[6147]?=some text29 := by decide +kernel
theorem line30 : Pinned.keygenLines[6148]?=some text30 := by decide +kernel
theorem line31 : Pinned.keygenLines[6149]?=some text31 := by decide +kernel
theorem line32 : Pinned.keygenLines[6150]?=some text32 := by decide +kernel
theorem line33 : Pinned.keygenLines[6151]?=some text33 := by decide +kernel
theorem line34 : Pinned.keygenLines[6152]?=some text34 := by decide +kernel
theorem line35 : Pinned.keygenLines[6153]?=some text35 := by decide +kernel
theorem line36 : Pinned.keygenLines[6154]?=some text36 := by decide +kernel
theorem line37 : Pinned.keygenLines[6155]?=some text37 := by decide +kernel
theorem line38 : Pinned.keygenLines[6156]?=some text38 := by decide +kernel
theorem line39 : Pinned.keygenLines[6157]?=some text39 := by decide +kernel
theorem line40 : Pinned.keygenLines[6158]?=some text40 := by decide +kernel
theorem line41 : Pinned.keygenLines[6159]?=some text41 := by decide +kernel
theorem line42 : Pinned.keygenLines[6160]?=some text42 := by decide +kernel
theorem line43 : Pinned.keygenLines[6161]?=some text43 := by decide +kernel
theorem line44 : Pinned.keygenLines[6162]?=some text44 := by decide +kernel
theorem line45 : Pinned.keygenLines[6163]?=some text45 := by decide +kernel
theorem line46 : Pinned.keygenLines[6164]?=some text46 := by decide +kernel
theorem line47 : Pinned.keygenLines[6165]?=some text47 := by decide +kernel
theorem line48 : Pinned.keygenLines[6166]?=some text48 := by decide +kernel
theorem line49 : Pinned.keygenLines[6167]?=some text49 := by decide +kernel
theorem line50 : Pinned.keygenLines[6168]?=some text50 := by decide +kernel
theorem line51 : Pinned.keygenLines[6169]?=some text51 := by decide +kernel
theorem line52 : Pinned.keygenLines[6170]?=some text52 := by decide +kernel
theorem line53 : Pinned.keygenLines[6171]?=some text53 := by decide +kernel
theorem line54 : Pinned.keygenLines[6172]?=some text54 := by decide +kernel
theorem line55 : Pinned.keygenLines[6173]?=some text55 := by decide +kernel
theorem line56 : Pinned.keygenLines[6174]?=some text56 := by decide +kernel
theorem line57 : Pinned.keygenLines[6175]?=some text57 := by decide +kernel
theorem line58 : Pinned.keygenLines[6176]?=some text58 := by decide +kernel
theorem line59 : Pinned.keygenLines[6177]?=some text59 := by decide +kernel
theorem line60 : Pinned.keygenLines[6178]?=some text60 := by decide +kernel
theorem line61 : Pinned.keygenLines[6179]?=some text61 := by decide +kernel
theorem line62 : Pinned.keygenLines[6180]?=some text62 := by decide +kernel
theorem line63 : Pinned.keygenLines[6181]?=some text63 := by decide +kernel
theorem line64 : Pinned.keygenLines[6182]?=some text64 := by decide +kernel
theorem line65 : Pinned.keygenLines[6183]?=some text65 := by decide +kernel
theorem line66 : Pinned.keygenLines[6184]?=some text66 := by decide +kernel
theorem line67 : Pinned.keygenLines[6185]?=some text67 := by decide +kernel
theorem line68 : Pinned.keygenLines[6186]?=some text68 := by decide +kernel
theorem line69 : Pinned.keygenLines[6187]?=some text69 := by decide +kernel
theorem line70 : Pinned.keygenLines[6188]?=some text70 := by decide +kernel
theorem line71 : Pinned.keygenLines[6189]?=some text71 := by decide +kernel
theorem line72 : Pinned.keygenLines[6190]?=some text72 := by decide +kernel
theorem line73 : Pinned.keygenLines[6191]?=some text73 := by decide +kernel
theorem line74 : Pinned.keygenLines[6192]?=some text74 := by decide +kernel
theorem line75 : Pinned.keygenLines[6193]?=some text75 := by decide +kernel
theorem line76 : Pinned.keygenLines[6194]?=some text76 := by decide +kernel
theorem line77 : Pinned.keygenLines[6195]?=some text77 := by decide +kernel
theorem line78 : Pinned.keygenLines[6196]?=some text78 := by decide +kernel
theorem line79 : Pinned.keygenLines[6197]?=some text79 := by decide +kernel
theorem bytes80 : (Pinned.keygenLines.drop 6198).take tail80.length=tail80 := rfl
theorem bytes79 : (Pinned.keygenLines.drop 6197).take tail79.length=tail79 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6197 text79 tail80 line79 bytes80
theorem bytes78 : (Pinned.keygenLines.drop 6196).take tail78.length=tail78 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6196 text78 tail79 line78 bytes79
theorem bytes77 : (Pinned.keygenLines.drop 6195).take tail77.length=tail77 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6195 text77 tail78 line77 bytes78
theorem bytes76 : (Pinned.keygenLines.drop 6194).take tail76.length=tail76 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6194 text76 tail77 line76 bytes77
theorem bytes75 : (Pinned.keygenLines.drop 6193).take tail75.length=tail75 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6193 text75 tail76 line75 bytes76
theorem bytes74 : (Pinned.keygenLines.drop 6192).take tail74.length=tail74 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6192 text74 tail75 line74 bytes75
theorem bytes73 : (Pinned.keygenLines.drop 6191).take tail73.length=tail73 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6191 text73 tail74 line73 bytes74
theorem bytes72 : (Pinned.keygenLines.drop 6190).take tail72.length=tail72 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6190 text72 tail73 line72 bytes73
theorem bytes71 : (Pinned.keygenLines.drop 6189).take tail71.length=tail71 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6189 text71 tail72 line71 bytes72
theorem bytes70 : (Pinned.keygenLines.drop 6188).take tail70.length=tail70 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6188 text70 tail71 line70 bytes71
theorem bytes69 : (Pinned.keygenLines.drop 6187).take tail69.length=tail69 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6187 text69 tail70 line69 bytes70
theorem bytes68 : (Pinned.keygenLines.drop 6186).take tail68.length=tail68 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6186 text68 tail69 line68 bytes69
theorem bytes67 : (Pinned.keygenLines.drop 6185).take tail67.length=tail67 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6185 text67 tail68 line67 bytes68
theorem bytes66 : (Pinned.keygenLines.drop 6184).take tail66.length=tail66 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6184 text66 tail67 line66 bytes67
theorem bytes65 : (Pinned.keygenLines.drop 6183).take tail65.length=tail65 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6183 text65 tail66 line65 bytes66
theorem bytes64 : (Pinned.keygenLines.drop 6182).take tail64.length=tail64 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6182 text64 tail65 line64 bytes65
theorem bytes63 : (Pinned.keygenLines.drop 6181).take tail63.length=tail63 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6181 text63 tail64 line63 bytes64
theorem bytes62 : (Pinned.keygenLines.drop 6180).take tail62.length=tail62 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6180 text62 tail63 line62 bytes63
theorem bytes61 : (Pinned.keygenLines.drop 6179).take tail61.length=tail61 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6179 text61 tail62 line61 bytes62
theorem bytes60 : (Pinned.keygenLines.drop 6178).take tail60.length=tail60 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6178 text60 tail61 line60 bytes61
theorem bytes59 : (Pinned.keygenLines.drop 6177).take tail59.length=tail59 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6177 text59 tail60 line59 bytes60
theorem bytes58 : (Pinned.keygenLines.drop 6176).take tail58.length=tail58 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6176 text58 tail59 line58 bytes59
theorem bytes57 : (Pinned.keygenLines.drop 6175).take tail57.length=tail57 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6175 text57 tail58 line57 bytes58
theorem bytes56 : (Pinned.keygenLines.drop 6174).take tail56.length=tail56 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6174 text56 tail57 line56 bytes57
theorem bytes55 : (Pinned.keygenLines.drop 6173).take tail55.length=tail55 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6173 text55 tail56 line55 bytes56
theorem bytes54 : (Pinned.keygenLines.drop 6172).take tail54.length=tail54 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6172 text54 tail55 line54 bytes55
theorem bytes53 : (Pinned.keygenLines.drop 6171).take tail53.length=tail53 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6171 text53 tail54 line53 bytes54
theorem bytes52 : (Pinned.keygenLines.drop 6170).take tail52.length=tail52 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6170 text52 tail53 line52 bytes53
theorem bytes51 : (Pinned.keygenLines.drop 6169).take tail51.length=tail51 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6169 text51 tail52 line51 bytes52
theorem bytes50 : (Pinned.keygenLines.drop 6168).take tail50.length=tail50 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6168 text50 tail51 line50 bytes51
theorem bytes49 : (Pinned.keygenLines.drop 6167).take tail49.length=tail49 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6167 text49 tail50 line49 bytes50
theorem bytes48 : (Pinned.keygenLines.drop 6166).take tail48.length=tail48 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6166 text48 tail49 line48 bytes49
theorem bytes47 : (Pinned.keygenLines.drop 6165).take tail47.length=tail47 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6165 text47 tail48 line47 bytes48
theorem bytes46 : (Pinned.keygenLines.drop 6164).take tail46.length=tail46 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6164 text46 tail47 line46 bytes47
theorem bytes45 : (Pinned.keygenLines.drop 6163).take tail45.length=tail45 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6163 text45 tail46 line45 bytes46
theorem bytes44 : (Pinned.keygenLines.drop 6162).take tail44.length=tail44 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6162 text44 tail45 line44 bytes45
theorem bytes43 : (Pinned.keygenLines.drop 6161).take tail43.length=tail43 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6161 text43 tail44 line43 bytes44
theorem bytes42 : (Pinned.keygenLines.drop 6160).take tail42.length=tail42 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6160 text42 tail43 line42 bytes43
theorem bytes41 : (Pinned.keygenLines.drop 6159).take tail41.length=tail41 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6159 text41 tail42 line41 bytes42
theorem bytes40 : (Pinned.keygenLines.drop 6158).take tail40.length=tail40 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6158 text40 tail41 line40 bytes41
theorem bytes39 : (Pinned.keygenLines.drop 6157).take tail39.length=tail39 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6157 text39 tail40 line39 bytes40
theorem bytes38 : (Pinned.keygenLines.drop 6156).take tail38.length=tail38 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6156 text38 tail39 line38 bytes39
theorem bytes37 : (Pinned.keygenLines.drop 6155).take tail37.length=tail37 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6155 text37 tail38 line37 bytes38
theorem bytes36 : (Pinned.keygenLines.drop 6154).take tail36.length=tail36 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6154 text36 tail37 line36 bytes37
theorem bytes35 : (Pinned.keygenLines.drop 6153).take tail35.length=tail35 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6153 text35 tail36 line35 bytes36
theorem bytes34 : (Pinned.keygenLines.drop 6152).take tail34.length=tail34 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6152 text34 tail35 line34 bytes35
theorem bytes33 : (Pinned.keygenLines.drop 6151).take tail33.length=tail33 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6151 text33 tail34 line33 bytes34
theorem bytes32 : (Pinned.keygenLines.drop 6150).take tail32.length=tail32 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6150 text32 tail33 line32 bytes33
theorem bytes31 : (Pinned.keygenLines.drop 6149).take tail31.length=tail31 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6149 text31 tail32 line31 bytes32
theorem bytes30 : (Pinned.keygenLines.drop 6148).take tail30.length=tail30 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6148 text30 tail31 line30 bytes31
theorem bytes29 : (Pinned.keygenLines.drop 6147).take tail29.length=tail29 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6147 text29 tail30 line29 bytes30
theorem bytes28 : (Pinned.keygenLines.drop 6146).take tail28.length=tail28 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6146 text28 tail29 line28 bytes29
theorem bytes27 : (Pinned.keygenLines.drop 6145).take tail27.length=tail27 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6145 text27 tail28 line27 bytes28
theorem bytes26 : (Pinned.keygenLines.drop 6144).take tail26.length=tail26 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6144 text26 tail27 line26 bytes27
theorem bytes25 : (Pinned.keygenLines.drop 6143).take tail25.length=tail25 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6143 text25 tail26 line25 bytes26
theorem bytes24 : (Pinned.keygenLines.drop 6142).take tail24.length=tail24 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6142 text24 tail25 line24 bytes25
theorem bytes23 : (Pinned.keygenLines.drop 6141).take tail23.length=tail23 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6141 text23 tail24 line23 bytes24
theorem bytes22 : (Pinned.keygenLines.drop 6140).take tail22.length=tail22 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6140 text22 tail23 line22 bytes23
theorem bytes21 : (Pinned.keygenLines.drop 6139).take tail21.length=tail21 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6139 text21 tail22 line21 bytes22
theorem bytes20 : (Pinned.keygenLines.drop 6138).take tail20.length=tail20 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6138 text20 tail21 line20 bytes21
theorem bytes19 : (Pinned.keygenLines.drop 6137).take tail19.length=tail19 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6137 text19 tail20 line19 bytes20
theorem bytes18 : (Pinned.keygenLines.drop 6136).take tail18.length=tail18 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6136 text18 tail19 line18 bytes19
theorem bytes17 : (Pinned.keygenLines.drop 6135).take tail17.length=tail17 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6135 text17 tail18 line17 bytes18
theorem bytes16 : (Pinned.keygenLines.drop 6134).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6134 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 6133).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6133 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 6132).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6132 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 6131).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6131 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 6130).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6130 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 6129).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6129 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 6128).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6128 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 6127).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6127 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 6126).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6126 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 6125).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6125 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 6124).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6124 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 6123).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6123 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 6122).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6122 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 6121).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6121 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 6120).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6120 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 6119).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6119 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 6118).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6118 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 6118).take 80=lines := bytes0
def group0 : List String := [text0]
def words0 : List B20.C.Token := [].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text1,text2,text3]
def words1 : List B20.C.Token := [].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text4]
def words2 : List B20.C.Token := ["zint_rebuild_CRT","(","Ft",",","llen",",","llen",",","n",",","primes",",","1",",","t1",")",";"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text5]
def words3 : List B20.C.Token := ["zint_rebuild_CRT","(","Gt",",","llen",",","llen",",","n",",","primes",",","1",",","t1",")",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text6]
def words4 : List B20.C.Token := [].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text7,text8,text9,text10]
def words5 : List B20.C.Token := [].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text11]
def words6 : List B20.C.Token := [].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text12,text13,text14,text15,text16,text17,text18,text19,text20,text21,text22,text23,text24,text25,text26,text27,text28,text29,text30,text31,text32,text33,text34,text35,text36,text37,text38]
def words7 : List B20.C.Token := [].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text39]
def words8 : List B20.C.Token := [].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text40,text41,text42,text43,text44,text45,text46,text47,text48,text49,text50,text51,text52,text53,text54,text55]
def words9 : List B20.C.Token := [].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text56]
def words10 : List B20.C.Token := [].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def group11 : List String := [text57]
def words11 : List B20.C.Token := ["rt3","=","align_fpr","(","fk","-",">","tmp",",","t1",")",";"].map String.toList
theorem lex11 : KeygenLexicalChunks.Checked group11 words11 := by
  constructor <;> decide +kernel
def group12 : List String := [text58]
def words12 : List B20.C.Token := ["rt4","=","rt3","+","n",";"].map String.toList
theorem lex12 : KeygenLexicalChunks.Checked group12 words12 := by
  constructor <;> decide +kernel
def group13 : List String := [text59]
def words13 : List B20.C.Token := ["rt5","=","rt4","+","n",";"].map String.toList
theorem lex13 : KeygenLexicalChunks.Checked group13 words13 := by
  constructor <;> decide +kernel
def group14 : List String := [text60]
def words14 : List B20.C.Token := ["rt1","=","rt5","+","(","n",">>","1",")",";"].map String.toList
theorem lex14 : KeygenLexicalChunks.Checked group14 words14 := by
  constructor <;> decide +kernel
def group15 : List String := [text61]
def words15 : List B20.C.Token := ["k","=","(","int32_t","*",")","align_u32","(","fk","-",">","tmp",",","rt1",")",";"].map String.toList
theorem lex15 : KeygenLexicalChunks.Checked group15 words15 := by
  constructor <;> decide +kernel
def group16 : List String := [text62]
def words16 : List B20.C.Token := ["rt2","=","align_fpr","(","fk","-",">","tmp",",","k","+","n",")",";"].map String.toList
theorem lex16 : KeygenLexicalChunks.Checked group16 words16 := by
  constructor <;> decide +kernel
def group17 : List String := [text63]
def words17 : List B20.C.Token := ["if","(","rt2","<","(","rt1","+","n",")",")","{"].map String.toList
theorem lex17 : KeygenLexicalChunks.Checked group17 words17 := by
  constructor <;> decide +kernel
def group18 : List String := [text64]
def words18 : List B20.C.Token := ["rt2","=","rt1","+","n",";"].map String.toList
theorem lex18 : KeygenLexicalChunks.Checked group18 words18 := by
  constructor <;> decide +kernel
def group19 : List String := [text65]
def words19 : List B20.C.Token := ["}"].map String.toList
theorem lex19 : KeygenLexicalChunks.Checked group19 words19 := by
  constructor <;> decide +kernel
def group20 : List String := [text66]
def words20 : List B20.C.Token := ["t1","=","(","uint32_t","*",")","k","+","n",";"].map String.toList
theorem lex20 : KeygenLexicalChunks.Checked group20 words20 := by
  constructor <;> decide +kernel
def group21 : List String := [text67]
def words21 : List B20.C.Token := [].map String.toList
theorem lex21 : KeygenLexicalChunks.Checked group21 words21 := by
  constructor <;> decide +kernel
def group22 : List String := [text68,text69,text70,text71]
def words22 : List B20.C.Token := [].map String.toList
theorem lex22 : KeygenLexicalChunks.Checked group22 words22 := by
  constructor <;> decide +kernel
def group23 : List String := [text72]
def words23 : List B20.C.Token := ["maxbl_f","=","poly_max_bitlength","(","ft",",","slen",",","slen",",","logn",",","full",")",";"].map String.toList
theorem lex23 : KeygenLexicalChunks.Checked group23 words23 := by
  constructor <;> decide +kernel
def group24 : List String := [text73]
def words24 : List B20.C.Token := ["maxbl_g","=","poly_max_bitlength","(","gt",",","slen",",","slen",",","logn",",","full",")",";"].map String.toList
theorem lex24 : KeygenLexicalChunks.Checked group24 words24 := by
  constructor <;> decide +kernel
def group25 : List String := [text74]
def words25 : List B20.C.Token := ["maxbl_fg","=","maxbl_f","<","maxbl_g","?","maxbl_g",":","maxbl_f",";"].map String.toList
theorem lex25 : KeygenLexicalChunks.Checked group25 words25 := by
  constructor <;> decide +kernel
def group26 : List String := [text75]
def words26 : List B20.C.Token := [].map String.toList
theorem lex26 : KeygenLexicalChunks.Checked group26 words26 := by
  constructor <;> decide +kernel
def group27 : List String := [text76,text77,text78,text79]
def words27 : List B20.C.Token := [].map String.toList
theorem lex27 : KeygenLexicalChunks.Checked group27 words27 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10,group11,group12,group13,group14,group15,group16,group17,group18,group19,group20,group21,group22,group23,group24,group25,group26,group27]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10,words11,words12,words13,words14,words15,words16,words17,words18,words19,words20,words21,words22,words23,words24,words25,words26,words27]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.cons lex11 (List.Forall₂.cons lex12 (List.Forall₂.cons lex13 (List.Forall₂.cons lex14 (List.Forall₂.cons lex15 (List.Forall₂.cons lex16 (List.Forall₂.cons lex17 (List.Forall₂.cons lex18 (List.Forall₂.cons lex19 (List.Forall₂.cons lex20 (List.Forall₂.cons lex21 (List.Forall₂.cons lex22 (List.Forall₂.cons lex23 (List.Forall₂.cons lex24 (List.Forall₂.cons lex25 (List.Forall₂.cons lex26 (List.Forall₂.cons lex27 (List.Forall₂.nil))))))))))))))))))))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 6118).take 80) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensTop5
