import Source3.KeygenIntermediateReduceData

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_piece_source.py. -/
namespace FT1536.Source3.KeygenIntermediateReduceCheck1
theorem checked : KeygenIntermediateReduceData.audit 1=some true := by decide +kernel
end FT1536.Source3.KeygenIntermediateReduceCheck1
