import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensLift4
def text0 : String := "\t\t/*\n"
def text1 : String := "\t\t * Compute our F and G modulo p.\n"
def text2 : String := "\t\t *\n"
def text3 : String := "\t\t * General case:\n"
def text4 : String := "\t\t *\n"
def text5 : String := "\t\t *   we divide degree by d = 2 or 3\n"
def text6 : String := "\t\t *   f'(x^d) = N(f)(x^d) = f * adj(f)\n"
def text7 : String := "\t\t *   g'(x^d) = N(g)(x^d) = g * adj(g)\n"
def text8 : String := "\t\t *   f'*G' - g'*F' = q\n"
def text9 : String := "\t\t *   F = F'(x^d) * adj(g)\n"
def text10 : String := "\t\t *   G = G'(x^d) * adj(f)\n"
def text11 : String := "\t\t *\n"
def text12 : String := "\t\t * We compute things in the NTT. We group roots of phi\n"
def text13 : String := "\t\t * such that all roots x in a group share the same x^d.\n"
def text14 : String := "\t\t * If the roots in a group are x_1, x_2... x_d, then:\n"
def text15 : String := "\t\t *\n"
def text16 : String := "\t\t *   N(f)(x_1^d) = f(x_1)*f(x_2)*...*f(x_d)\n"
def text17 : String := "\t\t *\n"
def text18 : String := "\t\t * Thus, we have:\n"
def text19 : String := "\t\t *\n"
def text20 : String := "\t\t *   G(x_1) = f(x_2)*f(x_3)*...*f(x_d)*G'(x_1^d)\n"
def text21 : String := "\t\t *   G(x_2) = f(x_1)*f(x_3)*...*f(x_d)*G'(x_1^d)\n"
def text22 : String := "\t\t *   ...\n"
def text23 : String := "\t\t *   G(x_d) = f(x_1)*f(x_2)*...*f(x_{d-1})*G'(x_1^d)\n"
def text24 : String := "\t\t *\n"
def text25 : String := "\t\t * In all cases, we can thus compute F and G in NTT\n"
def text26 : String := "\t\t * representation by a few simple multiplications.\n"
def text27 : String := "\t\t * Moreover, in our chosen NTT representation, roots\n"
def text28 : String := "\t\t * from the same group are consecutive in RAM.\n"
def text29 : String := "\t\t */\n"
def text30 : String := "\t\tif (full) {\n"
def text31 : String := "\t\t\tuint32_t R3;\n"
def text32 : String := "\t\t\tsize_t v2;\n"
def text33 : String := "\n"
def text34 : String := "\t\t\tR3 = modp_montymul(R2, R2, p, p0i);\n"
def text35 : String := "\t\t\tfor (v = 0, v2 = 0, x = Ft + u, y = Gt + u; v < n;\n"
def text36 : String := "\t\t\t\tv += 3, v2 ++, x += 3 * llen, y += 3 * llen)\n"
def text37 : String := "\t\t\t{\n"
def text38 : String := "\t\t\t\tuint32_t ftA, ftB, ftC, gtA, gtB, gtC;\n"
def text39 : String := "\t\t\t\tuint32_t mFp, mGp;\n"
def text40 : String := "\n"
def text41 : String := "\t\t\t\tftA = fx[v + 0];\n"
def text42 : String := "\t\t\t\tftB = fx[v + 1];\n"
def text43 : String := "\t\t\t\tftC = fx[v + 2];\n"
def text44 : String := "\t\t\t\tgtA = gx[v + 0];\n"
def text45 : String := "\t\t\t\tgtB = gx[v + 1];\n"
def text46 : String := "\t\t\t\tgtC = gx[v + 2];\n"
def text47 : String := "\t\t\t\tmFp = modp_montymul(Fp[v2], R3, p, p0i);\n"
def text48 : String := "\t\t\t\tmGp = modp_montymul(Gp[v2], R3, p, p0i);\n"
def text49 : String := "\t\t\t\tx[0] = modp_montymul(mFp,\n"
def text50 : String := "\t\t\t\t\tmodp_montymul(gtB, gtC, p, p0i),\n"
def text51 : String := "\t\t\t\t\tp, p0i);\n"
def text52 : String := "\t\t\t\tx[llen] = modp_montymul(mFp,\n"
def text53 : String := "\t\t\t\t\tmodp_montymul(gtC, gtA, p, p0i),\n"
def text54 : String := "\t\t\t\t\tp, p0i);\n"
def text55 : String := "\t\t\t\tx[2 * llen] = modp_montymul(mFp,\n"
def text56 : String := "\t\t\t\t\tmodp_montymul(gtA, gtB, p, p0i),\n"
def text57 : String := "\t\t\t\t\tp, p0i);\n"
def text58 : String := "\t\t\t\ty[0] = modp_montymul(mGp,\n"
def text59 : String := "\t\t\t\t\tmodp_montymul(ftB, ftC, p, p0i),\n"
def text60 : String := "\t\t\t\t\tp, p0i);\n"
def text61 : String := "\t\t\t\ty[llen] = modp_montymul(mGp,\n"
def text62 : String := "\t\t\t\t\tmodp_montymul(ftC, ftA, p, p0i),\n"
def text63 : String := "\t\t\t\t\tp, p0i);\n"
def text64 : String := "\t\t\t\ty[2 * llen] = modp_montymul(mGp,\n"
def text65 : String := "\t\t\t\t\tmodp_montymul(ftA, ftB, p, p0i),\n"
def text66 : String := "\t\t\t\t\tp, p0i);\n"
def text67 : String := "\t\t\t}\n"
def text68 : String := "\t\t} else {\n"
def text69 : String := "\t\t\tfor (v = 0, x = Ft + u, y = Gt + u; v < hn;\n"
def text70 : String := "\t\t\t\tv ++, x += (llen << 1), y += (llen << 1))\n"
def text71 : String := "\t\t\t{\n"
def text72 : String := "\t\t\t\tuint32_t ftA, ftB, gtA, gtB;\n"
def text73 : String := "\t\t\t\tuint32_t mFp, mGp;\n"
def text74 : String := "\n"
def text75 : String := "\t\t\t\tftA = fx[(v << 1) + 0];\n"
def text76 : String := "\t\t\t\tftB = fx[(v << 1) + 1];\n"
def text77 : String := "\t\t\t\tgtA = gx[(v << 1) + 0];\n"
def text78 : String := "\t\t\t\tgtB = gx[(v << 1) + 1];\n"
def text79 : String := "\t\t\t\tmFp = modp_montymul(Fp[v], R2, p, p0i);\n"
def text80 : String := "\t\t\t\tmGp = modp_montymul(Gp[v], R2, p, p0i);\n"
def text81 : String := "\t\t\t\tx[0] = modp_montymul(gtB, mFp, p, p0i);\n"
def text82 : String := "\t\t\t\tx[llen] = modp_montymul(gtA, mFp, p, p0i);\n"
def text83 : String := "\t\t\t\ty[0] = modp_montymul(ftB, mGp, p, p0i);\n"
def text84 : String := "\t\t\t\ty[llen] = modp_montymul(ftA, mGp, p, p0i);\n"
def text85 : String := "\t\t\t}\n"
def text86 : String := "\t\t}\n"
def tail87 : List String := []
def tail86 : List String := text86::tail87
def tail85 : List String := text85::tail86
def tail84 : List String := text84::tail85
def tail83 : List String := text83::tail84
def tail82 : List String := text82::tail83
def tail81 : List String := text81::tail82
def tail80 : List String := text80::tail81
def tail79 : List String := text79::tail80
def tail78 : List String := text78::tail79
def tail77 : List String := text77::tail78
def tail76 : List String := text76::tail77
def tail75 : List String := text75::tail76
def tail74 : List String := text74::tail75
def tail73 : List String := text73::tail74
def tail72 : List String := text72::tail73
def tail71 : List String := text71::tail72
def tail70 : List String := text70::tail71
def tail69 : List String := text69::tail70
def tail68 : List String := text68::tail69
def tail67 : List String := text67::tail68
def tail66 : List String := text66::tail67
def tail65 : List String := text65::tail66
def tail64 : List String := text64::tail65
def tail63 : List String := text63::tail64
def tail62 : List String := text62::tail63
def tail61 : List String := text61::tail62
def tail60 : List String := text60::tail61
def tail59 : List String := text59::tail60
def tail58 : List String := text58::tail59
def tail57 : List String := text57::tail58
def tail56 : List String := text56::tail57
def tail55 : List String := text55::tail56
def tail54 : List String := text54::tail55
def tail53 : List String := text53::tail54
def tail52 : List String := text52::tail53
def tail51 : List String := text51::tail52
def tail50 : List String := text50::tail51
def tail49 : List String := text49::tail50
def tail48 : List String := text48::tail49
def tail47 : List String := text47::tail48
def tail46 : List String := text46::tail47
def tail45 : List String := text45::tail46
def tail44 : List String := text44::tail45
def tail43 : List String := text43::tail44
def tail42 : List String := text42::tail43
def tail41 : List String := text41::tail42
def tail40 : List String := text40::tail41
def tail39 : List String := text39::tail40
def tail38 : List String := text38::tail39
def tail37 : List String := text37::tail38
def tail36 : List String := text36::tail37
def tail35 : List String := text35::tail36
def tail34 : List String := text34::tail35
def tail33 : List String := text33::tail34
def tail32 : List String := text32::tail33
def tail31 : List String := text31::tail32
def tail30 : List String := text30::tail31
def tail29 : List String := text29::tail30
def tail28 : List String := text28::tail29
def tail27 : List String := text27::tail28
def tail26 : List String := text26::tail27
def tail25 : List String := text25::tail26
def tail24 : List String := text24::tail25
def tail23 : List String := text23::tail24
def tail22 : List String := text22::tail23
def tail21 : List String := text21::tail22
def tail20 : List String := text20::tail21
def tail19 : List String := text19::tail20
def tail18 : List String := text18::tail19
def tail17 : List String := text17::tail18
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[6023]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[6024]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[6025]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[6026]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[6027]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[6028]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[6029]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[6030]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[6031]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[6032]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[6033]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[6034]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[6035]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[6036]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[6037]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[6038]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[6039]?=some text16 := by decide +kernel
theorem line17 : Pinned.keygenLines[6040]?=some text17 := by decide +kernel
theorem line18 : Pinned.keygenLines[6041]?=some text18 := by decide +kernel
theorem line19 : Pinned.keygenLines[6042]?=some text19 := by decide +kernel
theorem line20 : Pinned.keygenLines[6043]?=some text20 := by decide +kernel
theorem line21 : Pinned.keygenLines[6044]?=some text21 := by decide +kernel
theorem line22 : Pinned.keygenLines[6045]?=some text22 := by decide +kernel
theorem line23 : Pinned.keygenLines[6046]?=some text23 := by decide +kernel
theorem line24 : Pinned.keygenLines[6047]?=some text24 := by decide +kernel
theorem line25 : Pinned.keygenLines[6048]?=some text25 := by decide +kernel
theorem line26 : Pinned.keygenLines[6049]?=some text26 := by decide +kernel
theorem line27 : Pinned.keygenLines[6050]?=some text27 := by decide +kernel
theorem line28 : Pinned.keygenLines[6051]?=some text28 := by decide +kernel
theorem line29 : Pinned.keygenLines[6052]?=some text29 := by decide +kernel
theorem line30 : Pinned.keygenLines[6053]?=some text30 := by decide +kernel
theorem line31 : Pinned.keygenLines[6054]?=some text31 := by decide +kernel
theorem line32 : Pinned.keygenLines[6055]?=some text32 := by decide +kernel
theorem line33 : Pinned.keygenLines[6056]?=some text33 := by decide +kernel
theorem line34 : Pinned.keygenLines[6057]?=some text34 := by decide +kernel
theorem line35 : Pinned.keygenLines[6058]?=some text35 := by decide +kernel
theorem line36 : Pinned.keygenLines[6059]?=some text36 := by decide +kernel
theorem line37 : Pinned.keygenLines[6060]?=some text37 := by decide +kernel
theorem line38 : Pinned.keygenLines[6061]?=some text38 := by decide +kernel
theorem line39 : Pinned.keygenLines[6062]?=some text39 := by decide +kernel
theorem line40 : Pinned.keygenLines[6063]?=some text40 := by decide +kernel
theorem line41 : Pinned.keygenLines[6064]?=some text41 := by decide +kernel
theorem line42 : Pinned.keygenLines[6065]?=some text42 := by decide +kernel
theorem line43 : Pinned.keygenLines[6066]?=some text43 := by decide +kernel
theorem line44 : Pinned.keygenLines[6067]?=some text44 := by decide +kernel
theorem line45 : Pinned.keygenLines[6068]?=some text45 := by decide +kernel
theorem line46 : Pinned.keygenLines[6069]?=some text46 := by decide +kernel
theorem line47 : Pinned.keygenLines[6070]?=some text47 := by decide +kernel
theorem line48 : Pinned.keygenLines[6071]?=some text48 := by decide +kernel
theorem line49 : Pinned.keygenLines[6072]?=some text49 := by decide +kernel
theorem line50 : Pinned.keygenLines[6073]?=some text50 := by decide +kernel
theorem line51 : Pinned.keygenLines[6074]?=some text51 := by decide +kernel
theorem line52 : Pinned.keygenLines[6075]?=some text52 := by decide +kernel
theorem line53 : Pinned.keygenLines[6076]?=some text53 := by decide +kernel
theorem line54 : Pinned.keygenLines[6077]?=some text54 := by decide +kernel
theorem line55 : Pinned.keygenLines[6078]?=some text55 := by decide +kernel
theorem line56 : Pinned.keygenLines[6079]?=some text56 := by decide +kernel
theorem line57 : Pinned.keygenLines[6080]?=some text57 := by decide +kernel
theorem line58 : Pinned.keygenLines[6081]?=some text58 := by decide +kernel
theorem line59 : Pinned.keygenLines[6082]?=some text59 := by decide +kernel
theorem line60 : Pinned.keygenLines[6083]?=some text60 := by decide +kernel
theorem line61 : Pinned.keygenLines[6084]?=some text61 := by decide +kernel
theorem line62 : Pinned.keygenLines[6085]?=some text62 := by decide +kernel
theorem line63 : Pinned.keygenLines[6086]?=some text63 := by decide +kernel
theorem line64 : Pinned.keygenLines[6087]?=some text64 := by decide +kernel
theorem line65 : Pinned.keygenLines[6088]?=some text65 := by decide +kernel
theorem line66 : Pinned.keygenLines[6089]?=some text66 := by decide +kernel
theorem line67 : Pinned.keygenLines[6090]?=some text67 := by decide +kernel
theorem line68 : Pinned.keygenLines[6091]?=some text68 := by decide +kernel
theorem line69 : Pinned.keygenLines[6092]?=some text69 := by decide +kernel
theorem line70 : Pinned.keygenLines[6093]?=some text70 := by decide +kernel
theorem line71 : Pinned.keygenLines[6094]?=some text71 := by decide +kernel
theorem line72 : Pinned.keygenLines[6095]?=some text72 := by decide +kernel
theorem line73 : Pinned.keygenLines[6096]?=some text73 := by decide +kernel
theorem line74 : Pinned.keygenLines[6097]?=some text74 := by decide +kernel
theorem line75 : Pinned.keygenLines[6098]?=some text75 := by decide +kernel
theorem line76 : Pinned.keygenLines[6099]?=some text76 := by decide +kernel
theorem line77 : Pinned.keygenLines[6100]?=some text77 := by decide +kernel
theorem line78 : Pinned.keygenLines[6101]?=some text78 := by decide +kernel
theorem line79 : Pinned.keygenLines[6102]?=some text79 := by decide +kernel
theorem line80 : Pinned.keygenLines[6103]?=some text80 := by decide +kernel
theorem line81 : Pinned.keygenLines[6104]?=some text81 := by decide +kernel
theorem line82 : Pinned.keygenLines[6105]?=some text82 := by decide +kernel
theorem line83 : Pinned.keygenLines[6106]?=some text83 := by decide +kernel
theorem line84 : Pinned.keygenLines[6107]?=some text84 := by decide +kernel
theorem line85 : Pinned.keygenLines[6108]?=some text85 := by decide +kernel
theorem line86 : Pinned.keygenLines[6109]?=some text86 := by decide +kernel
theorem bytes87 : (Pinned.keygenLines.drop 6110).take tail87.length=tail87 := rfl
theorem bytes86 : (Pinned.keygenLines.drop 6109).take tail86.length=tail86 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6109 text86 tail87 line86 bytes87
theorem bytes85 : (Pinned.keygenLines.drop 6108).take tail85.length=tail85 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6108 text85 tail86 line85 bytes86
theorem bytes84 : (Pinned.keygenLines.drop 6107).take tail84.length=tail84 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6107 text84 tail85 line84 bytes85
theorem bytes83 : (Pinned.keygenLines.drop 6106).take tail83.length=tail83 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6106 text83 tail84 line83 bytes84
theorem bytes82 : (Pinned.keygenLines.drop 6105).take tail82.length=tail82 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6105 text82 tail83 line82 bytes83
theorem bytes81 : (Pinned.keygenLines.drop 6104).take tail81.length=tail81 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6104 text81 tail82 line81 bytes82
theorem bytes80 : (Pinned.keygenLines.drop 6103).take tail80.length=tail80 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6103 text80 tail81 line80 bytes81
theorem bytes79 : (Pinned.keygenLines.drop 6102).take tail79.length=tail79 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6102 text79 tail80 line79 bytes80
theorem bytes78 : (Pinned.keygenLines.drop 6101).take tail78.length=tail78 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6101 text78 tail79 line78 bytes79
theorem bytes77 : (Pinned.keygenLines.drop 6100).take tail77.length=tail77 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6100 text77 tail78 line77 bytes78
theorem bytes76 : (Pinned.keygenLines.drop 6099).take tail76.length=tail76 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6099 text76 tail77 line76 bytes77
theorem bytes75 : (Pinned.keygenLines.drop 6098).take tail75.length=tail75 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6098 text75 tail76 line75 bytes76
theorem bytes74 : (Pinned.keygenLines.drop 6097).take tail74.length=tail74 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6097 text74 tail75 line74 bytes75
theorem bytes73 : (Pinned.keygenLines.drop 6096).take tail73.length=tail73 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6096 text73 tail74 line73 bytes74
theorem bytes72 : (Pinned.keygenLines.drop 6095).take tail72.length=tail72 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6095 text72 tail73 line72 bytes73
theorem bytes71 : (Pinned.keygenLines.drop 6094).take tail71.length=tail71 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6094 text71 tail72 line71 bytes72
theorem bytes70 : (Pinned.keygenLines.drop 6093).take tail70.length=tail70 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6093 text70 tail71 line70 bytes71
theorem bytes69 : (Pinned.keygenLines.drop 6092).take tail69.length=tail69 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6092 text69 tail70 line69 bytes70
theorem bytes68 : (Pinned.keygenLines.drop 6091).take tail68.length=tail68 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6091 text68 tail69 line68 bytes69
theorem bytes67 : (Pinned.keygenLines.drop 6090).take tail67.length=tail67 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6090 text67 tail68 line67 bytes68
theorem bytes66 : (Pinned.keygenLines.drop 6089).take tail66.length=tail66 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6089 text66 tail67 line66 bytes67
theorem bytes65 : (Pinned.keygenLines.drop 6088).take tail65.length=tail65 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6088 text65 tail66 line65 bytes66
theorem bytes64 : (Pinned.keygenLines.drop 6087).take tail64.length=tail64 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6087 text64 tail65 line64 bytes65
theorem bytes63 : (Pinned.keygenLines.drop 6086).take tail63.length=tail63 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6086 text63 tail64 line63 bytes64
theorem bytes62 : (Pinned.keygenLines.drop 6085).take tail62.length=tail62 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6085 text62 tail63 line62 bytes63
theorem bytes61 : (Pinned.keygenLines.drop 6084).take tail61.length=tail61 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6084 text61 tail62 line61 bytes62
theorem bytes60 : (Pinned.keygenLines.drop 6083).take tail60.length=tail60 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6083 text60 tail61 line60 bytes61
theorem bytes59 : (Pinned.keygenLines.drop 6082).take tail59.length=tail59 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6082 text59 tail60 line59 bytes60
theorem bytes58 : (Pinned.keygenLines.drop 6081).take tail58.length=tail58 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6081 text58 tail59 line58 bytes59
theorem bytes57 : (Pinned.keygenLines.drop 6080).take tail57.length=tail57 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6080 text57 tail58 line57 bytes58
theorem bytes56 : (Pinned.keygenLines.drop 6079).take tail56.length=tail56 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6079 text56 tail57 line56 bytes57
theorem bytes55 : (Pinned.keygenLines.drop 6078).take tail55.length=tail55 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6078 text55 tail56 line55 bytes56
theorem bytes54 : (Pinned.keygenLines.drop 6077).take tail54.length=tail54 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6077 text54 tail55 line54 bytes55
theorem bytes53 : (Pinned.keygenLines.drop 6076).take tail53.length=tail53 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6076 text53 tail54 line53 bytes54
theorem bytes52 : (Pinned.keygenLines.drop 6075).take tail52.length=tail52 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6075 text52 tail53 line52 bytes53
theorem bytes51 : (Pinned.keygenLines.drop 6074).take tail51.length=tail51 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6074 text51 tail52 line51 bytes52
theorem bytes50 : (Pinned.keygenLines.drop 6073).take tail50.length=tail50 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6073 text50 tail51 line50 bytes51
theorem bytes49 : (Pinned.keygenLines.drop 6072).take tail49.length=tail49 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6072 text49 tail50 line49 bytes50
theorem bytes48 : (Pinned.keygenLines.drop 6071).take tail48.length=tail48 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6071 text48 tail49 line48 bytes49
theorem bytes47 : (Pinned.keygenLines.drop 6070).take tail47.length=tail47 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6070 text47 tail48 line47 bytes48
theorem bytes46 : (Pinned.keygenLines.drop 6069).take tail46.length=tail46 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6069 text46 tail47 line46 bytes47
theorem bytes45 : (Pinned.keygenLines.drop 6068).take tail45.length=tail45 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6068 text45 tail46 line45 bytes46
theorem bytes44 : (Pinned.keygenLines.drop 6067).take tail44.length=tail44 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6067 text44 tail45 line44 bytes45
theorem bytes43 : (Pinned.keygenLines.drop 6066).take tail43.length=tail43 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6066 text43 tail44 line43 bytes44
theorem bytes42 : (Pinned.keygenLines.drop 6065).take tail42.length=tail42 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6065 text42 tail43 line42 bytes43
theorem bytes41 : (Pinned.keygenLines.drop 6064).take tail41.length=tail41 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6064 text41 tail42 line41 bytes42
theorem bytes40 : (Pinned.keygenLines.drop 6063).take tail40.length=tail40 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6063 text40 tail41 line40 bytes41
theorem bytes39 : (Pinned.keygenLines.drop 6062).take tail39.length=tail39 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6062 text39 tail40 line39 bytes40
theorem bytes38 : (Pinned.keygenLines.drop 6061).take tail38.length=tail38 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6061 text38 tail39 line38 bytes39
theorem bytes37 : (Pinned.keygenLines.drop 6060).take tail37.length=tail37 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6060 text37 tail38 line37 bytes38
theorem bytes36 : (Pinned.keygenLines.drop 6059).take tail36.length=tail36 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6059 text36 tail37 line36 bytes37
theorem bytes35 : (Pinned.keygenLines.drop 6058).take tail35.length=tail35 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6058 text35 tail36 line35 bytes36
theorem bytes34 : (Pinned.keygenLines.drop 6057).take tail34.length=tail34 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6057 text34 tail35 line34 bytes35
theorem bytes33 : (Pinned.keygenLines.drop 6056).take tail33.length=tail33 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6056 text33 tail34 line33 bytes34
theorem bytes32 : (Pinned.keygenLines.drop 6055).take tail32.length=tail32 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6055 text32 tail33 line32 bytes33
theorem bytes31 : (Pinned.keygenLines.drop 6054).take tail31.length=tail31 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6054 text31 tail32 line31 bytes32
theorem bytes30 : (Pinned.keygenLines.drop 6053).take tail30.length=tail30 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6053 text30 tail31 line30 bytes31
theorem bytes29 : (Pinned.keygenLines.drop 6052).take tail29.length=tail29 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6052 text29 tail30 line29 bytes30
theorem bytes28 : (Pinned.keygenLines.drop 6051).take tail28.length=tail28 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6051 text28 tail29 line28 bytes29
theorem bytes27 : (Pinned.keygenLines.drop 6050).take tail27.length=tail27 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6050 text27 tail28 line27 bytes28
theorem bytes26 : (Pinned.keygenLines.drop 6049).take tail26.length=tail26 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6049 text26 tail27 line26 bytes27
theorem bytes25 : (Pinned.keygenLines.drop 6048).take tail25.length=tail25 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6048 text25 tail26 line25 bytes26
theorem bytes24 : (Pinned.keygenLines.drop 6047).take tail24.length=tail24 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6047 text24 tail25 line24 bytes25
theorem bytes23 : (Pinned.keygenLines.drop 6046).take tail23.length=tail23 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6046 text23 tail24 line23 bytes24
theorem bytes22 : (Pinned.keygenLines.drop 6045).take tail22.length=tail22 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6045 text22 tail23 line22 bytes23
theorem bytes21 : (Pinned.keygenLines.drop 6044).take tail21.length=tail21 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6044 text21 tail22 line21 bytes22
theorem bytes20 : (Pinned.keygenLines.drop 6043).take tail20.length=tail20 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6043 text20 tail21 line20 bytes21
theorem bytes19 : (Pinned.keygenLines.drop 6042).take tail19.length=tail19 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6042 text19 tail20 line19 bytes20
theorem bytes18 : (Pinned.keygenLines.drop 6041).take tail18.length=tail18 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6041 text18 tail19 line18 bytes19
theorem bytes17 : (Pinned.keygenLines.drop 6040).take tail17.length=tail17 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6040 text17 tail18 line17 bytes18
theorem bytes16 : (Pinned.keygenLines.drop 6039).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6039 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 6038).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6038 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 6037).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6037 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 6036).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6036 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 6035).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6035 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 6034).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6034 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 6033).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6033 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 6032).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6032 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 6031).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6031 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 6030).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6030 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 6029).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6029 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 6028).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6028 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 6027).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6027 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 6026).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6026 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 6025).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6025 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 6024).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6024 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 6023).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6023 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 6023).take 87=lines := bytes0
def group0 : List String := [text0,text1,text2,text3,text4,text5,text6,text7,text8,text9,text10,text11,text12,text13,text14,text15,text16,text17,text18,text19,text20,text21,text22,text23,text24,text25,text26,text27,text28,text29]
def words0 : List B20.C.Token := [].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text30]
def words1 : List B20.C.Token := ["if","(","full",")","{"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text31]
def words2 : List B20.C.Token := ["uint32_t","R3",";"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text32]
def words3 : List B20.C.Token := ["uint64_t","v2",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text33]
def words4 : List B20.C.Token := [].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text34]
def words5 : List B20.C.Token := ["R3","=","modp_montymul","(","R2",",","R2",",","p",",","p0i",")",";"].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text35]
def words6 : List B20.C.Token := ["for","(","v","=","0",",","v2","=","0",",","x","=","Ft","+","u",",","y","=","Gt","+","u",";","v","<","n",";"].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text36]
def words7 : List B20.C.Token := ["v","+=","3",",","v2","++",",","x","+=","3","*","llen",",","y","+=","3","*","llen",")"].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text37]
def words8 : List B20.C.Token := ["{"].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text38]
def words9 : List B20.C.Token := ["uint32_t","ftA",",","ftB",",","ftC",",","gtA",",","gtB",",","gtC",";"].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text39]
def words10 : List B20.C.Token := ["uint32_t","mFp",",","mGp",";"].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def group11 : List String := [text40]
def words11 : List B20.C.Token := [].map String.toList
theorem lex11 : KeygenLexicalChunks.Checked group11 words11 := by
  constructor <;> decide +kernel
def group12 : List String := [text41]
def words12 : List B20.C.Token := ["ftA","=","fx","[","v","+","0","]",";"].map String.toList
theorem lex12 : KeygenLexicalChunks.Checked group12 words12 := by
  constructor <;> decide +kernel
def group13 : List String := [text42]
def words13 : List B20.C.Token := ["ftB","=","fx","[","v","+","1","]",";"].map String.toList
theorem lex13 : KeygenLexicalChunks.Checked group13 words13 := by
  constructor <;> decide +kernel
def group14 : List String := [text43]
def words14 : List B20.C.Token := ["ftC","=","fx","[","v","+","2","]",";"].map String.toList
theorem lex14 : KeygenLexicalChunks.Checked group14 words14 := by
  constructor <;> decide +kernel
def group15 : List String := [text44]
def words15 : List B20.C.Token := ["gtA","=","gx","[","v","+","0","]",";"].map String.toList
theorem lex15 : KeygenLexicalChunks.Checked group15 words15 := by
  constructor <;> decide +kernel
def group16 : List String := [text45]
def words16 : List B20.C.Token := ["gtB","=","gx","[","v","+","1","]",";"].map String.toList
theorem lex16 : KeygenLexicalChunks.Checked group16 words16 := by
  constructor <;> decide +kernel
def group17 : List String := [text46]
def words17 : List B20.C.Token := ["gtC","=","gx","[","v","+","2","]",";"].map String.toList
theorem lex17 : KeygenLexicalChunks.Checked group17 words17 := by
  constructor <;> decide +kernel
def group18 : List String := [text47]
def words18 : List B20.C.Token := ["mFp","=","modp_montymul","(","Fp","[","v2","]",",","R3",",","p",",","p0i",")",";"].map String.toList
theorem lex18 : KeygenLexicalChunks.Checked group18 words18 := by
  constructor <;> decide +kernel
def group19 : List String := [text48]
def words19 : List B20.C.Token := ["mGp","=","modp_montymul","(","Gp","[","v2","]",",","R3",",","p",",","p0i",")",";"].map String.toList
theorem lex19 : KeygenLexicalChunks.Checked group19 words19 := by
  constructor <;> decide +kernel
def group20 : List String := [text49]
def words20 : List B20.C.Token := ["x","[","0","]","=","modp_montymul","(","mFp",","].map String.toList
theorem lex20 : KeygenLexicalChunks.Checked group20 words20 := by
  constructor <;> decide +kernel
def group21 : List String := [text50]
def words21 : List B20.C.Token := ["modp_montymul","(","gtB",",","gtC",",","p",",","p0i",")",","].map String.toList
theorem lex21 : KeygenLexicalChunks.Checked group21 words21 := by
  constructor <;> decide +kernel
def group22 : List String := [text51]
def words22 : List B20.C.Token := ["p",",","p0i",")",";"].map String.toList
theorem lex22 : KeygenLexicalChunks.Checked group22 words22 := by
  constructor <;> decide +kernel
def group23 : List String := [text52]
def words23 : List B20.C.Token := ["x","[","llen","]","=","modp_montymul","(","mFp",","].map String.toList
theorem lex23 : KeygenLexicalChunks.Checked group23 words23 := by
  constructor <;> decide +kernel
def group24 : List String := [text53]
def words24 : List B20.C.Token := ["modp_montymul","(","gtC",",","gtA",",","p",",","p0i",")",","].map String.toList
theorem lex24 : KeygenLexicalChunks.Checked group24 words24 := by
  constructor <;> decide +kernel
def group25 : List String := [text54]
def words25 : List B20.C.Token := ["p",",","p0i",")",";"].map String.toList
theorem lex25 : KeygenLexicalChunks.Checked group25 words25 := by
  constructor <;> decide +kernel
def group26 : List String := [text55]
def words26 : List B20.C.Token := ["x","[","2","*","llen","]","=","modp_montymul","(","mFp",","].map String.toList
theorem lex26 : KeygenLexicalChunks.Checked group26 words26 := by
  constructor <;> decide +kernel
def group27 : List String := [text56]
def words27 : List B20.C.Token := ["modp_montymul","(","gtA",",","gtB",",","p",",","p0i",")",","].map String.toList
theorem lex27 : KeygenLexicalChunks.Checked group27 words27 := by
  constructor <;> decide +kernel
def group28 : List String := [text57]
def words28 : List B20.C.Token := ["p",",","p0i",")",";"].map String.toList
theorem lex28 : KeygenLexicalChunks.Checked group28 words28 := by
  constructor <;> decide +kernel
def group29 : List String := [text58]
def words29 : List B20.C.Token := ["y","[","0","]","=","modp_montymul","(","mGp",","].map String.toList
theorem lex29 : KeygenLexicalChunks.Checked group29 words29 := by
  constructor <;> decide +kernel
def group30 : List String := [text59]
def words30 : List B20.C.Token := ["modp_montymul","(","ftB",",","ftC",",","p",",","p0i",")",","].map String.toList
theorem lex30 : KeygenLexicalChunks.Checked group30 words30 := by
  constructor <;> decide +kernel
def group31 : List String := [text60]
def words31 : List B20.C.Token := ["p",",","p0i",")",";"].map String.toList
theorem lex31 : KeygenLexicalChunks.Checked group31 words31 := by
  constructor <;> decide +kernel
def group32 : List String := [text61]
def words32 : List B20.C.Token := ["y","[","llen","]","=","modp_montymul","(","mGp",","].map String.toList
theorem lex32 : KeygenLexicalChunks.Checked group32 words32 := by
  constructor <;> decide +kernel
def group33 : List String := [text62]
def words33 : List B20.C.Token := ["modp_montymul","(","ftC",",","ftA",",","p",",","p0i",")",","].map String.toList
theorem lex33 : KeygenLexicalChunks.Checked group33 words33 := by
  constructor <;> decide +kernel
def group34 : List String := [text63]
def words34 : List B20.C.Token := ["p",",","p0i",")",";"].map String.toList
theorem lex34 : KeygenLexicalChunks.Checked group34 words34 := by
  constructor <;> decide +kernel
def group35 : List String := [text64]
def words35 : List B20.C.Token := ["y","[","2","*","llen","]","=","modp_montymul","(","mGp",","].map String.toList
theorem lex35 : KeygenLexicalChunks.Checked group35 words35 := by
  constructor <;> decide +kernel
def group36 : List String := [text65]
def words36 : List B20.C.Token := ["modp_montymul","(","ftA",",","ftB",",","p",",","p0i",")",","].map String.toList
theorem lex36 : KeygenLexicalChunks.Checked group36 words36 := by
  constructor <;> decide +kernel
def group37 : List String := [text66]
def words37 : List B20.C.Token := ["p",",","p0i",")",";"].map String.toList
theorem lex37 : KeygenLexicalChunks.Checked group37 words37 := by
  constructor <;> decide +kernel
def group38 : List String := [text67]
def words38 : List B20.C.Token := ["}"].map String.toList
theorem lex38 : KeygenLexicalChunks.Checked group38 words38 := by
  constructor <;> decide +kernel
def group39 : List String := [text68]
def words39 : List B20.C.Token := ["}","else","{"].map String.toList
theorem lex39 : KeygenLexicalChunks.Checked group39 words39 := by
  constructor <;> decide +kernel
def group40 : List String := [text69]
def words40 : List B20.C.Token := ["for","(","v","=","0",",","x","=","Ft","+","u",",","y","=","Gt","+","u",";","v","<","hn",";"].map String.toList
theorem lex40 : KeygenLexicalChunks.Checked group40 words40 := by
  constructor <;> decide +kernel
def group41 : List String := [text70]
def words41 : List B20.C.Token := ["v","++",",","x","+=","(","llen","<<","1",")",",","y","+=","(","llen","<<","1",")",")"].map String.toList
theorem lex41 : KeygenLexicalChunks.Checked group41 words41 := by
  constructor <;> decide +kernel
def group42 : List String := [text71]
def words42 : List B20.C.Token := ["{"].map String.toList
theorem lex42 : KeygenLexicalChunks.Checked group42 words42 := by
  constructor <;> decide +kernel
def group43 : List String := [text72]
def words43 : List B20.C.Token := ["uint32_t","ftA",",","ftB",",","gtA",",","gtB",";"].map String.toList
theorem lex43 : KeygenLexicalChunks.Checked group43 words43 := by
  constructor <;> decide +kernel
def group44 : List String := [text73]
def words44 : List B20.C.Token := ["uint32_t","mFp",",","mGp",";"].map String.toList
theorem lex44 : KeygenLexicalChunks.Checked group44 words44 := by
  constructor <;> decide +kernel
def group45 : List String := [text74]
def words45 : List B20.C.Token := [].map String.toList
theorem lex45 : KeygenLexicalChunks.Checked group45 words45 := by
  constructor <;> decide +kernel
def group46 : List String := [text75]
def words46 : List B20.C.Token := ["ftA","=","fx","[","(","v","<<","1",")","+","0","]",";"].map String.toList
theorem lex46 : KeygenLexicalChunks.Checked group46 words46 := by
  constructor <;> decide +kernel
def group47 : List String := [text76]
def words47 : List B20.C.Token := ["ftB","=","fx","[","(","v","<<","1",")","+","1","]",";"].map String.toList
theorem lex47 : KeygenLexicalChunks.Checked group47 words47 := by
  constructor <;> decide +kernel
def group48 : List String := [text77]
def words48 : List B20.C.Token := ["gtA","=","gx","[","(","v","<<","1",")","+","0","]",";"].map String.toList
theorem lex48 : KeygenLexicalChunks.Checked group48 words48 := by
  constructor <;> decide +kernel
def group49 : List String := [text78]
def words49 : List B20.C.Token := ["gtB","=","gx","[","(","v","<<","1",")","+","1","]",";"].map String.toList
theorem lex49 : KeygenLexicalChunks.Checked group49 words49 := by
  constructor <;> decide +kernel
def group50 : List String := [text79]
def words50 : List B20.C.Token := ["mFp","=","modp_montymul","(","Fp","[","v","]",",","R2",",","p",",","p0i",")",";"].map String.toList
theorem lex50 : KeygenLexicalChunks.Checked group50 words50 := by
  constructor <;> decide +kernel
def group51 : List String := [text80]
def words51 : List B20.C.Token := ["mGp","=","modp_montymul","(","Gp","[","v","]",",","R2",",","p",",","p0i",")",";"].map String.toList
theorem lex51 : KeygenLexicalChunks.Checked group51 words51 := by
  constructor <;> decide +kernel
def group52 : List String := [text81]
def words52 : List B20.C.Token := ["x","[","0","]","=","modp_montymul","(","gtB",",","mFp",",","p",",","p0i",")",";"].map String.toList
theorem lex52 : KeygenLexicalChunks.Checked group52 words52 := by
  constructor <;> decide +kernel
def group53 : List String := [text82]
def words53 : List B20.C.Token := ["x","[","llen","]","=","modp_montymul","(","gtA",",","mFp",",","p",",","p0i",")",";"].map String.toList
theorem lex53 : KeygenLexicalChunks.Checked group53 words53 := by
  constructor <;> decide +kernel
def group54 : List String := [text83]
def words54 : List B20.C.Token := ["y","[","0","]","=","modp_montymul","(","ftB",",","mGp",",","p",",","p0i",")",";"].map String.toList
theorem lex54 : KeygenLexicalChunks.Checked group54 words54 := by
  constructor <;> decide +kernel
def group55 : List String := [text84]
def words55 : List B20.C.Token := ["y","[","llen","]","=","modp_montymul","(","ftA",",","mGp",",","p",",","p0i",")",";"].map String.toList
theorem lex55 : KeygenLexicalChunks.Checked group55 words55 := by
  constructor <;> decide +kernel
def group56 : List String := [text85]
def words56 : List B20.C.Token := ["}"].map String.toList
theorem lex56 : KeygenLexicalChunks.Checked group56 words56 := by
  constructor <;> decide +kernel
def group57 : List String := [text86]
def words57 : List B20.C.Token := ["}"].map String.toList
theorem lex57 : KeygenLexicalChunks.Checked group57 words57 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10,group11,group12,group13,group14,group15,group16,group17,group18,group19,group20,group21,group22,group23,group24,group25,group26,group27,group28,group29,group30,group31,group32,group33,group34,group35,group36,group37,group38,group39,group40,group41,group42,group43,group44,group45,group46,group47,group48,group49,group50,group51,group52,group53,group54,group55,group56,group57]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10,words11,words12,words13,words14,words15,words16,words17,words18,words19,words20,words21,words22,words23,words24,words25,words26,words27,words28,words29,words30,words31,words32,words33,words34,words35,words36,words37,words38,words39,words40,words41,words42,words43,words44,words45,words46,words47,words48,words49,words50,words51,words52,words53,words54,words55,words56,words57]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.cons lex11 (List.Forall₂.cons lex12 (List.Forall₂.cons lex13 (List.Forall₂.cons lex14 (List.Forall₂.cons lex15 (List.Forall₂.cons lex16 (List.Forall₂.cons lex17 (List.Forall₂.cons lex18 (List.Forall₂.cons lex19 (List.Forall₂.cons lex20 (List.Forall₂.cons lex21 (List.Forall₂.cons lex22 (List.Forall₂.cons lex23 (List.Forall₂.cons lex24 (List.Forall₂.cons lex25 (List.Forall₂.cons lex26 (List.Forall₂.cons lex27 (List.Forall₂.cons lex28 (List.Forall₂.cons lex29 (List.Forall₂.cons lex30 (List.Forall₂.cons lex31 (List.Forall₂.cons lex32 (List.Forall₂.cons lex33 (List.Forall₂.cons lex34 (List.Forall₂.cons lex35 (List.Forall₂.cons lex36 (List.Forall₂.cons lex37 (List.Forall₂.cons lex38 (List.Forall₂.cons lex39 (List.Forall₂.cons lex40 (List.Forall₂.cons lex41 (List.Forall₂.cons lex42 (List.Forall₂.cons lex43 (List.Forall₂.cons lex44 (List.Forall₂.cons lex45 (List.Forall₂.cons lex46 (List.Forall₂.cons lex47 (List.Forall₂.cons lex48 (List.Forall₂.cons lex49 (List.Forall₂.cons lex50 (List.Forall₂.cons lex51 (List.Forall₂.cons lex52 (List.Forall₂.cons lex53 (List.Forall₂.cons lex54 (List.Forall₂.cons lex55 (List.Forall₂.cons lex56 (List.Forall₂.cons lex57 (List.Forall₂.nil))))))))))))))))))))))))))))))))))))))))))))))))))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 6023).take 87) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensLift4
