import Source3.KeygenAttemptPin
import Source3.KeygenAttemptFft
import Source3.KeygenAttemptNorm
import Source3.ShakePointFrame
import Source3.KeygenSamplerContext
import Source3.KeygenPublicScalar
import Source3.KeygenPublicWord
import Source3.KeygenPublicExec
import Source3.KeygenPublicParser
import Source3.KeygenPublicFrame
import Source3.KeygenPublicSource
import Source3.KeygenPublicStability
import Source3.KeygenAttemptSlots
import Source3.KeygenAttemptMaterial
import Source3.KeygenRootCaller
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated by tools/keygen_attempt_audit_source.py. Internal audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenAttemptPin,
      ["internalLines","vrfyLines"]),
    (`FT1536.Source3.KeygenAttemptFft,
      ["text","header","parsed","code","params","writable","audit","alias_source","source_audit","source_parsed","arguments","Call","frame","stable","slots"]),
    (`FT1536.Source3.KeygenAttemptNorm,
      ["types","writable","expand","signed_long_literal","parse","boundLines","gsHeadLines","gsTailLines","boundParsed","headParsed","tailParsed","boundCode","headCode","tailCode","bound_selection","bound_audit","head_audit","tail_audit","parsed_checked","bound_checked","head_checked","tail_checked","scaleSignatures","scaleParsed","scaleCode","scale_source","scale_first_checked","scale_second_checked","gateLines","gs_selection","same_gate","GS","Exec","Protected","Frame","search_frame","scale_frame","compose","tables_after","gs_frame","raw_checked","raw_frame","frame","bytes","material","gs_stable","raw_stable","stable"]),
    (`FT1536.Source3.ShakePointFrame,
      ["Pointers","Same","trans","address","bound","store8","store64","encode","invoke","process","source","call","rng"]),
    (`FT1536.Source3.KeygenSamplerContext,
      ["rng","Resolve","Call","actual_calls","address_source","rng_layout","OutsideRng","fields_outside","refill","inner","outer","sampler","context","profile","two_calls"]),
    (`FT1536.Source3.KeygenPublicScalar,
      ["constants","expand","constants_source","Kind","all","name","range","params","lines","header","expectedHeader","parsed","code","scalarOnly","exprOnly","only","callees","audit","conv_audit","add_audit","sub_audit","half_audit","mul_audit","square_audit","divB_audit","divT_audit","rev_audit","all_audit","parsed_source","empty","Body","IsLeaf","Leaf","Square","Call"]),
    (`FT1536.Source3.KeygenPublicWord,
      ["scalar","Address","Eval","narrow","narrowed_store","Bind","bind_heap"]),
    (`FT1536.Source3.KeygenPublicExec,
      ["Stmt","chain","Function","Program","allocated","localPointer","localEntry","localExit","Exec"]),
    (`FT1536.Source3.KeygenPublicParser,
      ["Types","Signatures","assignment","clause","clauses","simple","declarations","count","constant_counts","arrays","statement","body"]),
    (`FT1536.Source3.KeygenPublicFrame,
      ["Signatures","Permissions","only","Outside","Tables","Frame","address","bind","bind_tables","compose","live_after","tables_after","body"]),
    (`FT1536.Source3.KeygenPublicSource,
      ["Kind","all","name","range","params","signed","result","Header","parameter","parameters","header","find","signatures","types","parsed","code","function","program","writable","permissions","audit","generate_audit","forwardB_audit","inverseB_audit","forwardT_audit","inverseT_audit","forward_audit","inverse_audit","public_audit","all_audit","code_checked","aligned","closed","arguments","Call","caller_checked","frame","material"]),
    (`FT1536.Source3.KeygenPublicStability,
      ["body","call"]),
    (`FT1536.Source3.KeygenAttemptSlots,
      ["Slots","trans","restore","arrayOnly","array","procedureOnly","procedure","searchOnly","search","bound_checked","raw_checked","head_checked","tail_checked","raw","gs","norm"]),
    (`FT1536.Source3.KeygenAttemptMaterial,
      ["resultant_slots","resultant_stable","resultants","sampler_slots","publicSelected","public_gate_source","PublicGate","Exec","Entry","protected_slots","public_slots","sampling_metadata","Material","sampled_material","through_resultants","through_norm","material"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.KeygenRootCaller.Legal,
    ``FT1536.Source3.KeygenRootCaller.success,
    ``FT1536.Source3.KeygenSamplerCalls.Call,
    ``FT1536.Source3.KeygenSamplerCalls.two_calls,
    ``FT1536.Source3.KeygenResultantGate.Exec,
    ``FT1536.Source3.KeygenResultantGate.sampled_material,
    ``FT1536.Source3.KeygenNormFrame.Exec,
    ``FT1536.Source3.KeygenNormFrame.Gate,
    ``FT1536.Source3.KeygenSearchContext.Context,
    ``FT1536.Source3.KeygenSearchContext.ObjectLegal,
    ``FT1536.Source3.KeygenSearchContext.M0,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.KeygenMemoryStability.Stable,
    ``FT1536.Source3.C99ModularReference.GenExec,
    ``FT1536.Source3.C99ModularReference.bindParams,
    ``FT1536.Source3.C99NarrowReads.Load16,
    ``FT1536.Source3.C99NarrowReads.signedPromotion,
    ``FT1536.Source3.C99NarrowReads.unsignedPromotion,
    ``FT1536.Source3.KeygenSmallOutput.Store16,
    ``FT1536.Source3.ShakeExtractSource.Layout,
    ``FT1536.Source3.ShakeExtractSource.Exec,
    ``FT1536.Source3.ShakeExtractFrame.Call,
    ``FT1536.Source3.KeygenRngSource.Call,
    ``FT1536.Source3.C99ArrayReference.Bind,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../ATTEMPT_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.withFile "../ATTEMPT_AUDIT_ENTRIES.jsonl" .append fun stream =>
      stream.putStrLn rows.back!.compress
  IO.FS.writeFile "../ATTEMPT_AUDIT.json" (Lean.Json.arr rows |>.pretty)
