import Source3.KeygenSourceLines

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenTokenPinProbe
def text0 : String := "\t\tuint32_t p, p0i, R2;\n"
def text1 : String := "\t\tuint32_t *gm, *igm, *fx, *gx, *Fp, *Gp;\n"
def text2 : String := "\t\tsize_t v;\n"
def text3 : String := "\n"
def text4 : String := "\t\t/*\n"
def text5 : String := "\t\t * All computations are done modulo p.\n"
def text6 : String := "\t\t */\n"
def text7 : String := "\t\tp = primes[u].p;\n"
def text8 : String := "\t\tp0i = modp_ninv31(p);\n"
def text9 : String := "\t\tR2 = modp_R2(p, p0i);\n"
def text10 : String := "\n"
def text11 : String := "\t\t/*\n"
def text12 : String := "\t\t * If we processed slen words, then f and g have been\n"
def text13 : String := "\t\t * de-NTTized, and are in RNS; we can rebuild them.\n"
def text14 : String := "\t\t */\n"
def text15 : String := "\t\tif (u == slen) {\n"
def text16 : String := "\t\t\tzint_rebuild_CRT(ft, slen, slen, n, primes, 1, t1);\n"
def text17 : String := "\t\t\tzint_rebuild_CRT(gt, slen, slen, n, primes, 1, t1);\n"
def text18 : String := "\t\t}\n"
def text19 : String := "\n"
def text20 : String := "\t\tgm = t1;\n"
def text21 : String := "\t\tif (full) {\n"
def text22 : String := "\t\t\tigm = gm + ((size_t)1 << logn);\n"
def text23 : String := "\t\t\tfx = igm + ((size_t)1 << logn);\n"
def text24 : String := "\t\t} else {\n"
def text25 : String := "\t\t\tgm = t1;\n"
def text26 : String := "\t\t\tigm = gm + n;\n"
def text27 : String := "\t\t\tfx = igm + n;\n"
def text28 : String := "\t\t}\n"
def text29 : String := "\t\tgx = fx + n;\n"
def text30 : String := "\n"
def lines : List String := [text0,text1,text2,text3,text4,text5,text6,text7,text8,text9,text10,text11,text12,text13,text14,text15,text16,text17,text18,text19,text20,text21,text22,text23,text24,text25,text26,text27,text28,text29,text30]
theorem line0 : Pinned.keygenLines[5923]?=some text0 := by decide
theorem line1 : Pinned.keygenLines[5924]?=some text1 := by decide
theorem line2 : Pinned.keygenLines[5925]?=some text2 := by decide
theorem line3 : Pinned.keygenLines[5926]?=some text3 := by decide
theorem line4 : Pinned.keygenLines[5927]?=some text4 := by decide
theorem line5 : Pinned.keygenLines[5928]?=some text5 := by decide
theorem line6 : Pinned.keygenLines[5929]?=some text6 := by decide
theorem line7 : Pinned.keygenLines[5930]?=some text7 := by decide
theorem line8 : Pinned.keygenLines[5931]?=some text8 := by decide
theorem line9 : Pinned.keygenLines[5932]?=some text9 := by decide
theorem line10 : Pinned.keygenLines[5933]?=some text10 := by decide
theorem line11 : Pinned.keygenLines[5934]?=some text11 := by decide
theorem line12 : Pinned.keygenLines[5935]?=some text12 := by decide
theorem line13 : Pinned.keygenLines[5936]?=some text13 := by decide
theorem line14 : Pinned.keygenLines[5937]?=some text14 := by decide
theorem line15 : Pinned.keygenLines[5938]?=some text15 := by decide
theorem line16 : Pinned.keygenLines[5939]?=some text16 := by decide
theorem line17 : Pinned.keygenLines[5940]?=some text17 := by decide
theorem line18 : Pinned.keygenLines[5941]?=some text18 := by decide
theorem line19 : Pinned.keygenLines[5942]?=some text19 := by decide
theorem line20 : Pinned.keygenLines[5943]?=some text20 := by decide
theorem line21 : Pinned.keygenLines[5944]?=some text21 := by decide
theorem line22 : Pinned.keygenLines[5945]?=some text22 := by decide
theorem line23 : Pinned.keygenLines[5946]?=some text23 := by decide
theorem line24 : Pinned.keygenLines[5947]?=some text24 := by decide
theorem line25 : Pinned.keygenLines[5948]?=some text25 := by decide
theorem line26 : Pinned.keygenLines[5949]?=some text26 := by decide
theorem line27 : Pinned.keygenLines[5950]?=some text27 := by decide
theorem line28 : Pinned.keygenLines[5951]?=some text28 := by decide
theorem line29 : Pinned.keygenLines[5952]?=some text29 := by decide
theorem line30 : Pinned.keygenLines[5953]?=some text30 := by decide
theorem entries (i : Fin 31) : Pinned.keygenLines[5923+i.val]?=lines[i.val]? := by
  fin_cases i
  · exact line0
  · exact line1
  · exact line2
  · exact line3
  · exact line4
  · exact line5
  · exact line6
  · exact line7
  · exact line8
  · exact line9
  · exact line10
  · exact line11
  · exact line12
  · exact line13
  · exact line14
  · exact line15
  · exact line16
  · exact line17
  · exact line18
  · exact line19
  · exact line20
  · exact line21
  · exact line22
  · exact line23
  · exact line24
  · exact line25
  · exact line26
  · exact line27
  · exact line28
  · exact line29
  · exact line30
theorem bytes : (Pinned.keygenLines.drop 5923).take 31=lines :=
  KeygenSourceLines.slice Pinned.keygenLines lines 5923 entries
def tokenChunk0 : List B20.C.Token := ["uint32_t","p",",","p0i",",","R2",";","uint32_t","*","gm",",","*"].map String.toList
def tokenChunk1 : List B20.C.Token := ["igm",",","*","fx",",","*","gx",",","*","Fp",",","*"].map String.toList
def tokenChunk2 : List B20.C.Token := ["Gp",";","uint64_t","v",";","p","=","primes","[","u","]","."].map String.toList
def tokenChunk3 : List B20.C.Token := ["p",";","p0i","=","modp_ninv31","(","p",")",";","R2","=","modp_R2"].map String.toList
def tokenChunk4 : List B20.C.Token := ["(","p",",","p0i",")",";","if","(","u","==","slen",")"].map String.toList
def tokenChunk5 : List B20.C.Token := ["{","zint_rebuild_CRT","(","ft",",","slen",",","slen",",","n",",","primes"].map String.toList
def tokenChunk6 : List B20.C.Token := [",","1",",","t1",")",";","zint_rebuild_CRT","(","gt",",","slen",","].map String.toList
def tokenChunk7 : List B20.C.Token := ["slen",",","n",",","primes",",","1",",","t1",")",";","}"].map String.toList
def tokenChunk8 : List B20.C.Token := ["gm","=","t1",";","if","(","full",")","{","igm","=","gm"].map String.toList
def tokenChunk9 : List B20.C.Token := ["+","(","(","uint64_t",")","1","<<","logn",")",";","fx","="].map String.toList
def tokenChunk10 : List B20.C.Token := ["igm","+","(","(","uint64_t",")","1","<<","logn",")",";","}"].map String.toList
def tokenChunk11 : List B20.C.Token := ["else","{","gm","=","t1",";","igm","=","gm","+","n",";"].map String.toList
def tokenChunk12 : List B20.C.Token := ["fx","=","igm","+","n",";","}","gx","=","fx","+","n"].map String.toList
def tokenChunk13 : List B20.C.Token := [";","}"].map String.toList
def tokens : List B20.C.Token := tokenChunk0 ++ tokenChunk1 ++ tokenChunk2 ++ tokenChunk3 ++ tokenChunk4 ++ tokenChunk5 ++ tokenChunk6 ++ tokenChunk7 ++ tokenChunk8 ++ tokenChunk9 ++ tokenChunk10 ++ tokenChunk11 ++ tokenChunk12 ++ tokenChunk13
end FT1536.Source3.KeygenTokenPinProbe
