import Source3.KeygenRootSearch
import Source3.KeygenRootControl
import Source3.KeygenMemoryStability
import Source3.KeygenHelperStability
import Source3.KeygenSearchStability
import Source3.KeygenRootObjects
import Source3.KeygenRootValidationSource
import Source3.KeygenRootValidation
import Source3.KeygenRootSource
import Source3.KeygenRootCaller
import Source3.KeygenRootCoverage
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated by tools/keygen_root_audit_source.py. Internal audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenRootSearch,
      ["lines","tokens","lex","header","declarations_source","initialization_source","deepest_source","dispatch_source","loop_source","depth0_source","inactive_binary_source","partition","declared","logged","view","sizeExpr","ready","Start","start_m0","Kind","Call","Protected","call_slots","call_bytes","Gate","gate_frame","Post","post_frame","Loop","loop_frame","depthEntry","smallTest","DepthBody","depth_body_frame","Dispatch","dispatch_frame","Exec","frame","material","output_caller"]),
    (`FT1536.Source3.KeygenRootControl,
      ["load32_same_bytes","ternary_after","dispatch_enabled","Counter","decremented","post_exact","decremented_counter","Trace","depths","depths_step","loop_trace","m0_depths"]),
    (`FT1536.Source3.KeygenMemoryStability,
      ["Stable","refl","trans","store32","store64","copy","move","zero","steps","procedure","modular","word","receive","zint"]),
    (`FT1536.Source3.KeygenHelperStability,
      ["compose","level_call","level","binary","binary_call","make_top","make","top","top_call","poly","scaled_call","quadratic","sub_ntt"]),
    (`FT1536.Source3.KeygenSearchStability,
      ["deepest","small_to_fp","search","intermediate_body","intermediate_call","intermediate","root_call","gate","loop","dispatch","root"]),
    (`FT1536.Source3.KeygenRootObjects,
      ["load64","prime","size_table","rev_table","scratch","search_profile","store16","small","small_call","evaluated","gate","gate_slots"]),
    (`FT1536.Source3.KeygenRootValidationSource,
      ["uint32_cast","aliases","selected","primed","ready","prepare_source","generation_source","transform_dispatch","transform_inactive","close","Prepare","genArgs","returned","Exec","first_read","prepared","generator_entry"]),
    (`FT1536.Source3.KeygenRootValidation,
      ["arrays","Entry","ready_inputs","ready_caller","validation","checked"]),
    (`FT1536.Source3.KeygenRootSource,
      ["Exec","Entry","suffix_entry","success","params","arguments","Call","slots"]),
    (`FT1536.Source3.KeygenRootCaller,
      ["booleanReturns","BooleanFlow","modular_flow","target_boolean","root_flow","return_one","Legal","bound","bind_exact","bound_entry","success"]),
    (`FT1536.Source3.KeygenRootCoverage,
      ["complete_body","mkn_source","mkn_expansion","caller_source","caller_arguments"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.KeygenSolverEquation.Bounds,
    ``FT1536.Source3.KeygenSolverEquation.Equation,
    ``FT1536.Source3.KeygenDeepestSource.Call,
    ``FT1536.Source3.KeygenIntermediateSource.Call,
    ``FT1536.Source3.KeygenDepth0Call.Call,
    ``FT1536.Source3.KeygenDepth0Call.MemberGate,
    ``FT1536.Source3.KeygenOutputGateSource.Exec,
    ``FT1536.Source3.KeygenOutputGateValidation.Validation,
    ``FT1536.Source3.KeygenOutputGateValidation.gate_validated,
    ``FT1536.Source3.KeygenSearchContext.Context,
    ``FT1536.Source3.KeygenSearchContext.ReadLogn,
    ``FT1536.Source3.KeygenSearchContext.ReadTernary,
    ``FT1536.Source3.KeygenSearchContext.ReadTmp,
    ``FT1536.Source3.KeygenStaticTables.PrimeObject,
    ``FT1536.Source3.KeygenMkgm3RevMemory.SourceTable,
    ``FT1536.Source3.KeygenMkgm3Layout.Legal,
    ``FT1536.Source3.KeygenMkgm3.Entry,
    ``FT1536.Source3.KeygenResidueProgram.source_bound,
    ``FT1536.Source3.KeygenSolverNttCalls.source_bound,
    ``FT1536.Source3.KeygenCheckProgram.source_bound,
    ``FT1536.Source3.C99ArrayReference.Bind,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../ROOT_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.withFile "../ROOT_AUDIT_ENTRIES.jsonl" .append fun stream =>
      stream.putStrLn rows.back!.compress
  IO.FS.writeFile "../ROOT_AUDIT.json" (Lean.Json.arr rows |>.pretty)
