import Source3.KeygenMkgm3Indices

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000

/- Generated by generate_keygen_row_certificate.sage. Each bounded
   candidate below is checked by the kernel, including all indices. -/
namespace FT1536.Source3.KeygenMkgm3IndexCert
open KeygenMkgm3Indices

theorem chunk00 : ∀ i : Fin 16, IndexFact (0+i.val) := by decide
theorem chunk01 : ∀ i : Fin 16, IndexFact (16+i.val) := by decide
theorem chunk02 : ∀ i : Fin 16, IndexFact (32+i.val) := by decide
theorem chunk03 : ∀ i : Fin 16, IndexFact (48+i.val) := by decide
theorem chunk04 : ∀ i : Fin 16, IndexFact (64+i.val) := by decide
theorem chunk05 : ∀ i : Fin 16, IndexFact (80+i.val) := by decide
theorem chunk06 : ∀ i : Fin 16, IndexFact (96+i.val) := by decide
theorem chunk07 : ∀ i : Fin 16, IndexFact (112+i.val) := by decide
theorem chunk08 : ∀ i : Fin 16, IndexFact (128+i.val) := by decide
theorem chunk09 : ∀ i : Fin 16, IndexFact (144+i.val) := by decide
theorem chunk10 : ∀ i : Fin 16, IndexFact (160+i.val) := by decide
theorem chunk11 : ∀ i : Fin 16, IndexFact (176+i.val) := by decide
theorem chunk12 : ∀ i : Fin 16, IndexFact (192+i.val) := by decide
theorem chunk13 : ∀ i : Fin 16, IndexFact (208+i.val) := by decide
theorem chunk14 : ∀ i : Fin 16, IndexFact (224+i.val) := by decide
theorem chunk15 : ∀ i : Fin 16, IndexFact (240+i.val) := by decide
theorem chunk16 : ∀ i : Fin 16, IndexFact (256+i.val) := by decide
theorem chunk17 : ∀ i : Fin 16, IndexFact (272+i.val) := by decide
theorem chunk18 : ∀ i : Fin 16, IndexFact (288+i.val) := by decide
theorem chunk19 : ∀ i : Fin 16, IndexFact (304+i.val) := by decide
theorem chunk20 : ∀ i : Fin 16, IndexFact (320+i.val) := by decide
theorem chunk21 : ∀ i : Fin 16, IndexFact (336+i.val) := by decide
theorem chunk22 : ∀ i : Fin 16, IndexFact (352+i.val) := by decide
theorem chunk23 : ∀ i : Fin 16, IndexFact (368+i.val) := by decide
theorem chunk24 : ∀ i : Fin 16, IndexFact (384+i.val) := by decide
theorem chunk25 : ∀ i : Fin 16, IndexFact (400+i.val) := by decide
theorem chunk26 : ∀ i : Fin 16, IndexFact (416+i.val) := by decide
theorem chunk27 : ∀ i : Fin 16, IndexFact (432+i.val) := by decide
theorem chunk28 : ∀ i : Fin 16, IndexFact (448+i.val) := by decide
theorem chunk29 : ∀ i : Fin 16, IndexFact (464+i.val) := by decide
theorem chunk30 : ∀ i : Fin 16, IndexFact (480+i.val) := by decide
theorem chunk31 : ∀ i : Fin 16, IndexFact (496+i.val) := by decide
theorem chunk32 : ∀ i : Fin 16, IndexFact (512+i.val) := by decide
theorem chunk33 : ∀ i : Fin 16, IndexFact (528+i.val) := by decide
theorem chunk34 : ∀ i : Fin 16, IndexFact (544+i.val) := by decide
theorem chunk35 : ∀ i : Fin 16, IndexFact (560+i.val) := by decide
theorem chunk36 : ∀ i : Fin 16, IndexFact (576+i.val) := by decide
theorem chunk37 : ∀ i : Fin 16, IndexFact (592+i.val) := by decide
theorem chunk38 : ∀ i : Fin 16, IndexFact (608+i.val) := by decide
theorem chunk39 : ∀ i : Fin 16, IndexFact (624+i.val) := by decide
theorem chunk40 : ∀ i : Fin 16, IndexFact (640+i.val) := by decide
theorem chunk41 : ∀ i : Fin 16, IndexFact (656+i.val) := by decide
theorem chunk42 : ∀ i : Fin 16, IndexFact (672+i.val) := by decide
theorem chunk43 : ∀ i : Fin 16, IndexFact (688+i.val) := by decide
theorem chunk44 : ∀ i : Fin 16, IndexFact (704+i.val) := by decide
theorem chunk45 : ∀ i : Fin 16, IndexFact (720+i.val) := by decide
theorem chunk46 : ∀ i : Fin 16, IndexFact (736+i.val) := by decide
theorem chunk47 : ∀ i : Fin 16, IndexFact (752+i.val) := by decide
theorem chunk48 : ∀ i : Fin 16, IndexFact (768+i.val) := by decide
theorem chunk49 : ∀ i : Fin 16, IndexFact (784+i.val) := by decide
theorem chunk50 : ∀ i : Fin 16, IndexFact (800+i.val) := by decide
theorem chunk51 : ∀ i : Fin 16, IndexFact (816+i.val) := by decide
theorem chunk52 : ∀ i : Fin 16, IndexFact (832+i.val) := by decide
theorem chunk53 : ∀ i : Fin 16, IndexFact (848+i.val) := by decide
theorem chunk54 : ∀ i : Fin 16, IndexFact (864+i.val) := by decide
theorem chunk55 : ∀ i : Fin 16, IndexFact (880+i.val) := by decide
theorem chunk56 : ∀ i : Fin 16, IndexFact (896+i.val) := by decide
theorem chunk57 : ∀ i : Fin 16, IndexFact (912+i.val) := by decide
theorem chunk58 : ∀ i : Fin 16, IndexFact (928+i.val) := by decide
theorem chunk59 : ∀ i : Fin 16, IndexFact (944+i.val) := by decide
theorem chunk60 : ∀ i : Fin 16, IndexFact (960+i.val) := by decide
theorem chunk61 : ∀ i : Fin 16, IndexFact (976+i.val) := by decide
theorem chunk62 : ∀ i : Fin 16, IndexFact (992+i.val) := by decide
theorem chunk63 : ∀ i : Fin 16, IndexFact (1008+i.val) := by decide

theorem chunks (c : Fin 64) (i : Fin 16) : IndexFact (16*c.val+i.val) := by
  fin_cases c
  · exact chunk00 i
  · exact chunk01 i
  · exact chunk02 i
  · exact chunk03 i
  · exact chunk04 i
  · exact chunk05 i
  · exact chunk06 i
  · exact chunk07 i
  · exact chunk08 i
  · exact chunk09 i
  · exact chunk10 i
  · exact chunk11 i
  · exact chunk12 i
  · exact chunk13 i
  · exact chunk14 i
  · exact chunk15 i
  · exact chunk16 i
  · exact chunk17 i
  · exact chunk18 i
  · exact chunk19 i
  · exact chunk20 i
  · exact chunk21 i
  · exact chunk22 i
  · exact chunk23 i
  · exact chunk24 i
  · exact chunk25 i
  · exact chunk26 i
  · exact chunk27 i
  · exact chunk28 i
  · exact chunk29 i
  · exact chunk30 i
  · exact chunk31 i
  · exact chunk32 i
  · exact chunk33 i
  · exact chunk34 i
  · exact chunk35 i
  · exact chunk36 i
  · exact chunk37 i
  · exact chunk38 i
  · exact chunk39 i
  · exact chunk40 i
  · exact chunk41 i
  · exact chunk42 i
  · exact chunk43 i
  · exact chunk44 i
  · exact chunk45 i
  · exact chunk46 i
  · exact chunk47 i
  · exact chunk48 i
  · exact chunk49 i
  · exact chunk50 i
  · exact chunk51 i
  · exact chunk52 i
  · exact chunk53 i
  · exact chunk54 i
  · exact chunk55 i
  · exact chunk56 i
  · exact chunk57 i
  · exact chunk58 i
  · exact chunk59 i
  · exact chunk60 i
  · exact chunk61 i
  · exact chunk62 i
  · exact chunk63 i

theorem all_indices (i : Nat) (hi : i<1024) : IndexFact i := by
  have hc : i/16<64 := by omega
  have h := chunks ⟨i/16,hc⟩ ⟨i%16,Nat.mod_lt _ (by decide)⟩
  have he : 16*(i/16)+i%16=i := by omega
  simpa only [he] using h

end FT1536.Source3.KeygenMkgm3IndexCert
