import Source3.KeygenIntermediateLiftData

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_piece_source.py. -/
namespace FT1536.Source3.KeygenIntermediateLiftCheck5
theorem checked : KeygenIntermediateLiftData.audit 5=some true := by decide +kernel
end FT1536.Source3.KeygenIntermediateLiftCheck5
