import Source3.KeygenStaticTables

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000

/- Generated by tools/keygen_prime_table_source.py; every equality is kernel checked. -/
namespace FT1536.Source3.KeygenPrimeTablesTernaryHigh
open KeygenStaticTables

theorem chunk35 : Checked .ternary 35 := by decide
theorem chunk36 : Checked .ternary 36 := by decide
theorem chunk37 : Checked .ternary 37 := by decide
theorem chunk38 : Checked .ternary 38 := by decide
theorem chunk39 : Checked .ternary 39 := by decide
theorem chunk40 : Checked .ternary 40 := by decide
theorem chunk41 : Checked .ternary 41 := by decide
theorem chunk42 : Checked .ternary 42 := by decide
theorem chunk43 : Checked .ternary 43 := by decide
theorem chunk44 : Checked .ternary 44 := by decide
theorem chunk45 : Checked .ternary 45 := by decide
theorem chunk46 : Checked .ternary 46 := by decide
theorem chunk47 : Checked .ternary 47 := by decide
theorem chunk48 : Checked .ternary 48 := by decide
theorem chunk49 : Checked .ternary 49 := by decide
theorem chunk50 : Checked .ternary 50 := by decide
theorem chunk51 : Checked .ternary 51 := by decide
theorem chunk52 : Checked .ternary 52 := by decide
theorem chunk53 : Checked .ternary 53 := by decide
theorem chunk54 : Checked .ternary 54 := by decide
theorem chunk55 : Checked .ternary 55 := by decide
theorem chunk56 : Checked .ternary 56 := by decide
theorem chunk57 : Checked .ternary 57 := by decide
theorem chunk58 : Checked .ternary 58 := by decide
theorem chunk59 : Checked .ternary 59 := by decide
theorem chunk60 : Checked .ternary 60 := by decide
theorem chunk61 : Checked .ternary 61 := by decide
theorem chunk62 : Checked .ternary 62 := by decide
theorem chunk63 : Checked .ternary 63 := by decide
theorem chunk64 : Checked .ternary 64 := by decide
theorem chunk65 : Checked .ternary 65 := by decide
theorem chunk66 : Checked .ternary 66 := by decide
theorem chunk67 : Checked .ternary 67 := by decide
theorem chunk68 : Checked .ternary 68 := by decide

theorem all_chunks (i : Fin 34) : Checked .ternary (i.val+35) := by
  fin_cases i
  · exact chunk35
  · exact chunk36
  · exact chunk37
  · exact chunk38
  · exact chunk39
  · exact chunk40
  · exact chunk41
  · exact chunk42
  · exact chunk43
  · exact chunk44
  · exact chunk45
  · exact chunk46
  · exact chunk47
  · exact chunk48
  · exact chunk49
  · exact chunk50
  · exact chunk51
  · exact chunk52
  · exact chunk53
  · exact chunk54
  · exact chunk55
  · exact chunk56
  · exact chunk57
  · exact chunk58
  · exact chunk59
  · exact chunk60
  · exact chunk61
  · exact chunk62
  · exact chunk63
  · exact chunk64
  · exact chunk65
  · exact chunk66
  · exact chunk67
  · exact chunk68

end FT1536.Source3.KeygenPrimeTablesTernaryHigh
