import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensReduce4
def text0 : String := "\t\tfor (u = 0; u < n; u ++) {\n"
def text1 : String := "\t\t\tint64_t kx, ks;\n"
def text2 : String := "\n"
def text3 : String := "\t\t\tkx = fpr_rint(rt2[u]);\n"
def text4 : String := "\t\t\t{\n"
def text5 : String := "\t\t\t\tuint64_t ukx;\n"
def text6 : String := "\n"
def text7 : String := "\t\t\t\tukx = (uint64_t)kx;\n"
def text8 : String := "\t\t\t\tif (kx < 0) {\n"
def text9 : String := "\t\t\t\t\tukx = (uint64_t)0 - ukx;\n"
def text10 : String := "\t\t\t\t}\n"
def text11 : String := "\t\t\t\tks = (int32_t)(ukx >> scale_k);\n"
def text12 : String := "\t\t\t\tif (kx < 0) {\n"
def text13 : String := "\t\t\t\t\tks = -ks;\n"
def text14 : String := "\t\t\t\t}\n"
def text15 : String := "\t\t\t}\n"
def text16 : String := "\t\t\tk[u] = ks;\n"
def text17 : String := "\t\t}\n"
def text18 : String := "\n"
def tail19 : List String := []
def tail18 : List String := text18::tail19
def tail17 : List String := text17::tail18
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[6314]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[6315]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[6316]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[6317]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[6318]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[6319]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[6320]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[6321]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[6322]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[6323]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[6324]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[6325]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[6326]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[6327]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[6328]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[6329]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[6330]?=some text16 := by decide +kernel
theorem line17 : Pinned.keygenLines[6331]?=some text17 := by decide +kernel
theorem line18 : Pinned.keygenLines[6332]?=some text18 := by decide +kernel
theorem bytes19 : (Pinned.keygenLines.drop 6333).take tail19.length=tail19 := rfl
theorem bytes18 : (Pinned.keygenLines.drop 6332).take tail18.length=tail18 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6332 text18 tail19 line18 bytes19
theorem bytes17 : (Pinned.keygenLines.drop 6331).take tail17.length=tail17 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6331 text17 tail18 line17 bytes18
theorem bytes16 : (Pinned.keygenLines.drop 6330).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6330 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 6329).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6329 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 6328).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6328 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 6327).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6327 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 6326).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6326 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 6325).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6325 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 6324).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6324 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 6323).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6323 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 6322).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6322 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 6321).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6321 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 6320).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6320 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 6319).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6319 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 6318).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6318 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 6317).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6317 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 6316).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6316 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 6315).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6315 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 6314).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6314 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 6314).take 19=lines := bytes0
def group0 : List String := [text0]
def words0 : List B20.C.Token := ["for","(","u","=","0",";","u","<","n",";","u","++",")","{"].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text1]
def words1 : List B20.C.Token := ["int64_t","kx",",","ks",";"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text2]
def words2 : List B20.C.Token := [].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text3]
def words3 : List B20.C.Token := ["kx","=","fpr_rint","(","rt2","[","u","]",")",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text4]
def words4 : List B20.C.Token := ["{"].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text5]
def words5 : List B20.C.Token := ["uint64_t","ukx",";"].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text6]
def words6 : List B20.C.Token := [].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text7]
def words7 : List B20.C.Token := ["ukx","=","(","uint64_t",")","kx",";"].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text8]
def words8 : List B20.C.Token := ["if","(","kx","<","0",")","{"].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text9]
def words9 : List B20.C.Token := ["ukx","=","(","uint64_t",")","0","-","ukx",";"].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text10]
def words10 : List B20.C.Token := ["}"].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def group11 : List String := [text11]
def words11 : List B20.C.Token := ["ks","=","(","int32_t",")","(","ukx",">>","scale_k",")",";"].map String.toList
theorem lex11 : KeygenLexicalChunks.Checked group11 words11 := by
  constructor <;> decide +kernel
def group12 : List String := [text12]
def words12 : List B20.C.Token := ["if","(","kx","<","0",")","{"].map String.toList
theorem lex12 : KeygenLexicalChunks.Checked group12 words12 := by
  constructor <;> decide +kernel
def group13 : List String := [text13]
def words13 : List B20.C.Token := ["ks","=","-","ks",";"].map String.toList
theorem lex13 : KeygenLexicalChunks.Checked group13 words13 := by
  constructor <;> decide +kernel
def group14 : List String := [text14]
def words14 : List B20.C.Token := ["}"].map String.toList
theorem lex14 : KeygenLexicalChunks.Checked group14 words14 := by
  constructor <;> decide +kernel
def group15 : List String := [text15]
def words15 : List B20.C.Token := ["}"].map String.toList
theorem lex15 : KeygenLexicalChunks.Checked group15 words15 := by
  constructor <;> decide +kernel
def group16 : List String := [text16]
def words16 : List B20.C.Token := ["k","[","u","]","=","ks",";"].map String.toList
theorem lex16 : KeygenLexicalChunks.Checked group16 words16 := by
  constructor <;> decide +kernel
def group17 : List String := [text17]
def words17 : List B20.C.Token := ["}"].map String.toList
theorem lex17 : KeygenLexicalChunks.Checked group17 words17 := by
  constructor <;> decide +kernel
def group18 : List String := [text18]
def words18 : List B20.C.Token := [].map String.toList
theorem lex18 : KeygenLexicalChunks.Checked group18 words18 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10,group11,group12,group13,group14,group15,group16,group17,group18]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10,words11,words12,words13,words14,words15,words16,words17,words18]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.cons lex11 (List.Forall₂.cons lex12 (List.Forall₂.cons lex13 (List.Forall₂.cons lex14 (List.Forall₂.cons lex15 (List.Forall₂.cons lex16 (List.Forall₂.cons lex17 (List.Forall₂.cons lex18 (List.Forall₂.nil)))))))))))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 6314).take 19) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensReduce4
