import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensLift1
def text0 : String := "\t\tif (fk->ternary) {\n"
def text1 : String := "\t\t\tmodp_mkgm3(gm, igm, logn, full, primes[u].g, p, p0i);\n"
def text2 : String := "\t\t} else {\n"
def text3 : String := "\t\t\tmodp_mkgm2(gm, igm, logn, primes[u].g, p, p0i);\n"
def text4 : String := "\t\t}\n"
def text5 : String := "\n"
def tail6 : List String := []
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[5954]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[5955]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[5956]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[5957]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[5958]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[5959]?=some text5 := by decide +kernel
theorem bytes6 : (Pinned.keygenLines.drop 5960).take tail6.length=tail6 := rfl
theorem bytes5 : (Pinned.keygenLines.drop 5959).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5959 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 5958).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5958 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 5957).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5957 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 5956).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5956 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 5955).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5955 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 5954).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 5954 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 5954).take 6=lines := bytes0
def group0 : List String := [text0]
def words0 : List B20.C.Token := ["if","(","fk","-",">","ternary",")","{"].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text1]
def words1 : List B20.C.Token := ["modp_mkgm3","(","gm",",","igm",",","logn",",","full",",","primes","[","u","]",".","g",",","p",",","p0i",")",";"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text2]
def words2 : List B20.C.Token := ["}","else","{"].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text3]
def words3 : List B20.C.Token := ["modp_mkgm2","(","gm",",","igm",",","logn",",","primes","[","u","]",".","g",",","p",",","p0i",")",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text4]
def words4 : List B20.C.Token := ["}"].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text5]
def words5 : List B20.C.Token := [].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.nil))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 5954).take 6) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensLift1
