import Source3.KeygenStaticTables

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000

/- Generated by tools/keygen_prime_table_source.py; every equality is kernel checked. -/
namespace FT1536.Source3.KeygenPrimeTablesBinary
open KeygenStaticTables

theorem chunk0 : Checked .binary 0 := by decide
theorem chunk1 : Checked .binary 1 := by decide
theorem chunk2 : Checked .binary 2 := by decide
theorem chunk3 : Checked .binary 3 := by decide
theorem chunk4 : Checked .binary 4 := by decide
theorem chunk5 : Checked .binary 5 := by decide
theorem chunk6 : Checked .binary 6 := by decide
theorem chunk7 : Checked .binary 7 := by decide
theorem chunk8 : Checked .binary 8 := by decide
theorem chunk9 : Checked .binary 9 := by decide
theorem chunk10 : Checked .binary 10 := by decide
theorem chunk11 : Checked .binary 11 := by decide
theorem chunk12 : Checked .binary 12 := by decide
theorem chunk13 : Checked .binary 13 := by decide
theorem chunk14 : Checked .binary 14 := by decide
theorem chunk15 : Checked .binary 15 := by decide
theorem chunk16 : Checked .binary 16 := by decide
theorem chunk17 : Checked .binary 17 := by decide
theorem chunk18 : Checked .binary 18 := by decide
theorem chunk19 : Checked .binary 19 := by decide
theorem chunk20 : Checked .binary 20 := by decide
theorem chunk21 : Checked .binary 21 := by decide
theorem chunk22 : Checked .binary 22 := by decide
theorem chunk23 : Checked .binary 23 := by decide
theorem chunk24 : Checked .binary 24 := by decide
theorem chunk25 : Checked .binary 25 := by decide
theorem chunk26 : Checked .binary 26 := by decide
theorem chunk27 : Checked .binary 27 := by decide
theorem chunk28 : Checked .binary 28 := by decide
theorem chunk29 : Checked .binary 29 := by decide
theorem chunk30 : Checked .binary 30 := by decide
theorem chunk31 : Checked .binary 31 := by decide
theorem chunk32 : Checked .binary 32 := by decide

theorem all_chunks (i : Fin 33) : Checked .binary (i.val+0) := by
  fin_cases i
  · exact chunk0
  · exact chunk1
  · exact chunk2
  · exact chunk3
  · exact chunk4
  · exact chunk5
  · exact chunk6
  · exact chunk7
  · exact chunk8
  · exact chunk9
  · exact chunk10
  · exact chunk11
  · exact chunk12
  · exact chunk13
  · exact chunk14
  · exact chunk15
  · exact chunk16
  · exact chunk17
  · exact chunk18
  · exact chunk19
  · exact chunk20
  · exact chunk21
  · exact chunk22
  · exact chunk23
  · exact chunk24
  · exact chunk25
  · exact chunk26
  · exact chunk27
  · exact chunk28
  · exact chunk29
  · exact chunk30
  · exact chunk31
  · exact chunk32

end FT1536.Source3.KeygenPrimeTablesBinary
