import Source3.KeygenPublicFirstTables
import Source3.KeygenPublicFirstEntry
import Source3.KeygenPublicFirstInvocation
import Source3.KeygenPublicFirstCalls
import Source3.KeygenPublicFirstMaterial
import Source3.KeygenPublicRadixValues
import Source3.KeygenPublicRadixFold
import Source3.KeygenPublicSplitPolynomial
import Source3.KeygenPublicTripleOrder
import Source3.KeygenPublicFirstFold
import Lean.Util.CollectAxioms

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option pp.proofs true
set_option pp.deepTerms true
set_option pp.fullNames true
set_option pp.universes true
set_option pp.maxSteps 200000

/- Generated complete internal041 audit, not independent review. -/
run_cmd Lean.Elab.Command.liftTermElabM do
  let groups : Array (Lean.Name × List String) := #[
    (`FT1536.Source3.KeygenPublicFirstTables,
      ["Table","generate_values","dynamic_values","first_cell","cells_block"]),
    (`FT1536.Source3.KeygenPublicFirstEntry,
      ["Types","initU","n_value","hn_value","table_load","FirstRun","tail_first","ready_first"]),
    (`FT1536.Source3.KeygenPublicFirstInvocation,
      ["Outcome","initialized","source_first","folded"]),
    (`FT1536.Source3.KeygenPublicFirstCalls,
      ["normal","transport","binding","ternary_call","ternary_body","source_dispatch","call","source_call","both"]),
    (`FT1536.Source3.KeygenPublicFirstMaterial,
      ["Front","source_front","source_same_material"]),
    (`FT1536.Source3.KeygenPublicRadixValues,
      ["lowIndex","highIndex","names","declaration","readLow","readHigh","multiply","storeLow","storeHigh","inner","body","contains","source_inner","source_occurrence","body_supported","Fixed","PairUpdate","fixed_after","low_value","high_value","source_body"]),
    (`FT1536.Source3.KeygenPublicRadixFold,
      ["guard","increment","loop","pass","source_pass","source_occurrence","low","high","image","image_zero","image_input_low","image_input_high","image_low","image_high","image_unchanged","Data","Inv","guard_value","increment_result","body_data","step","loop_result","source_loop"]),
    (`FT1536.Source3.KeygenPublicSplitPolynomial,
      ["polynomial","lowPolynomial","highPolynomial","modulus","coefficient","degree_bound","split_halves","low_decomposition","negate_low","low_remainder","high_remainder","eval_low","eval_high","RemainderImage","source_remainders"]),
    (`FT1536.Source3.KeygenPublicTripleOrder,
      ["unity_cube","unity_power","triple_order","quadratic","output","output_eval","physical_evaluation","all_physical_evaluations"]),
    (`FT1536.Source3.KeygenPublicFirstFold,
      ["root","lowP","highP","image","reduced_low","reduced_high","lowP_coeff","highP_coeff","image_low","image_low_un","image_high","image_high_un","image_zero","image_advance","image_advance_high","image_input_low","image_input_high","image_unchanged","guard_cmp","increment_result","increment_counter","preserve_pair","Data","Inv","body_data","step","loop_result","folded","source_first_fold"])]
  let inherited : Array Lean.Name := #[
    ``FT1536.Source3.C99MemoryReference.Memory,
    ``FT1536.Source3.C99MemoryReference.ArrayPointer,
    ``FT1536.Source3.C99MemoryReference.ArrayPointer.offset,
    ``FT1536.Source3.C99MemoryReference.Allocated,
    ``FT1536.Source3.C99MemoryReference.PointerAdd,
    ``FT1536.Source3.C99IntegerReference.Ty,
    ``FT1536.Source3.C99IntegerReference.Value,
    ``FT1536.Source3.C99IntegerReference.Value.integer,
    ``FT1536.Source3.C99IntegerReference.Value.type,
    ``FT1536.Source3.C99IntegerReference.convert,
    ``FT1536.Source3.C99IntegerReference.compare,
    ``FT1536.Source3.C99IntegerReference.promote,
    ``FT1536.Source3.C99IntegerReference.usual,
    ``FT1536.Source3.C99IntegerReference.ArithmeticExec,
    ``FT1536.Source3.C99ScalarReference.Env,
    ``FT1536.Source3.C99ScalarReference.set,
    ``FT1536.Source3.C99ScalarReference.boolean,
    ``FT1536.Source3.C99ScalarReference.Stmt,
    ``FT1536.Source3.C99ScalarReference.Exec,
    ``FT1536.Source3.C99ScalarReference.Eval,
    ``FT1536.Source3.C99Frontend.scalar,
    ``FT1536.Source3.C99Frontend.expression,
    ``FT1536.Source3.C99Frontend.binary,
    ``FT1536.Source3.C99DeclarationCells.declareCells,
    ``FT1536.Source3.C99DeclarationCells.complete,
    ``FT1536.Source3.C99ArrayReference.Name,
    ``FT1536.Source3.C99ArrayReference.Arg,
    ``FT1536.Source3.C99ArrayReference.Param,
    ``FT1536.Source3.C99ArrayReference.State,
    ``FT1536.Source3.C99ArrayReference.bindValue,
    ``FT1536.Source3.C99ArrayReference.bindPointer,
    ``FT1536.Source3.C99ArrayReference.restoreScope,
    ``FT1536.Source3.C99ProcedureReference.Result,
    ``FT1536.Source3.C99ProcedureReference.Flow,
    ``FT1536.Source3.C99ProcedureReference.ReturnValue,
    ``FT1536.Source3.C99ProcedureParser.zero,
    ``FT1536.Source3.C99CountedWords.comparison_result,
    ``FT1536.Source3.C99NarrowReads.Load16,
    ``FT1536.Source3.C99NarrowReads.le16,
    ``FT1536.Source3.C99NarrowReads.unsignedPromotion,
    ``FT1536.Source3.C99NarrowReads.unsigned_promotion_exact,
    ``FT1536.Source3.C99NarrowReads.load16_deterministic,
    ``FT1536.Source3.C99NarrowReads.load16_transport,
    ``FT1536.Source3.KeygenSmallOutput.element,
    ``FT1536.Source3.KeygenSmallOutput.byte16,
    ``FT1536.Source3.KeygenSmallOutput.Stored,
    ``FT1536.Source3.KeygenSmallOutput.Store16,
    ``FT1536.Source3.KeygenResidueVectors.join_bytes,
    ``FT1536.Source3.KeygenWordExpr.Expr,
    ``FT1536.Source3.KeygenWordExpr.expression,
    ``FT1536.Source3.KeygenPublicScalar.Kind,
    ``FT1536.Source3.KeygenPublicScalar.Call,
    ``FT1536.Source3.KeygenPublicScalar.Square,
    ``FT1536.Source3.KeygenPublicScalar.name,
    ``FT1536.Source3.KeygenPublicScalar.params,
    ``FT1536.Source3.KeygenPublicScalar.lines,
    ``FT1536.Source3.KeygenPublicScalar.expand,
    ``FT1536.Source3.KeygenPublicAlgebra.R,
    ``FT1536.Source3.KeygenPublicAlgebra.Canonical,
    ``FT1536.Source3.KeygenPublicAlgebra.value,
    ``FT1536.Source3.KeygenPublicAlgebra.source_add,
    ``FT1536.Source3.KeygenPublicAlgebra.source_sub,
    ``FT1536.Source3.KeygenPublicAlgebra.call_leaf,
    ``FT1536.Source3.KeygenPublicMontgomery.modulus,
    ``FT1536.Source3.KeygenPublicMontgomery.inverse,
    ``FT1536.Source3.KeygenPublicMontgomery.word_contract,
    ``FT1536.Source3.KeygenPublicArguments.U32,
    ``FT1536.Source3.KeygenPublicArguments.Conversion,
    ``FT1536.Source3.KeygenPublicArguments.u32_self,
    ``FT1536.Source3.KeygenPublicArguments.call_leaf_conversion,
    ``FT1536.Source3.KeygenPublicArguments.source_mul_exact,
    ``FT1536.Source3.KeygenPublicLeafWords.source_add,
    ``FT1536.Source3.KeygenPublicLeafWords.source_sub,
    ``FT1536.Source3.KeygenPublicSquare.source_square_arguments,
    ``FT1536.Source3.KeygenPublicWord.Eval,
    ``FT1536.Source3.KeygenPublicWord.Address,
    ``FT1536.Source3.KeygenPublicWord.scalar,
    ``FT1536.Source3.KeygenPublicWord.Bind,
    ``FT1536.Source3.KeygenPublicWord.narrow,
    ``FT1536.Source3.KeygenPublicWord.bind_heap,
    ``FT1536.Source3.KeygenPublicExec.Stmt,
    ``FT1536.Source3.KeygenPublicExec.Exec,
    ``FT1536.Source3.KeygenPublicExec.Function,
    ``FT1536.Source3.KeygenPublicExec.Program,
    ``FT1536.Source3.KeygenPublicExec.chain,
    ``FT1536.Source3.KeygenPublicExec.allocated,
    ``FT1536.Source3.KeygenPublicExec.localPointer,
    ``FT1536.Source3.KeygenPublicExec.localEntry,
    ``FT1536.Source3.KeygenPublicExec.localExit,
    ``FT1536.Source3.KeygenPublicParser.Types,
    ``FT1536.Source3.KeygenPublicParser.body,
    ``FT1536.Source3.KeygenPublicParser.statement,
    ``FT1536.Source3.KeygenPublicSource.Kind,
    ``FT1536.Source3.KeygenPublicSource.name,
    ``FT1536.Source3.KeygenPublicSource.code,
    ``FT1536.Source3.KeygenPublicSource.params,
    ``FT1536.Source3.KeygenPublicSource.function,
    ``FT1536.Source3.KeygenPublicSource.program,
    ``FT1536.Source3.KeygenPublicSource.types,
    ``FT1536.Source3.KeygenPublicSource.signatures,
    ``FT1536.Source3.KeygenPublicSource.code_checked,
    ``FT1536.Source3.KeygenPublicTableAtoms.Slot,
    ``FT1536.Source3.KeygenPublicTableAtoms.var,
    ``FT1536.Source3.KeygenPublicTableAtoms.literal,
    ``FT1536.Source3.KeygenPublicTableAtoms.variable_value,
    ``FT1536.Source3.KeygenPublicTableAtoms.literal_value,
    ``FT1536.Source3.KeygenPublicTableAtoms.literal_argument,
    ``FT1536.Source3.KeygenPublicTableIndex.address,
    ``FT1536.Source3.KeygenPublicTableStore.Pointers,
    ``FT1536.Source3.KeygenPublicTableStore.Separate,
    ``FT1536.Source3.KeygenPublicTableCells.Cell,
    ``FT1536.Source3.KeygenPublicTableControl.writes,
    ``FT1536.Source3.KeygenPublicTableControl.supported,
    ``FT1536.Source3.KeygenPublicTableControl.frame,
    ``FT1536.Source3.KeygenPublicTableControl.declare_frame,
    ``FT1536.Source3.KeygenPublicTableRows.noReturn,
    ``FT1536.Source3.KeygenPublicTableRows.normal,
    ``FT1536.Source3.KeygenPublicUpperLoops.PairCells,
    ``FT1536.Source3.KeygenPublicUpperFrames.UpperFrame,
    ``FT1536.Source3.KeygenPublicUpperFrames.OutsideFull,
    ``FT1536.Source3.KeygenPublicUpperImages.source_complete_tables,
    ``FT1536.Source3.KeygenPublicRoots.root,
    ``FT1536.Source3.KeygenMkgm3Indices.tableExponent,
    ``FT1536.Source3.KeygenRngSource.Fresh,
    ``FT1536.Source3.KeygenRngSource.disposed,
    ``FT1536.Source3.ShakeExtractFrame.SameBlock,
    ``FT1536.Source3.KeygenZintTop.tokens,
    ``FT1536.Source3.KeygenPublicForwardWrapper.source_forward_canonical,
    ``FT1536.Source3.KeygenPublicForwardWrapper.domain_of_image,
    ``FT1536.Source3.KeygenPublicForwardMemory.Block,
    ``FT1536.Source3.KeygenPublicForwardMemory.load_block,
    ``FT1536.Source3.KeygenPublicForwardMemory.initialized_live,
    ``FT1536.Source3.KeygenPublicForwardMemory.allocated_other,
    ``FT1536.Source3.KeygenPublicRangeMemory.read_after_store,
    ``FT1536.Source3.KeygenPublicRangeMemory.image,
    ``FT1536.Source3.KeygenPublicRangeMemory.domain_same_block,
    ``FT1536.Source3.KeygenPublicRangeMemory.initialized_same_block,
    ``FT1536.Source3.KeygenPublicRangeExpr.word_nat,
    ``FT1536.Source3.KeygenPublicRangeExpr.word_argument,
    ``FT1536.Source3.KeygenPublicRangeExpr.narrowed_range,
    ``FT1536.Source3.KeygenPublicAlgebra.source_conv,
    ``FT1536.Source3.KeygenPublicTableCells.stored_load,
    ``FT1536.Source3.KeygenPublicTableCells.narrowing,
    ``FT1536.Source3.KeygenMaterial.Represents,
    ``FT1536.Source3.KeygenIntegerLift.Bound,
    ``FT1536.Source3.KeygenSmallOutput.narrowed_exact,
    ``FT1536.Source3.KeygenNttLoopSupport.USlot,
    ``FT1536.Source3.KeygenNttLoopSupport.plus_u64,
    ``FT1536.Source3.KeygenPublicFrame.body,
    ``FT1536.Source3.KeygenPublicRoots.firstRoot,
    ``FT1536.Source3.KeygenPublicRoots.first_root_relation,
    ``FT1536.Source3.KeygenPublicRoots.point_half_power,
    ``FT1536.Relation.reduceVec,
    ``FT1536.Run2.CoefficientQuotient.polynomial,
    ``FT1536.Run2.CoefficientQuotient.coefficient_low,
    ``FT1536.Run2.CoefficientQuotient.coefficient_high,
    ``FT1536.Run2.CoefficientQuotient.coefficient_outside,
    ``FT1536.Source3.KeygenPublicInputProgram.signed,
    ``FT1536.Source3.KeygenPublicInputProgram.index,
    ``FT1536.Source3.KeygenPublicInputProgram.converted,
    ``FT1536.Source3.KeygenPublicInputProgram.firstStore,
    ``FT1536.Source3.KeygenPublicInputProgram.secondStore,
    ``FT1536.Source3.KeygenPublicInputProgram.body,
    ``FT1536.Source3.KeygenPublicInputProgram.condition,
    ``FT1536.Source3.KeygenPublicInputProgram.increment,
    ``FT1536.Source3.KeygenPublicInputProgram.loop,
    ``FT1536.Source3.KeygenPublicInputProgram.initial,
    ``FT1536.Source3.KeygenPublicInputProgram.conversion,
    ``FT1536.Source3.KeygenPublicInputProgram.hArgs,
    ``FT1536.Source3.KeygenPublicInputProgram.tArgs,
    ``FT1536.Source3.KeygenPublicInputProgram.hForward,
    ``FT1536.Source3.KeygenPublicInputProgram.tForward,
    ``FT1536.Source3.KeygenPublicInputProgram.fragment,
    ``FT1536.Source3.KeygenPublicInputProgram.setup,
    ``FT1536.Source3.KeygenPublicInputProgram.suffix,
    ``FT1536.Source3.KeygenPublicInputProgram.append,
    ``FT1536.Source3.KeygenPublicInputProgram.ready,
    ``FT1536.Source3.KeygenPublicInputProgram.completeReady,
    ``FT1536.Source3.KeygenPublicInputProgram.declareDimensions,
    ``FT1536.Source3.KeygenPublicInputProgram.complete,
    ``FT1536.Source3.KeygenPublicInputProgram.source_complete,
    ``FT1536.Source3.KeygenPublicInputProgram.signed_source,
    ``FT1536.Source3.KeygenPublicInputProgram.body_supported,
    ``FT1536.Source3.KeygenPublicInputProgram.loop_supported,
    ``FT1536.Source3.KeygenPublicInputProgram.conversion_supported,
    ``FT1536.Source3.KeygenPublicInputProgram.loop_writes,
    ``FT1536.Source3.KeygenPublicInputProgram.body_writes,
    ``FT1536.Source3.KeygenPublicInputProgram.conversion_writes,
    ``FT1536.Source3.KeygenPublicInputCells.Cell,
    ``FT1536.Source3.KeygenPublicInputCells.Cells,
    ``FT1536.Source3.KeygenPublicInputCells.Signed,
    ``FT1536.Source3.KeygenPublicInputCells.TailEmpty,
    ``FT1536.Source3.KeygenPublicInputCells.written,
    ``FT1536.Source3.KeygenPublicInputCells.preserves,
    ``FT1536.Source3.KeygenPublicInputCells.other_block,
    ``FT1536.Source3.KeygenPublicInputCells.signed_other,
    ``FT1536.Source3.KeygenPublicInputCells.tail_store,
    ``FT1536.Source3.KeygenPublicInputCells.empty_allocated,
    ``FT1536.Source3.KeygenPublicInputCells.image,
    ``FT1536.Source3.KeygenPublicInputCells.domain,
    ``FT1536.Source3.KeygenPublicInputAtoms.seq_inv,
    ``FT1536.Source3.KeygenPublicInputAtoms.word64,
    ``FT1536.Source3.KeygenPublicInputAtoms.index_address,
    ``FT1536.Source3.KeygenPublicInputAtoms.converted_value,
    ``FT1536.Source3.KeygenPublicInputAtoms.store,
    ``FT1536.Source3.KeygenPublicInputAtoms.guard,
    ``FT1536.Source3.KeygenPublicInputAtoms.increment_result,
    ``FT1536.Source3.KeygenPublicInputAtoms.increment_counter,
    ``FT1536.Source3.KeygenPublicInputLoop.Pointers,
    ``FT1536.Source3.KeygenPublicInputLoop.Layout,
    ``FT1536.Source3.KeygenPublicInputLoop.Fixed,
    ``FT1536.Source3.KeygenPublicInputLoop.Data,
    ``FT1536.Source3.KeygenPublicInputLoop.Invariant,
    ``FT1536.Source3.KeygenPublicInputLoop.fixed_after,
    ``FT1536.Source3.KeygenPublicInputLoop.body_data,
    ``FT1536.Source3.KeygenPublicInputLoop.step,
    ``FT1536.Source3.KeygenPublicInputLoop.source_loop,
    ``FT1536.Source3.KeygenPublicInputMaterial.coefficient,
    ``FT1536.Source3.KeygenPublicInputMaterial.reduced,
    ``FT1536.Source3.KeygenPublicInputMaterial.Legal,
    ``FT1536.Source3.KeygenPublicInputMaterial.signed_material,
    ``FT1536.Source3.KeygenPublicInputMaterial.initial_result,
    ``FT1536.Source3.KeygenPublicInputMaterial.source_conversion,
    ``FT1536.Source3.KeygenPublicInputMaterial.source_vectors,
    ``FT1536.Source3.KeygenPublicInputSetup.ternaryShift,
    ``FT1536.Source3.KeygenPublicInputSetup.leftCount,
    ``FT1536.Source3.KeygenPublicInputSetup.rightCount,
    ``FT1536.Source3.KeygenPublicInputSetup.dimension,
    ``FT1536.Source3.KeygenPublicInputSetup.declareQ,
    ``FT1536.Source3.KeygenPublicInputSetup.nSet,
    ``FT1536.Source3.KeygenPublicInputSetup.qSet,
    ``FT1536.Source3.KeygenPublicInputSetup.complete,
    ``FT1536.Source3.KeygenPublicInputSetup.source_complete,
    ``FT1536.Source3.KeygenPublicInputSetup.supported,
    ``FT1536.Source3.KeygenPublicInputSetup.writes,
    ``FT1536.Source3.KeygenPublicInputSetup.ternary_value,
    ``FT1536.Source3.KeygenPublicInputSetup.dimension_value,
    ``FT1536.Source3.KeygenPublicInputSetup.source_setup,
    ``FT1536.Source3.KeygenPublicInputCalls.inputPrefix,
    ``FT1536.Source3.KeygenPublicInputCalls.forwards,
    ``FT1536.Source3.KeygenPublicInputCalls.convertedForward,
    ``FT1536.Source3.KeygenPublicInputCalls.remaining,
    ``FT1536.Source3.KeygenPublicInputCalls.Globals,
    ``FT1536.Source3.KeygenPublicInputCalls.complete_seam,
    ``FT1536.Source3.KeygenPublicInputCalls.prefix_supported,
    ``FT1536.Source3.KeygenPublicInputCalls.normal_seq_inv,
    ``FT1536.Source3.KeygenPublicInputCalls.append_inv,
    ``FT1536.Source3.KeygenPublicInputCalls.globals_preserved,
    ``FT1536.Source3.KeygenPublicInputCalls.global_range,
    ``FT1536.Source3.KeygenPublicInputCalls.prefix_result,
    ``FT1536.Source3.KeygenPublicInputCalls.call_binding,
    ``FT1536.Source3.KeygenPublicInputCalls.source_call_canonical,
    ``FT1536.Source3.KeygenPublicInputCalls.forward_other,
    ``FT1536.Source3.KeygenPublicInputCalls.source_both_forward,
    ``FT1536.Source3.KeygenPublicInputBridge.append_intro,
    ``FT1536.Source3.KeygenPublicInputBridge.tables_preserved,
    ``FT1536.Source3.KeygenPublicInputBridge.source_converted_forward,
    ``FT1536.Source3.KeygenPublicInputBridge.source_same_vectors_forward,
    ``FT1536.Source3.KeygenPublicInputLifetime.LiveTables,
    ``FT1536.Source3.KeygenPublicInputLifetime.Front,
    ``FT1536.Source3.KeygenPublicInputLifetime.legal_live,
    ``FT1536.Source3.KeygenPublicInputLifetime.signed_block,
    ``FT1536.Source3.KeygenPublicInputLifetime.source_front,
    ``FT1536.Source3.KeygenPublicInputLifetime.source_same_material_front,
    ``FT1536.Source3.KeygenPublicValueExpr.meaning,
    ``FT1536.Source3.KeygenPublicValueExpr.Evaluates,
    ``FT1536.Source3.KeygenPublicValueExpr.Local,
    ``FT1536.Source3.KeygenPublicValueExpr.add,
    ``FT1536.Source3.KeygenPublicValueExpr.sub,
    ``FT1536.Source3.KeygenPublicValueExpr.word_meaning,
    ``FT1536.Source3.KeygenPublicValueExpr.local_value,
    ``FT1536.Source3.KeygenPublicValueExpr.add_value,
    ``FT1536.Source3.KeygenPublicValueExpr.sub_value,
    ``FT1536.Source3.KeygenPublicValueExpr.twiddle_value,
    ``FT1536.Source3.KeygenPublicValueExpr.local_after,
    ``FT1536.Source3.KeygenPublicValueExpr.assign_value,
    ``FT1536.Source3.KeygenPublicFirstValues.lowIndex,
    ``FT1536.Source3.KeygenPublicFirstValues.highIndex,
    ``FT1536.Source3.KeygenPublicFirstValues.names,
    ``FT1536.Source3.KeygenPublicFirstValues.declaration,
    ``FT1536.Source3.KeygenPublicFirstValues.readLow,
    ``FT1536.Source3.KeygenPublicFirstValues.readHigh,
    ``FT1536.Source3.KeygenPublicFirstValues.multiply,
    ``FT1536.Source3.KeygenPublicFirstValues.storeLow,
    ``FT1536.Source3.KeygenPublicFirstValues.storeHigh,
    ``FT1536.Source3.KeygenPublicFirstValues.inner,
    ``FT1536.Source3.KeygenPublicFirstValues.body,
    ``FT1536.Source3.KeygenPublicFirstValues.firstLoop,
    ``FT1536.Source3.KeygenPublicFirstValues.pass,
    ``FT1536.Source3.KeygenPublicFirstValues.seed,
    ``FT1536.Source3.KeygenPublicFirstValues.remaining,
    ``FT1536.Source3.KeygenPublicFirstValues.source_first_pass,
    ``FT1536.Source3.KeygenPublicFirstValues.body_supported,
    ``FT1536.Source3.KeygenPublicFirstValues.Fixed,
    ``FT1536.Source3.KeygenPublicFirstValues.PairUpdate,
    ``FT1536.Source3.KeygenPublicFirstValues.fixed_after,
    ``FT1536.Source3.KeygenPublicFirstValues.low_value,
    ``FT1536.Source3.KeygenPublicFirstValues.high_value,
    ``FT1536.Source3.KeygenPublicFirstValues.load_value,
    ``FT1536.Source3.KeygenPublicFirstValues.store_value,
    ``FT1536.Source3.KeygenPublicFirstValues.source_body,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.low,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.high,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.low_coefficient,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.high_coefficient,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.low_degree,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.eval_original,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.first_low_evaluation,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.first_high_evaluation,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.original_reduced_coefficient,
    ``FT1536.Source3.KeygenPublicFirstPolynomial.source_original_coefficients]
  let names := groups.flatMap fun (ns,decls) => decls.toArray.map (Lean.Name.str ns)
  let allowed : Array Lean.Name := #[``propext, ``Classical.choice, ``Quot.sound]
  let render (e : Lean.Expr) := do
    let text := (← Lean.Meta.ppExpr e).pretty
    if text.contains '⋯' then throwError "Truncated audit text"
    pure text
  let mut rows : Array Lean.Json := #[]
  for name in names ++ inherited do
    IO.FS.writeFile "../PUBLIC_FIRST_AUDIT_PROGRESS.json" (Lean.toJson name.toString |>.pretty)
    let info ← Lean.getConstInfo name
    let axes ← Lean.collectAxioms name
    for ax in axes do
      unless allowed.contains ax do throwError "Unexpected axiom {ax} in {name}"
    let body ← match info.value? (allowOpaque := true) with
      | some term => pure (Lean.Json.mkObj [("kind",Lean.toJson "definition_or_theorem"),
          ("term",Lean.toJson (← render term))])
      | none =>
          match info with
          | .inductInfo ind =>
              let mut constructors : Array Lean.Json := #[]
              for ctor in ind.ctors do
                let ci ← Lean.getConstInfo ctor
                constructors := constructors.push (Lean.Json.mkObj [
                  ("name",Lean.toJson ctor.toString),("type",Lean.toJson (← render ci.type))])
              pure (Lean.Json.mkObj [("kind",Lean.toJson "kernel_inductive"),
                ("constructors",Lean.Json.arr constructors)])
          | _ => throwError "Unexpected bodyless declaration {name}"
    rows := rows.push (Lean.Json.mkObj [
      ("name",Lean.toJson name.toString),("type",Lean.toJson (← render info.type)),
      ("body",body),("axioms",Lean.toJson (axes.map Lean.Name.toString))])
    IO.FS.withFile "../PUBLIC_FIRST_AUDIT_ENTRIES.jsonl" .append fun stream =>
      stream.putStrLn rows.back!.compress
  IO.FS.writeFile "../PUBLIC_FIRST_AUDIT.json" (Lean.Json.arr rows |>.pretty)
