import Source3.KeygenSourceLines
import Source3.KeygenLexicalChunks

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000
set_option Elab.async false

/- Generated by tools/keygen_intermediate_tokens.py; the kernel binds every token. -/
namespace FT1536.Source3.KeygenIntermediateTokensReduce1
def text0 : String := "\t\tpoly_big_to_fp(rt1, Ft, FGlen, llen,\n"
def text1 : String := "\t\t\tlogn, full, maxbl_FG, scale_FG);\n"
def text2 : String := "\t\tpoly_big_to_fp(rt2, Gt, FGlen, llen,\n"
def text3 : String := "\t\t\tlogn, full, maxbl_FG, scale_FG);\n"
def text4 : String := "\n"
def text5 : String := "\t\tif (fk->ternary) {\n"
def text6 : String := "\t\t\tfalcon_FFT3(rt1, logn, full);\n"
def text7 : String := "\t\t\tfalcon_FFT3(rt2, logn, full);\n"
def text8 : String := "\t\t\tfalcon_poly_mul_fft3(rt1, rt3, logn, full);\n"
def text9 : String := "\t\t\tfalcon_poly_mul_fft3(rt2, rt4, logn, full);\n"
def text10 : String := "\t\t\tfalcon_poly_add_fft3(rt2, rt1, logn, full);\n"
def text11 : String := "\t\t\tfalcon_poly_mul_autoadj_fft3(rt2, rt5, logn, full);\n"
def text12 : String := "\t\t\tfalcon_iFFT3(rt2, logn, full);\n"
def text13 : String := "\t\t} else {\n"
def text14 : String := "\t\t\tfalcon_FFT(rt1, logn);\n"
def text15 : String := "\t\t\tfalcon_FFT(rt2, logn);\n"
def text16 : String := "\t\t\tfalcon_poly_mul_fft(rt1, rt3, logn);\n"
def text17 : String := "\t\t\tfalcon_poly_mul_fft(rt2, rt4, logn);\n"
def text18 : String := "\t\t\tfalcon_poly_add_fft(rt2, rt1, logn);\n"
def text19 : String := "\t\t\tfalcon_poly_mul_autoadj_fft(rt2, rt5, logn);\n"
def text20 : String := "\t\t\tfalcon_iFFT(rt2, logn);\n"
def text21 : String := "\t\t}\n"
def tail22 : List String := []
def tail21 : List String := text21::tail22
def tail20 : List String := text20::tail21
def tail19 : List String := text19::tail20
def tail18 : List String := text18::tail19
def tail17 : List String := text17::tail18
def tail16 : List String := text16::tail17
def tail15 : List String := text15::tail16
def tail14 : List String := text14::tail15
def tail13 : List String := text13::tail14
def tail12 : List String := text12::tail13
def tail11 : List String := text11::tail12
def tail10 : List String := text10::tail11
def tail9 : List String := text9::tail10
def tail8 : List String := text8::tail9
def tail7 : List String := text7::tail8
def tail6 : List String := text6::tail7
def tail5 : List String := text5::tail6
def tail4 : List String := text4::tail5
def tail3 : List String := text3::tail4
def tail2 : List String := text2::tail3
def tail1 : List String := text1::tail2
def tail0 : List String := text0::tail1
def lines : List String := tail0
theorem line0 : Pinned.keygenLines[6251]?=some text0 := by decide +kernel
theorem line1 : Pinned.keygenLines[6252]?=some text1 := by decide +kernel
theorem line2 : Pinned.keygenLines[6253]?=some text2 := by decide +kernel
theorem line3 : Pinned.keygenLines[6254]?=some text3 := by decide +kernel
theorem line4 : Pinned.keygenLines[6255]?=some text4 := by decide +kernel
theorem line5 : Pinned.keygenLines[6256]?=some text5 := by decide +kernel
theorem line6 : Pinned.keygenLines[6257]?=some text6 := by decide +kernel
theorem line7 : Pinned.keygenLines[6258]?=some text7 := by decide +kernel
theorem line8 : Pinned.keygenLines[6259]?=some text8 := by decide +kernel
theorem line9 : Pinned.keygenLines[6260]?=some text9 := by decide +kernel
theorem line10 : Pinned.keygenLines[6261]?=some text10 := by decide +kernel
theorem line11 : Pinned.keygenLines[6262]?=some text11 := by decide +kernel
theorem line12 : Pinned.keygenLines[6263]?=some text12 := by decide +kernel
theorem line13 : Pinned.keygenLines[6264]?=some text13 := by decide +kernel
theorem line14 : Pinned.keygenLines[6265]?=some text14 := by decide +kernel
theorem line15 : Pinned.keygenLines[6266]?=some text15 := by decide +kernel
theorem line16 : Pinned.keygenLines[6267]?=some text16 := by decide +kernel
theorem line17 : Pinned.keygenLines[6268]?=some text17 := by decide +kernel
theorem line18 : Pinned.keygenLines[6269]?=some text18 := by decide +kernel
theorem line19 : Pinned.keygenLines[6270]?=some text19 := by decide +kernel
theorem line20 : Pinned.keygenLines[6271]?=some text20 := by decide +kernel
theorem line21 : Pinned.keygenLines[6272]?=some text21 := by decide +kernel
theorem bytes22 : (Pinned.keygenLines.drop 6273).take tail22.length=tail22 := rfl
theorem bytes21 : (Pinned.keygenLines.drop 6272).take tail21.length=tail21 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6272 text21 tail22 line21 bytes22
theorem bytes20 : (Pinned.keygenLines.drop 6271).take tail20.length=tail20 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6271 text20 tail21 line20 bytes21
theorem bytes19 : (Pinned.keygenLines.drop 6270).take tail19.length=tail19 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6270 text19 tail20 line19 bytes20
theorem bytes18 : (Pinned.keygenLines.drop 6269).take tail18.length=tail18 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6269 text18 tail19 line18 bytes19
theorem bytes17 : (Pinned.keygenLines.drop 6268).take tail17.length=tail17 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6268 text17 tail18 line17 bytes18
theorem bytes16 : (Pinned.keygenLines.drop 6267).take tail16.length=tail16 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6267 text16 tail17 line16 bytes17
theorem bytes15 : (Pinned.keygenLines.drop 6266).take tail15.length=tail15 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6266 text15 tail16 line15 bytes16
theorem bytes14 : (Pinned.keygenLines.drop 6265).take tail14.length=tail14 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6265 text14 tail15 line14 bytes15
theorem bytes13 : (Pinned.keygenLines.drop 6264).take tail13.length=tail13 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6264 text13 tail14 line13 bytes14
theorem bytes12 : (Pinned.keygenLines.drop 6263).take tail12.length=tail12 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6263 text12 tail13 line12 bytes13
theorem bytes11 : (Pinned.keygenLines.drop 6262).take tail11.length=tail11 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6262 text11 tail12 line11 bytes12
theorem bytes10 : (Pinned.keygenLines.drop 6261).take tail10.length=tail10 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6261 text10 tail11 line10 bytes11
theorem bytes9 : (Pinned.keygenLines.drop 6260).take tail9.length=tail9 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6260 text9 tail10 line9 bytes10
theorem bytes8 : (Pinned.keygenLines.drop 6259).take tail8.length=tail8 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6259 text8 tail9 line8 bytes9
theorem bytes7 : (Pinned.keygenLines.drop 6258).take tail7.length=tail7 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6258 text7 tail8 line7 bytes8
theorem bytes6 : (Pinned.keygenLines.drop 6257).take tail6.length=tail6 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6257 text6 tail7 line6 bytes7
theorem bytes5 : (Pinned.keygenLines.drop 6256).take tail5.length=tail5 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6256 text5 tail6 line5 bytes6
theorem bytes4 : (Pinned.keygenLines.drop 6255).take tail4.length=tail4 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6255 text4 tail5 line4 bytes5
theorem bytes3 : (Pinned.keygenLines.drop 6254).take tail3.length=tail3 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6254 text3 tail4 line3 bytes4
theorem bytes2 : (Pinned.keygenLines.drop 6253).take tail2.length=tail2 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6253 text2 tail3 line2 bytes3
theorem bytes1 : (Pinned.keygenLines.drop 6252).take tail1.length=tail1 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6252 text1 tail2 line1 bytes2
theorem bytes0 : (Pinned.keygenLines.drop 6251).take tail0.length=tail0 :=
  KeygenSourceLines.consSlice Pinned.keygenLines 6251 text0 tail1 line0 bytes1
theorem bytes : (Pinned.keygenLines.drop 6251).take 22=lines := bytes0
def group0 : List String := [text0]
def words0 : List B20.C.Token := ["poly_big_to_fp","(","rt1",",","Ft",",","FGlen",",","llen",","].map String.toList
theorem lex0 : KeygenLexicalChunks.Checked group0 words0 := by
  constructor <;> decide +kernel
def group1 : List String := [text1]
def words1 : List B20.C.Token := ["logn",",","full",",","maxbl_FG",",","scale_FG",")",";"].map String.toList
theorem lex1 : KeygenLexicalChunks.Checked group1 words1 := by
  constructor <;> decide +kernel
def group2 : List String := [text2]
def words2 : List B20.C.Token := ["poly_big_to_fp","(","rt2",",","Gt",",","FGlen",",","llen",","].map String.toList
theorem lex2 : KeygenLexicalChunks.Checked group2 words2 := by
  constructor <;> decide +kernel
def group3 : List String := [text3]
def words3 : List B20.C.Token := ["logn",",","full",",","maxbl_FG",",","scale_FG",")",";"].map String.toList
theorem lex3 : KeygenLexicalChunks.Checked group3 words3 := by
  constructor <;> decide +kernel
def group4 : List String := [text4]
def words4 : List B20.C.Token := [].map String.toList
theorem lex4 : KeygenLexicalChunks.Checked group4 words4 := by
  constructor <;> decide +kernel
def group5 : List String := [text5]
def words5 : List B20.C.Token := ["if","(","fk","-",">","ternary",")","{"].map String.toList
theorem lex5 : KeygenLexicalChunks.Checked group5 words5 := by
  constructor <;> decide +kernel
def group6 : List String := [text6]
def words6 : List B20.C.Token := ["falcon_FFT3","(","rt1",",","logn",",","full",")",";"].map String.toList
theorem lex6 : KeygenLexicalChunks.Checked group6 words6 := by
  constructor <;> decide +kernel
def group7 : List String := [text7]
def words7 : List B20.C.Token := ["falcon_FFT3","(","rt2",",","logn",",","full",")",";"].map String.toList
theorem lex7 : KeygenLexicalChunks.Checked group7 words7 := by
  constructor <;> decide +kernel
def group8 : List String := [text8]
def words8 : List B20.C.Token := ["falcon_poly_mul_fft3","(","rt1",",","rt3",",","logn",",","full",")",";"].map String.toList
theorem lex8 : KeygenLexicalChunks.Checked group8 words8 := by
  constructor <;> decide +kernel
def group9 : List String := [text9]
def words9 : List B20.C.Token := ["falcon_poly_mul_fft3","(","rt2",",","rt4",",","logn",",","full",")",";"].map String.toList
theorem lex9 : KeygenLexicalChunks.Checked group9 words9 := by
  constructor <;> decide +kernel
def group10 : List String := [text10]
def words10 : List B20.C.Token := ["falcon_poly_add_fft3","(","rt2",",","rt1",",","logn",",","full",")",";"].map String.toList
theorem lex10 : KeygenLexicalChunks.Checked group10 words10 := by
  constructor <;> decide +kernel
def group11 : List String := [text11]
def words11 : List B20.C.Token := ["falcon_poly_mul_autoadj_fft3","(","rt2",",","rt5",",","logn",",","full",")",";"].map String.toList
theorem lex11 : KeygenLexicalChunks.Checked group11 words11 := by
  constructor <;> decide +kernel
def group12 : List String := [text12]
def words12 : List B20.C.Token := ["falcon_iFFT3","(","rt2",",","logn",",","full",")",";"].map String.toList
theorem lex12 : KeygenLexicalChunks.Checked group12 words12 := by
  constructor <;> decide +kernel
def group13 : List String := [text13]
def words13 : List B20.C.Token := ["}","else","{"].map String.toList
theorem lex13 : KeygenLexicalChunks.Checked group13 words13 := by
  constructor <;> decide +kernel
def group14 : List String := [text14]
def words14 : List B20.C.Token := ["falcon_FFT","(","rt1",",","logn",")",";"].map String.toList
theorem lex14 : KeygenLexicalChunks.Checked group14 words14 := by
  constructor <;> decide +kernel
def group15 : List String := [text15]
def words15 : List B20.C.Token := ["falcon_FFT","(","rt2",",","logn",")",";"].map String.toList
theorem lex15 : KeygenLexicalChunks.Checked group15 words15 := by
  constructor <;> decide +kernel
def group16 : List String := [text16]
def words16 : List B20.C.Token := ["falcon_poly_mul_fft","(","rt1",",","rt3",",","logn",")",";"].map String.toList
theorem lex16 : KeygenLexicalChunks.Checked group16 words16 := by
  constructor <;> decide +kernel
def group17 : List String := [text17]
def words17 : List B20.C.Token := ["falcon_poly_mul_fft","(","rt2",",","rt4",",","logn",")",";"].map String.toList
theorem lex17 : KeygenLexicalChunks.Checked group17 words17 := by
  constructor <;> decide +kernel
def group18 : List String := [text18]
def words18 : List B20.C.Token := ["falcon_poly_add_fft","(","rt2",",","rt1",",","logn",")",";"].map String.toList
theorem lex18 : KeygenLexicalChunks.Checked group18 words18 := by
  constructor <;> decide +kernel
def group19 : List String := [text19]
def words19 : List B20.C.Token := ["falcon_poly_mul_autoadj_fft","(","rt2",",","rt5",",","logn",")",";"].map String.toList
theorem lex19 : KeygenLexicalChunks.Checked group19 words19 := by
  constructor <;> decide +kernel
def group20 : List String := [text20]
def words20 : List B20.C.Token := ["falcon_iFFT","(","rt2",",","logn",")",";"].map String.toList
theorem lex20 : KeygenLexicalChunks.Checked group20 words20 := by
  constructor <;> decide +kernel
def group21 : List String := [text21]
def words21 : List B20.C.Token := ["}"].map String.toList
theorem lex21 : KeygenLexicalChunks.Checked group21 words21 := by
  constructor <;> decide +kernel
def groups : List (List String) := [group0,group1,group2,group3,group4,group5,group6,group7,group8,group9,group10,group11,group12,group13,group14,group15,group16,group17,group18,group19,group20,group21]
def words : List (List B20.C.Token) := [words0,words1,words2,words3,words4,words5,words6,words7,words8,words9,words10,words11,words12,words13,words14,words15,words16,words17,words18,words19,words20,words21]
def tokens : List B20.C.Token := words.flatten++KeygenLexicalChunks.closing
theorem partition : groups.flatten=lines := rfl
theorem lexed : List.Forall₂ KeygenLexicalChunks.Checked groups words := List.Forall₂.cons lex0 (List.Forall₂.cons lex1 (List.Forall₂.cons lex2 (List.Forall₂.cons lex3 (List.Forall₂.cons lex4 (List.Forall₂.cons lex5 (List.Forall₂.cons lex6 (List.Forall₂.cons lex7 (List.Forall₂.cons lex8 (List.Forall₂.cons lex9 (List.Forall₂.cons lex10 (List.Forall₂.cons lex11 (List.Forall₂.cons lex12 (List.Forall₂.cons lex13 (List.Forall₂.cons lex14 (List.Forall₂.cons lex15 (List.Forall₂.cons lex16 (List.Forall₂.cons lex17 (List.Forall₂.cons lex18 (List.Forall₂.cons lex19 (List.Forall₂.cons lex20 (List.Forall₂.cons lex21 (List.Forall₂.nil))))))))))))))))))))))
theorem source : KeygenLexicalChunks.Bound ((Pinned.keygenLines.drop 6251).take 22) tokens :=
  KeygenLexicalChunks.transport _ _ _ bytes (.parts groups words partition lexed rfl)
end FT1536.Source3.KeygenIntermediateTokensReduce1
