import Source3.ShakeSource
import Source3.KeygenSmallSource

set_option maxRecDepth 32768
set_option maxHeartbeats 2000000

/- Word-array source semantics for the actual SHAKE process_block body.
   Array expressions use ordinary C integer evaluation and actual Load64;
   the special expression names are generated by the array grammar, never
   supplied as an abstract Keccak call. No cryptographic property is used. -/
namespace FT1536.Source3.ShakeBlock
open C99ArrayReference (Name State bindValue)
open C99IntegerReference (Value Ty)
open C99MemoryReference
open B20.C (Token)

def readName (name : Name) : Name := "$read64:".toList++name

inductive ReadCall (s : State) : C99ScalarReference.CallRelation where
  | read (name : Name) (index : Value) (root p : ArrayPointer) (w : BitVec 64)
      (binding : s.arrays name=some root) (nonnegative : 0 ≤ index.integer)
      (address : PointerAdd root index.integer.toNat p) (value : Load64 s.heap p w) :
      ReadCall s (readName name) [index] (.uint64 w)

def Eval (s : State) (e : CLogic.Expr) (v : Value) : Prop :=
  C99ScalarReference.Eval (ReadCall s) s.locals (C99Frontend.expression e) v

def unary (sub : CLogicParser.Parser) : Nat → CLogicParser.Parser
  | 0,_ => none
  | fuel+1,['-']::rest => (unary sub fuel rest).map (fun (e,tail) => (.neg e,tail))
  | fuel+1,['~']::rest => (unary sub fuel rest).map (fun (e,tail) => (.bitNot e,tail))
  | fuel+1,['!']::rest => (unary sub fuel rest).map (fun (e,tail) => (.lnot e,tail))
  | fuel+1,['(']::ty::[')']::rest =>
      match B20.C.Scalar.typeToken ty with
      | some t => (unary sub fuel rest).map (fun (e,tail) => (.cast t e,tail))
      | none => do
          let (e,tail) ← sub (ty::[')']::rest)
          match tail with | [')']::tail => pure (e,tail) | _ => none
  | _+1,['(']::rest => do
      let (e,tail) ← sub rest
      match tail with | [')']::tail => pure (e,tail) | _ => none
  | _+1,name::['[']::rest => do
      if name≠"A".toList && name≠"RC".toList then none else do
        let (index,tail) ← sub rest
        match tail with
        | [']']::tail => pure (.call1 (readName name) index,tail)
        | _ => none
  | _+1,_::['(']::_ => none
  | _+1,t::rest =>
      if t.isEmpty then none
      else if B20.C.digit t.head! then (CLogicParser.number t).map (fun e => (e,rest))
      else if t.all B20.C.wordChar then some (.var t,rest) else none
  | _+1,[] => none

def expressionAt : Nat → Nat → CLogicParser.Parser
  | 0,_,_ => none
  | fuel+1,precedence,ts => do
      let sub := fun prec => expressionAt fuel prec
      let (head,rest) ← unary (sub 1) fuel ts
      CLogicParser.parseMore sub precedence fuel head rest
def expression : CLogicParser.Parser := expressionAt 32 1

inductive Stmt where
  | scalar (code : CLogic.Stmt)
  | store (array : Name) (index value : CLogic.Expr)
  | skip
  | seq (first second : Stmt)
  | scope (locals : List Name) (body : Stmt)
  | loop (condition : CLogic.Expr) (body increment : Stmt)
  deriving DecidableEq, Repr

def chain : List Stmt → Stmt
  | [] => .skip
  | first::rest => .seq first (chain rest)

def clause (ending : Token) : List Token → Option (Stmt × List Token)
  | name::op::rest => do
      let (value,tail) ← expression rest
      match tail with
      | last::tail =>
          if last≠ending then none else do
            let code ← if op=['='] then some (CLogic.Stmt.assign name value)
              else (B20.C.Scalar.updateOp op).map (fun operation => .update name operation value)
            pure (.scalar code,tail)
      | _ => none
  | _ => none

def simple : List Token → Option (Stmt × List Token)
  | name::['[']::rest => do
      let (index,rest) ← expression rest
      match rest with
      | [']']::op::rest => do
          let (rhs,tail) ← expression rest
          let value ← if op=['='] then some rhs else
            (B20.C.Scalar.updateOp op).map (fun operation => .bin operation (.call1 (readName name) index) rhs)
          match tail with
          | [';']::tail => pure (.store name index value,tail)
          | _ => none
      | _ => none
  | ty::rest =>
      match B20.C.Scalar.typeToken ty with
      | some t => do
          let (names,tail) ← B20.C.Scalar.names 32 rest
          pure (.scalar (.declare t names),tail)
      | none => clause [';'] (ty::rest)
  | _ => none

def declarations : Stmt → List Name
  | .scalar (.declare _ ns) => ns
  | .seq a b => declarations a++declarations b
  | _ => []

mutual
  def statement : Nat → List Token → Option (Stmt × List Token)
    | 0,_ => none
    | fuel+1,['{']::rest => do
        let (code,rest) ← body fuel rest
        pure (.scope (declarations code) code,rest)
    | fuel+1,['f','o','r']::['(']::rest => do
        let (initial,rest) ← clause [';'] rest
        let (condition,rest) ← expression rest
        match rest with
        | [';']::rest => do
            let (increment,rest) ← clause [')'] rest
            let (inner,rest) ← statement fuel rest
            pure (.seq initial (.loop condition inner increment),rest)
        | _ => none
    | _+1,rest => simple rest
  def body : Nat → List Token → Option (Stmt × List Token)
    | 0,_ => none
    | _+1,['}']::rest => some (.skip,rest)
    | fuel+1,rest => do
        let (head,rest) ← statement fuel rest
        let (tail,rest) ← body fuel rest
        pure (.seq head tail,rest)
end

/- process_block has a single partially-unrolled for-loop and one complete
   instruction per physical body line. Parse those lines separately so the
   unchanged recursion limit is not spent tokenizing a 400-line expression.
   The scaffold parser still checks all declarations and the actual loop
   initialization, comparison and increment; the two closing braces are
   checked separately. Blank lines are the only lines mapped directly to skip. -/
def instruction (line : String) : Option Stmt := do
  let tokens ← C99ProcedureParser.tokens line.toList
  if tokens.isEmpty then pure .skip else do
    let (code,tail) ← simple tokens
    if tail.isEmpty then pure code else none
def iterationLines : List String := (ShakeSource.sourceLines.drop 123).take 388
def parseLines : List String → Option (List Stmt)
  | [] => some []
  | line::rest => do
      let first ← instruction line
      let tail ← parseLines rest
      pure (first::tail)
theorem parse_append (left right : List String) :
    parseLines (left++right)=(parseLines left).bind (fun a => (parseLines right).map (a++·)) := by
  induction left with
  | nil => simp [parseLines]
  | cons line rest ih =>
      simp only [List.cons_append,parseLines,ih]
      cases first : instruction line with
      | none => simp
      | some head =>
        cases parsed : parseLines rest with
        | none => simp
        | some tail =>
          cases parseLines right <;> simp
def instructions : Option (List Stmt) := parseLines iterationLines
def prologue : List Stmt := [
  .scalar (.declare .u64 ["t0".toList,"t1".toList,"t2".toList,"t3".toList,"t4".toList]),
  .scalar (.declare .u64 ["tt0".toList,"tt1".toList,"tt2".toList,"tt3".toList]),
  .scalar (.declare .u64 ["t".toList,"kt".toList]),
  .scalar (.declare .u64 ["c0".toList,"c1".toList,"c2".toList,"c3".toList,"c4".toList,"bnn".toList]),
  .scalar (.declare .i32 ["j".toList])]
def initial : Stmt := .scalar (.assign "j".toList (.literal .i32 0))
def condition : CLogic.Expr := .cmp .lt (.var "j".toList) (.literal .i32 24)
def increment : Stmt := .scalar (.update "j".toList .add (.literal .i32 2))
def assemble (steps : List Stmt) : Stmt :=
  chain (prologue++[.seq initial (.loop condition (.scope [] (chain steps)) increment)])
def scaffold : Option Stmt := do
  let tokens ← C99ProcedureParser.tokens
    ((((ShakeSource.sourceLines.drop 112).take 11).flatMap String.toList)++"}\n}\n".toList)
  let (code,tail) ← body 32 tokens
  if tail.isEmpty then pure code else none
theorem scaffold_source : scaffold=some (assemble []) := by decide
theorem closing_source : (ShakeSource.sourceLines.drop 511).take 2=["\t}\n","}\n"] := by decide
theorem signature_source : (ShakeSource.sourceLines.drop 109).take 3 =
    ["static void\n","process_block(uint64_t *A)\n","{\n"] := by decide

inductive Exec : Stmt → State → State → Prop where
  | scalar (code : CLogic.Stmt) (before : State) (env : C99ScalarReference.Env)
      (body : C99ScalarReference.Exec (ReadCall before) before.locals (C99Frontend.scalar code) (.normal env)) :
      Exec (.scalar code) before {before with locals := env}
  | store (name : Name) (index value : CLogic.Expr) (before : State) (after : Memory)
      (p : ArrayPointer) (v : Value) (address : C99ArrayReference.Pointer before name index p)
      (evaluated : Eval before value v) (write : Store64 before.heap p (BitVec.ofInt 64 v.integer) after) :
      Exec (.store name index value) before {before with heap := after}
  | skip (s : State) : Exec .skip s s
  | seq (first second : Stmt) (before middle after : State)
      (head : Exec first before middle) (tail : Exec second middle after) : Exec (.seq first second) before after
  | scope (locals : List Name) (body : Stmt) (before after : State) (inner : Exec body before after) :
      Exec (.scope locals body) before (C99ArrayReference.restoreScope before after locals [])
  | loopFalse (condition : CLogic.Expr) (body increment : Stmt) (before : State) (v : Value)
      (guard : Eval before condition v) (zero : v.integer=0) : Exec (.loop condition body increment) before before
  | loopNext (condition : CLogic.Expr) (body increment : Stmt) (before middle next after : State) (v : Value)
      (guard : Eval before condition v) (nonzero : v.integer≠0) (iteration : Exec body before middle)
      (update : Exec increment middle next) (rest : Exec (.loop condition body increment) next after) :
      Exec (.loop condition body increment) before after

theorem pointers_frame (statement : Stmt) (before after : State) (source : Exec statement before after) :
    after.arrays=before.arrays := by
  induction source with
  | scalar | store | skip | loopFalse => rfl
  | seq _ _ _ _ _ _ _ ih1 ih2 => exact ih2.trans ih1
  | scope _ _ _ _ _ ih => exact ih
  | loopNext _ _ _ _ _ _ _ _ _ _ _ _ _ ih1 ih2 ih3 => exact ih3.trans (ih2.trans ih1)

def writesOnly (name : Name) : Stmt → Bool
  | .scalar _ | .skip => true
  | .store target _ _ => target==name
  | .seq first second | .loop _ first second => writesOnly name first && writesOnly name second
  | .scope _ body => writesOnly name body

def Outside (p : ArrayPointer) (block offset : Nat) : Prop :=
  block≠p.block ∨ offset<p.base ∨ p.base+p.elementBytes*p.count≤offset

def Frame (before after : Memory) (root : ArrayPointer) : Prop :=
  after.size=before.size ∧ after.writable=before.writable ∧
    ∀ block offset, Outside root block offset → after.bytes block offset=before.bytes block offset

theorem frame_trans (a b c : Memory) (root : ArrayPointer) (first : Frame a b root) (second : Frame b c root) :
    Frame a c root := ⟨second.1.trans first.1,second.2.1.trans first.2.1,
      fun block offset outside => (second.2.2 block offset outside).trans (first.2.2 block offset outside)⟩

theorem memory_frame (statement : Stmt) (before after : State) (root : ArrayPointer)
    (source : Exec statement before after) (binding : before.arrays "A".toList=some root)
    (checked : writesOnly "A".toList statement=true) : Frame before.heap after.heap root := by
  induction source with
  | scalar | skip | loopFalse => exact ⟨rfl,rfl,fun _ _ _ => rfl⟩
  | store name index value before after p v address evaluated write =>
      have hn : name="A".toList := beq_iff_eq.mp checked
      subst name
      cases address with
      | add original p i bound value nonnegative within =>
        have he : original=root := Option.some.inj (bound.symm.trans binding)
        subst original
        cases within with
        | within within =>
          refine ⟨write.2.2.2.1,write.2.2.2.2.1,?_⟩
          intro block offset outside
          apply write.2.2.2.2.2.2 block offset
          have width : root.elementBytes=8 := write.2.1
          have allocated : root.index+i.integer.toNat<root.count := write.1.2.2.1
          dsimp [Outside,ArrayPointer.offset] at outside ⊢
          simp only [width] at outside ⊢
          omega
  | seq first second before middle after head tail ih1 ih2 =>
      have checks := Bool.and_eq_true_iff.mp checked
      exact frame_trans _ _ _ root (ih1 binding checks.1)
        (ih2 ((congrFun (pointers_frame _ before middle head) _).trans binding) checks.2)
  | scope names body before after inner ih => exact ih binding checked
  | loopNext condition body increment before middle next after v guard nonzero iteration update rest ih1 ih2 ih3 =>
      have checks := Bool.and_eq_true_iff.mp checked
      have middleBinding := (congrFun (pointers_frame _ before middle iteration) _).trans binding
      have nextBinding := (congrFun (pointers_frame _ middle next update) _).trans middleBinding
      exact frame_trans _ _ _ root (ih1 binding checks.1)
        (frame_trans _ _ _ root (ih2 middleBinding checks.2) (ih3 nextBinding checked))

end FT1536.Source3.ShakeBlock
