# Finite interface do przyszłego PRNG_REAL_TO_IID_BUFFER

Consumer otrzymuje J<=16, legal stateful sequence source SHAKE56 calls,
type0→1 i counter64/refill projection, actual getter schedule i resets.
Ideal oracle generuje nowy independent4096-byte block KAŻDEGO refill/init;
ordinal nigdy się nie cofa. Pomijane getter bytes i re-init tails są ujęte
osobno. H z RESOURCE_BOUND implikuje6352 blocks/26017792 generated bytes,
z complement<2^-1020, expected resources także jawnie wyeksportowane.

W przyszłym finite hybrid można użyć identycznego ghost budget bad event
i coupling do nieograniczonej idealnej gry. Budget exhaustion jest tagiem
proofu; nie wolno wstawić go jako nowego abortu obecnego C. Eksport nie daje
automatycznie real-game probability budget failure: wymaga właściwego hopu
i odpowiadającej mu miary/distinguishera/lossu.

OPEN: actual SHAKE seed/state law, correlated/repeated56-byte initialization,
ChaCha repeated states/counters i assumptions potrzebne dla indifferentiability
lub PRG security; composition z nonce/H2P i parent success. Nie traktować
56 bytes jako independent448-bit key. Nie zastępować real state przez
ideal key sampling bez oddzielnego uzasadnienia. W tym pakiecie nie
uruchamiano real seeded PRNG, KeyGen ani pełnego Sign/do_sign.

Po takim hopie pozostaje oddzielny reference-integer recovery/congruence,
Sign→Verify i security/CT. IID region bound2^-80 nie jest wpisem eta_pre
realnego M0. Kolejny etap uruchamia właściciel osobno po odbiorze.
