import json
from pathlib import Path
from replaylib import sha
W=Path.cwd();c=json.loads((W/'SCALAR_KERNEL_CERTIFICATE.json').read_text());r=json.loads((W/'artifacts/fresh_replay.json').read_text());assert r['status']=='FRESH_REPLAY_PASS' and r['matches'] and r['matched']==r['expected_files']
assert json.loads((W/'artifacts/replay_negative.json').read_text())['destination_created'] is False
result=dict(c);result.update(fresh_replay=dict(status=r['status'],matched=r['matched'],expected=r['expected_files'],receipt='artifacts/fresh_replay.json',receipt_sha256=sha(W/'artifacts/fresh_replay.json'),external_anchor_sha256=r['external_manifest_sha256']),postfreeze_recipe='scripts/replay_controller.py ABSENT_DEST EXTERNAL_OUTPUTS_SHA256; later writes only in fresh DEST',certificate_sha256=sha(W/'SCALAR_KERNEL_CERTIFICATE.json'),own_jobs='completed bounded computations; no background worker or nightly RUN_002 launched')
(W/'RESULT.json').write_text(json.dumps(result,indent=2)+'\n')
report=f'''# FT1536 — SCALAR_KERNEL_IID

Autor projektu: **Niirmata**. Data: 2026-09-21.

## Werdykt i granica gry

**H3_SCALAR_KERNEL_PROVED_FOR_PINNED_IID_BUFFER_MODEL**.

Dowiedziono dokładnego prawa skalarnego kernela oryginalnego sampler_large
w jawnej grze **IID_BUFFER**. Każdy refill dostarcza fresh independent uniform
4096-byte block; original getters, drops, CDF, FPEMU i rejection pozostają
źródłowe. **Przejście od rzeczywistego ChaCha/SHAKE do IID_BUFFER pozostaje OPEN**:
real_prng_to_iid_bridge_proved=false. Ten raport nie nadaje statusu pełnego
prawa realnego source Sign ani jego zakończenia lub bezpieczeństwa.

## Wynik w IID_BUFFER

Dla każdego required NumericCenter mu word, actual normalized stored/paired
sigma word i legalnego typed context/faultNONE, warunkowo względem legalnej
PAST historii (bez conditioning na unread buffer/future tape):

- Exact CDF masses n_j,k/2^128 z literalnych5×512 thresholds, strict U<T,
  shared U128 i pierwszego source banku. Supports29/59/118/235/365.
- Exact integer BerExp probability:0 dla e>=64; w pozostałym zakresie
  min(Z,2^55)/2^(e+55), Z=expm_C(rB)>>8. Cutoff, saturation i oba word reads
  rozliczone; nie założono exp(-x),remainder[0,log2) lub komentarza393.
- Nowy high-word limb/carry refinement oraz mały source trunc/Horner proof.
  Positive atom k0,smaller delta daje Z>=2^54+92 i **A>=1/256** uniwersalnie.
- **Pr_IID[N=n,Y=y|PAST]=(1-A)^(n-1)w_y**, returned PMF **w_y/A**,
  **Pr_IID[N>m|PAST]<=(255/256)^m**, **Pr_IID[N=∞|PAST]=0**,
  **E_IID[N|PAST]<=256**. Positivity A wyprowadzona przed normalization.
- Actual schedule u64,u64,u8,u64,u64:33 returned bytes/proposal, pointer
  cutoff4087, drops≤9/refill; R<=min(n,1+floor(33n/4087)). E returned bytes≤8448.
  Generated bytes/refills i entry block są osobnymi zasobami.
- Conditional fresh unread tail po return przez product-measure/stopping-time
  argument. Następny mu/sigma może zależeć od poprzednich outputs. Nie
  zastąpiono source adaptive composition iloczynem independent marginals.

Exact source maps, legal domains i fault/normal/nonreturn tags opisano w CLAIM,
BYTE_SCHEDULE,CDF_MASS,BEREXP_INTEGER_KERNEL,ACCEPTANCE_FLOOR,REJECTION_LAW.

## Otwarte kwestie i ograniczenia

1. **PRNG_REAL_TO_IID_BUFFER:** source state56/key32+IV16+counter64,root SHAKE,
   actual ChaCha counter/refill/getter transcript game i computational loss.
  56 bytes nie oznacza automatycznie standardowego448-bitowego klucza.
2. **SCALAR_GAUSSIAN_COMPARISON:** exact K_C kontra odpowiednia niezależna
   reference law, z cutoff/quantization/normalizer i kierunkiem miary.
3. **ORDERED_JOINT_KERNEL/H6P:** actual recursive order, adaptive dependence,
   joint WholeCallBad obu vectors/wszystkich completed attempts i retry.
4. Safe16,reference recovery,Sign→Verify,whole real Sign termination,security
   i full CT nadal OPEN. Historyczny **POST pozostaje PARTIAL_PROOF**.

A.s. w IID nie jest all-tapes termination. Local all-zero continuation ma
powtarzalne k29 i cutoff rejection; bounded source fixture obserwuje124 odrzucenia,
potem **HARNESS_EXHAUSTED/NONE**, nie źródłowe0. To ilustracja zakresu lokalnego
modelu, bez required emitted-history membership i bez zgłoszenia nowego błędu C.
Nie dodano clippingu, abortu, source capu, key gate, conditioning ani eta_pre.

## Dowody i kontrole

- **Lean4.34/Std:32 moduły,208 twierdzeń,37 nowych**; pełne nowe types/terms,
  axioms wszystkich konsumowanych twierdzeń, clean final logs. Tylko standardowe
  propext/Classical.choice/Quot.sound; brak sorry/admit/native_decide/ofReduceBool
  i warning suppression.25 inherited modules przebudowane od źródła.
- Normal oraz **ASan/UBSan**:32 native batches każdy, wszystkie word/trace/
  context/canary comparisons exact.2383 CDF boundaries,4096 valid start pointers
  +u8 boundary,16528 primitive cases,204 BerExp cases,21114 iteration atoms,
 13 oryginalnych sampler traces (normal,stutter,rejections,faults,exhaustion).
- **54 exact normalized PMFs**, independent Sage QQ oracle,4449 small-domain
  native trunc checks,65536 reduced-limb pairs i120 reduced comparator counts.
- **13 meaningful model mutations +no-op** rzeczywiście wykonano. Full baseline/
  changed evidence i failed Lean/Sage attempts zachowane w FAILED_ROUTES/logs.
- **Fresh rehearsal FRESH_REPLAY_PASS {r['matched']}/{r['expected_files']}** regenerated
  semantic path/SHA matches, bez project cache/olean/bin, package RO,
  Dokumenty/stages ukryte, network-off,single bounded worker. Sealed receipt:
  artifacts/fresh_replay.json, z niepustymi matches[{{path,sha256}}].
- Wrong external pin odrzucony PRZED nowym DEST. Standard replay i freeze
  recipe są w REPLAY/OUTPUT_SCOPE; źródłowy scope pozostał niezmieniony.

**Proof kind: mixed kernel/exact integer-QQ/universal analytical product-measure
proof.** Probability filtration/stopping time/geometric limits oraz source C
instantiation są jawnie analityczne; fully_kernelized=false,C_compiler_verified=false.
Finite fixture success nie zastępuje universal source bounds/probability proofu.

## Piny i zakres przekazania

TASK SHA-256: `f80f7ef0592e1f2bf99e15935d8bf6ac8687c7d9ac15f8e49c8d2eb2fb9e8eec`.
Bootstrap SHA-256: `eb890ea42dad55d397ebd6f71fad5457676d705e5443a5a672201a0ce6e553a8`.
BASE: `fe6f92af799dc11830998f8ddf9cf1dc591a448a`.
Source17-file pin: `56974571b46e8257bdd3b4097c8c70fded6bb4b94c64805f6e35ec80929a0985`.
SCALAR_KERNEL_CERTIFICATE.json SHA-256: `{sha(W/'SCALAR_KERNEL_CERTIFICATE.json')}`.
Fresh anchor SHA-256: `{r['external_manifest_sha256']}`.

source_changed=false,production_source_changed=false,new_source_patch_integrated=false,
owner_accepted=false. Bez Git/importu/nowych keys/seeds/private API/KeyGen/
pełnego Sign/do_sign lub real seeded PRNG. Nocny RUN_002 nieuruchomiony.
REPORT/OUTPUTS mają zewnętrzne hashe przekazane po freeze.

## Własne podsumowanie dla właściciela

**Co osiągnięto:** znane jest teraz dokładne prawo jednego źródłowego scalar
rejection call, jego dodatni próg akceptacji, ogon/średnia i pozostały bufor
**w zdefiniowanej grze IID_BUFFER**. Nie ukryto source rounding,cutoff lub drops.

**Co pozostaje otwarte:** rzeczywista ekspansja ChaCha/SHAKE nie została
utożsamiona z IID. Ten bridge i jego koszt, Gaussian comparison oraz pełna
ordered joint composition są osobnymi zadaniami. To jawna granica modelu,
a nie wykryty błąd źródła lub nieudana normalization w tym modelu.

**Znaczenie:** następny etap może konsumować exact conditional kernel wraz
z fresh-tail i resources, zamiast zakładać idealnego Gaussa lub niezależność
adaptacyjnych marginals. Pojedynczy K_seed[E]/p_K i kontrakt M0 są zachowane.

**Następny krok:** wykonać odrębny PRNG_REAL_TO_IID_BUFFER i/lub
SCALAR_GAUSSIAN_COMPARISON, potem ORDERED_JOINT_KERNEL/H6P według NEXT_INTERFACE.
Własne obliczenia kończą się na handoffie przed odrębną kampanią nocną.
'''
(W/'REPORT.md').write_text(report);print(json.dumps(dict(status=c['status'],report_sha256=sha(W/'REPORT.md'),fresh_matches=r['matched']),indent=2))
