import B20.Foundation.Core
import B20.Foundation.CExec
import B20.Foundation.SourceBinding
import B20.Foundation.Certificate
import B20.Foundation.CertificateTransport
import B20.Foundation.Probability
import B20.Foundation.EndToEnd

-- Dokładne drukowane typy eksportów (wejście do GOAL_SPEC)
#check @B20.Foundation.CExec
#check @B20.Foundation.evalStmt
#check @B20.Foundation.evalStmt_sound
#check @B20.Foundation.CExec_complete
#check @B20.Foundation.compile_refines
#check @B20.Foundation.u64Add_toNat
#check @B20.Foundation.Outcome.stuck_ne_abort
#check @B20.Foundation.SourceBinding
#check @B20.Foundation.checker_sound
#check @B20.Foundation.translateStmt
#check @B20.Foundation.SourceTranslation
#check @B20.Foundation.source17ReturnZero_translation
#check @B20.Foundation.source17ReturnZero_binding
#check @B20.Foundation.mutated_constant_rejected
#check @B20.Foundation.mutated_operator_rejected
#check @B20.Foundation.syntheticShape_binding
#check @B20.Foundation.RationalInterval.Certifies
#check @B20.Foundation.RationalInterval.checkSqrt2
#check @B20.Foundation.certificate_sound
#check @B20.Foundation.CertificateSound
#check @B20.Foundation.sqrt2Witness_sound
#check @B20.Foundation.false_inequality_rejected
#check @B20.Foundation.reversed_endpoint_rejected
#check @B20.Foundation.missing_denominator_rejected
#check @B20.Foundation.Transport.decodeNat
#check @B20.Foundation.Transport.decodeNat_encodeNat
#check @B20.Foundation.Transport.decodeInt
#check @B20.Foundation.ObservedKernel
#check @B20.Foundation.conditionalHistory
#check @B20.Foundation.totalVariation
#check @B20.Foundation.directedChi2
#check @B20.Foundation.totalVariation_self_zero
#check @B20.Foundation.directedChi2_self_zero
#check @B20.Foundation.pinnedKernel
#check @B20.Foundation.pinnedObserved
#check @B20.Foundation.pinned_observed_initState
#check @B20.Foundation.pinned_tv_self
#check @B20.Foundation.pinned_chi2_self
#check @B20.Foundation.pinned_conditionalHistory_state
#check @B20.Foundation.endToEndReceipt
#check @B20.Foundation.endToEnd_receipt_valid
#check @B20.Foundation.endToEnd_chain
