namespace B20.Pinned
def packLines : List String := ["static inline fpr\n", "FPR(int s, int e, uint64_t m)\n", "{\n", "\tfpr x;\n", "\tuint32_t t;\n", "\tunsigned f;\n", "\n", "\te += 1076;\n", "\tt = (uint32_t)e >> 31;\n", "\tm &= (uint64_t)t - 1;\n", "\tt = (uint32_t)(m >> 54);\n", "\te &= -(int)t;\n", "\tx = (((uint64_t)s << 63) | (m >> 2)) + ((uint64_t)(uint32_t)e << 52);\n", "\tf = (unsigned)m & 7U;\n", "\tx += (0xC8U >> f) & 1;\n", "\treturn x;\n", "}\n"]
def packChars : List Char := packLines.flatMap String.toList
def packTokens : List (List Char) := ["static", "inline", "fpr", "FPR", "(", "int", "s", ",", "int", "e", ",", "uint64_t", "m", ")", "{", "fpr", "x", ";", "uint32_t", "t", ";", "unsigned", "f", ";", "e", "+=", "1076", ";", "t", "=", "(", "uint32_t", ")", "e", ">>", "31", ";", "m", "&=", "(", "uint64_t", ")", "t", "-", "1", ";", "t", "=", "(", "uint32_t", ")", "(", "m", ">>", "54", ")", ";", "e", "&=", "-", "(", "int", ")", "t", ";", "x", "=", "(", "(", "(", "uint64_t", ")", "s", "<<", "63", ")", "|", "(", "m", ">>", "2", ")", ")", "+", "(", "(", "uint64_t", ")", "(", "uint32_t", ")", "e", "<<", "52", ")", ";", "f", "=", "(", "unsigned", ")", "m", "&", "7U", ";", "x", "+=", "(", "0xC8U", ">>", "f", ")", "&", "1", ";", "return", "x", ";", "}"].map String.toList
def rintLines : List String := ["static inline int64_t\n", "fpr_rint(fpr x)\n", "{\n", "\tuint64_t m, d;\n", "\tint e;\n", "\tuint32_t s, dd, f;\n", "\n", "\tm = ((x << 10) | ((uint64_t)1 << 62)) & (((uint64_t)1 << 63) - 1);\n", "\te = 1085 - ((int)(x >> 52) & 0x7FF);\n", "\tm &= -(uint64_t)((uint32_t)(e - 64) >> 31);\n", "\te &= 63;\n", "\td = fpr_ulsh(m, 63 - e);\n", "\tdd = (uint32_t)d | ((uint32_t)(d >> 32) & 0x1FFFFFFF);\n", "\tf = (uint32_t)(d >> 61) | ((dd | -dd) >> 31);\n", "\tm = fpr_ursh(m, e) + (uint64_t)((0xC8U >> f) & 1U);\n", "\ts = (uint32_t)(x >> 63);\n", "\treturn ((int64_t)m ^ -(int64_t)s) + (int64_t)s;\n", "}\n"]
def rintChars : List Char := rintLines.flatMap String.toList
def rintTokens : List (List Char) := ["static", "inline", "int64_t", "fpr_rint", "(", "fpr", "x", ")", "{", "uint64_t", "m", ",", "d", ";", "int", "e", ";", "uint32_t", "s", ",", "dd", ",", "f", ";", "m", "=", "(", "(", "x", "<<", "10", ")", "|", "(", "(", "uint64_t", ")", "1", "<<", "62", ")", ")", "&", "(", "(", "(", "uint64_t", ")", "1", "<<", "63", ")", "-", "1", ")", ";", "e", "=", "1085", "-", "(", "(", "int", ")", "(", "x", ">>", "52", ")", "&", "0x7FF", ")", ";", "m", "&=", "-", "(", "uint64_t", ")", "(", "(", "uint32_t", ")", "(", "e", "-", "64", ")", ">>", "31", ")", ";", "e", "&=", "63", ";", "d", "=", "fpr_ulsh", "(", "m", ",", "63", "-", "e", ")", ";", "dd", "=", "(", "uint32_t", ")", "d", "|", "(", "(", "uint32_t", ")", "(", "d", ">>", "32", ")", "&", "0x1FFFFFFF", ")", ";", "f", "=", "(", "uint32_t", ")", "(", "d", ">>", "61", ")", "|", "(", "(", "dd", "|", "-", "dd", ")", ">>", "31", ")", ";", "m", "=", "fpr_ursh", "(", "m", ",", "e", ")", "+", "(", "uint64_t", ")", "(", "(", "0xC8U", ">>", "f", ")", "&", "1U", ")", ";", "s", "=", "(", "uint32_t", ")", "(", "x", ">>", "63", ")", ";", "return", "(", "(", "int64_t", ")", "m", "^", "-", "(", "int64_t", ")", "s", ")", "+", "(", "int64_t", ")", "s", ";", "}"].map String.toList
def floorLines : List String := ["static inline long\n", "fpr_floor(fpr x)\n", "{\n", "\tuint64_t t, mask;\n", "\tint64_t xi;\n", "\tint e, cc;\n", "\n", "\te = (int)(x >> 52) & 0x7FF;\n", "\tt = x >> 63;\n", "\txi = (int64_t)(((x << 10) | ((uint64_t)1 << 62))\n", "\t\t& (((uint64_t)1 << 63) - 1));\n", "\txi = (xi ^ -(int64_t)t) + (int64_t)t;\n", "\tcc = 1085 - e;\n", "\txi = fpr_irsh(xi, cc & 63);\n", "\t/* FT1536: preserve the raw-word result with an unsigned selection. */\n", "\tmask = -(uint64_t)((uint32_t)(63 - cc) >> 31);\n", "\txi = (int64_t)(((uint64_t)xi & ~mask) | ((-t) & mask));\n", "\treturn (long)xi;\n", "}\n"]
def floorChars : List Char := floorLines.flatMap String.toList
def floorTokens : List (List Char) := ["static", "inline", "long", "fpr_floor", "(", "fpr", "x", ")", "{", "uint64_t", "t", ",", "mask", ";", "int64_t", "xi", ";", "int", "e", ",", "cc", ";", "e", "=", "(", "int", ")", "(", "x", ">>", "52", ")", "&", "0x7FF", ";", "t", "=", "x", ">>", "63", ";", "xi", "=", "(", "int64_t", ")", "(", "(", "(", "x", "<<", "10", ")", "|", "(", "(", "uint64_t", ")", "1", "<<", "62", ")", ")", "&", "(", "(", "(", "uint64_t", ")", "1", "<<", "63", ")", "-", "1", ")", ")", ";", "xi", "=", "(", "xi", "^", "-", "(", "int64_t", ")", "t", ")", "+", "(", "int64_t", ")", "t", ";", "cc", "=", "1085", "-", "e", ";", "xi", "=", "fpr_irsh", "(", "xi", ",", "cc", "&", "63", ")", ";", "mask", "=", "-", "(", "uint64_t", ")", "(", "(", "uint32_t", ")", "(", "63", "-", "cc", ")", ">>", "31", ")", ";", "xi", "=", "(", "int64_t", ")", "(", "(", "(", "uint64_t", ")", "xi", "&", "~", "mask", ")", "|", "(", "(", "-", "t", ")", "&", "mask", ")", ")", ";", "return", "(", "long", ")", "xi", ";", "}"].map String.toList
def subLines : List String := ["static inline fpr\n", "fpr_sub(fpr x, fpr y)\n", "{\n", "\ty ^= (uint64_t)1 << 63;\n", "\treturn fpr_add(x, y);\n", "}\n"]
def subChars : List Char := subLines.flatMap String.toList
def subTokens : List (List Char) := ["static", "inline", "fpr", "fpr_sub", "(", "fpr", "x", ",", "fpr", "y", ")", "{", "y", "^=", "(", "uint64_t", ")", "1", "<<", "63", ";", "return", "fpr_add", "(", "x", ",", "y", ")", ";", "}"].map String.toList
def negLines : List String := ["static inline fpr\n", "fpr_neg(fpr x)\n", "{\n", "\tx ^= (uint64_t)1 << 63;\n", "\treturn x;\n", "}\n"]
def negChars : List Char := negLines.flatMap String.toList
def negTokens : List (List Char) := ["static", "inline", "fpr", "fpr_neg", "(", "fpr", "x", ")", "{", "x", "^=", "(", "uint64_t", ")", "1", "<<", "63", ";", "return", "x", ";", "}"].map String.toList
def halfLines : List String := ["static inline fpr\n", "fpr_half(fpr x)\n", "{\n", "\tuint32_t t;\n", "\n", "\tx -= (uint64_t)1 << 52;\n", "\tt = (((uint32_t)(x >> 52) & 0x7FF) + 1) >> 11;\n", "\tx &= (uint64_t)t - 1;\n", "\treturn x;\n", "}\n"]
def halfChars : List Char := halfLines.flatMap String.toList
def halfTokens : List (List Char) := ["static", "inline", "fpr", "fpr_half", "(", "fpr", "x", ")", "{", "uint32_t", "t", ";", "x", "-=", "(", "uint64_t", ")", "1", "<<", "52", ";", "t", "=", "(", "(", "(", "uint32_t", ")", "(", "x", ">>", "52", ")", "&", "0x7FF", ")", "+", "1", ")", ">>", "11", ";", "x", "&=", "(", "uint64_t", ")", "t", "-", "1", ";", "return", "x", ";", "}"].map String.toList
def doubleLines : List String := ["static inline fpr\n", "fpr_double(fpr x)\n", "{\n", "\tx += (uint64_t)((((unsigned)(x >> 52) & 0x7FFU) + 0x7FFU) >> 11) << 52;\n", "\treturn x;\n", "}\n"]
def doubleChars : List Char := doubleLines.flatMap String.toList
def doubleTokens : List (List Char) := ["static", "inline", "fpr", "fpr_double", "(", "fpr", "x", ")", "{", "x", "+=", "(", "uint64_t", ")", "(", "(", "(", "(", "unsigned", ")", "(", "x", ">>", "52", ")", "&", "0x7FFU", ")", "+", "0x7FFU", ")", ">>", "11", ")", "<<", "52", ";", "return", "x", ";", "}"].map String.toList
end B20.Pinned
