import hashlib,json
from pathlib import Path
W=Path.cwd();source='source/falcon-vrfy.c';sh=hashlib.sha256((W/source).read_bytes()).hexdigest()
rows=[]
def add(key,claim,span,premises,evidence,command,status,gap=None):
    rows.append(dict(id=key,claim=claim,source_file=source,source_lines=span,source_sha256=sh,
      premises=premises,evidence=evidence,check_command=command,status=status,gap=gap))
word='python3 -B scripts/run.py 120 /home/footfalcon/.elan/toolchains/leanprover--lean4---v4.34.0/bin/lean formal/Words.lean'
tab='python3 -B scripts/run.py 240 /home/footfalcon/.elan/toolchains/leanprover--lean4---v4.34.0/bin/lean formal/Tables.lean'
lin='python3 -B scripts/run.py 90 /home/footfalcon/.elan/toolchains/leanprover--lean4---v4.34.0/bin/lean formal/Linear.lean'
comp='python3 -B scripts/run.py 90 /home/footfalcon/.elan/toolchains/leanprover--lean4---v4.34.0/bin/lean formal/Composition.lean'
model=['pinned GCC/C99/LP64 widths','canonical operands','C unsigned arithmetic and bit-mask/shift interpretation explained in DERIVATION D1']
add('W_ADD','forall canonical x,y: mq_add is canonical (x+y) mod q',[582,597],model,['formal/Words.lean:add_contract','DERIVATION.md:D1'],word,'PROVED_MODEL_WITH_C_TRANSLATION')
add('W_SUB','forall canonical x,y: mq_sub is canonical (x-y) mod q',[602,614],model,['formal/Words.lean:sub_contract','DERIVATION.md:D1'],word,'PROVED_MODEL_WITH_C_TRANSLATION')
add('W_HALF','canonical modular division by 2; supplemental, not used in active ternary transform',[619,624],model,['formal/Words.lean:half_contract'],word,'PROVED_SUPPLEMENTAL')
add('W_MONT','forall canonical x,y: canonical x*y*Rinv; exact low16 under uint32 wrap; all ranges',[631,671],model,['formal/Words.lean:mq_montymul_contract','formal/Words.lean:mq_montysqr_contract','DERIVATION.md:D1'],word,'PROVED_MODEL_WITH_C_TRANSLATION')
add('PRIME_ROOT','q prime; required quadratic/cubic root and unit identities for concrete tables',[59,68],['literal constants and complete finite certificates'],['formal/Words.lean:prime_factorization','formal/Tables.lean:root_and_scale_facts','artifacts/constants_certificate.json'],word+'; '+tab,'PROVED_REQUIRED_RELATIONS','Exact order-25 power checks are diagnostic, not an unproved premise of the closed local contracts.')
add('DIV_USED','actual addition-chain result and canonical quotient for all three constant division instances used by logn=10',[743,803],['W_MONT','three fixed nonzero denominators 1874,8479,1536'],['formal/Tables.lean:chain_*_checked','formal/Tables.lean:root_and_scale_facts','DERIVATION.md:D2'],tab,'CERTIFIED_REQUIRED_INSTANCES')
add('GEN10','exact initialized 0..1023 table values, Montgomery interpretation, source recurrence and rev10 order',[805,885],['W_MONT','DIV_USED','fixed logn=10','disjoint gm/igm buffers'],['formal/Tables.lean:rev_even_range','formal/Tables.lean:rev_even_involution','formal/Tables.lean:sequence/parents/units','artifacts/constants_certificate.json','DERIVATION.md:D3'],tab,'CERTIFIED_FIXED_GENERATOR')
add('INDEX_INIT','fixed address schedule, initialization-before-read for tables, valid transform index spans',[805,1243],['valid aligned buffers and required nonaliasing','fixed N=1536/logn=10'],['artifacts/constants_certificate.json:generator_reads/generator_writes/binary_stages','formal/Tables.lean:rev_even_range','DERIVATION.md:D3,D5'],tab,'FIXED_SCHEDULE_CHECKED','Global buffer-state-to-polynomial invariant is separate and remains open.')
add('LOCAL_BLOCKS','2x2 and 3x3 block identities for all variable block inputs with the certified coefficients',[998,1158],['W_MONT/W_ADD/W_SUB','GEN10','literal coefficients bound to source expressions'],['formal/Linear.lean','formal/Tables.lean:rows2/rows3','DERIVATION.md:D4'],lin+'; '+tab,'PROVED_LOCAL_BLOCK_IDENTITIES')
add('FORWARD_GLOBAL','forall canonical v: source forward output is evaluation at alpha_i*omega^j in exact physical order 3i+j',[980,1062],['closed word/table/local-block results'],['DERIVATION.md:D5','formal/Composition.lean:forward_product premise'],comp,'OPEN','No closed source in-place-buffer/CRT model instance proving the full stage invariant for arbitrary coefficient vectors.')
add('INVERSE_GLOBAL','forall canonical v: source inverse of source forward equals v, with correct reverse schedule and n scaling',[1068,1159],['LOCAL_BLOCKS','INDEX_INIT','GEN10'],['formal/Linear.lean:final_scaling','DERIVATION.md:D5','formal/Composition.lean:inverse_forward premise'],comp,'OPEN','Local inverse matrices and scale are checked, but global in-place composition is not instantiated as a source theorem.')
add('PRODUCT','universal coefficient product modulo Phi after mathematical key preparation and point multiplication',[1185,1222],['FORWARD_GLOBAL','INVERSE_GLOBAL'],['formal/Composition.lean:L_NTT_after_global_interfaces','formal/Composition.lean:prepared_product','DERIVATION.md:D6'],comp,'CONDITIONAL','The final theorem still has forward_product and inverse_forward hypotheses.')
add('SUBTRACT','canonical subtraction d=p-c once p is the correct canonical product',[1228,1243],['W_SUB','PRODUCT for identification of p'],['formal/Words.lean:sub_contract','formal/Composition.lean','DERIVATION.md:D6'],word+'; '+comp,'LOCAL_PROVED_COMPOSITION_CONDITIONAL','Algebraic identification d=h*r-c inherits PRODUCT gap.')
add('RHO_SUBSTITUTION','r=rho(s) implies r congruent to s; after L_NTT, d=canonical(h*s-c)',[1377,1424],['pinned L_RHO','L_NTT completion'],['inputs/L_RHO_RESULT.json','inputs/context/8_Rho.lean','DERIVATION.md:D6'],comp,'CONDITIONAL_ON_L_NTT','Does not independently close source forward/inverse semantics.')
add('SOURCE_BINDING','17-file candidate identity, exact source slices and reversible observation-only injection',[59,1589],['trusted source pin','non-symlink public inputs'],['artifacts/source_binding.json','INPUTS.sha256'], 'python3 -B scripts/audit.py --originals --out tmp/audit-new.json','VERIFIED')
add('IMPLEMENTATION_CHECKS','required constants/primitive/pipeline controls, sanitizer, integration case and mutations',[582,1243],['pinned build and public inputs'],['artifacts/test_suite.json','artifacts/primitive_check.json','artifacts/primitive_check_asan.json'],'python3 -B scripts/test_suite.py (fresh copy only)','CONTROLS_PASSED_NOT_UNIVERSAL_PROOF')
out=dict(schema='FT1536_L_NTT_OBLIGATIONS_V1',main_result='PARTIAL_PROOF',source_integrated=False,owner_accepted=False,full_L_V_proved=False,
         source_sha256=sh,obligations=rows,blocking=['FORWARD_GLOBAL','INVERSE_GLOBAL','PRODUCT'])
(W/'OBLIGATIONS.json').write_text(json.dumps(out,indent=2)+'\n')
print(json.dumps({'obligations':len(rows),'blocking':out['blocking'],'main_result':out['main_result']}))
